{"abstract":[{"text":"Returns a default model which will fetch all Help Center content for the current locale.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"To customise the content, update propertys on a default model."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/defaultContent()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"externalID":"c:objc(cs)ZDKHelpCenterOverviewContentModel(cm)defaultContent","symbolKind":"method","navigatorTitle":[{"text":"defaultContent","kind":"identifier"}],"title":"defaultContent()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"defaultContent","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultContent","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":"!","kind":"text"}]}]},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"a default content model.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/defaultcontent()"]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/defaultcontent()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel/defaultContent()":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultContent","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Self","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"defaultContent","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/defaultcontent()","kind":"symbol","abstract":[{"type":"text","text":"Returns a default model which will fetch all Help Center content for the current locale."},{"type":"text","text":" "},{"type":"text","text":"To customise the content, update propertys on a default model."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/defaultContent()","type":"topic","title":"defaultContent()"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel","kind":"symbol","abstract":[{"type":"text","text":"Model which allows customizations on the content displayed by Help Center."}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel","title":"ZDKHelpCenterOverviewContentModel"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"defaultContent","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"defaultContent","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"defaultContent","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1defaultContent()\/title","value":"defaultContent"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"defaultContent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1defaultContent()\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/title","op":"replace","value":"ZDKHelpCenterOverviewContentModel"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterOverviewContentModel"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}