{"kind":"symbol","metadata":{"externalID":"c:@CM@SupportProvidersSDK@objc(cs)ZDKRequestStorage(im)storeRequestsAndResetCacheTime:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"storeRequestsAndResetCacheTime","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","text":"RequestForStorage"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"storeRequestsAndResetCacheTime:"}],"role":"symbol","symbolKind":"method","title":"storeRequestsAndResetCacheTime(_:)","roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"storeRequestsAndResetCacheTime","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"requests","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/requeststorage\/storerequestsandresetcachetime(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/requeststorage\/storerequestsandresetcachetime(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage\/storeRequestsAndResetCacheTime(_:)"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestStorage":{"abstract":[],"url":"\/documentation\/supportproviderssdk\/requeststorage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestStorage"}],"type":"topic","title":"RequestStorage","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestStorage","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage":{"abstract":[],"url":"\/documentation\/supportproviderssdk\/requestforstorage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestForStorage"}],"type":"topic","title":"RequestForStorage","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestForStorage","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestStorage/storeRequestsAndResetCacheTime(_:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"storeRequestsAndResetCacheTime:","kind":"identifier"}],"title":"storeRequestsAndResetCacheTime(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeRequestsAndResetCacheTime"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","kind":"typeIdentifier","text":"RequestForStorage"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/requeststorage\/storerequestsandresetcachetime(_:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage\/storeRequestsAndResetCacheTime(_:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"storeRequestsAndResetCacheTime:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"storeRequestsAndResetCacheTime:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"storeRequestsAndResetCacheTime:"},{"kind":"text","text":"("},{"text":"NSArray<ZDKRequestForStorage *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"requests"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKRequestStorage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKRequestStorage"}]},{"op":"replace","value":"ZDKRequestForStorage","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/fragments","value":[{"kind":"identifier","text":"ZDKRequestForStorage"}],"op":"replace"},{"op":"replace","value":"storeRequestsAndResetCacheTime:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage~1storeRequestsAndResetCacheTime(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage~1storeRequestsAndResetCacheTime(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"storeRequestsAndResetCacheTime:"}]}]}]}