{"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"ZDKHelpCenterOverviewGroupTypeDefault","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@E@ZDKHelpCenterOverviewGroupType@ZDKHelpCenterOverviewGroupTypeDefault","role":"symbol","title":"ZDKHelpCenterOverviewGroupType.default","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType"]]},"abstract":[{"type":"text","text":"This default results in every category and seciton being fetched."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/default"]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/default"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/default","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType/default":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/default","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterOverviewGroupTypeDefault","kind":"identifier"}],"abstract":[{"type":"text","text":"This default results in every category and seciton being fetched."}],"role":"symbol","title":"ZDKHelpCenterOverviewGroupType.default","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"`default`","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/default"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupType"}],"type":"topic","abstract":[{"text":"Used to specify what type of ids will be supplied.","type":"text"}],"title":"ZDKHelpCenterOverviewGroupType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKHelpCenterOverviewGroupTypeDefault","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"ZDKHelpCenterOverviewGroupTypeDefault","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ZDKHelpCenterOverviewGroupTypeDefault","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"ZDKHelpCenterOverviewGroupTypeDefault","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1default\/title","op":"replace"},{"value":[{"text":"ZDKHelpCenterOverviewGroupTypeDefault","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1default\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType\/title","value":"ZDKHelpCenterOverviewGroupType"},{"value":[{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}