{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkattachmentprovider\/getavatarforurl(_:withcallback:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkattachmentprovider\/getavatarforurl(_:withcallback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","title":"getAvatarForUrl(_:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getAvatarForUrl"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ZDKAvatarCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKAttachmentProvider.h@T@ZDKAvatarCallback"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"getAvatarForUrl:withCallback:","kind":"identifier"}],"externalID":"c:objc(cs)ZDKAttachmentProvider(im)getAvatarForUrl:withCallback:","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getAvatarForUrl","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"avatarUrl","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":": ","kind":"text"},{"text":"ZDKAvatarCallback","preciseIdentifier":"c:ZDKAttachmentProvider.h@T@ZDKAvatarCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAvatarCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"NSString url of the image to be fetched","type":"text"}],"type":"paragraph"}],"name":"avatarUrl"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"block callback executed on error or success states"}]}],"name":"callback"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachmentProvider"]]},"abstract":[{"text":"Get the image\/avatar data for a given URL","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachmentProvider\/getAvatarForUrl(_:withCallback:)"},"kind":"symbol","sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachmentProvider/getAvatarForUrl(_:withCallback:)":{"url":"\/documentation\/supportproviderssdk\/zdkattachmentprovider\/getavatarforurl(_:withcallback:)","kind":"symbol","role":"symbol","title":"getAvatarForUrl(_:withCallback:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getAvatarForUrl","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKAttachmentProvider.h@T@ZDKAvatarCallback","text":"ZDKAvatarCallback"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"getAvatarForUrl:withCallback:","kind":"identifier"}],"abstract":[{"type":"text","text":"Get the image\/avatar data for a given URL"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachmentProvider\/getAvatarForUrl(_:withCallback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachmentProvider":{"url":"\/documentation\/supportproviderssdk\/zdkattachmentprovider","kind":"symbol","role":"symbol","title":"ZDKAttachmentProvider","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAttachmentProvider"}],"navigatorTitle":[{"text":"ZDKAttachmentProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"Provider for images\/avatars."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachmentProvider"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAvatarCallback":{"abstract":[{"type":"text","text":"Block invoked to pass data back from API call"}],"navigatorTitle":[{"text":"ZDKAvatarCallback","kind":"identifier"}],"title":"ZDKAvatarCallback","url":"\/documentation\/supportproviderssdk\/zdkavatarcallback","role":"symbol","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAvatarCallback"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAvatarCallback"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"getAvatarForUrl:withCallback:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getAvatarForUrl:withCallback:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getAvatarForUrl:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"avatarUrl","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withCallback:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ZDKAvatarCallback","preciseIdentifier":"c:ZDKAttachmentProvider.h@T@ZDKAvatarCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAvatarCallback","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachmentProvider~1getAvatarForUrl(_:withCallback:)\/title","value":"getAvatarForUrl:withCallback:"},{"value":[{"kind":"text","text":"- "},{"text":"getAvatarForUrl:withCallback:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachmentProvider~1getAvatarForUrl(_:withCallback:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachmentProvider\/title","value":"ZDKAttachmentProvider"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachmentProvider\/fragments","op":"replace","value":[{"text":"ZDKAttachmentProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAvatarCallback\/title","value":"ZDKAvatarCallback"},{"value":[{"text":"ZDKAvatarCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAvatarCallback\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}