{"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"customFieldDictionary","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","role":"symbol","title":"customFieldDictionary","navigatorTitle":[{"text":"customFieldDictionary","kind":"identifier"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKCustomField(py)customFieldDictionary"},"abstract":[{"type":"text","text":"Custom field represented as a dictionary."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/CustomField\/customFieldDictionary","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/customfield\/customfielddictionary"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/customfield\/customfielddictionary"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/CustomField"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customFieldDictionary"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"type":"text","text":"The format of the dictionary: "},{"type":"codeVoice","code":"[\"id\": 1234456, \"value\": fieldValue]"},{"type":"text","text":"."}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/CustomField":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomField"}],"role":"symbol","type":"topic","abstract":[],"title":"CustomField","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/CustomField","kind":"symbol","navigatorTitle":[{"text":"CustomField","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/customfield"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/CustomField/customFieldDictionary":{"type":"topic","abstract":[{"type":"text","text":"Custom field represented as a dictionary."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/CustomField\/customFieldDictionary","navigatorTitle":[{"text":"customFieldDictionary","kind":"identifier"}],"title":"customFieldDictionary","url":"\/documentation\/supportproviderssdk\/customfield\/customfielddictionary","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customFieldDictionary","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"customFieldDictionary"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"customFieldDictionary"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"customFieldDictionary","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"ZDKCustomField","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1CustomField\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1CustomField\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKCustomField"}]},{"value":"customFieldDictionary","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1CustomField~1customFieldDictionary\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"customFieldDictionary"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1CustomField~1customFieldDictionary\/fragments"}]}]}