{"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Case","title":"ZDKTicketFieldType.multiSelect","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiSelect"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldTypeMultiSelect"}],"role":"symbol","externalID":"c:@E@ZDKTicketFieldType@ZDKTicketFieldTypeMultiSelect","symbolKind":"case"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/multiselect"]},{"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/multiselect"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Ticket field ticket system type"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/multiSelect"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiSelect","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/multiSelect":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multiSelect"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/multiselect","type":"topic","abstract":[{"text":"Ticket field ticket system type","type":"text"}],"title":"ZDKTicketFieldType.multiSelect","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/multiSelect","navigatorTitle":[{"text":"ZDKTicketFieldTypeMultiSelect","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType":{"role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype","kind":"symbol","title":"ZDKTicketFieldType","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType","abstract":[{"type":"text","text":"Ticket field type"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldType"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKTicketFieldTypeMultiSelect"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"ZDKTicketFieldTypeMultiSelect","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKTicketFieldTypeMultiSelect","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1multiSelect\/title","value":"ZDKTicketFieldTypeMultiSelect"},{"value":[{"text":"ZDKTicketFieldTypeMultiSelect","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1multiSelect\/fragments"},{"value":"ZDKTicketFieldType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/title"},{"op":"replace","value":[{"text":"ZDKTicketFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}