{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"textArea","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"ZDKTicketFieldTypeTextArea","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","title":"ZDKTicketFieldType.textArea","externalID":"c:@E@ZDKTicketFieldType@ZDKTicketFieldTypeTextArea","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"textArea","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/textArea","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/textarea"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/textarea"]}],"abstract":[{"text":"Ticket field text area type that allows multi-line text","type":"text"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType":{"role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype","kind":"symbol","title":"ZDKTicketFieldType","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType","abstract":[{"type":"text","text":"Ticket field type"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldType"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/textArea":{"title":"ZDKTicketFieldType.textArea","kind":"symbol","navigatorTitle":[{"text":"ZDKTicketFieldTypeTextArea","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/textArea","role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/textarea","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textArea","kind":"identifier"}],"abstract":[{"text":"Ticket field text area type that allows multi-line text","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"ZDKTicketFieldTypeTextArea","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKTicketFieldTypeTextArea","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKTicketFieldTypeTextArea"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKTicketFieldType","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKTicketFieldType"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1textArea\/title","value":"ZDKTicketFieldTypeTextArea","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKTicketFieldTypeTextArea"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1textArea\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}