{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/initialize(withZendesk:)"},"abstract":[{"type":"text","text":"Initialize the Support singleton with the Zendesk singleton"},{"type":"text","text":" "},{"text":"from ZendeskCoreSDK","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withZendesk"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"zendesk"},{"text":": ","kind":"text"},{"text":"Zendesk","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"text":"?)","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"withZendesk","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"text":"?)","kind":"text"}],"roleHeading":"Type Method","role":"symbol","title":"initialize(withZendesk:)","navigatorTitle":[{"kind":"identifier","text":"initializeWithZendesk:"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport(cm)initializeWithZendesk:"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/support\/initialize(withzendesk:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/support\/initialize(withzendesk:)"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support/initialize(withZendesk:)":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/initialize(withZendesk:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"withZendesk","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Initialize the Support singleton with the Zendesk singleton","type":"text"},{"type":"text","text":" "},{"type":"text","text":"from ZendeskCoreSDK"}],"role":"symbol","title":"initialize(withZendesk:)","type":"topic","navigatorTitle":[{"text":"initializeWithZendesk:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/support\/initialize(withzendesk:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support":{"role":"symbol","title":"Support","navigatorTitle":[{"text":"Support","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/support","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support","abstract":[{"text":"ZDKSupport is responsible for initialization of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the SDK and manages the backend configuration."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Support","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"initializeWithZendesk:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initializeWithZendesk:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initializeWithZendesk:"},{"text":"(","kind":"text"},{"text":"ZDKClassicZendesk","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKClassicZendesk"},{"text":" *) ","kind":"text"},{"text":"zendesk","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1initialize(withZendesk:)\/title","value":"initializeWithZendesk:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1initialize(withZendesk:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithZendesk:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support\/title","value":"ZDKSupport"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support\/fragments","value":[{"text":"ZDKSupport","kind":"identifier"}]}]}]}