{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/refreshRequest(requestId:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"requestId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]},{"parameters":[{"name":"requestId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the request to refresh"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A boolean indicating whether the Request Detail Screen has been refresh or not.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"requestId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Method","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"refreshRequestWithRequestId:"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport(im)refreshRequestWithRequestId:","role":"symbol","symbolKind":"method","title":"refreshRequest(requestId:)"},"kind":"symbol","abstract":[{"type":"text","text":"This method can be used to aid in handling push notifications relating to requests."},{"text":" ","type":"text"},{"text":"This method can result in a dynamic update in the request UI. For this occur,","type":"text"},{"text":" ","type":"text"},{"text":"the push notification and the on screen request must contain matching request ids.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This method will return true only in the case of a successful UI update."},{"type":"text","text":" "},{"type":"text","text":"A return value of false means that the push notification was unhandled."},{"type":"text","text":" "},{"text":"At this point you can decided how best to update the user based on the contents of the notification.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/supportproviderssdk\/support\/refreshrequest(requestid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/support\/refreshrequest(requestid:)"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support":{"role":"symbol","title":"Support","navigatorTitle":[{"text":"Support","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/support","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support","abstract":[{"text":"ZDKSupport is responsible for initialization of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the SDK and manages the backend configuration."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Support","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support/refreshRequest(requestId:)":{"url":"\/documentation\/supportproviderssdk\/support\/refreshrequest(requestid:)","abstract":[{"type":"text","text":"This method can be used to aid in handling push notifications relating to requests."},{"type":"text","text":" "},{"text":"This method can result in a dynamic update in the request UI. For this occur,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the push notification and the on screen request must contain matching request ids."},{"text":" ","type":"text"},{"text":"This method will return true only in the case of a successful UI update.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"A return value of false means that the push notification was unhandled."},{"text":" ","type":"text"},{"type":"text","text":"At this point you can decided how best to update the user based on the contents of the notification."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"requestId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"refreshRequestWithRequestId:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/refreshRequest(requestId:)","role":"symbol","title":"refreshRequest(requestId:)","kind":"symbol","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"refreshRequestWithRequestId:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"refreshRequestWithRequestId:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"refreshRequestWithRequestId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"requestId"},{"text":";","kind":"text"}]}]}},{"value":"ZDKSupport","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKSupport"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1refreshRequest(requestId:)\/title","value":"refreshRequestWithRequestId:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1refreshRequest(requestId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshRequestWithRequestId:"}]}]}]}