{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toDictionary"},{"kind":"text","text":" "},{"kind":"internalParam","text":"objectToConvert"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"!) -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil\/convertobject(todictionary:for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil\/convertobject(todictionary:for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertObject(toDictionary:for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Generates a dictionary representation of a classes properties."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toDictionary"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"!) -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"title":"convertObject(toDictionary:for:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ZDKJsonUtil(cm)convertObjectToDictionary:forClass:","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"convertObjectToDictionary:forClass:"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/convertObject(toDictionary:for:)":{"role":"symbol","title":"convertObject(toDictionary:for:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toDictionary"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"!) -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Generates a dictionary representation of a classes properties."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertObject(toDictionary:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"convertObjectToDictionary:forClass:"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/convertobject(todictionary:for:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil":{"role":"symbol","title":"ZDKJsonUtil","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKJsonUtil"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKJsonUtil"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"convertObjectToDictionary:forClass:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"convertObjectToDictionary:forClass:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"convertObjectToDictionary:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"objectToConvert"},{"kind":"text","text":" "},{"kind":"identifier","text":"forClass:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:@T@Class"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aClass"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertObject(toDictionary:for:)\/title","value":"convertObjectToDictionary:forClass:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertObject(toDictionary:for:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"convertObjectToDictionary:forClass:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/title","value":"ZDKJsonUtil"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/fragments","value":[{"kind":"identifier","text":"ZDKJsonUtil"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}