{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/loggingIn","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkapiloginstate\/loggingin"]},{"paths":["\/documentation\/supportproviderssdk\/zdkapiloginstate\/loggingin"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"The SDK is in the process of logging in."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"loggingIn","kind":"identifier"}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"loggingIn","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"case","externalID":"c:@E@ZDKAPILoginState@ZDKAPILoginStateLoggingIn","title":"ZDKAPILoginState.loggingIn","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ZDKAPILoginStateLoggingIn"}],"role":"symbol"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState":{"url":"\/documentation\/supportproviderssdk\/zdkapiloginstate","abstract":[{"text":"ZDKAPI Login state.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAPILoginState","kind":"identifier"}],"kind":"symbol","title":"ZDKAPILoginState","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKAPILoginState"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState/loggingIn":{"abstract":[{"text":"The SDK is in the process of logging in.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkapiloginstate\/loggingin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"loggingIn","kind":"identifier"}],"kind":"symbol","title":"ZDKAPILoginState.loggingIn","type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKAPILoginStateLoggingIn","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/loggingIn"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKAPILoginStateLoggingIn"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKAPILoginStateLoggingIn","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKAPILoginStateLoggingIn","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState\/title","value":"ZDKAPILoginState"},{"value":[{"text":"ZDKAPILoginState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1loggingIn\/title","value":"ZDKAPILoginStateLoggingIn"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1loggingIn\/fragments","value":[{"text":"ZDKAPILoginStateLoggingIn","kind":"identifier"}],"op":"replace"}]}]}