{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKValidation\/emptyStringError","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"emptyStringError"}],"role":"symbol","title":"ZDKValidation.emptyStringError","roleHeading":"Case","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"case","externalID":"c:@E@ZDKValidation@ZDKValidationEmptyStringError","navigatorTitle":[{"kind":"identifier","text":"ZDKValidationEmptyStringError"}]},"kind":"symbol","sections":[],"abstract":[{"text":"Empty string error code","type":"text"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkvalidation\/emptystringerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkvalidation\/emptystringerror"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"emptyStringError"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKValidation"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKValidation/emptyStringError":{"role":"symbol","navigatorTitle":[{"text":"ZDKValidationEmptyStringError","kind":"identifier"}],"title":"ZDKValidation.emptyStringError","abstract":[{"text":"Empty string error code","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKValidation\/emptyStringError","url":"\/documentation\/supportproviderssdk\/zdkvalidation\/emptystringerror","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"emptyStringError"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKValidation":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKValidation","url":"\/documentation\/supportproviderssdk\/zdkvalidation","title":"ZDKValidation","abstract":[{"text":"Validation error codes","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKValidation","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKValidation"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKValidationEmptyStringError"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ZDKValidationEmptyStringError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKValidationEmptyStringError","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKValidation~1emptyStringError\/title","op":"replace","value":"ZDKValidationEmptyStringError"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKValidation~1emptyStringError\/fragments","value":[{"text":"ZDKValidationEmptyStringError","kind":"identifier"}]},{"op":"replace","value":"ZDKValidation","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKValidation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKValidation\/fragments","value":[{"text":"ZDKValidation","kind":"identifier"}]}]}]}