{"abstract":[{"text":"List of tags associated with the request","type":"text"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"tags"}],"role":"symbol","title":"tags","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tags","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"text":"]!","kind":"text"}],"externalID":"c:objc(cs)ZDKCreateRequest(py)tags","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"property","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/tags"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkcreaterequest\/tags"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkcreaterequest\/tags"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tags","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]! { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKCreateRequest","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest","navigatorTitle":[{"kind":"identifier","text":"ZDKCreateRequest"}],"type":"topic","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest","title":"ZDKCreateRequest","abstract":[{"type":"text","text":"A request sent by the user."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest/tags":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"tags","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"title":"tags","role":"symbol","kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest\/tags","navigatorTitle":[{"text":"tags","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"List of tags associated with the request"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/tags"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"tags"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"tags","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tags"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest\/title","value":"ZDKCreateRequest"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest\/fragments","op":"replace","value":[{"text":"ZDKCreateRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1tags\/title","value":"tags","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1tags\/fragments","value":[{"kind":"identifier","text":"tags"}],"op":"replace"}]}]}