{"metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@E@ZDKAuthenticationType@ZDKAuthenticationTypeUnknown","navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationTypeUnknown"}],"symbolKind":"case","title":"ZDKAuthenticationType.unknown","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"modules":[{"name":"SupportProvidersSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/unknown","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Authentication type unknown.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkauthenticationtype\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkauthenticationtype\/unknown"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType/unknown":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/unknown","url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype\/unknown","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ZDKAuthenticationTypeUnknown","kind":"identifier"}],"type":"topic","title":"ZDKAuthenticationType.unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"abstract":[{"text":"Authentication type unknown.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType","url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ZDKAuthenticationType","kind":"identifier"}],"type":"topic","title":"ZDKAuthenticationType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKAuthenticationType","kind":"identifier"}],"abstract":[{"text":"Represents the types of authentication SDK supports.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKAuthenticationTypeUnknown","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"ZDKAuthenticationTypeUnknown","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKAuthenticationTypeUnknown"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKAuthenticationTypeUnknown","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1unknown\/title"},{"value":[{"text":"ZDKAuthenticationTypeUnknown","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1unknown\/fragments"},{"value":"ZDKAuthenticationType","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType\/fragments","value":[{"text":"ZDKAuthenticationType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}