{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/calculateRequestUpdates(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/calculaterequestupdates(_:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateRequestUpdates"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"requests"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","text":"RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates","text":"RequestUpdates"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"symbolKind":"method","extendedModule":"SupportProvidersSDK","title":"calculateRequestUpdates(_:)","role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"externalID":"s:So18ZDKRequestProviderC19SupportProvidersSDKE23calculateRequestUpdatesyAC0gH0CSayAC0G10ForStorageCGFZ","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateRequestUpdates"},{"text":"([","kind":"text"},{"text":"RequestForStorage","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage"},{"kind":"text","text":"]) -> "},{"text":"RequestUpdates","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates","kind":"typeIdentifier"}],"roleHeading":"Type Method"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/calculateRequestUpdates(_:)":{"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/calculaterequestupdates(_:)","title":"calculateRequestUpdates(_:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"calculateRequestUpdates"},{"text":"([","kind":"text"},{"text":"RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"RequestUpdates","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/calculateRequestUpdates(_:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage":{"abstract":[],"url":"\/documentation\/supportproviderssdk\/requestforstorage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestForStorage"}],"type":"topic","title":"RequestForStorage","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestForStorage","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"abstract":[],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","title":"ZDKRequestProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestProvider"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestProvider"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestUpdates":{"url":"\/documentation\/supportproviderssdk\/requestupdates","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestUpdates"}],"title":"RequestUpdates","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates","navigatorTitle":[{"text":"RequestUpdates","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"RequestUpdates object contains information about"},{"type":"text","text":" "},{"type":"text","text":"unread comments on each request the user has open."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/title","op":"replace","value":"ZDKRequestForStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/fragments","value":[{"text":"ZDKRequestForStorage","kind":"identifier"}]},{"value":"ZDKRequestProvider","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKRequestProvider"}]},{"op":"replace","value":"ZDKRequestUpdates","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates\/title"},{"value":[{"text":"ZDKRequestUpdates","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates\/fragments"}]}]}