{"metadata":{"navigatorTitle":[{"text":"getRequestById:withCallback:","kind":"identifier"}],"role":"symbol","title":"getRequestById(_:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getRequestById"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestCallback","kind":"typeIdentifier","text":"ZDKRequestCallback"},{"text":"!)","kind":"text"}],"externalID":"c:objc(cs)ZDKRequestProvider(im)getRequestById:withCallback:","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getrequestbyid(_:withcallback:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getrequestbyid(_:withcallback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Gets the request specified by the ID.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getRequestById"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"requestId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKRequestCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestCallback"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"requestId","content":[{"inlineContent":[{"text":"The ID of a request in Zendesk.","type":"text"}],"type":"paragraph"}]},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"text":"The callback to invoke which will return a ZDKRequest object.","type":"text"}]}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getRequestById(_:withCallback:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestCallback"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestcallback","title":"ZDKRequestCallback","navigatorTitle":[{"text":"ZDKRequestCallback","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestCallback","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Block defined for callback to be used for handling async server responses for fetching a single request."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"abstract":[],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","title":"ZDKRequestProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestProvider"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestProvider"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getRequestById(_:withCallback:)":{"navigatorTitle":[{"text":"getRequestById:withCallback:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getrequestbyid(_:withcallback:)","title":"getRequestById(_:withCallback:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getRequestById","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestCallback","text":"ZDKRequestCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Gets the request specified by the ID."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getRequestById(_:withCallback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"getRequestById:withCallback:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getRequestById:withCallback:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"getRequestById:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"requestId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withCallback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKRequestCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestCallback"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestCallback\/title","value":"ZDKRequestCallback","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKRequestCallback"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestCallback\/fragments"},{"op":"replace","value":"ZDKRequestProvider","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments","value":[{"text":"ZDKRequestProvider","kind":"identifier"}]},{"value":"getRequestById:withCallback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getRequestById(_:withCallback:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getRequestById:withCallback:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getRequestById(_:withCallback:)\/fragments"}]}]}