{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getRequestsByStatus(_:withCallback:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Filters requests that user has opened by a status."},{"type":"text","text":" "},{"type":"text","text":"It will also get an access token if one has not been previously stored."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getRequestsByStatus"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":" "},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestListCallback","text":"ZDKRequestListCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestListCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A comma separated list of status to filter the results by"}],"type":"paragraph"}],"name":"status"},{"name":"callback","content":[{"inlineContent":[{"type":"text","text":"The callback to invoke which will return a list of requests"}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getRequestsByStatus:withCallback:"}],"title":"getRequestsByStatus(_:withCallback:)","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","externalID":"c:objc(cs)ZDKRequestProvider(im)getRequestsByStatus:withCallback:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getRequestsByStatus","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ZDKRequestListCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestListCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getrequestsbystatus(_:withcallback:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getrequestsbystatus(_:withcallback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getRequestsByStatus(_:withCallback:)":{"navigatorTitle":[{"kind":"identifier","text":"getRequestsByStatus:withCallback:"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getrequestsbystatus(_:withcallback:)","title":"getRequestsByStatus(_:withCallback:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getRequestsByStatus","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestListCallback","text":"ZDKRequestListCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"abstract":[{"text":"Filters requests that user has opened by a status.","type":"text"},{"text":" ","type":"text"},{"text":"It will also get an access token if one has not been previously stored.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getRequestsByStatus(_:withCallback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestListCallback":{"url":"\/documentation\/supportproviderssdk\/zdkrequestlistcallback","kind":"symbol","abstract":[{"type":"text","text":"Block defined for callback to be used for handling async server responses for fetching a list of requests and agents that have publically"},{"text":" ","type":"text"},{"type":"text","text":"commented on them"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestListCallback","type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKRequestListCallback","kind":"identifier"}],"title":"ZDKRequestListCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ZDKRequestListCallback","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"abstract":[],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","title":"ZDKRequestProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestProvider"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestProvider"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"getRequestsByStatus:withCallback:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getRequestsByStatus:withCallback:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"getRequestsByStatus:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"status","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withCallback:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestListCallback","text":"ZDKRequestListCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestListCallback","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"callback","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getRequestsByStatus(_:withCallback:)\/title","value":"getRequestsByStatus:withCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getRequestsByStatus(_:withCallback:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getRequestsByStatus:withCallback:"}]},{"op":"replace","value":"ZDKRequestListCallback","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestListCallback\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestListCallback\/fragments","value":[{"kind":"identifier","text":"ZDKRequestListCallback"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title","value":"ZDKRequestProvider"},{"op":"replace","value":[{"text":"ZDKRequestProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments"}]}]}