{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/markRequestAsUnread(_:)"},"abstract":[{"type":"text","text":"Marks the request as unread"},{"type":"text","text":" "},{"text":"by incrementing the commentCount by one.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This should be used when a push notification has been recieved to"},{"type":"text","text":" "},{"type":"text","text":"updated the request as unread."}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/markrequestasunread(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/markrequestasunread(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"markRequestAsUnread","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"requestId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"requestId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of request to mark as unread"}]}]}],"kind":"parameters"}],"metadata":{"title":"markRequestAsUnread(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markRequestAsUnread"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"extendedModule":"SupportProvidersSDK","role":"symbol","externalID":"c:@CM@SupportProvidersSDK@@objc(cs)ZDKRequestProvider(im)markRequestAsUnread:","navigatorTitle":[{"text":"markRequestAsUnread:","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"abstract":[],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","title":"ZDKRequestProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestProvider"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestProvider"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/markRequestAsUnread(_:)":{"abstract":[{"type":"text","text":"Marks the request as unread"},{"text":" ","type":"text"},{"text":"by incrementing the commentCount by one.","type":"text"},{"type":"text","text":" "},{"text":"This should be used when a push notification has been recieved to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"updated the request as unread."}],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/markrequestasunread(_:)","title":"markRequestAsUnread(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markRequestAsUnread","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/markRequestAsUnread(_:)","role":"symbol","navigatorTitle":[{"text":"markRequestAsUnread:","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"markRequestAsUnread:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"markRequestAsUnread:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"markRequestAsUnread:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"requestId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title","value":"ZDKRequestProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments","value":[{"text":"ZDKRequestProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1markRequestAsUnread(_:)\/title","op":"replace","value":"markRequestAsUnread:"},{"value":[{"kind":"text","text":"- "},{"text":"markRequestAsUnread:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1markRequestAsUnread(_:)\/fragments","op":"replace"}]}]}