{"abstract":[{"type":"text","text":"Determines whether the current user has any unread requests"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasUpdatedRequests"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"A bool indicating whether the user has unread requests","type":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates(im)hasUpdatedRequests","modules":[{"name":"SupportProvidersSDK"}],"title":"hasUpdatedRequests()","roleHeading":"Instance Method","navigatorTitle":[{"text":"hasUpdatedRequests","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasUpdatedRequests","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates\/hasUpdatedRequests()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/requestupdates\/hasupdatedrequests()"]},{"paths":["\/documentation\/supportproviderssdk\/requestupdates\/hasupdatedrequests()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestUpdates":{"abstract":[{"type":"text","text":"RequestUpdates object contains information about"},{"type":"text","text":" "},{"text":"unread comments on each request the user has open.","type":"text"}],"type":"topic","role":"symbol","title":"RequestUpdates","kind":"symbol","url":"\/documentation\/supportproviderssdk\/requestupdates","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestUpdates","kind":"identifier"}],"navigatorTitle":[{"text":"RequestUpdates","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestUpdates/hasUpdatedRequests()":{"abstract":[{"text":"Determines whether the current user has any unread requests","type":"text"}],"type":"topic","role":"symbol","title":"hasUpdatedRequests()","kind":"symbol","url":"\/documentation\/supportproviderssdk\/requestupdates\/hasupdatedrequests()","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates\/hasUpdatedRequests()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasUpdatedRequests","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"hasUpdatedRequests"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"hasUpdatedRequests","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"hasUpdatedRequests","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"hasUpdatedRequests","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates\/title","op":"replace","value":"ZDKRequestUpdates"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates\/fragments","value":[{"text":"ZDKRequestUpdates","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates~1hasUpdatedRequests()\/title","value":"hasUpdatedRequests","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"hasUpdatedRequests","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates~1hasUpdatedRequests()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}