{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates\/requestUpdates","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/requestupdates\/requestupdates"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/requestupdates\/requestupdates"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestUpdates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates(py)requestUpdates","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"requestUpdates","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"requestUpdates","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestUpdates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"]","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates"]]},"abstract":[{"text":"Dictionary with requestIds as keys and the unread comment count","type":"text"},{"text":" ","type":"text"},{"text":"as values.","type":"text"}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestUpdates":{"abstract":[{"type":"text","text":"RequestUpdates object contains information about"},{"type":"text","text":" "},{"text":"unread comments on each request the user has open.","type":"text"}],"type":"topic","role":"symbol","title":"RequestUpdates","kind":"symbol","url":"\/documentation\/supportproviderssdk\/requestupdates","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestUpdates","kind":"identifier"}],"navigatorTitle":[{"text":"RequestUpdates","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestUpdates/requestUpdates":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates\/requestUpdates","type":"topic","kind":"symbol","navigatorTitle":[{"text":"requestUpdates","kind":"identifier"}],"abstract":[{"type":"text","text":"Dictionary with requestIds as keys and the unread comment count"},{"type":"text","text":" "},{"type":"text","text":"as values."}],"role":"symbol","title":"requestUpdates","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestUpdates"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/requestupdates\/requestupdates"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"requestUpdates","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"requestUpdates","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSNumber *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"requestUpdates","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates\/title","op":"replace","value":"ZDKRequestUpdates"},{"value":[{"text":"ZDKRequestUpdates","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates~1requestUpdates\/title","op":"replace","value":"requestUpdates"},{"value":[{"text":"requestUpdates","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates~1requestUpdates\/fragments","op":"replace"}]}]}