{"metadata":{"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates(py)totalUpdates","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"totalUpdates"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"totalUpdates","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalUpdates","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/supportproviderssdk\/requestupdates\/totalupdates"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/requestupdates\/totalupdates"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"totalUpdates"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates\/totalUpdates","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The total unread comments on all the user’s requests.","type":"text"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestUpdates/totalUpdates":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates\/totalUpdates","type":"topic","kind":"symbol","navigatorTitle":[{"text":"totalUpdates","kind":"identifier"}],"abstract":[{"text":"The total unread comments on all the user’s requests.","type":"text"}],"role":"symbol","title":"totalUpdates","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalUpdates","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/supportproviderssdk\/requestupdates\/totalupdates"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestUpdates":{"abstract":[{"type":"text","text":"RequestUpdates object contains information about"},{"type":"text","text":" "},{"text":"unread comments on each request the user has open.","type":"text"}],"type":"topic","role":"symbol","title":"RequestUpdates","kind":"symbol","url":"\/documentation\/supportproviderssdk\/requestupdates","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestUpdates","kind":"identifier"}],"navigatorTitle":[{"text":"RequestUpdates","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"totalUpdates","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"totalUpdates","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"totalUpdates","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","value":"totalUpdates","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates~1totalUpdates\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates~1totalUpdates\/fragments","value":[{"kind":"identifier","text":"totalUpdates"}]},{"op":"replace","value":"ZDKRequestUpdates","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates\/fragments","value":[{"kind":"identifier","text":"ZDKRequestUpdates"}],"op":"replace"}]}]}