{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ticketFormsSettings"},{"kind":"text","text":": "},{"text":"TicketFormsSettings","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/TicketFormsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKTicketFormsSettings"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/ticketFormsSettings","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ticketFormsSettings"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupportSettings(py)ticketFormsSettings","title":"ticketFormsSettings","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ticketFormsSettings"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKTicketFormsSettings","text":"TicketFormsSettings","kind":"typeIdentifier"}],"modules":[{"name":"SupportProvidersSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/supportsettings\/ticketformssettings"]},{"paths":["\/documentation\/supportproviderssdk\/supportsettings\/ticketformssettings"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/TicketFormsSettings":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/TicketFormsSettings","url":"\/documentation\/supportproviderssdk\/ticketformssettings","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TicketFormsSettings","kind":"identifier"}],"abstract":[],"title":"TicketFormsSettings","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TicketFormsSettings"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings":{"kind":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings","title":"SupportSettings","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportSettings"}],"navigatorTitle":[{"text":"SupportSettings","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/ticketFormsSettings":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ticketFormsSettings"}],"type":"topic","title":"ticketFormsSettings","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ticketFormsSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TicketFormsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKTicketFormsSettings"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/ticketFormsSettings","url":"\/documentation\/supportproviderssdk\/supportsettings\/ticketformssettings","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ticketFormsSettings","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ticketFormsSettings"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"ZDKTicketFormsSettings","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/TicketFormsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKTicketFormsSettings"},{"kind":"text","text":" * "},{"text":"ticketFormsSettings","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1TicketFormsSettings\/title","value":"ZDKTicketFormsSettings"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1TicketFormsSettings\/fragments","value":[{"text":"ZDKTicketFormsSettings","kind":"identifier"}],"op":"replace"},{"value":"ZDKSupportSettings","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings\/fragments","value":[{"kind":"identifier","text":"ZDKSupportSettings"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1ticketFormsSettings\/title","value":"ticketFormsSettings","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1ticketFormsSettings\/fragments","value":[{"text":"ticketFormsSettings","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}