{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/parsearticles(_:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/parsearticles(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseArticles(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Parses a collection of Help Center json article objects.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseArticles"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!) -> [","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of ZDKHelpCenterArticle objects."}]}]}],"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"parseArticles","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!) -> [","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(cs)ZDKHelpCenterParser(im)parseArticles:","title":"parseArticles(_:)","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"parseArticles:"}]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser/parseArticles(_:)":{"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/parsearticles(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"parseArticles","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!) -> [","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseArticles(_:)","abstract":[{"type":"text","text":"Parses a collection of Help Center json article objects."}],"title":"parseArticles(_:)","role":"symbol","navigatorTitle":[{"text":"parseArticles:","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterParser","kind":"identifier"}],"title":"ZDKHelpCenterParser","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterParser","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser","abstract":[{"text":"A Help Center Parser class containing static and instance methods to parse json to objects.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"parseArticles:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseArticles:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"parseArticles:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseArticles(_:)\/title","value":"parseArticles:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseArticles(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"parseArticles:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser\/title","value":"ZDKHelpCenterParser"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser\/fragments","value":[{"text":"ZDKHelpCenterParser","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}