{"abstract":[{"type":"text","text":"The SDK has not yet authenticated during this session."}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notLoggedIn","kind":"identifier"}],"title":"ZDKAPILoginState.notLoggedIn","roleHeading":"Case","symbolKind":"case","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKAPILoginStateNotLoggedIn"}],"externalID":"c:@E@ZDKAPILoginState@ZDKAPILoginStateNotLoggedIn"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/notLoggedIn"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notLoggedIn","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkapiloginstate\/notloggedin"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkapiloginstate\/notloggedin"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState/notLoggedIn":{"url":"\/documentation\/supportproviderssdk\/zdkapiloginstate\/notloggedin","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notLoggedIn","kind":"identifier"}],"abstract":[{"type":"text","text":"The SDK has not yet authenticated during this session."}],"kind":"symbol","title":"ZDKAPILoginState.notLoggedIn","type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKAPILoginStateNotLoggedIn","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/notLoggedIn"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState":{"title":"ZDKAPILoginState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAPILoginState","kind":"identifier"}],"abstract":[{"type":"text","text":"ZDKAPI Login state."}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkapiloginstate","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKAPILoginState"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKAPILoginStateNotLoggedIn"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKAPILoginStateNotLoggedIn"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKAPILoginStateNotLoggedIn","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1notLoggedIn\/title","value":"ZDKAPILoginStateNotLoggedIn","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1notLoggedIn\/fragments","op":"replace","value":[{"text":"ZDKAPILoginStateNotLoggedIn","kind":"identifier"}]},{"value":"ZDKAPILoginState","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState\/fragments","value":[{"text":"ZDKAPILoginState","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}