{"kind":"symbol","abstract":[{"type":"text","text":"This models the “category” parameter.  This specifies that the search will be restricted to content that is in the given"},{"text":" ","type":"text"},{"text":"array of categories.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryIds"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"]! { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ZDKHelpCenterSearch(py)categoryIds","title":"categoryIds","roleHeading":"Instance Property","navigatorTitle":[{"text":"categoryIds","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"categoryIds","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"]!"}],"modules":[{"name":"SupportProvidersSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch\/categoryIds"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersearch\/categoryids"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersearch\/categoryids"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch"]]},"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSearch/categoryIds":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"categoryIds"}],"abstract":[{"type":"text","text":"This models the “category” parameter.  This specifies that the search will be restricted to content that is in the given"},{"type":"text","text":" "},{"text":"array of categories.","type":"text"}],"role":"symbol","title":"categoryIds","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch\/categoryIds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"categoryIds"},{"text":": [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersearch\/categoryids","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSearch":{"type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcentersearch","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterSearch","kind":"identifier"}],"abstract":[{"type":"text","text":"This class models a Help Center search.  For more details about Help Centre search please see:"},{"type":"text","text":" "},{"type":"text","text":"https:\/\/developer.zendesk.com\/rest_api\/docs\/help_center\/search"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterSearch"}],"title":"ZDKHelpCenterSearch","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"categoryIds","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"categoryIds","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"categoryIds"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch~1categoryIds\/title","value":"categoryIds","op":"replace"},{"value":[{"text":"categoryIds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch~1categoryIds\/fragments"},{"op":"replace","value":"ZDKHelpCenterSearch","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterSearch"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch\/fragments"}]}]}