{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkreachability\/currentreachabilitystatus()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkreachability\/currentreachabilitystatus()"]}],"metadata":{"navigatorTitle":[{"text":"currentReachabilityStatus","kind":"identifier"}],"role":"symbol","title":"currentReachabilityStatus()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"currentReachabilityStatus","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKNetworkStatus","text":"ZDKNetworkStatus"}],"externalID":"c:objc(cs)ZDKReachability(im)currentReachabilityStatus","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKReachability\/currentReachabilityStatus()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"currentReachabilityStatus","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus","preciseIdentifier":"c:@E@ZDKNetworkStatus","text":"ZDKNetworkStatus"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKReachability"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKReachability/currentReachabilityStatus()":{"navigatorTitle":[{"text":"currentReachabilityStatus","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkreachability\/currentreachabilitystatus()","type":"topic","title":"currentReachabilityStatus()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentReachabilityStatus","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKNetworkStatus","text":"ZDKNetworkStatus"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKReachability\/currentReachabilityStatus()"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus","kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKNetworkStatus","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdknetworkstatus","navigatorTitle":[{"kind":"identifier","text":"ZDKNetworkStatus"}],"title":"ZDKNetworkStatus"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKReachability":{"role":"symbol","navigatorTitle":[{"text":"ZDKReachability","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKReachability"}],"url":"\/documentation\/supportproviderssdk\/zdkreachability","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKReachability","title":"ZDKReachability","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"currentReachabilityStatus","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"currentReachabilityStatus"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus","preciseIdentifier":"c:@E@ZDKNetworkStatus","text":"ZDKNetworkStatus"},{"kind":"text","text":") "},{"text":"currentReachabilityStatus","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"currentReachabilityStatus","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKReachability~1currentReachabilityStatus()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"currentReachabilityStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKReachability~1currentReachabilityStatus()\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus\/title","op":"replace","value":"ZDKNetworkStatus"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKNetworkStatus"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKReachability\/title","value":"ZDKReachability"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKReachability\/fragments","op":"replace","value":[{"text":"ZDKReachability","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}