{"metadata":{"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ZDKHelpCenterProvider(im)getArticlesByLabels:withCallback:","title":"getArticlesByLabels(_:withCallback:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"getArticlesByLabels:withCallback:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getArticlesByLabels","kind":"identifier"},{"kind":"text","text":"(["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]!, ","kind":"text"},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"modules":[{"name":"SupportProvidersSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getArticlesByLabels"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"labels"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":" "},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"an array of labels used to filter articles by","type":"text"}],"type":"paragraph"}],"name":"labels"},{"content":[{"inlineContent":[{"text":"the callback that is invoked when a request is either successful or has errors","type":"text"}],"type":"paragraph"}],"name":"callback"}],"kind":"parameters"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"]]},"abstract":[{"text":"Fetch a list of articles for a given array of labels from a Help Center instance","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlesbylabels(_:withcallback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlesbylabels(_:withcallback:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticlesByLabels(_:withCallback:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider","title":"ZDKHelpCenterProvider","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getArticlesByLabels(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getArticlesByLabels:withCallback:"}],"title":"getArticlesByLabels(_:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getArticlesByLabels"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticlesByLabels(_:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlesbylabels(_:withcallback:)","abstract":[{"type":"text","text":"Fetch a list of articles for a given array of labels from a Help Center instance"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCallback":{"navigatorTitle":[{"text":"ZDKHelpCenterCallback","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercallback","title":"ZDKHelpCenterCallback","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"Callback block."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"getArticlesByLabels:withCallback:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getArticlesByLabels:withCallback:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"getArticlesByLabels:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"labels"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCallback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKHelpCenterCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"ZDKHelpCenterProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title"},{"op":"replace","value":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticlesByLabels(_:withCallback:)\/title","value":"getArticlesByLabels:withCallback:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticlesByLabels(_:withCallback:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getArticlesByLabels:withCallback:","kind":"identifier"}]},{"value":"ZDKHelpCenterCallback","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/title"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}