{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getArticleWithId"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"externalID":"c:objc(cs)ZDKHelpCenterProvider(im)getArticleWithId:withCallback:","title":"getArticleWithId(_:withCallback:)","role":"symbol","navigatorTitle":[{"text":"getArticleWithId:withCallback:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlewithid(_:withcallback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlewithid(_:withcallback:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticleWithId(_:withCallback:)"},"abstract":[{"type":"text","text":"Fetch an article by ID."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getArticleWithId","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"articleId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the article to fetch."}]}],"name":"articleId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback that is invoked when a request is either successful or has error."}]}],"name":"callback"}],"kind":"parameters"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider","title":"ZDKHelpCenterProvider","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCallback":{"navigatorTitle":[{"text":"ZDKHelpCenterCallback","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercallback","title":"ZDKHelpCenterCallback","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"Callback block."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getArticleWithId(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"getArticleWithId:withCallback:","kind":"identifier"}],"title":"getArticleWithId(_:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getArticleWithId"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticleWithId(_:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlewithid(_:withcallback:)","abstract":[{"text":"Fetch an article by ID.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"getArticleWithId:withCallback:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getArticleWithId:withCallback:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"getArticleWithId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"articleId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withCallback:"},{"text":"(","kind":"text"},{"text":"ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title","value":"ZDKHelpCenterProvider","op":"replace"},{"value":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/title","op":"replace","value":"ZDKHelpCenterCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/fragments","value":[{"text":"ZDKHelpCenterCallback","kind":"identifier"}]},{"op":"replace","value":"getArticleWithId:withCallback:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticleWithId(_:withCallback:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getArticleWithId:withCallback:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticleWithId(_:withCallback:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}