{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formatter","kind":"identifier"},{"kind":"text","text":"("},{"text":"forFormat","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"format","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!) -> ","kind":"text"},{"kind":"typeIdentifier","text":"DateFormatter","preciseIdentifier":"c:objc(cs)NSDateFormatter"},{"text":"!","kind":"text"}]}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"the formatter"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkdateutil\/formatter(forformat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkdateutil\/formatter(forformat:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDateUtil"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDateUtil\/formatter(forFormat:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"formatter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forFormat","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!) -> ","kind":"text"},{"text":"DateFormatter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDateFormatter"},{"kind":"text","text":"!"}],"symbolKind":"method","role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:objc(cs)ZDKDateUtil(cm)formatterForFormat:","navigatorTitle":[{"text":"formatterForFormat:","kind":"identifier"}],"roleHeading":"Type Method","title":"formatter(forFormat:)"},"abstract":[{"type":"text","text":"Get a cached thread local formatter for the requested date format."}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDateUtil":{"url":"\/documentation\/supportproviderssdk\/zdkdateutil","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDateUtil","title":"ZDKDateUtil","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ZDKDateUtil","kind":"identifier"}],"abstract":[{"text":"A date util.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKDateUtil","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDateUtil/formatter(forFormat:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"formatterForFormat:","kind":"identifier"}],"title":"formatter(forFormat:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formatter"},{"text":"(","kind":"text"},{"text":"forFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDateFormatter","text":"DateFormatter"},{"text":"!","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDateUtil\/formatter(forFormat:)","url":"\/documentation\/supportproviderssdk\/zdkdateutil\/formatter(forformat:)","abstract":[{"text":"Get a cached thread local formatter for the requested date format.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"formatterForFormat:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"formatterForFormat:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"NSDateFormatter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDateFormatter"},{"text":" *) ","kind":"text"},{"text":"formatterForFormat:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"format","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDateUtil\/title","op":"replace","value":"ZDKDateUtil"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDateUtil\/fragments","value":[{"kind":"identifier","text":"ZDKDateUtil"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDateUtil~1formatter(forFormat:)\/title","op":"replace","value":"formatterForFormat:"},{"value":[{"text":"+ ","kind":"text"},{"text":"formatterForFormat:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDateUtil~1formatter(forFormat:)\/fragments"}]}]}