{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A model for recording the last search in Help Center."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}],"title":"ZDKHelpCenterLastSearch","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ZDKHelpCenterLastSearch","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/init(query:resultsCount:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/query","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/results_count"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/toJson()"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterLastSearch/query":{"role":"symbol","title":"query","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The last search query performed."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/query","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"query"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch\/query"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterLastSearch/results_count":{"role":"symbol","title":"results_count","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"results_count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The result count for the last search query."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/results_count","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"results_count"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch\/results_count"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterLastSearch/toJson()":{"role":"symbol","title":"toJson()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Get the json representation for this object."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/toJson()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"toJson"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch\/tojson()"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ"},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterLastSearch":{"role":"symbol","title":"ZDKHelpCenterLastSearch","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}],"abstract":[{"type":"text","text":"A model for recording the last search in Help Center."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterLastSearch/init(query:resultsCount:)":{"role":"symbol","title":"init(query:resultsCount:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"resultsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Create a new last search model."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/init(query:resultsCount:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithQuery:resultsCount:"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch\/init(query:resultscount:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKHelpCenterLastSearch"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/query","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/results_count"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/init(query:resultsCount:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/toJson()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterLastSearch"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch~1query\/title","value":"query"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch~1query\/fragments","value":[{"kind":"identifier","text":"query"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch~1results_count\/title","value":"results_count"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch~1results_count\/fragments","value":[{"kind":"identifier","text":"results_count"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch~1toJson()\/title","value":"toJson"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch~1toJson()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJson"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch\/title","value":"ZDKHelpCenterLastSearch"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch~1init(query:resultsCount:)\/title","value":"initWithQuery:resultsCount:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch~1init(query:resultsCount:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQuery:resultsCount:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}