{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterParser"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterparser"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterparser"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Help Center Parser class containing static and instance methods to parse json to objects."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterParser"}],"title":"ZDKHelpCenterParser","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ZDKHelpCenterParser","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterParser"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/init(dictionary:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseArticleSearchResults(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseArticles(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseArticles(withRootKey:withRootKey:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseFlatArticles(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/createAuthorLookup(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/createCategoryLookup(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/createSectionLookup(_:)"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser/createAuthorLookup(_:)":{"role":"symbol","title":"createAuthorLookup(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAuthorLookup"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Parses a json array of author objects."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/createAuthorLookup(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createAuthorLookup:"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/createauthorlookup(_:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser/createCategoryLookup(_:)":{"role":"symbol","title":"createCategoryLookup(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCategoryLookup"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Parses a json array of Help Center categories."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/createCategoryLookup(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createCategoryLookup:"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/createcategorylookup(_:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser/parseArticleSearchResults(_:)":{"role":"symbol","title":"parseArticleSearchResults(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseArticleSearchResults"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Parses a collection of Help Center search results into an array of article objects."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseArticleSearchResults(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parseArticleSearchResults:"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/parsearticlesearchresults(_:)"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser/init(dictionary:)":{"role":"symbol","title":"init(dictionary:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"dictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"abstract":[{"type":"text","text":"Creates an ZDKHelpCentreParser object and parses json dictionary into"},{"type":"text","text":" "},{"type":"text","text":"categoryLookup, sectionLookup and userLookup properties if they exist in the json."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/init(dictionary:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/init(dictionary:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser/parseFlatArticles(_:)":{"role":"symbol","title":"parseFlatArticles(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseFlatArticles"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Parses a collection of Help Center json article objects, section objects and category objects"},{"type":"text","text":" "},{"type":"text","text":"into a FlatArticle objects and puts them in alphabetical order."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseFlatArticles(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parseFlatArticles:"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/parseflatarticles(_:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser/createSectionLookup(_:)":{"role":"symbol","title":"createSectionLookup(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createSectionLookup"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Parses a json array of Help Center sections."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/createSectionLookup(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createSectionLookup:"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/createsectionlookup(_:)"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser":{"role":"symbol","title":"ZDKHelpCenterParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterParser"}],"abstract":[{"type":"text","text":"A Help Center Parser class containing static and instance methods to parse json to objects."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterParser"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser/parseArticles(_:)":{"role":"symbol","title":"parseArticles(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseArticles"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Parses a collection of Help Center json article objects."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseArticles(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parseArticles:"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/parsearticles(_:)"},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser/parseArticles(withRootKey:withRootKey:)":{"role":"symbol","title":"parseArticles(withRootKey:withRootKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseArticles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withRootKey"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"withRootKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Parse a collection of Help Center json article objects beginning at root."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseArticles(withRootKey:withRootKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parseArticlesWithRootKey:withRootKey:"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/parsearticles(withrootkey:withrootkey:)"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKHelpCenterParser"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterParser"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKHelpCenterParser"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/init(dictionary:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseArticleSearchResults(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseArticles(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseArticles(withRootKey:withRootKey:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseFlatArticles(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/createAuthorLookup(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/createCategoryLookup(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/createSectionLookup(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterParser"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1createAuthorLookup(_:)\/title","value":"createAuthorLookup:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1createAuthorLookup(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createAuthorLookup:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1createCategoryLookup(_:)\/title","value":"createCategoryLookup:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1createCategoryLookup(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createCategoryLookup:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseArticleSearchResults(_:)\/title","value":"parseArticleSearchResults:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseArticleSearchResults(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseArticleSearchResults:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1init(dictionary:)\/title","value":"initWithDictionary:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1init(dictionary:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseFlatArticles(_:)\/title","value":"parseFlatArticles:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseFlatArticles(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseFlatArticles:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1createSectionLookup(_:)\/title","value":"createSectionLookup:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1createSectionLookup(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createSectionLookup:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser\/title","value":"ZDKHelpCenterParser"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterParser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseArticles(_:)\/title","value":"parseArticles:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseArticles(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseArticles:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseArticles(withRootKey:withRootKey:)\/title","value":"parseArticlesWithRootKey:withRootKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseArticles(withRootKey:withRootKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseArticlesWithRootKey:withRootKey:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}