{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKJsonUtil"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/array(withPropertiesOfObject:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/cleanJSONArrayVal(_:key:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/cleanJSONVal(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/cleanJSONVal(_:key:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertArray(ofJsonObjects:toArrayOfType:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertJsonObject(_:toObjectOfType:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertObject(toDictionary:for:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKJsonUtil"}],"title":"ZDKJsonUtil","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ZDKJsonUtil","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKJsonUtil"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/convertJsonObject(_:toObjectOfType:)":{"role":"symbol","title":"convertJsonObject(_:toObjectOfType:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertJsonObject"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"toObjectOfType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"!) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Convert JSON based dictionary to an object of type Class"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertJsonObject(_:toObjectOfType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"convertJsonObject:toObjectOfType:"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/convertjsonobject(_:toobjectoftype:)"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/cleanJSONVal(_:key:)":{"role":"symbol","title":"cleanJSONVal(_:key:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanJSONVal"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Checks the return value for NSNull and converts to nil if found."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/cleanJSONVal(_:key:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cleanJSONVal:key:"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/cleanjsonval(_:key:)"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil":{"role":"symbol","title":"ZDKJsonUtil","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKJsonUtil"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKJsonUtil"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/cleanJSONVal(_:)":{"role":"symbol","title":"cleanJSONVal(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanJSONVal"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Check the value for NSNull."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/cleanJSONVal(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cleanJSONVal:"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/cleanjsonval(_:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/convertObject(toDictionary:for:)":{"role":"symbol","title":"convertObject(toDictionary:for:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toDictionary"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"!) -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Generates a dictionary representation of a classes properties."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertObject(toDictionary:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"convertObjectToDictionary:forClass:"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/convertobject(todictionary:for:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/convertArray(ofJsonObjects:toArrayOfType:)":{"role":"symbol","title":"convertArray(ofJsonObjects:toArrayOfType:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertArray"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofJsonObjects"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"toArrayOfType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Converts an array of json into an array of objects. The objects"},{"type":"text","text":" "},{"type":"text","text":"in the return array will be instances of the class that was passed in."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertArray(ofJsonObjects:toArrayOfType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"convertArrayOfJsonObjects:toArrayOfType:"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/convertarray(ofjsonobjects:toarrayoftype:)"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/cleanJSONArrayVal(_:key:)":{"role":"symbol","title":"cleanJSONArrayVal(_:key:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanJSONArrayVal"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Checks the return value for NSNull and converts to an empty array if found."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/cleanJSONArrayVal(_:key:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cleanJSONArrayVal:key:"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/cleanjsonarrayval(_:key:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/array(withPropertiesOfObject:)":{"role":"symbol","title":"array(withPropertiesOfObject:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"array"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPropertiesOfObject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Fetch Array of properties of a class"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/array(withPropertiesOfObject:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"arrayWithPropertiesOfObject:"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/array(withpropertiesofobject:)"},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKJsonUtil"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKJsonUtil"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKJsonUtil"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/array(withPropertiesOfObject:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/cleanJSONArrayVal(_:key:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/cleanJSONVal(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/cleanJSONVal(_:key:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertArray(ofJsonObjects:toArrayOfType:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertJsonObject(_:toObjectOfType:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertObject(toDictionary:for:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKJsonUtil"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertJsonObject(_:toObjectOfType:)\/title","value":"convertJsonObject:toObjectOfType:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertJsonObject(_:toObjectOfType:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"convertJsonObject:toObjectOfType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1cleanJSONVal(_:key:)\/title","value":"cleanJSONVal:key:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1cleanJSONVal(_:key:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cleanJSONVal:key:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/title","value":"ZDKJsonUtil"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/fragments","value":[{"kind":"identifier","text":"ZDKJsonUtil"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1cleanJSONVal(_:)\/title","value":"cleanJSONVal:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1cleanJSONVal(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cleanJSONVal:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertObject(toDictionary:for:)\/title","value":"convertObjectToDictionary:forClass:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertObject(toDictionary:for:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"convertObjectToDictionary:forClass:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertArray(ofJsonObjects:toArrayOfType:)\/title","value":"convertArrayOfJsonObjects:toArrayOfType:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertArray(ofJsonObjects:toArrayOfType:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"convertArrayOfJsonObjects:toArrayOfType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1cleanJSONArrayVal(_:key:)\/title","value":"cleanJSONArrayVal:key:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1cleanJSONArrayVal(_:key:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cleanJSONArrayVal:key:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1array(withPropertiesOfObject:)\/title","value":"arrayWithPropertiesOfObject:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1array(withPropertiesOfObject:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"arrayWithPropertiesOfObject:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}