{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/checkbox","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","externalID":"c:@E@ZDKTicketFieldType@ZDKTicketFieldTypeCheckbox","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldTypeCheckbox"}],"symbolKind":"case","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkbox"}],"role":"symbol","title":"ZDKTicketFieldType.checkbox"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Ticket field check box type"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/checkbox"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/checkbox"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"checkbox","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldType","kind":"identifier"}],"title":"ZDKTicketFieldType","abstract":[{"text":"Ticket field type","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype","navigatorTitle":[{"text":"ZDKTicketFieldType","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/checkbox":{"navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldTypeCheckbox"}],"abstract":[{"text":"Ticket field check box type","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkbox"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/checkbox","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/checkbox","title":"ZDKTicketFieldType.checkbox","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKTicketFieldTypeCheckbox","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKTicketFieldTypeCheckbox"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKTicketFieldTypeCheckbox","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/title","value":"ZDKTicketFieldType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/fragments","value":[{"text":"ZDKTicketFieldType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1checkbox\/title","value":"ZDKTicketFieldTypeCheckbox","op":"replace"},{"op":"replace","value":[{"text":"ZDKTicketFieldTypeCheckbox","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1checkbox\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}