{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/decimal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/decimal"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType"]]},"abstract":[{"type":"text","text":"Ticket field decimal box type"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decimal"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldTypeDecimal"}],"symbolKind":"case","title":"ZDKTicketFieldType.decimal","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decimal"}],"externalID":"c:@E@ZDKTicketFieldType@ZDKTicketFieldTypeDecimal","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Case","role":"symbol"},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/decimal","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldType","kind":"identifier"}],"title":"ZDKTicketFieldType","abstract":[{"text":"Ticket field type","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype","navigatorTitle":[{"text":"ZDKTicketFieldType","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/decimal":{"abstract":[{"type":"text","text":"Ticket field decimal box type"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/decimal","role":"symbol","title":"ZDKTicketFieldType.decimal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decimal"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldTypeDecimal"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/decimal","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKTicketFieldTypeDecimal"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKTicketFieldTypeDecimal"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKTicketFieldTypeDecimal"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/title","value":"ZDKTicketFieldType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKTicketFieldType"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1decimal\/title","op":"replace","value":"ZDKTicketFieldTypeDecimal"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1decimal\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldTypeDecimal"}]}]}]}