{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"title":"array(withPropertiesOfObject:)","symbolKind":"method","navigatorTitle":[{"text":"arrayWithPropertiesOfObject:","kind":"identifier"}],"externalID":"c:objc(cs)ZDKJsonUtil(cm)arrayWithPropertiesOfObject:","roleHeading":"Type Method","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"array"},{"text":"(","kind":"text"},{"text":"withPropertiesOfObject","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"},{"text":"!) -> ","kind":"text"},{"text":"NSMutableArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"text":"!","kind":"text"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"array","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPropertiesOfObject","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"text":"!) -> ","kind":"text"},{"text":"NSMutableArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"class to get properties for"}],"type":"paragraph"}],"name":"aClass"}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"text":"NSMutableArray of properties for the class specified","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/array(withPropertiesOfObject:)","interfaceLanguage":"swift"},"abstract":[{"text":"Fetch Array of properties of a class","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil\/array(withpropertiesofobject:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil\/array(withpropertiesofobject:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/array(withPropertiesOfObject:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"array","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPropertiesOfObject","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!"}],"abstract":[{"text":"Fetch Array of properties of a class","type":"text"}],"title":"array(withPropertiesOfObject:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"arrayWithPropertiesOfObject:"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/array(withPropertiesOfObject:)","kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/array(withpropertiesofobject:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil":{"url":"\/documentation\/supportproviderssdk\/zdkjsonutil","navigatorTitle":[{"kind":"identifier","text":"ZDKJsonUtil"}],"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKJsonUtil"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil","type":"topic","role":"symbol","title":"ZDKJsonUtil"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"arrayWithPropertiesOfObject:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"arrayWithPropertiesOfObject:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSMutableArray","kind":"typeIdentifier","text":"NSMutableArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"arrayWithPropertiesOfObject:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@Class","text":"Class"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"aClass"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1array(withPropertiesOfObject:)\/title","value":"arrayWithPropertiesOfObject:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"arrayWithPropertiesOfObject:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1array(withPropertiesOfObject:)\/fragments"},{"value":"ZDKJsonUtil","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/fragments","op":"replace","value":[{"text":"ZDKJsonUtil","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}