{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle\/parseDeflectionSearchResults(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Parse a collection of simple articles returned by the suggested articles provider."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle"]]},"metadata":{"title":"parseDeflectionSearchResults(_:)","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"parseDeflectionSearchResults","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!) -> ["},{"kind":"keyword","text":"Any"},{"text":"]!","kind":"text"}],"navigatorTitle":[{"text":"parseDeflectionSearchResults:","kind":"identifier"}],"roleHeading":"Type Method","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:objc(cs)ZDKHelpCenterSimpleArticle(cm)parseDeflectionSearchResults:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parseDeflectionSearchResults","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"json"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!) -> ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle\/parsedeflectionsearchresults(_:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle\/parsedeflectionsearchresults(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSimpleArticle/parseDeflectionSearchResults(_:)":{"navigatorTitle":[{"kind":"identifier","text":"parseDeflectionSearchResults:"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle\/parseDeflectionSearchResults(_:)","abstract":[{"type":"text","text":"Parse a collection of simple articles returned by the suggested articles provider."}],"type":"topic","role":"symbol","title":"parseDeflectionSearchResults(_:)","kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle\/parsedeflectionsearchresults(_:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"parseDeflectionSearchResults","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!) -> [","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!","kind":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSimpleArticle":{"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle","title":"ZDKHelpCenterSimpleArticle","navigatorTitle":[{"text":"ZDKHelpCenterSimpleArticle","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterSimpleArticle"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle","abstract":[{"type":"text","text":"This is a model object for a simple article returned by the suggested article provider"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"parseDeflectionSearchResults:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"parseDeflectionSearchResults:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"text":" *) ","kind":"text"},{"text":"parseDeflectionSearchResults:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle~1parseDeflectionSearchResults(_:)\/title","op":"replace","value":"parseDeflectionSearchResults:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle~1parseDeflectionSearchResults(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"parseDeflectionSearchResults:","kind":"identifier"}]},{"value":"ZDKHelpCenterSimpleArticle","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterSimpleArticle"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle\/fragments"}]}]}