{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"maxAttachmentSize"}],"roleHeading":"Instance Property","title":"maxAttachmentSize","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxAttachmentSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"symbolKind":"property","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettings(py)maxAttachmentSize"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/attachmentsettings\/maxattachmentsize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/attachmentsettings\/maxattachmentsize"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings\/maxAttachmentSize","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxAttachmentSize"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/AttachmentSettings":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AttachmentSettings"}],"title":"AttachmentSettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AttachmentSettings"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/attachmentsettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/AttachmentSettings/maxAttachmentSize":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"maxAttachmentSize","kind":"identifier"}],"title":"maxAttachmentSize","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxAttachmentSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/attachmentsettings\/maxattachmentsize","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings\/maxAttachmentSize","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"maxAttachmentSize","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"maxAttachmentSize","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"text":"maxAttachmentSize","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"ZDKAttachmentSettings","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings\/title"},{"value":[{"kind":"identifier","text":"ZDKAttachmentSettings"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings~1maxAttachmentSize\/title","value":"maxAttachmentSize"},{"value":[{"kind":"identifier","text":"maxAttachmentSize"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings~1maxAttachmentSize\/fragments"}]}]}