{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRequestForId"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","text":"RequestForStorage"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/requeststorage\/getrequestforid(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/requeststorage\/getrequestforid(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage\/getRequestForId(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRequestForId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage"},{"kind":"text","text":"?"}],"title":"getRequestForId(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestStorage(im)getRequestForId:","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getRequestForId:"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestStorage/getRequestForId(_:)":{"role":"symbol","title":"getRequestForId(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRequestForId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage\/getRequestForId(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getRequestForId:"}],"url":"\/documentation\/supportproviderssdk\/requeststorage\/getrequestforid(_:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestStorage":{"role":"symbol","title":"RequestStorage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestStorage"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestStorage"}],"url":"\/documentation\/supportproviderssdk\/requeststorage"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage":{"role":"symbol","title":"RequestForStorage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestForStorage"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestForStorage"}],"url":"\/documentation\/supportproviderssdk\/requestforstorage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getRequestForId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRequestForId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","text":"ZDKRequestForStorage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getRequestForId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"requestId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage~1getRequestForId(_:)\/title","value":"getRequestForId:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage~1getRequestForId(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRequestForId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/title","value":"ZDKRequestStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/fragments","value":[{"kind":"identifier","text":"ZDKRequestStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/title","value":"ZDKRequestForStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/fragments","value":[{"kind":"identifier","text":"ZDKRequestForStorage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}