{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sections"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel","text":"HelpCenterSectionViewModel"},{"text":"]","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterCategoryViewModel"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterCategoryViewModel\/sections","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/helpcentercategoryviewmodel\/sections"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/helpcentercategoryviewmodel\/sections"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sections","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel","text":"HelpCenterSectionViewModel"},{"text":"]","kind":"text"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterCategoryViewModel(py)sections","role":"symbol","roleHeading":"Instance Property","title":"sections","navigatorTitle":[{"kind":"identifier","text":"sections"}],"modules":[{"name":"SupportProvidersSDK"}]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterCategoryViewModel":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterCategoryViewModel","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterCategoryViewModel","kind":"symbol","navigatorTitle":[{"text":"HelpCenterCategoryViewModel","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/helpcentercategoryviewmodel","role":"symbol","title":"HelpCenterCategoryViewModel"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSectionViewModel":{"url":"\/documentation\/supportproviderssdk\/helpcentersectionviewmodel","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HelpCenterSectionViewModel","kind":"identifier"}],"title":"HelpCenterSectionViewModel","navigatorTitle":[{"kind":"identifier","text":"HelpCenterSectionViewModel"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterCategoryViewModel/sections":{"abstract":[],"url":"\/documentation\/supportproviderssdk\/helpcentercategoryviewmodel\/sections","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sections"}],"type":"topic","title":"sections","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterCategoryViewModel\/sections","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sections","kind":"identifier"},{"text":": [","kind":"text"},{"text":"HelpCenterSectionViewModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel"},{"text":"]","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"sections","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sections"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSArray<ZDKHelpCenterSectionViewModel *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"sections","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"ZDKHelpCenterCategoryViewModel","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterCategoryViewModel\/title"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterCategoryViewModel"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterCategoryViewModel\/fragments"},{"value":"ZDKHelpCenterSectionViewModel","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterSectionViewModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterCategoryViewModel~1sections\/title","op":"replace","value":"sections"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterCategoryViewModel~1sections\/fragments","value":[{"kind":"identifier","text":"sections"}],"op":"replace"}]}]}