{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"section"},{"text":" ","kind":"text"},{"text":"newSection","kind":"internalParam"},{"kind":"text","text":": "},{"text":"HelpCenterSectionViewModel","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterCategoryViewModel","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterCategoryViewModel","kind":"typeIdentifier","text":"HelpCenterCategoryViewModel"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/helpcentercategoryviewmodel\/update(section:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/helpcentercategoryviewmodel\/update(section:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"section"},{"kind":"text","text":": "},{"text":"HelpCenterSectionViewModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel"},{"text":") -> ","kind":"text"},{"text":"HelpCenterCategoryViewModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterCategoryViewModel"}],"navigatorTitle":[{"text":"updateWithSection:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterCategoryViewModel(im)updateWithSection:","roleHeading":"Instance Method","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","title":"update(section:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterCategoryViewModel"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterCategoryViewModel\/update(section:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSectionViewModel":{"url":"\/documentation\/supportproviderssdk\/helpcentersectionviewmodel","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HelpCenterSectionViewModel","kind":"identifier"}],"title":"HelpCenterSectionViewModel","navigatorTitle":[{"kind":"identifier","text":"HelpCenterSectionViewModel"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterCategoryViewModel/update(section:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"section"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel","text":"HelpCenterSectionViewModel","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HelpCenterCategoryViewModel","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterCategoryViewModel","kind":"typeIdentifier"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterCategoryViewModel\/update(section:)","navigatorTitle":[{"kind":"identifier","text":"updateWithSection:"}],"url":"\/documentation\/supportproviderssdk\/helpcentercategoryviewmodel\/update(section:)","role":"symbol","title":"update(section:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterCategoryViewModel":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterCategoryViewModel","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterCategoryViewModel","kind":"symbol","navigatorTitle":[{"text":"HelpCenterCategoryViewModel","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/helpcentercategoryviewmodel","role":"symbol","title":"HelpCenterCategoryViewModel"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"updateWithSection:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"updateWithSection:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterCategoryViewModel","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterCategoryViewModel","kind":"typeIdentifier","text":"ZDKHelpCenterCategoryViewModel"},{"text":" *) ","kind":"text"},{"text":"updateWithSection:","kind":"identifier"},{"kind":"text","text":"("},{"text":"ZDKHelpCenterSectionViewModel","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"newSection"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel\/title","value":"ZDKHelpCenterSectionViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel\/fragments","value":[{"text":"ZDKHelpCenterSectionViewModel","kind":"identifier"}]},{"value":"updateWithSection:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterCategoryViewModel~1update(section:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"updateWithSection:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterCategoryViewModel~1update(section:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterCategoryViewModel\/title","op":"replace","value":"ZDKHelpCenterCategoryViewModel"},{"value":[{"text":"ZDKHelpCenterCategoryViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterCategoryViewModel\/fragments","op":"replace"}]}]}