{"abstract":[{"type":"text","text":"Gets details of any updates to requests for this device."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getUpdatesForDevice"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"RequestUpdates","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"callback supplies a optional "},{"code":"ZDKRequestUpdates","type":"codeVoice"},{"text":" object that is either nil if unsuccessful","type":"text"},{"type":"text","text":" "},{"text":"or ","type":"text"},{"code":"nonnil","type":"codeVoice"},{"text":" if successful.","type":"text"}]}],"name":"callback"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"code":"ZDKRequestUpdates","type":"codeVoice"},{"type":"text","text":" are cached for up to one hour. Subsequent calls to this method within"},{"text":" ","type":"text"},{"text":"the hour will return the same object without querying the network. Calling this method once","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the hour has expired will query the network again, and cache the new results for the next"},{"type":"text","text":" "},{"text":"hour.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If using the Zendesk UI, viewing a request will update the cached "},{"code":"ZDKRequestUpdates","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"to remove the viewed request. If using the providers only, a request can be removed from"},{"type":"text","text":" "},{"type":"text","text":"the cached "},{"type":"codeVoice","code":"ZDKRequestUpdates"},{"type":"text","text":" by calling "},{"code":"markRequestAsRead:","type":"codeVoice"},{"type":"text","text":"."}]}]}],"metadata":{"role":"symbol","externalID":"c:@CM@SupportProvidersSDK@@objc(cs)ZDKRequestProvider(im)getUpdatesForDeviceWithCallback:","navigatorTitle":[{"kind":"identifier","text":"getUpdatesForDeviceWithCallback:"}],"title":"getUpdatesForDevice(callback:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getUpdatesForDevice"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates","text":"RequestUpdates"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"SupportProvidersSDK"}],"extendedModule":"SupportProvidersSDK","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getupdatesfordevice(callback:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getupdatesfordevice(callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getUpdatesForDevice(callback:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestUpdates":{"abstract":[{"type":"text","text":"RequestUpdates object contains information about"},{"type":"text","text":" "},{"text":"unread comments on each request the user has open.","type":"text"}],"type":"topic","role":"symbol","title":"RequestUpdates","kind":"symbol","url":"\/documentation\/supportproviderssdk\/requestupdates","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestUpdates","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestUpdates","kind":"identifier"}],"navigatorTitle":[{"text":"RequestUpdates","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"title":"ZDKRequestProvider","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKRequestProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKRequestProvider","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getUpdatesForDevice(callback:)":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getUpdatesForDevice(callback:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getUpdatesForDeviceWithCallback:"}],"title":"getUpdatesForDevice(callback:)","abstract":[{"text":"Gets details of any updates to requests for this device.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getUpdatesForDevice"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates","text":"RequestUpdates","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getupdatesfordevice(callback:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"getUpdatesForDeviceWithCallback:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getUpdatesForDeviceWithCallback:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"getUpdatesForDeviceWithCallback:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(ZDKRequestUpdates *)","preciseIdentifier":"c:BFv(#*$@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates)"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"ZDKRequestUpdates","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates\/title"},{"value":[{"kind":"identifier","text":"ZDKRequestUpdates"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestUpdates\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title","op":"replace","value":"ZDKRequestProvider"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKRequestProvider"}]},{"value":"getUpdatesForDeviceWithCallback:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getUpdatesForDevice(callback:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getUpdatesForDevice(callback:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"getUpdatesForDeviceWithCallback:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}