{"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"systemOptions"}],"title":"systemOptions","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","externalID":"c:objc(cs)ZDKTicketField(py)systemOptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"systemOptions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)ZDKTicketFieldSystemOption","text":"ZDKTicketFieldSystemOption","kind":"typeIdentifier"},{"text":"]!","kind":"text"}],"roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/systemOptions","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfield\/systemoptions"]},{"paths":["\/documentation\/supportproviderssdk\/zdkticketfield\/systemoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField"]]},"sections":[],"abstract":[{"text":"Ticket field system options, this field will only be populated for ","type":"text"},{"type":"codeVoice","code":"ZDKTicketFieldTypeStatus"},{"text":", ","type":"text"},{"code":"ZDKTicketFieldTypePriority","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"ZDKTicketFieldTypeTicketType"},{"type":"text","text":" field types"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"systemOptions"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption","text":"ZDKTicketFieldSystemOption","preciseIdentifier":"c:objc(cs)ZDKTicketFieldSystemOption","kind":"typeIdentifier"},{"kind":"text","text":"]! { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/systemOptions":{"kind":"symbol","title":"systemOptions","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/systemOptions","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"systemOptions","kind":"identifier"},{"kind":"text","text":": ["},{"text":"ZDKTicketFieldSystemOption","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKTicketFieldSystemOption"},{"kind":"text","text":"]!"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfield\/systemoptions","role":"symbol","abstract":[{"type":"text","text":"Ticket field system options, this field will only be populated for "},{"type":"codeVoice","code":"ZDKTicketFieldTypeStatus"},{"type":"text","text":", "},{"type":"codeVoice","code":"ZDKTicketFieldTypePriority"},{"type":"text","text":" and "},{"type":"codeVoice","code":"ZDKTicketFieldTypeTicketType"},{"type":"text","text":" field types"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"systemOptions"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField":{"url":"\/documentation\/supportproviderssdk\/zdkticketfield","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Ticket field class","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKTicketField"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField","title":"ZDKTicketField","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketField"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldSystemOption":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldSystemOption"}],"title":"ZDKTicketFieldSystemOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldSystemOption","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfieldsystemoption","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption","abstract":[{"text":"Ticket Field System Option (for ","type":"text"},{"code":"ZDKTicketFieldTypeStatus","type":"codeVoice"},{"type":"text","text":", "},{"code":"ZDKTicketFieldTypePriority","type":"codeVoice"},{"type":"text","text":" and "},{"code":"ZDKTicketFieldTypeTicketType","type":"codeVoice"},{"text":" ticket field types)","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"systemOptions"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"systemOptions","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<ZDKTicketFieldSystemOption *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"systemOptions"}]}],"kind":"declarations"},"op":"replace"},{"value":"systemOptions","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1systemOptions\/title"},{"value":[{"text":"systemOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1systemOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField\/title","value":"ZDKTicketField"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField\/fragments","op":"replace","value":[{"text":"ZDKTicketField","kind":"identifier"}]},{"op":"replace","value":"ZDKTicketFieldSystemOption","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption\/fragments","value":[{"text":"ZDKTicketFieldSystemOption","kind":"identifier"}]}]}]}