{"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getSupportSettingsWithCallback:"}],"roleHeading":"Type Method","title":"getSupportSettings(callback:)","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getSupportSettings"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"SupportSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupportSettings"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupportSettingsProvider(cm)getSupportSettingsWithCallback:","role":"symbol"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdksupportsettingsprovider\/getsupportsettings(callback:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdksupportsettingsprovider\/getsupportsettings(callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getSupportSettings","kind":"identifier"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupportSettings","text":"SupportSettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportSettingsProvider\/getSupportSettings(callback:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportSettingsProvider"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKSupportSettingsProvider/getSupportSettings(callback:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSupportSettings"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"SupportSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupportSettings"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportSettingsProvider\/getSupportSettings(callback:)","role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdksupportsettingsprovider\/getsupportsettings(callback:)","title":"getSupportSettings(callback:)","navigatorTitle":[{"text":"getSupportSettingsWithCallback:","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKSupportSettingsProvider":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportSettingsProvider","url":"\/documentation\/supportproviderssdk\/zdksupportsettingsprovider","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKSupportSettingsProvider"}],"type":"topic","title":"ZDKSupportSettingsProvider","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKSupportSettingsProvider"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportSettings","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SupportSettings"}],"role":"symbol","title":"SupportSettings","url":"\/documentation\/supportproviderssdk\/supportsettings","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getSupportSettingsWithCallback:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getSupportSettingsWithCallback:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"getSupportSettingsWithCallback:"},{"kind":"text","text":"("},{"text":"void (^)(ZDKSupportSettings *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@SupportProvidersSDK@objc(cs)ZDKSupportSettings)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportSettingsProvider~1getSupportSettings(callback:)\/title","value":"getSupportSettingsWithCallback:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportSettingsProvider~1getSupportSettings(callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getSupportSettingsWithCallback:","kind":"identifier"}],"op":"replace"},{"value":"ZDKSupportSettingsProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportSettingsProvider\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportSettingsProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKSupportSettingsProvider"}]},{"value":"ZDKSupportSettings","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings\/fragments","value":[{"text":"ZDKSupportSettings","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}