{"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/frameworkStringsBundle()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"frameworkStringsBundle","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"languages":["swift"]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The frameworks strings NSBundle or nil if the SDK bundle was not found."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Gets the framework strings bundle."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"frameworkStringsBundle","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle"},{"text":"!","kind":"text"}],"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","role":"symbol","roleHeading":"Type Method","title":"frameworkStringsBundle()","externalID":"c:objc(cs)ZDKBundleUtils(cm)frameworkStringsBundle","navigatorTitle":[{"kind":"identifier","text":"frameworkStringsBundle"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkbundleutils\/frameworkstringsbundle()"]},{"paths":["\/documentation\/supportproviderssdk\/zdkbundleutils\/frameworkstringsbundle()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils/frameworkStringsBundle()":{"title":"frameworkStringsBundle()","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/frameworkStringsBundle()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"frameworkStringsBundle","kind":"identifier"}],"abstract":[{"text":"Gets the framework strings bundle.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frameworkStringsBundle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle"},{"text":"!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkbundleutils\/frameworkstringsbundle()"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils","navigatorTitle":[{"text":"ZDKBundleUtils","kind":"identifier"}],"title":"ZDKBundleUtils","abstract":[{"type":"text","text":"Util for working with SupportSDK bundles."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKBundleUtils"}],"url":"\/documentation\/supportproviderssdk\/zdkbundleutils","type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"frameworkStringsBundle","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"frameworkStringsBundle"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"NSBundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"frameworkStringsBundle"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1frameworkStringsBundle()\/title","op":"replace","value":"frameworkStringsBundle"},{"value":[{"kind":"text","text":"+ "},{"text":"frameworkStringsBundle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1frameworkStringsBundle()\/fragments"},{"op":"replace","value":"ZDKBundleUtils","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils\/title"},{"value":[{"text":"ZDKBundleUtils","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils\/fragments"}]}]}