{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/addcomment(_:forrequestid:attachments:withcallback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/addcomment(_:forrequestid:attachments:withcallback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"addComment(_:forRequestId:attachments:withCallback:)","roleHeading":"Instance Method","externalID":"c:objc(cs)ZDKRequestProvider(im)addComment:forRequestId:attachments:withCallback:","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"addComment:forRequestId:attachments:withCallback:","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addComment"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"forRequestId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!, "},{"text":"attachments","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!, ","kind":"text"},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"text":"ZDKRequestAddCommentCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestAddCommentCallback"},{"kind":"text","text":"!)"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/addComment(_:forRequestId:attachments:withCallback:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addComment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"comment","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"forRequestId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"requestId","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"attachments","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestAddCommentCallback","text":"ZDKRequestAddCommentCallback","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestAddCommentCallback"},{"kind":"text","text":"!)"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The text of the comment to create"}]}],"name":"comment"},{"name":"requestId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Id of a request to add this comment to"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"List of ZDKUploadResponse objects. Can be nil"}],"type":"paragraph"}],"name":"attachments"},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback that will deliver a ZDKComment."}]}]}]}],"sections":[],"abstract":[{"type":"text","text":"Add a comment message to a request with attachments on behalf of the end-user."},{"type":"text","text":" "},{"text":"It will also get an access token if one has not been previously stored.","type":"text"}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKRequestProvider"}],"type":"topic","abstract":[],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","role":"symbol","navigatorTitle":[{"text":"ZDKRequestProvider","kind":"identifier"}],"title":"ZDKRequestProvider"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestAddCommentCallback":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestAddCommentCallback","url":"\/documentation\/supportproviderssdk\/zdkrequestaddcommentcallback","kind":"symbol","role":"symbol","type":"topic","title":"ZDKRequestAddCommentCallback","abstract":[{"type":"text","text":"Block defined for callback to be used for handling async server responses for adding a comment to a request"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKRequestAddCommentCallback"}],"navigatorTitle":[{"text":"ZDKRequestAddCommentCallback","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/addComment(_:forRequestId:attachments:withCallback:)":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/addComment(_:forRequestId:attachments:withCallback:)","navigatorTitle":[{"text":"addComment:forRequestId:attachments:withCallback:","kind":"identifier"}],"title":"addComment(_:forRequestId:attachments:withCallback:)","abstract":[{"text":"Add a comment message to a request with attachments on behalf of the end-user.","type":"text"},{"type":"text","text":" "},{"text":"It will also get an access token if one has not been previously stored.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addComment"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"forRequestId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"attachments"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!, "},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKRequestAddCommentCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestAddCommentCallback"},{"text":"!)","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/addcomment(_:forrequestid:attachments:withcallback:)","type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"addComment:forRequestId:attachments:withCallback:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addComment:forRequestId:attachments:withCallback:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"addComment:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"comment"},{"text":" ","kind":"text"},{"text":"forRequestId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"requestId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attachments:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"attachments"},{"kind":"text","text":" "},{"text":"withCallback:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestAddCommentCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestAddCommentCallback","text":"ZDKRequestAddCommentCallback","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title","value":"ZDKRequestProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments","value":[{"kind":"identifier","text":"ZDKRequestProvider"}]},{"value":"ZDKRequestAddCommentCallback","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestAddCommentCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestAddCommentCallback\/fragments","value":[{"text":"ZDKRequestAddCommentCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1addComment(_:forRequestId:attachments:withCallback:)\/title","value":"addComment:forRequestId:attachments:withCallback:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1addComment(_:forRequestId:attachments:withCallback:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addComment:forRequestId:attachments:withCallback:","kind":"identifier"}],"op":"replace"}]}]}