{"abstract":[{"text":"Gets the ticket froms","type":"text"},{"text":" ","type":"text"},{"text":"Only the first 5 ticket form Ids will be fetched.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getTicketForm"},{"text":"(","kind":"text"},{"text":"withIds","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ticketFormIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"]!, ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKTicketFormCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFormCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKTicketFormCallback"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback that is invoked when a request is either successful or has error."}]}],"name":"callback"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getticketform(withids:callback:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getticketform(withids:callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"sections":[],"metadata":{"externalID":"c:objc(cs)ZDKRequestProvider(im)getTicketFormWithIds:callback:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","navigatorTitle":[{"text":"getTicketFormWithIds:callback:","kind":"identifier"}],"title":"getTicketForm(withIds:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getTicketForm","kind":"identifier"},{"kind":"text","text":"("},{"text":"withIds","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]!, ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"text":"ZDKTicketFormCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKTicketFormCallback"},{"kind":"text","text":"!)"}]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getTicketForm(withIds:callback:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getTicketForm(withIds:callback:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getTicketFormWithIds:callback:"}],"abstract":[{"text":"Gets the ticket froms","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Only the first 5 ticket form Ids will be fetched."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getTicketForm(withIds:callback:)","title":"getTicketForm(withIds:callback:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getticketform(withids:callback:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTicketForm"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIds"},{"kind":"text","text":": ["},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"]!, ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKTicketFormCallback","text":"ZDKTicketFormCallback"},{"text":"!)","kind":"text"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFormCallback":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFormCallback","title":"ZDKTicketFormCallback","abstract":[{"type":"text","text":"Callback for ticket form request"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ZDKTicketFormCallback","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketformcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKTicketFormCallback","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKRequestProvider"}],"type":"topic","abstract":[],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","role":"symbol","navigatorTitle":[{"text":"ZDKRequestProvider","kind":"identifier"}],"title":"ZDKRequestProvider"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"getTicketFormWithIds:callback:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"getTicketFormWithIds:callback:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"getTicketFormWithIds:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ticketFormIds"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callback:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFormCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKTicketFormCallback","text":"ZDKTicketFormCallback"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getTicketForm(withIds:callback:)\/title","value":"getTicketFormWithIds:callback:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"getTicketFormWithIds:callback:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getTicketForm(withIds:callback:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFormCallback\/title","op":"replace","value":"ZDKTicketFormCallback"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFormCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKTicketFormCallback"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title","value":"ZDKRequestProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments","value":[{"text":"ZDKRequestProvider","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}