{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeVote"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"voteId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":" "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterGenericCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterGenericCallback","text":"ZDKHelpCenterGenericCallback"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/removevote(withid:withcallback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/removevote(withid:withcallback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/removeVote(withId:withCallback:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Deletes a vote for a given id"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeVote"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKHelpCenterGenericCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterGenericCallback"},{"kind":"text","text":"!)"}],"title":"removeVote(withId:withCallback:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ZDKHelpCenterProvider(im)removeVoteWithId:withCallback:","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"removeVoteWithId:withCallback:"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/removeVote(withId:withCallback:)":{"role":"symbol","title":"removeVote(withId:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeVote"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKHelpCenterGenericCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterGenericCallback"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Deletes a vote for a given id"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/removeVote(withId:withCallback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeVoteWithId:withCallback:"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/removevote(withid:withcallback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"role":"symbol","title":"ZDKHelpCenterProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterGenericCallback":{"role":"symbol","title":"ZDKHelpCenterGenericCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterGenericCallback"}],"abstract":[{"type":"text","text":"Callback for Help Center simple responses, i.e. Status codes."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterGenericCallback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterGenericCallback"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentergenericcallback"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeVoteWithId:withCallback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeVoteWithId:withCallback:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeVoteWithId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"voteId"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCallback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterGenericCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterGenericCallback","text":"ZDKHelpCenterGenericCallback"},{"kind":"text","text":")"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1removeVote(withId:withCallback:)\/title","value":"removeVoteWithId:withCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1removeVote(withId:withCallback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeVoteWithId:withCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title","value":"ZDKHelpCenterProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterGenericCallback\/title","value":"ZDKHelpCenterGenericCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterGenericCallback\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterGenericCallback"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}