{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getflatarticles(callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getflatarticles(callback:)"]}],"abstract":[{"text":"Fetch a list of FlatArticle objects for a given Help Center instance. Supplies a hardcoded perPage of 100 and page of 1 to getFlatArticles:withCallback.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getFlatArticles"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ZDKHelpCenterCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"callback","content":[{"inlineContent":[{"type":"text","text":"The callback that is invoked when a request is either successful or has error."}],"type":"paragraph"}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getFlatArticles(callback:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFlatArticles"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"title":"getFlatArticles(callback:)","externalID":"c:objc(cs)ZDKHelpCenterProvider(im)getFlatArticlesWithCallback:","navigatorTitle":[{"kind":"identifier","text":"getFlatArticlesWithCallback:"}],"platforms":[]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use getFlatArticles:withCallback: instead."}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"navigatorTitle":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"title":"ZDKHelpCenterProvider"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getFlatArticles(callback:)":{"type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getflatarticles(callback:)","role":"symbol","kind":"symbol","abstract":[{"text":"Fetch a list of FlatArticle objects for a given Help Center instance. Supplies a hardcoded perPage of 100 and page of 1 to getFlatArticles:withCallback.","type":"text"}],"title":"getFlatArticles(callback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getFlatArticles(callback:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getFlatArticles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"getFlatArticlesWithCallback:"}],"deprecated":true},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCallback":{"kind":"symbol","abstract":[{"text":"Callback block.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterCallback","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKHelpCenterCallback","kind":"identifier"}],"title":"ZDKHelpCenterCallback"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getFlatArticlesWithCallback:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getFlatArticlesWithCallback:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"getFlatArticlesWithCallback:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback"},{"kind":"text","text":") "},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title","value":"ZDKHelpCenterProvider","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments"},{"value":"getFlatArticlesWithCallback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getFlatArticles(callback:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getFlatArticles(callback:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getFlatArticlesWithCallback:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/title","value":"ZDKHelpCenterCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/fragments","value":[{"text":"ZDKHelpCenterCallback","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}