{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/category"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/category"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"category"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"category","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"ZDKHelpCenterOverviewGroupTypeCategory","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:@E@ZDKHelpCenterOverviewGroupType@ZDKHelpCenterOverviewGroupTypeCategory","symbolKind":"case","title":"ZDKHelpCenterOverviewGroupType.category"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Used to specify that category ids are being used."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/category","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType":{"abstract":[{"text":"Used to specify what type of ids will be supplied.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype","type":"topic","title":"ZDKHelpCenterOverviewGroupType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType/category":{"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/category","type":"topic","title":"ZDKHelpCenterOverviewGroupType.category","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"category"}],"role":"symbol","abstract":[{"type":"text","text":"Used to specify that category ids are being used."}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupTypeCategory"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/category"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKHelpCenterOverviewGroupTypeCategory","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupTypeCategory"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ZDKHelpCenterOverviewGroupTypeCategory","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"ZDKHelpCenterOverviewGroupType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupType"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1category\/title","op":"replace","value":"ZDKHelpCenterOverviewGroupTypeCategory"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupTypeCategory"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1category\/fragments"}]}]}