{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil\/convertjsonobject(_:toobjectoftype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil\/convertjsonobject(_:toobjectoftype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertJsonObject(_:toObjectOfType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Convert JSON based dictionary to an object of type Class"}],"sections":[],"metadata":{"title":"convertJsonObject(_:toObjectOfType:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"convertJsonObject","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"toObjectOfType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier","text":"AnyClass"},{"kind":"text","text":"!) -> "},{"text":"Any","kind":"keyword"},{"text":"!","kind":"text"}],"modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ZDKJsonUtil(cm)convertJsonObject:toObjectOfType:","navigatorTitle":[{"text":"convertJsonObject:toObjectOfType:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"convertJsonObject","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!, ","kind":"text"},{"text":"toObjectOfType","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"classToMap","kind":"internalParam"},{"kind":"text","text":": "},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"},{"text":"!) -> ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"NSDictionary of JSON","type":"text"}]}],"name":"json"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"class to be converted to"}]}],"name":"classToMap"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"instance of type class from JSON"}]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/convertJsonObject(_:toObjectOfType:)":{"title":"convertJsonObject(_:toObjectOfType:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertJsonObject(_:toObjectOfType:)","role":"symbol","abstract":[{"type":"text","text":"Convert JSON based dictionary to an object of type Class"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/convertjsonobject(_:toobjectoftype:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"convertJsonObject","kind":"identifier"},{"kind":"text","text":"(["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!, ","kind":"text"},{"text":"toObjectOfType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"},{"text":"!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"convertJsonObject:toObjectOfType:"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil":{"url":"\/documentation\/supportproviderssdk\/zdkjsonutil","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKJsonUtil"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil","title":"ZDKJsonUtil","abstract":[],"role":"symbol","navigatorTitle":[{"text":"ZDKJsonUtil","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"convertJsonObject:toObjectOfType:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"convertJsonObject:toObjectOfType:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"convertJsonObject:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"toObjectOfType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"Class","kind":"typeIdentifier","preciseIdentifier":"c:@T@Class"},{"kind":"text","text":") "},{"kind":"internalParam","text":"classToMap"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertJsonObject(_:toObjectOfType:)\/title","value":"convertJsonObject:toObjectOfType:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"convertJsonObject:toObjectOfType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertJsonObject(_:toObjectOfType:)\/fragments"},{"value":"ZDKJsonUtil","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/fragments","op":"replace","value":[{"text":"ZDKJsonUtil","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}