{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterArticleViewModel"]]},"metadata":{"roleHeading":"Type Method","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterArticleViewModel(cm)convertWithArticles:","navigatorTitle":[{"text":"convertWithArticles:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"convert","kind":"identifier"},{"text":"(","kind":"text"},{"text":"articles","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle","text":"ZDKHelpCenterArticle","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"text":"HelpCenterArticleViewModel","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterArticleViewModel","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"role":"symbol","title":"convert(articles:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"convert"},{"kind":"text","text":"("},{"kind":"externalParam","text":"articles"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterArticle","kind":"typeIdentifier","text":"ZDKHelpCenterArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"kind":"text","text":"]) -> ["},{"text":"HelpCenterArticleViewModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterArticleViewModel","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterArticleViewModel"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterArticleViewModel\/convert(articles:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/helpcenterarticleviewmodel\/convert(articles:)"]},{"paths":["\/documentation\/supportproviderssdk\/helpcenterarticleviewmodel\/convert(articles:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterArticleViewModel/convert(articles:)":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"convertWithArticles:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterArticleViewModel\/convert(articles:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"convert","kind":"identifier"},{"text":"(","kind":"text"},{"text":"articles","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle","text":"ZDKHelpCenterArticle","kind":"typeIdentifier"},{"kind":"text","text":"]) -> ["},{"text":"HelpCenterArticleViewModel","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterArticleViewModel","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"url":"\/documentation\/supportproviderssdk\/helpcenterarticleviewmodel\/convert(articles:)","title":"convert(articles:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterArticle":{"navigatorTitle":[{"text":"ZDKHelpCenterArticle","kind":"identifier"}],"type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterarticle","title":"ZDKHelpCenterArticle","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterArticle","abstract":[{"type":"text","text":"A Help Center Article."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterArticle","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterArticleViewModel":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"HelpCenterArticleViewModel","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterArticleViewModel","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterArticleViewModel"}],"url":"\/documentation\/supportproviderssdk\/helpcenterarticleviewmodel","title":"HelpCenterArticleViewModel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"convertWithArticles:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"convertWithArticles:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ZDKHelpCenterArticleViewModel *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"convertWithArticles:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<ZDKHelpCenterArticle *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"articles"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"convertWithArticles:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterArticleViewModel~1convert(articles:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterArticleViewModel~1convert(articles:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"convertWithArticles:","kind":"identifier"}]},{"value":"ZDKHelpCenterArticle","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterArticle\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterArticle\/fragments","value":[{"text":"ZDKHelpCenterArticle","kind":"identifier"}]},{"value":"ZDKHelpCenterArticleViewModel","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterArticleViewModel\/title"},{"op":"replace","value":[{"text":"ZDKHelpCenterArticleViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterArticleViewModel\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}