{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@NSCopying"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"labelNames","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch"]]},"sections":[],"abstract":[{"text":"This models the “label_names” parameter. This will be a comma-separated list of label names to restrict the search to.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersearch\/labelnames"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersearch\/labelnames"]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"labelNames","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelNames"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSMutableArray","text":"NSMutableArray","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"labelNames","kind":"identifier"}],"externalID":"c:objc(cs)ZDKHelpCenterSearch(py)labelNames","role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch\/labelNames","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSearch":{"abstract":[{"type":"text","text":"This class models a Help Center search.  For more details about Help Centre search please see:"},{"text":" ","type":"text"},{"type":"text","text":"https:\/\/developer.zendesk.com\/rest_api\/docs\/help_center\/search"}],"title":"ZDKHelpCenterSearch","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterSearch","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersearch","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterSearch"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSearch/labelNames":{"kind":"symbol","abstract":[{"type":"text","text":"This models the “label_names” parameter. This will be a comma-separated list of label names to restrict the search to."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"labelNames","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSMutableArray","text":"NSMutableArray","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersearch\/labelnames","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch\/labelNames","type":"topic","title":"labelNames","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"labelNames"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"labelNames","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"labelNames"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"text":" * ","kind":"text"},{"text":"labelNames","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKHelpCenterSearch","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch\/title"},{"value":[{"text":"ZDKHelpCenterSearch","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch\/fragments","op":"replace"},{"op":"replace","value":"labelNames","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch~1labelNames\/title"},{"op":"replace","value":[{"text":"labelNames","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch~1labelNames\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}