{"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch\/sideLoads","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This models the “include” parameter.  This specifies the elements to side-load and include in the results."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersearch\/sideloads"]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersearch\/sideloads"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@NSCopying"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sideLoads","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray","kind":"typeIdentifier"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch"]]},"metadata":{"title":"sideLoads","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"sideLoads","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)ZDKHelpCenterSearch(py)sideLoads","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sideLoads"},{"kind":"text","text":": "},{"text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSearch/sideLoads":{"kind":"symbol","abstract":[{"text":"This models the “include” parameter.  This specifies the elements to side-load and include in the results.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sideLoads","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSMutableArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"text":"!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersearch\/sideloads","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch\/sideLoads","type":"topic","title":"sideLoads","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sideLoads"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSearch":{"abstract":[{"type":"text","text":"This class models a Help Center search.  For more details about Help Centre search please see:"},{"text":" ","type":"text"},{"type":"text","text":"https:\/\/developer.zendesk.com\/rest_api\/docs\/help_center\/search"}],"title":"ZDKHelpCenterSearch","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSearch","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterSearch","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersearch","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterSearch"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"sideLoads","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"sideLoads"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSMutableArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":" * "},{"text":"sideLoads","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"sideLoads","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch~1sideLoads\/title"},{"value":[{"kind":"identifier","text":"sideLoads"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch~1sideLoads\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch\/title","op":"replace","value":"ZDKHelpCenterSearch"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSearch\/fragments","value":[{"text":"ZDKHelpCenterSearch","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}