{"abstract":[{"type":"text","text":"The articles position in it’s parent section."}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterarticle\/position"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterarticle\/position"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterArticle\/position","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterArticle"]]},"metadata":{"navigatorTitle":[{"text":"position","kind":"identifier"}],"title":"position","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","externalID":"c:objc(cs)ZDKHelpCenterArticle(py)position","modules":[{"name":"SupportProvidersSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterArticle/position":{"title":"position","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterArticle\/position","navigatorTitle":[{"text":"position","kind":"identifier"}],"abstract":[{"text":"The articles position in it’s parent section.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterarticle\/position"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterArticle":{"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterarticle","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterArticle","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterArticle"}],"title":"ZDKHelpCenterArticle","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterArticle"}],"abstract":[{"type":"text","text":"A Help Center Article."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"position","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"position","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterArticle~1position\/title","op":"replace","value":"position"},{"value":[{"text":"position","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterArticle~1position\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterArticle\/title","value":"ZDKHelpCenterArticle"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterArticle"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterArticle\/fragments"}]}]}