{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/attachments","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attachments"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]! { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkcreaterequest\/attachments"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkcreaterequest\/attachments"]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attachments"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"navigatorTitle":[{"text":"attachments","kind":"identifier"}],"title":"attachments","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","externalID":"c:objc(cs)ZDKCreateRequest(py)attachments"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest"]]},"abstract":[{"text":"List of ZDKUploadResponse objects.","type":"text"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest/attachments":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"attachments","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"title":"attachments","role":"symbol","navigatorTitle":[{"text":"attachments","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/attachments","abstract":[{"type":"text","text":"List of ZDKUploadResponse objects."}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest\/attachments"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest":{"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKCreateRequest","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest","navigatorTitle":[{"text":"ZDKCreateRequest","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"A request sent by the user.","type":"text"}],"title":"ZDKCreateRequest"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"attachments","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"attachments"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"attachments"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1attachments\/title","value":"attachments","op":"replace"},{"value":[{"kind":"identifier","text":"attachments"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1attachments\/fragments"},{"value":"ZDKCreateRequest","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest\/fragments","value":[{"kind":"identifier","text":"ZDKCreateRequest"}]}]}]}