{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest"]]},"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)ZDKCreateRequest(py)requestDescription","navigatorTitle":[{"text":"requestDescription","kind":"identifier"}],"symbolKind":"property","title":"requestDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requestDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"modules":[{"name":"SupportProvidersSDK"}]},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkcreaterequest\/requestdescription"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkcreaterequest\/requestdescription"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The body of the request","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/requestDescription"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest":{"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKCreateRequest","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest","navigatorTitle":[{"text":"ZDKCreateRequest","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"A request sent by the user.","type":"text"}],"title":"ZDKCreateRequest"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest/requestDescription":{"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest\/requestdescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/requestDescription","navigatorTitle":[{"text":"requestDescription","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The body of the request","type":"text"}],"title":"requestDescription"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"requestDescription"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"requestDescription","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"requestDescription","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest\/title","value":"ZDKCreateRequest","op":"replace"},{"value":[{"text":"ZDKCreateRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1requestDescription\/title","value":"requestDescription"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1requestDescription\/fragments","value":[{"text":"requestDescription","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}