{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addComment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"comment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"forRequestId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":" "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestAddCommentCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestAddCommentCallback","text":"ZDKRequestAddCommentCallback"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/addcomment(_:forrequestid:withcallback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/addcomment(_:forrequestid:withcallback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/addComment(_:forRequestId:withCallback:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Add a comment message to a request."},{"type":"text","text":" "},{"type":"text","text":"It will also get an access token if one has not been previously stored."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addComment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"forRequestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKRequestAddCommentCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestAddCommentCallback"},{"kind":"text","text":"!)"}],"title":"addComment(_:forRequestId:withCallback:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ZDKRequestProvider(im)addComment:forRequestId:withCallback:","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addComment:forRequestId:withCallback:"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/addComment(_:forRequestId:withCallback:)":{"role":"symbol","title":"addComment(_:forRequestId:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addComment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"forRequestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKRequestAddCommentCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestAddCommentCallback"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Add a comment message to a request."},{"type":"text","text":" "},{"type":"text","text":"It will also get an access token if one has not been previously stored."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/addComment(_:forRequestId:withCallback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addComment:forRequestId:withCallback:"}],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/addcomment(_:forrequestid:withcallback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"role":"symbol","title":"ZDKRequestProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestProvider"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestProvider"}],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestAddCommentCallback":{"role":"symbol","title":"ZDKRequestAddCommentCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestAddCommentCallback"}],"abstract":[{"type":"text","text":"Block defined for callback to be used for handling async server responses for adding a comment to a request"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestAddCommentCallback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestAddCommentCallback"}],"url":"\/documentation\/supportproviderssdk\/zdkrequestaddcommentcallback"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addComment:forRequestId:withCallback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addComment:forRequestId:withCallback:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addComment:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"comment"},{"kind":"text","text":" "},{"kind":"identifier","text":"forRequestId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"requestId"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCallback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestAddCommentCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestAddCommentCallback","text":"ZDKRequestAddCommentCallback"},{"kind":"text","text":")"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1addComment(_:forRequestId:withCallback:)\/title","value":"addComment:forRequestId:withCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1addComment(_:forRequestId:withCallback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addComment:forRequestId:withCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title","value":"ZDKRequestProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments","value":[{"kind":"identifier","text":"ZDKRequestProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestAddCommentCallback\/title","value":"ZDKRequestAddCommentCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestAddCommentCallback\/fragments","value":[{"kind":"identifier","text":"ZDKRequestAddCommentCallback"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}