{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterOverviewGroupType","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType","preciseIdentifier":"c:@E@ZDKHelpCenterOverviewGroupType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"groupType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@ZDKHelpCenterOverviewGroupType","text":"ZDKHelpCenterOverviewGroupType","kind":"typeIdentifier"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)ZDKHelpCenterOverviewContentModel(py)groupType","title":"groupType","navigatorTitle":[{"text":"groupType","kind":"identifier"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/groupType","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"The type of ids being used.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/grouptype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/grouptype"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterOverviewContentModel"}],"role":"symbol","type":"topic","abstract":[{"text":"Model which allows customizations on the content displayed by Help Center.","type":"text"}],"title":"ZDKHelpCenterOverviewContentModel","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel","navigatorTitle":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel/groupType":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"groupType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ZDKHelpCenterOverviewGroupType","kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKHelpCenterOverviewGroupType"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The type of ids being used."}],"title":"groupType","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/groupType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"groupType"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/grouptype"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType":{"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType","title":"ZDKHelpCenterOverviewGroupType","abstract":[{"type":"text","text":"Used to specify what type of ids will be supplied."}],"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"groupType","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"groupType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ZDKHelpCenterOverviewGroupType","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType","preciseIdentifier":"c:@E@ZDKHelpCenterOverviewGroupType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupType"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/title","op":"replace","value":"ZDKHelpCenterOverviewContentModel"},{"value":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/fragments"},{"value":"groupType","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1groupType\/title","op":"replace"},{"value":[{"text":"groupType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1groupType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType\/title","op":"replace","value":"ZDKHelpCenterOverviewGroupType"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupType"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}