{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"reachableViaWWAN","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/reachableViaWWAN"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdknetworkstatus\/reachableviawwan"]},{"paths":["\/documentation\/supportproviderssdk\/zdknetworkstatus\/reachableviawwan"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","externalID":"c:@E@ZDKNetworkStatus@ZDKNetworkStatusReachableViaWWAN","navigatorTitle":[{"kind":"identifier","text":"ZDKNetworkStatusReachableViaWWAN"}],"role":"symbol","roleHeading":"Case","title":"ZDKNetworkStatus.reachableViaWWAN","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reachableViaWWAN"}],"modules":[{"name":"SupportProvidersSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus"]]},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus","kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKNetworkStatus","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdknetworkstatus","navigatorTitle":[{"kind":"identifier","text":"ZDKNetworkStatus"}],"title":"ZDKNetworkStatus"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus/reachableViaWWAN":{"url":"\/documentation\/supportproviderssdk\/zdknetworkstatus\/reachableviawwan","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reachableViaWWAN"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/reachableViaWWAN","title":"ZDKNetworkStatus.reachableViaWWAN","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKNetworkStatusReachableViaWWAN"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ZDKNetworkStatusReachableViaWWAN","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKNetworkStatusReachableViaWWAN","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ZDKNetworkStatusReachableViaWWAN","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKNetworkStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus\/title"},{"value":[{"text":"ZDKNetworkStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1reachableViaWWAN\/title","op":"replace","value":"ZDKNetworkStatusReachableViaWWAN"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1reachableViaWWAN\/fragments","value":[{"kind":"identifier","text":"ZDKNetworkStatusReachableViaWWAN"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}