{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDispatcherResponse\/init(response:andData:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Initializer","role":"symbol","title":"init(response:andData:)","externalID":"c:objc(cs)ZDKDispatcherResponse(im)initWithResponse:andData:","symbolKind":"init","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"text":"HTTPURLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSHTTPURLResponse"},{"kind":"text","text":"!, "},{"text":"andData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"initWithResponse:andData:","kind":"identifier"}]},"abstract":[{"type":"text","text":"Init a ZDKDispatcherResponse."}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkdispatcherresponse\/init(response:anddata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkdispatcherresponse\/init(response:anddata:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"text":"response","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HTTPURLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSHTTPURLResponse"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"andData"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"!)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"response","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A HTTP response."}]}]},{"name":"data","content":[{"inlineContent":[{"type":"text","text":"Data from a HTTP response."}],"type":"paragraph"}]}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"a new instance.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDispatcherResponse"]]},"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDispatcherResponse":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDispatcherResponse","navigatorTitle":[{"kind":"identifier","text":"ZDKDispatcherResponse"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKDispatcherResponse"}],"kind":"symbol","title":"ZDKDispatcherResponse","role":"symbol","abstract":[{"text":"A model for the responses from the dispatcher.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkdispatcherresponse"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDispatcherResponse/init(response:andData:)":{"navigatorTitle":[{"text":"initWithResponse:andData:","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkdispatcherresponse\/init(response:anddata:)","abstract":[{"text":"Init a ZDKDispatcherResponse.","type":"text"}],"title":"init(response:andData:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"!(","kind":"text"},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"text":"HTTPURLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSHTTPURLResponse"},{"kind":"text","text":"!, "},{"text":"andData","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"!)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDispatcherResponse\/init(response:andData:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithResponse:andData:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithResponse:andData:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithResponse:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSHTTPURLResponse","text":"NSHTTPURLResponse"},{"kind":"text","text":" *) "},{"text":"response","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"andData:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"data","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDispatcherResponse\/title","value":"ZDKDispatcherResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDispatcherResponse\/fragments","op":"replace","value":[{"text":"ZDKDispatcherResponse","kind":"identifier"}]},{"value":"initWithResponse:andData:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDispatcherResponse~1init(response:andData:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithResponse:andData:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDispatcherResponse~1init(response:andData:)\/fragments","op":"replace"}]}]}