{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getflatarticles(_:withcallback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getflatarticles(_:withcallback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Fetch number of FlatArticle objects based on the number of results and page provided in the ZDKListArticleQuery object.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getFlatArticles(_:withCallback:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"]]},"sections":[],"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFlatArticles"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKListArticleQuery","text":"ListArticleQuery","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withCallback"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","title":"getFlatArticles(_:withCallback:)","navigatorTitle":[{"text":"getFlatArticles:withCallback:","kind":"identifier"}],"externalID":"c:objc(cs)ZDKHelpCenterProvider(im)getFlatArticles:withCallback:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getFlatArticles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"query","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ListArticleQuery","text":"ListArticleQuery","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKListArticleQuery","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":" "},{"text":"callback","kind":"internalParam"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page and amount of results to be returned (up to 100)"}]}],"name":"query"},{"name":"callback","content":[{"inlineContent":[{"text":"The callback that is invoked when a request is either successful or has error.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ListArticleQuery":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListArticleQuery"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ListArticleQuery","title":"ListArticleQuery","url":"\/documentation\/supportproviderssdk\/listarticlequery","navigatorTitle":[{"kind":"identifier","text":"ListArticleQuery"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCallback":{"kind":"symbol","abstract":[{"type":"text","text":"Callback block."}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterCallback","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentercallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","title":"ZDKHelpCenterCallback","type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterCallback","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider","type":"topic","title":"ZDKHelpCenterProvider","role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getFlatArticles(_:withCallback:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getFlatArticles","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKListArticleQuery","text":"ListArticleQuery"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"kind":"symbol","abstract":[{"text":"Fetch number of FlatArticle objects based on the number of results and page provided in the ZDKListArticleQuery object.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getFlatArticles(_:withCallback:)","type":"topic","title":"getFlatArticles(_:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getflatarticles(_:withcallback:)","navigatorTitle":[{"text":"getFlatArticles:withCallback:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getFlatArticles:withCallback:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFlatArticles:withCallback:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"getFlatArticles:"},{"text":"(","kind":"text"},{"text":"ZDKListArticleQuery","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ListArticleQuery","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKListArticleQuery","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"query"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCallback:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKListArticleQuery","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ListArticleQuery\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ListArticleQuery\/fragments","value":[{"kind":"identifier","text":"ZDKListArticleQuery"}]},{"value":"ZDKHelpCenterCallback","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterCallback"}]},{"value":"ZDKHelpCenterProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments","value":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getFlatArticles(_:withCallback:)\/title","value":"getFlatArticles:withCallback:"},{"value":[{"text":"- ","kind":"text"},{"text":"getFlatArticles:withCallback:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getFlatArticles(_:withCallback:)\/fragments","op":"replace"}]}]}