{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"init(dictionary:)","roleHeading":"Initializer","required":true,"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"!("},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"externalID":"c:objc(pl)ZDKDictionaryCreatable(im)initWithDictionary:","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDictionaryCreatable"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"dictionary"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkdictionarycreatable\/init(dictionary:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkdictionarycreatable\/init(dictionary:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDictionaryCreatable\/init(dictionary:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDictionaryCreatable":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKDictionaryCreatable","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"title":"ZDKDictionaryCreatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDictionaryCreatable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKDictionaryCreatable"}],"url":"\/documentation\/supportproviderssdk\/zdkdictionarycreatable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDictionaryCreatable/init(dictionary:)":{"required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"!("},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkdictionarycreatable\/init(dictionary:)","title":"init(dictionary:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDictionaryCreatable\/init(dictionary:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithDictionary:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDictionary:"},{"kind":"text","text":"("},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"dictionary","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"ZDKDictionaryCreatable","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDictionaryCreatable\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDictionaryCreatable\/fragments","value":[{"kind":"identifier","text":"ZDKDictionaryCreatable"}],"op":"replace"},{"value":"initWithDictionary:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDictionaryCreatable~1init(dictionary:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithDictionary:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDictionaryCreatable~1init(dictionary:)\/fragments"}]}]}