{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseRequestList"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dictionary","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!) -> [","kind":"text"},{"text":"ZDKRequest","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","preciseIdentifier":"c:objc(cs)ZDKRequest"},{"text":"]!","kind":"text"}]}]}],"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:objc(cs)ZDKRequestsResponse(cm)parseRequestListWithDictionary:","title":"parseRequestList(with:)","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"parseRequestListWithDictionary:"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"parseRequestList","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!) -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKRequest","text":"ZDKRequest"},{"text":"]!","kind":"text"}],"modules":[{"name":"SupportProvidersSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsResponse\/parseRequestList(with:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestsresponse\/parserequestlist(with:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkrequestsresponse\/parserequestlist(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsResponse"]]},"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestsResponse":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKRequestsResponse","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestsresponse","title":"ZDKRequestsResponse","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestsResponse"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsResponse","kind":"symbol","type":"topic","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequest":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequest"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKRequest","kind":"identifier"}],"abstract":[{"type":"text","text":"Object representing a Zendesk end user request returned by the server."}],"kind":"symbol","title":"ZDKRequest","url":"\/documentation\/supportproviderssdk\/zdkrequest"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestsResponse/parseRequestList(with:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parseRequestList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!) -> ["},{"preciseIdentifier":"c:objc(cs)ZDKRequest","text":"ZDKRequest","kind":"typeIdentifier"},{"text":"]!","kind":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestsresponse\/parserequestlist(with:)","title":"parseRequestList(with:)","navigatorTitle":[{"kind":"identifier","text":"parseRequestListWithDictionary:"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsResponse\/parseRequestList(with:)","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"parseRequestListWithDictionary:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"parseRequestListWithDictionary:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"NSArray<ZDKRequest *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"parseRequestListWithDictionary:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dictionary"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsResponse\/title","value":"ZDKRequestsResponse","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsResponse\/fragments","value":[{"text":"ZDKRequestsResponse","kind":"identifier"}]},{"value":"ZDKRequest","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/title"},{"value":[{"text":"ZDKRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsResponse~1parseRequestList(with:)\/title","value":"parseRequestListWithDictionary:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsResponse~1parseRequestList(with:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"parseRequestListWithDictionary:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}