{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/requestforstorage\/incrementcommentcounts()"]},{"paths":["\/documentation\/supportproviderssdk\/requestforstorage\/incrementcommentcounts()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"extendedModule":"SupportProvidersSDK","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"incrementCommentCounts"}],"symbolKind":"method","role":"symbol","externalID":"c:@CM@SupportProvidersSDK@objc(cs)ZDKRequestForStorage(im)incrementCommentCounts","roleHeading":"Instance Method","title":"incrementCommentCounts()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incrementCommentCounts","kind":"identifier"},{"text":"()","kind":"text"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/incrementCommentCounts()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"incrementCommentCounts"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage"]]},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage/incrementCommentCounts()":{"title":"incrementCommentCounts()","navigatorTitle":[{"kind":"identifier","text":"incrementCommentCounts"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incrementCommentCounts"},{"text":"()","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/incrementCommentCounts()","type":"topic","url":"\/documentation\/supportproviderssdk\/requestforstorage\/incrementcommentcounts()","abstract":[],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","url":"\/documentation\/supportproviderssdk\/requestforstorage","kind":"symbol","navigatorTitle":[{"text":"RequestForStorage","kind":"identifier"}],"type":"topic","abstract":[],"title":"RequestForStorage","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RequestForStorage","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"incrementCommentCounts"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"incrementCommentCounts","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"incrementCommentCounts"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"incrementCommentCounts","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage~1incrementCommentCounts()\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage~1incrementCommentCounts()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"incrementCommentCounts"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/title","value":"ZDKRequestForStorage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/fragments","value":[{"text":"ZDKRequestForStorage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}