{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/none"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/none"]},{"paths":["\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"No conversations nav bar in Help Center.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Case","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeNone"}],"externalID":"c:@E@ZDKNavBarConversationsUIType@ZDKNavBarConversationsUITypeNone","title":"ZDKNavBarConversationsUIType.none","modules":[{"name":"SupportProvidersSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType/none":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/none","url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/none","abstract":[{"type":"text","text":"No conversations nav bar in Help Center."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"text":"ZDKNavBarConversationsUITypeNone","kind":"identifier"}],"kind":"symbol","title":"ZDKNavBarConversationsUIType.none","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType":{"abstract":[{"text":"Enum to describe the types of nav bar button that display conversations.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKNavBarConversationsUIType"}],"type":"topic","navigatorTitle":[{"text":"ZDKNavBarConversationsUIType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType","title":"ZDKNavBarConversationsUIType","url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"ZDKNavBarConversationsUITypeNone","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKNavBarConversationsUITypeNone","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ZDKNavBarConversationsUITypeNone","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1none\/title","value":"ZDKNavBarConversationsUITypeNone"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1none\/fragments","value":[{"text":"ZDKNavBarConversationsUITypeNone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType\/title","value":"ZDKNavBarConversationsUIType","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKNavBarConversationsUIType"}]}]}]}