{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkrequest\/createdat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequest\/createdat"]}],"abstract":[{"text":"The timestamp of the request creation.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest\/createdAt","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"title":"createdAt","navigatorTitle":[{"text":"createdAt","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createdAt"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"externalID":"c:objc(cs)ZDKRequest(py)createdAt","roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"createdAt","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequest":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKRequest"}],"type":"topic","abstract":[{"text":"Object representing a Zendesk end user request returned by the server.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkrequest","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequest"}],"title":"ZDKRequest"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequest/createdAt":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest\/createdAt","navigatorTitle":[{"kind":"identifier","text":"createdAt"}],"url":"\/documentation\/supportproviderssdk\/zdkrequest\/createdat","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createdAt"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The timestamp of the request creation."}],"title":"createdAt","type":"topic","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"createdAt","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"createdAt"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" * "},{"text":"createdAt","kind":"identifier"}]}],"kind":"declarations"}},{"value":"ZDKRequest","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/title","op":"replace"},{"value":[{"text":"ZDKRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/fragments"},{"op":"replace","value":"createdAt","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest~1createdAt\/title"},{"value":[{"kind":"identifier","text":"createdAt"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest~1createdAt\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}