{"abstract":[{"type":"text","text":"Array of custom fields on the request"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"customFields","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CustomField","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/CustomField","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKCustomField"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:objc(cs)ZDKRequest(py)customFields","title":"customFields","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"CustomField","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKCustomField"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"customFields","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequest\/customfields"]},{"paths":["\/documentation\/supportproviderssdk\/zdkrequest\/customfields"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest\/customFields","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/CustomField":{"role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/customfield","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"CustomField","kind":"identifier"}],"title":"CustomField","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/CustomField","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomField","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequest":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKRequest"}],"type":"topic","abstract":[{"text":"Object representing a Zendesk end user request returned by the server.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkrequest","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequest"}],"title":"ZDKRequest"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequest/customFields":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest\/customFields","navigatorTitle":[{"text":"customFields","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkrequest\/customfields","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"customFields","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CustomField","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKCustomField"},{"text":"]?","kind":"text"}],"abstract":[{"type":"text","text":"Array of custom fields on the request"}],"title":"customFields","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"customFields","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"customFields","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nullable","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ZDKCustomField *>"},{"kind":"text","text":" * "},{"text":"customFields","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"ZDKCustomField","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1CustomField\/title"},{"value":[{"text":"ZDKCustomField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1CustomField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/title","value":"ZDKRequest"},{"value":[{"kind":"identifier","text":"ZDKRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/fragments"},{"op":"replace","value":"customFields","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest~1customFields\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest~1customFields\/fragments","value":[{"text":"customFields","kind":"identifier"}]}]}]}