{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sectionByReplacing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"articles","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterArticleViewModel","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterArticleViewModel","kind":"typeIdentifier","text":"HelpCenterArticleViewModel"},{"text":"]) -> ","kind":"text"},{"text":"HelpCenterSectionViewModel","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel"}]}]}],"metadata":{"role":"symbol","symbolKind":"method","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel(im)sectionByReplacingWithArticles:","title":"sectionByReplacing(articles:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"sectionByReplacingWithArticles:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sectionByReplacing","kind":"identifier"},{"kind":"text","text":"("},{"text":"articles","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterArticleViewModel","text":"HelpCenterArticleViewModel"},{"text":"]) -> ","kind":"text"},{"text":"HelpCenterSectionViewModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel"}],"modules":[{"name":"SupportProvidersSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel\/sectionByReplacing(articles:)"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/helpcentersectionviewmodel\/sectionbyreplacing(articles:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/helpcentersectionviewmodel\/sectionbyreplacing(articles:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSectionViewModel":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterSectionViewModel","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"HelpCenterSectionViewModel","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HelpCenterSectionViewModel"}],"url":"\/documentation\/supportproviderssdk\/helpcentersectionviewmodel","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSectionViewModel/sectionByReplacing(articles:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sectionByReplacing","kind":"identifier"},{"kind":"text","text":"("},{"text":"articles","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterArticleViewModel","text":"HelpCenterArticleViewModel"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel","text":"HelpCenterSectionViewModel","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/helpcentersectionviewmodel\/sectionbyreplacing(articles:)","title":"sectionByReplacing(articles:)","navigatorTitle":[{"kind":"identifier","text":"sectionByReplacingWithArticles:"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel\/sectionByReplacing(articles:)","kind":"symbol","type":"topic","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterArticleViewModel":{"abstract":[],"navigatorTitle":[{"text":"HelpCenterArticleViewModel","kind":"identifier"}],"type":"topic","title":"HelpCenterArticleViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterArticleViewModel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/helpcenterarticleviewmodel","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterArticleViewModel","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"sectionByReplacingWithArticles:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sectionByReplacingWithArticles:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel","kind":"typeIdentifier","text":"ZDKHelpCenterSectionViewModel","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel"},{"kind":"text","text":" *) "},{"text":"sectionByReplacingWithArticles:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<ZDKHelpCenterArticleViewModel *>"},{"text":" *) ","kind":"text"},{"text":"articles","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKHelpCenterSectionViewModel","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel\/fragments","value":[{"text":"ZDKHelpCenterSectionViewModel","kind":"identifier"}],"op":"replace"},{"value":"sectionByReplacingWithArticles:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel~1sectionByReplacing(articles:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel~1sectionByReplacing(articles:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sectionByReplacingWithArticles:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterArticleViewModel\/title","value":"ZDKHelpCenterArticleViewModel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterArticleViewModel\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterArticleViewModel"}]}]}]}