{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadResponse\/attachment","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadResponse"]]},"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKAttachment","text":"ZDKAttachment"},{"text":"!","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)ZDKUploadResponse(py)attachment","navigatorTitle":[{"text":"attachment","kind":"identifier"}],"title":"attachment"},"abstract":[{"type":"text","text":"The attachment model for the upload."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKAttachment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment","text":"ZDKAttachment"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkuploadresponse\/attachment"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkuploadresponse\/attachment"]}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment":{"abstract":[{"type":"text","text":"An attachment to a Zendesk comment"}],"role":"symbol","navigatorTitle":[{"text":"ZDKAttachment","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAttachment"}],"kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkattachment","title":"ZDKAttachment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKUploadResponse":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUploadResponse"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Model for an upload response."}],"title":"ZDKUploadResponse","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadResponse","kind":"symbol","navigatorTitle":[{"text":"ZDKUploadResponse","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkuploadresponse"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKUploadResponse/attachment":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachment"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKAttachment","text":"ZDKAttachment","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"attachment","kind":"identifier"}],"abstract":[{"text":"The attachment model for the upload.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadResponse\/attachment","title":"attachment","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkuploadresponse\/attachment","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"attachment"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"attachment"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment","text":"ZDKAttachment","preciseIdentifier":"c:objc(cs)ZDKAttachment"},{"text":" * ","kind":"text"},{"text":"attachment","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKAttachment","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment\/fragments","value":[{"kind":"identifier","text":"ZDKAttachment"}]},{"value":"ZDKUploadResponse","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadResponse\/title"},{"value":[{"text":"ZDKUploadResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadResponse\/fragments"},{"value":"attachment","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadResponse~1attachment\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadResponse~1attachment\/fragments","value":[{"text":"attachment","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}