{"metadata":{"navigatorTitle":[{"text":"createRequest:withCallback:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createRequest"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ZDKCreateRequest","preciseIdentifier":"c:objc(cs)ZDKCreateRequest"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKCreateRequestCallback","text":"ZDKCreateRequestCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"title":"createRequest(_:withCallback:)","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:objc(cs)ZDKRequestProvider(im)createRequest:withCallback:","role":"symbol","symbolKind":"method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createRequest","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"request","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest","text":"ZDKCreateRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKCreateRequest"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequestCallback","text":"ZDKCreateRequestCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKCreateRequestCallback"},{"text":"!)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"request","content":[{"inlineContent":[{"type":"text","text":"Request model object."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"callback invoked in response to remote API invocation."}]}],"name":"callback"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/createRequest(_:withCallback:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Calls a request service to create a request on behalf of the end user."}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/createrequest(_:withcallback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/createrequest(_:withcallback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequestCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ZDKCreateRequestCallback","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Block defined for a callback to be used for handling async server response for creating a request"}],"title":"ZDKCreateRequestCallback","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequestCallback","navigatorTitle":[{"kind":"identifier","text":"ZDKCreateRequestCallback"}],"url":"\/documentation\/supportproviderssdk\/zdkcreaterequestcallback"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/createRequest(_:withCallback:)":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Calls a request service to create a request on behalf of the end user.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/createRequest(_:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createRequest","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKCreateRequest","kind":"typeIdentifier","text":"ZDKCreateRequest"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ZDKCreateRequestCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKCreateRequestCallback"},{"kind":"text","text":"!)"}],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/createrequest(_:withcallback:)","navigatorTitle":[{"kind":"identifier","text":"createRequest:withCallback:"}],"title":"createRequest(_:withCallback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKRequestProvider","kind":"identifier"}],"type":"topic","title":"ZDKRequestProvider","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","kind":"symbol","navigatorTitle":[{"text":"ZDKRequestProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest":{"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKCreateRequest","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest","navigatorTitle":[{"text":"ZDKCreateRequest","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"A request sent by the user.","type":"text"}],"title":"ZDKCreateRequest"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"createRequest:withCallback:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createRequest:withCallback:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"createRequest:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest","text":"ZDKCreateRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKCreateRequest"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"request"},{"text":" ","kind":"text"},{"text":"withCallback:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequestCallback","text":"ZDKCreateRequestCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKCreateRequestCallback"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"ZDKCreateRequestCallback","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequestCallback\/title"},{"value":[{"kind":"identifier","text":"ZDKCreateRequestCallback"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequestCallback\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1createRequest(_:withCallback:)\/title","value":"createRequest:withCallback:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1createRequest(_:withCallback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createRequest:withCallback:"}]},{"value":"ZDKRequestProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments","value":[{"text":"ZDKRequestProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest\/title","value":"ZDKCreateRequest"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest\/fragments","op":"replace","value":[{"text":"ZDKCreateRequest","kind":"identifier"}]}]}]}