{"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getAllRequests","kind":"identifier"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestListCallback","text":"ZDKRequestListCallback"},{"text":"!)","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","title":"getAllRequests(callback:)","navigatorTitle":[{"kind":"identifier","text":"getAllRequestsWithCallback:"}],"externalID":"c:objc(cs)ZDKRequestProvider(im)getAllRequestsWithCallback:"},"abstract":[{"text":"Gets all requests that user has opened.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It will also get an access token if one has not been previously stored."},{"type":"text","text":" "},{"text":"If you are using anonymous identities we will check to see if you have any stored request IDs.","type":"text"},{"type":"text","text":" "},{"text":"This is how requests work when dealing with anonymous identities. If you do have stored request","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"IDs we will fetch these requests from your Zendesk instance. If you do not have any stored request"},{"type":"text","text":" "},{"type":"text","text":"IDs we will skip the network call and return an empty list of Requests."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getAllRequests(callback:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getAllRequests"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestListCallback","text":"ZDKRequestListCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestListCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"callback","content":[{"inlineContent":[{"type":"text","text":"invoked in response to remote API invocation"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getallrequests(callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getallrequests(callback:)"]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKRequestProvider","kind":"identifier"}],"type":"topic","title":"ZDKRequestProvider","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","kind":"symbol","navigatorTitle":[{"text":"ZDKRequestProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestListCallback":{"title":"ZDKRequestListCallback","url":"\/documentation\/supportproviderssdk\/zdkrequestlistcallback","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestListCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestListCallback"}],"kind":"symbol","abstract":[{"text":"Block defined for callback to be used for handling async server responses for fetching a list of requests and agents that have publically","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"commented on them"}],"navigatorTitle":[{"text":"ZDKRequestListCallback","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getAllRequests(callback:)":{"kind":"symbol","abstract":[{"type":"text","text":"Gets all requests that user has opened."},{"type":"text","text":" "},{"text":"It will also get an access token if one has not been previously stored.","type":"text"},{"type":"text","text":" "},{"text":"If you are using anonymous identities we will check to see if you have any stored request IDs.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This is how requests work when dealing with anonymous identities. If you do have stored request"},{"text":" ","type":"text"},{"text":"IDs we will fetch these requests from your Zendesk instance. If you do not have any stored request","type":"text"},{"type":"text","text":" "},{"type":"text","text":"IDs we will skip the network call and return an empty list of Requests."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllRequests"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestListCallback","kind":"typeIdentifier","text":"ZDKRequestListCallback"},{"kind":"text","text":"!)"}],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getallrequests(callback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getAllRequests(callback:)","type":"topic","title":"getAllRequests(callback:)","role":"symbol","navigatorTitle":[{"text":"getAllRequestsWithCallback:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"getAllRequestsWithCallback:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"getAllRequestsWithCallback:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"getAllRequestsWithCallback:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestListCallback","text":"ZDKRequestListCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestListCallback","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title","op":"replace","value":"ZDKRequestProvider"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKRequestProvider"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestListCallback\/title","value":"ZDKRequestListCallback"},{"value":[{"text":"ZDKRequestListCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestListCallback\/fragments"},{"op":"replace","value":"getAllRequestsWithCallback:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getAllRequests(callback:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getAllRequests(callback:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getAllRequestsWithCallback:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}