{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getCommentsWithRequestId(_:since:onlyAgent:withCallback:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getcommentswithrequestid(_:since:onlyagent:withcallback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/getcommentswithrequestid(_:since:onlyagent:withcallback:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCommentsWithRequestId"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"requestId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"since","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sinceDate"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"!, "},{"text":"onlyAgent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":": ","kind":"text"},{"text":"ZDKRequestCommentListCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestCommentListCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestCommentListCallback"},{"kind":"text","text":"!)"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"getCommentsWithRequestId(_:since:onlyAgent:withCallback:)","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","externalID":"c:objc(cs)ZDKRequestProvider(im)getCommentsWithRequestId:sinceDate:onlyAgent:withCallback:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getCommentsWithRequestId","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"since"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"!, ","kind":"text"},{"text":"onlyAgent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ZDKRequestCommentListCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestCommentListCallback"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"getCommentsWithRequestId:sinceDate:onlyAgent:withCallback:","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getCommentsWithRequestId(_:since:onlyAgent:withCallback:)":{"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getcommentswithrequestid(_:since:onlyagent:withcallback:)","title":"getCommentsWithRequestId(_:since:onlyAgent:withCallback:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getCommentsWithRequestId(_:since:onlyAgent:withCallback:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCommentsWithRequestId"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"text":"since","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"onlyAgent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCallback"},{"text":": ","kind":"text"},{"text":"ZDKRequestCommentListCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestCommentListCallback"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"getCommentsWithRequestId:sinceDate:onlyAgent:withCallback:","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestCommentListCallback":{"role":"symbol","title":"ZDKRequestCommentListCallback","url":"\/documentation\/supportproviderssdk\/zdkrequestcommentlistcallback","abstract":[{"type":"text","text":"Block defined for callback to be used for handling async server responses for fetching a list of comments"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestCommentListCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKRequestCommentListCallback","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKRequestCommentListCallback","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKRequestProvider","kind":"identifier"}],"type":"topic","title":"ZDKRequestProvider","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","kind":"symbol","navigatorTitle":[{"text":"ZDKRequestProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"getCommentsWithRequestId:sinceDate:onlyAgent:withCallback:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getCommentsWithRequestId:sinceDate:onlyAgent:withCallback:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"getCommentsWithRequestId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"requestId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"sinceDate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *) "},{"text":"sinceDate","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyAgent:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"onlyAgent"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCallback:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestCommentListCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestCommentListCallback","text":"ZDKRequestCommentListCallback"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"getCommentsWithRequestId:sinceDate:onlyAgent:withCallback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getCommentsWithRequestId(_:since:onlyAgent:withCallback:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"getCommentsWithRequestId:sinceDate:onlyAgent:withCallback:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getCommentsWithRequestId(_:since:onlyAgent:withCallback:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestCommentListCallback\/title","value":"ZDKRequestCommentListCallback","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestCommentListCallback\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKRequestCommentListCallback"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title","value":"ZDKRequestProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments","value":[{"text":"ZDKRequestProvider","kind":"identifier"}]}]}]}