{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/updaterequeststoragewithrequests(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/updaterequeststoragewithrequests(_:)"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/updateRequestStorageWithRequests(_:)"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"c:@CM@SupportProvidersSDK@@objc(cs)ZDKRequestProvider(im)updateRequestStorageWithRequests:","extendedModule":"SupportProvidersSDK","modules":[{"name":"SupportProvidersSDK"}],"title":"updateRequestStorageWithRequests(_:)","symbolKind":"method","navigatorTitle":[{"text":"updateRequestStorageWithRequests:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateRequestStorageWithRequests","kind":"identifier"},{"text":"([","kind":"text"},{"text":"ZDKRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKRequest"},{"text":"])","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRequestStorageWithRequests"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"requests"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKRequest","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","text":"ZDKRequest"},{"text":"])","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/updateRequestStorageWithRequests(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateRequestStorageWithRequests","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKRequest","kind":"typeIdentifier","text":"ZDKRequest"},{"text":"])","kind":"text"}],"role":"symbol","type":"topic","abstract":[],"title":"updateRequestStorageWithRequests(_:)","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/updateRequestStorageWithRequests(_:)","navigatorTitle":[{"kind":"identifier","text":"updateRequestStorageWithRequests:"}],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/updaterequeststoragewithrequests(_:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKRequestProvider","kind":"identifier"}],"type":"topic","title":"ZDKRequestProvider","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","kind":"symbol","navigatorTitle":[{"text":"ZDKRequestProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequest":{"title":"ZDKRequest","navigatorTitle":[{"text":"ZDKRequest","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkrequest","abstract":[{"type":"text","text":"Object representing a Zendesk end user request returned by the server."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequest"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"updateRequestStorageWithRequests:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"updateRequestStorageWithRequests:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"updateRequestStorageWithRequests:"},{"kind":"text","text":"("},{"text":"NSArray<ZDKRequest *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"requests","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1updateRequestStorageWithRequests(_:)\/title","op":"replace","value":"updateRequestStorageWithRequests:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1updateRequestStorageWithRequests(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateRequestStorageWithRequests:"}]},{"value":"ZDKRequestProvider","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKRequestProvider"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments"},{"value":"ZDKRequest","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/fragments","op":"replace","value":[{"text":"ZDKRequest","kind":"identifier"}]}]}]}