{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withRequestStorage"},{"kind":"text","text":" "},{"kind":"internalParam","text":"requestStorage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestStorage","text":"RequestStorage"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator\/init(withrequeststorage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator\/init(withrequeststorage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator\/init(withRequestStorage:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withRequestStorage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RequestStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestStorage"},{"kind":"text","text":")"}],"title":"init(withRequestStorage:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKLegacyRequestStorageMigrator(im)initWithRequestStorage:","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRequestStorage:"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestStorage":{"role":"symbol","title":"RequestStorage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestStorage"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestStorage"}],"url":"\/documentation\/supportproviderssdk\/requeststorage"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/LegacyRequestStorageMigrator/init(withRequestStorage:)":{"role":"symbol","title":"init(withRequestStorage:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withRequestStorage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RequestStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestStorage"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator\/init(withRequestStorage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRequestStorage:"}],"url":"\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator\/init(withrequeststorage:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/LegacyRequestStorageMigrator":{"role":"symbol","title":"LegacyRequestStorageMigrator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegacyRequestStorageMigrator"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegacyRequestStorageMigrator"}],"url":"\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithRequestStorage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRequestStorage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRequestStorage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestStorage","text":"ZDKRequestStorage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"requestStorage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/title","value":"ZDKRequestStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/fragments","value":[{"kind":"identifier","text":"ZDKRequestStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator~1init(withRequestStorage:)\/title","value":"initWithRequestStorage:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator~1init(withRequestStorage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRequestStorage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator\/title","value":"ZDKLegacyRequestStorageMigrator"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator\/fragments","value":[{"kind":"identifier","text":"ZDKLegacyRequestStorageMigrator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}