{"abstract":[{"type":"text","text":"Anonymous authentication."}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkauthenticationtype\/anonymous"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkauthenticationtype\/anonymous"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/anonymous"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"anonymous","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","title":"ZDKAuthenticationType.anonymous","symbolKind":"case","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationTypeAnonymous"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"anonymous","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@ZDKAuthenticationType@ZDKAuthenticationTypeAnonymous"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType/anonymous":{"kind":"symbol","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype\/anonymous","navigatorTitle":[{"text":"ZDKAuthenticationTypeAnonymous","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"anonymous"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/anonymous","abstract":[{"text":"Anonymous authentication.","type":"text"}],"title":"ZDKAuthenticationType.anonymous"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType":{"type":"topic","kind":"symbol","title":"ZDKAuthenticationType","abstract":[{"text":"Represents the types of authentication SDK supports.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType","url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKAuthenticationType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationType"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ZDKAuthenticationTypeAnonymous","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKAuthenticationTypeAnonymous","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"ZDKAuthenticationTypeAnonymous","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"ZDKAuthenticationTypeAnonymous","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1anonymous\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1anonymous\/fragments","value":[{"text":"ZDKAuthenticationTypeAnonymous","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType\/title","value":"ZDKAuthenticationType"},{"op":"replace","value":[{"text":"ZDKAuthenticationType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}