{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkdeviceinfo\/deviceinfodictionary()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkdeviceinfo\/deviceinfodictionary()"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeviceInfo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeviceInfo\/deviceInfoDictionary()"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Returns an NSDictionary of all device info.","type":"text"}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"deviceInfoDictionary"}],"role":"symbol","title":"deviceInfoDictionary()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceInfoDictionary"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!","kind":"text"}],"externalID":"c:objc(cs)ZDKDeviceInfo(cm)deviceInfoDictionary","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deviceInfoDictionary","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"all device info","type":"text"}]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDeviceInfo/deviceInfoDictionary()":{"navigatorTitle":[{"text":"deviceInfoDictionary","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkdeviceinfo\/deviceinfodictionary()","title":"deviceInfoDictionary()","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deviceInfoDictionary","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"text":"Returns an NSDictionary of all device info.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeviceInfo\/deviceInfoDictionary()"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDeviceInfo":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKDeviceInfo","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkdeviceinfo","title":"ZDKDeviceInfo","navigatorTitle":[{"kind":"identifier","text":"ZDKDeviceInfo"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeviceInfo","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Helper class for retrieving device information."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"deviceInfoDictionary"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"deviceInfoDictionary","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"deviceInfoDictionary"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"deviceInfoDictionary","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeviceInfo~1deviceInfoDictionary()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeviceInfo~1deviceInfoDictionary()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"deviceInfoDictionary","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeviceInfo\/title","value":"ZDKDeviceInfo"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeviceInfo\/fragments","value":[{"kind":"identifier","text":"ZDKDeviceInfo"}],"op":"replace"}]}]}