{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKLegacyRequestStorageMigrator) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LegacyRequestStorageMigrator","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Class","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKLegacyRequestStorageMigrator","navigatorTitle":[{"text":"LegacyRequestStorageMigrator","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LegacyRequestStorageMigrator","kind":"identifier"}],"role":"symbol","title":"LegacyRequestStorageMigrator"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"variants":[{"paths":["\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator\/init(withRequestStorage:)"],"title":"Initializers"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator\/checkAndMigrateOldTicketIds()"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/LegacyRequestStorageMigrator":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"LegacyRequestStorageMigrator","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LegacyRequestStorageMigrator"}],"url":"\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator","title":"LegacyRequestStorageMigrator"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/LegacyRequestStorageMigrator/checkAndMigrateOldTicketIds()":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"checkAndMigrateOldTicketIds"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator\/checkAndMigrateOldTicketIds()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"checkAndMigrateOldTicketIds","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator\/checkandmigrateoldticketids()","title":"checkAndMigrateOldTicketIds()"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/LegacyRequestStorageMigrator/init(withRequestStorage:)":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithRequestStorage:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator\/init(withRequestStorage:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"withRequestStorage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RequestStorage","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestStorage"},{"kind":"text","text":")"}],"url":"\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator\/init(withrequeststorage:)","title":"init(withRequestStorage:)"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"ZDKLegacyRequestStorageMigrator","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKLegacyRequestStorageMigrator"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKLegacyRequestStorageMigrator","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator\/checkAndMigrateOldTicketIds()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator\/init(withRequestStorage:)"]}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKLegacyRequestStorageMigrator","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator\/title","op":"replace","value":"ZDKLegacyRequestStorageMigrator"},{"value":[{"text":"ZDKLegacyRequestStorageMigrator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator~1checkAndMigrateOldTicketIds()\/title","value":"checkAndMigrateOldTicketIds"},{"value":[{"text":"- ","kind":"text"},{"text":"checkAndMigrateOldTicketIds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator~1checkAndMigrateOldTicketIds()\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator~1init(withRequestStorage:)\/title","value":"initWithRequestStorage:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator~1init(withRequestStorage:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithRequestStorage:","kind":"identifier"}]}]}]}