{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAPILoginState","kind":"identifier"}]}]}],"abstract":[{"text":"ZDKAPI Login state.","type":"text"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkapiloginstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkapiloginstate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Enumeration","externalID":"c:@E@ZDKAPILoginState","navigatorTitle":[{"kind":"identifier","text":"ZDKAPILoginState"}],"symbolKind":"enum","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPILoginState"}],"role":"symbol","title":"ZDKAPILoginState"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/loggedIn","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/loggingIn","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/notLoggedIn"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/Equatable-Implementations","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH","doc:\/\/com.zendesk.SupportProvidersSDK\/SY","doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/Equatable-Implementations","kind":"article","url":"\/documentation\/supportproviderssdk\/zdkapiloginstate\/equatable-implementations","title":"Equatable Implementations"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/supportproviderssdk\/zdkapiloginstate\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState":{"title":"ZDKAPILoginState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAPILoginState","kind":"identifier"}],"abstract":[{"type":"text","text":"ZDKAPI Login state."}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkapiloginstate","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKAPILoginState"}]},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState/loggingIn":{"title":"ZDKAPILoginState.loggingIn","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loggingIn"}],"abstract":[{"text":"The SDK is in the process of logging in.","type":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkapiloginstate\/loggingin","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/loggingIn","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKAPILoginStateLoggingIn"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState/init(rawValue:)":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkapiloginstate\/init(rawvalue:)","title":"init(rawValue:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState/loggedIn":{"abstract":[{"text":"The SDK has an oauth token that was valid the last time it was used.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ZDKAPILoginStateLoggedIn","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/loggedIn","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"loggedIn","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkapiloginstate\/loggedin","title":"ZDKAPILoginState.loggedIn"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState/notLoggedIn":{"url":"\/documentation\/supportproviderssdk\/zdkapiloginstate\/notloggedin","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notLoggedIn","kind":"identifier"}],"abstract":[{"type":"text","text":"The SDK has not yet authenticated during this session."}],"kind":"symbol","title":"ZDKAPILoginState.notLoggedIn","type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKAPILoginStateNotLoggedIn","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/notLoggedIn"},"doc://com.zendesk.SupportProvidersSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP","title":"Swift.Sendable"},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.SupportProvidersSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SY","title":"Swift.RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKAPILoginState","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ZDKAPILoginState","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ZDKAPILoginState","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/loggedIn","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/loggingIn","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/notLoggedIn"]}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAPILoginState","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}]}},{"value":"ZDKAPILoginState","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAPILoginState"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1loggingIn\/title","value":"ZDKAPILoginStateLoggingIn"},{"value":[{"kind":"identifier","text":"ZDKAPILoginStateLoggingIn"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1loggingIn\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1loggedIn\/title","value":"ZDKAPILoginStateLoggedIn","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1loggedIn\/fragments","value":[{"text":"ZDKAPILoginStateLoggedIn","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1notLoggedIn\/title","op":"replace","value":"ZDKAPILoginStateNotLoggedIn"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1notLoggedIn\/fragments","value":[{"text":"ZDKAPILoginStateNotLoggedIn","kind":"identifier"}],"op":"replace"}]}]}