{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_requestsubmissionstarting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_requestsubmissionstarting"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ZDKAPI_RequestSubmissionStarting","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Global Variable","externalID":"c:@ZDKAPI_RequestSubmissionStarting","navigatorTitle":[{"text":"ZDKAPI_RequestSubmissionStarting","kind":"identifier"}],"symbolKind":"var","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_RequestSubmissionStarting"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","title":"ZDKAPI_RequestSubmissionStarting"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"kind":"symbol","abstract":[{"type":"text","text":"Notification that a request is about to be submitted."}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_RequestSubmissionStarting","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPI_RequestSubmissionStarting":{"abstract":[{"type":"text","text":"Notification that a request is about to be submitted."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_RequestSubmissionStarting"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_RequestSubmissionStarting","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAPI_RequestSubmissionStarting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/supportproviderssdk\/zdkapi_requestsubmissionstarting","title":"ZDKAPI_RequestSubmissionStarting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"ZDKAPI_RequestSubmissionStarting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","value":[{"text":"ZDKAPI_RequestSubmissionStarting","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAPI_RequestSubmissionStarting"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"ZDKAPI_RequestSubmissionStarting","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_RequestSubmissionStarting\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_RequestSubmissionStarting\/fragments","value":[{"kind":"identifier","text":"ZDKAPI_RequestSubmissionStarting"}],"op":"replace"}]}]}