{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKCommentWithUser","kind":"identifier"}],"title":"ZDKCommentWithUser","symbolKind":"class","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:objc(cs)ZDKCommentWithUser","navigatorTitle":[{"text":"ZDKCommentWithUser","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKCommentWithUser"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser","interfaceLanguage":"swift"},"abstract":[{"text":"Aggregate model for comments with users.","type":"text"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/comment","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/user"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/build(_:withUsers:)"],"title":"Type Methods"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkcommentwithuser"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkcommentwithuser"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentWithUser/build(_:withUsers:)":{"type":"topic","url":"\/documentation\/supportproviderssdk\/zdkcommentwithuser\/build(_:withusers:)","role":"symbol","kind":"symbol","abstract":[{"text":"Build an instance with comment and a user.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/build(_:withUsers:)","title":"build(_:withUsers:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ZDKComment","preciseIdentifier":"c:objc(cs)ZDKComment"},{"text":"!, ","kind":"text"},{"text":"withUsers","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> "},{"kind":"typeIdentifier","text":"Self"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"buildCommentWithUser:withUsers:","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentWithUser":{"title":"ZDKCommentWithUser","abstract":[{"text":"Aggregate model for comments with users.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKCommentWithUser"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKCommentWithUser","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser","url":"\/documentation\/supportproviderssdk\/zdkcommentwithuser"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentWithUser/user":{"type":"topic","url":"\/documentation\/supportproviderssdk\/zdkcommentwithuser\/user","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/user","role":"symbol","kind":"symbol","abstract":[{"text":"The user associated with the comment model.","type":"text"}],"title":"user","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"user","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ZDKSupportUser","kind":"typeIdentifier","text":"ZDKSupportUser"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"user"}]},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentWithUser/comment":{"abstract":[{"text":"The comment model.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"comment"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKComment","kind":"typeIdentifier","text":"ZDKComment"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"comment","kind":"identifier"}],"type":"topic","role":"symbol","title":"comment","kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcommentwithuser\/comment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/comment"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKCommentWithUser"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKCommentWithUser"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKCommentWithUser"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/comment","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/user"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/build(_:withUsers:)"],"title":"Type Methods"}]},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"ZDKCommentWithUser","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1build(_:withUsers:)\/title","value":"buildCommentWithUser:withUsers:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1build(_:withUsers:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"buildCommentWithUser:withUsers:"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser\/title","value":"ZDKCommentWithUser","op":"replace"},{"value":[{"text":"ZDKCommentWithUser","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser\/fragments"},{"op":"replace","value":"user","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1user\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1user\/fragments","value":[{"text":"user","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1comment\/title","value":"comment","op":"replace"},{"value":[{"text":"comment","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1comment\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}