{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"abstract":[{"text":"ZDKNSCodingUtil is deprcated, and should no longer be used","type":"text"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"ZDKNSCodingUtil is deprcated, and should no longer be used"}],"type":"paragraph"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKNSCodingUtil"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Class","externalID":"c:objc(cs)ZDKNSCodingUtil","navigatorTitle":[{"kind":"identifier","text":"ZDKNSCodingUtil"}],"symbolKind":"class","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKNSCodingUtil","kind":"identifier"}],"platforms":[],"role":"symbol","title":"ZDKNSCodingUtil"},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNSCodingUtil\/decode(with:forInstance:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNSCodingUtil\/encode(with:forInstance:)"],"title":"Type Methods"}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdknscodingutil"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdknscodingutil"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNSCodingUtil"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNSCodingUtil/encode(with:forInstance:)":{"navigatorTitle":[{"kind":"identifier","text":"encodeWithCoder:forInstance:"}],"type":"topic","kind":"symbol","abstract":[],"title":"encode(with:forInstance:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"forInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"},{"kind":"text","text":"!)"}],"deprecated":true,"url":"\/documentation\/supportproviderssdk\/zdknscodingutil\/encode(with:forinstance:)","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNSCodingUtil\/encode(with:forInstance:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNSCodingUtil/decode(with:forInstance:)":{"url":"\/documentation\/supportproviderssdk\/zdknscodingutil\/decode(with:forinstance:)","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNSCodingUtil\/decode(with:forInstance:)","title":"decode(with:forInstance:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"decode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"forInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"text":"decodeWithCoder:forInstance:","kind":"identifier"}],"deprecated":true},"doc://com.zendesk.SupportProvidersSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNSCodingUtil":{"abstract":[{"type":"text","text":"ZDKNSCodingUtil is deprcated, and should no longer be used"}],"role":"symbol","navigatorTitle":[{"text":"ZDKNSCodingUtil","kind":"identifier"}],"deprecated":true,"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNSCodingUtil","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKNSCodingUtil","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdknscodingutil","title":"ZDKNSCodingUtil"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"ZDKNSCodingUtil","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKNSCodingUtil","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ZDKNSCodingUtil","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNSCodingUtil\/decode(with:forInstance:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNSCodingUtil\/encode(with:forInstance:)"],"title":"Type Methods"}]},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKNSCodingUtil"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"encodeWithCoder:forInstance:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNSCodingUtil~1encode(with:forInstance:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNSCodingUtil~1encode(with:forInstance:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"encodeWithCoder:forInstance:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNSCodingUtil~1decode(with:forInstance:)\/title","value":"decodeWithCoder:forInstance:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"decodeWithCoder:forInstance:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNSCodingUtil~1decode(with:forInstance:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNSCodingUtil\/title","value":"ZDKNSCodingUtil"},{"op":"replace","value":[{"text":"ZDKNSCodingUtil","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNSCodingUtil\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}