{"sections":[],"kind":"symbol","metadata":{"roleHeading":"Class","externalID":"c:objc(cs)ZDKRequestProvider","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestProvider"}],"title":"ZDKRequestProvider","symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestProvider"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKRequestProvider","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/addComment(_:forRequestId:attachments:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/addComment(_:forRequestId:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/createRequest(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getAllRequests(callback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getCommentsWithRequestId(_:since:onlyAgent:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getCommentsWithRequestId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getRequestById(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getRequestsByStatus(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getTicketForm(withIds:callback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getUpdatesForDevice(callback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/markRequestAsRead(_:withCommentCount:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/markRequestAsUnread(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/updateRequestStorageWithRequests(_:)"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/calculateRequestUpdates(_:)"],"title":"Type Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKProvider"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/markRequestAsUnread(_:)":{"title":"markRequestAsUnread(_:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/markrequestasunread(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"markRequestAsUnread","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"markRequestAsUnread:"}],"abstract":[{"type":"text","text":"Marks the request as unread"},{"text":" ","type":"text"},{"type":"text","text":"by incrementing the commentCount by one."},{"text":" ","type":"text"},{"text":"This should be used when a push notification has been recieved to","type":"text"},{"type":"text","text":" "},{"text":"updated the request as unread.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/markRequestAsUnread(_:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getCommentsWithRequestId(_:withCallback:)":{"abstract":[{"text":"Gets all comments for a request.","type":"text"},{"text":" ","type":"text"},{"text":"It will also get an access token if one has not been previously stored.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"getCommentsWithRequestId:withCallback:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getCommentsWithRequestId(_:withCallback:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getCommentsWithRequestId","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"text":"ZDKRequestCommentListCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestCommentListCallback"},{"kind":"text","text":"!)"}],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getcommentswithrequestid(_:withcallback:)","title":"getCommentsWithRequestId(_:withCallback:)"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/addComment(_:forRequestId:attachments:withCallback:)":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Add a comment message to a request with attachments on behalf of the end-user."},{"type":"text","text":" "},{"type":"text","text":"It will also get an access token if one has not been previously stored."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/addComment(_:forRequestId:attachments:withCallback:)","title":"addComment(_:forRequestId:attachments:withCallback:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addComment","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"forRequestId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"attachments"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestAddCommentCallback","text":"ZDKRequestAddCommentCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/addcomment(_:forrequestid:attachments:withcallback:)","navigatorTitle":[{"text":"addComment:forRequestId:attachments:withCallback:","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getUpdatesForDevice(callback:)":{"title":"getUpdatesForDevice(callback:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getupdatesfordevice(callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUpdatesForDevice"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates","text":"RequestUpdates"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"text":"getUpdatesForDeviceWithCallback:","kind":"identifier"}],"abstract":[{"text":"Gets details of any updates to requests for this device.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getUpdatesForDevice(callback:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/addComment(_:forRequestId:withCallback:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addComment:forRequestId:withCallback:"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addComment"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"forRequestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKRequestAddCommentCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestAddCommentCallback"},{"kind":"text","text":"!)"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/addComment(_:forRequestId:withCallback:)","title":"addComment(_:forRequestId:withCallback:)","abstract":[{"type":"text","text":"Add a comment message to a request."},{"type":"text","text":" "},{"type":"text","text":"It will also get an access token if one has not been previously stored."}],"url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/addcomment(_:forrequestid:withcallback:)","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/updateRequestStorageWithRequests(_:)":{"title":"updateRequestStorageWithRequests(_:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/updaterequeststoragewithrequests(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateRequestStorageWithRequests"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"ZDKRequest","preciseIdentifier":"c:objc(cs)ZDKRequest"},{"kind":"text","text":"])"}],"type":"topic","navigatorTitle":[{"text":"updateRequestStorageWithRequests:","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/updateRequestStorageWithRequests(_:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/calculateRequestUpdates(_:)":{"title":"calculateRequestUpdates(_:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/calculaterequestupdates(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"calculateRequestUpdates"},{"text":"([","kind":"text"},{"text":"RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestUpdates","text":"RequestUpdates"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/calculateRequestUpdates(_:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKProvider":{"navigatorTitle":[{"text":"ZDKProvider","kind":"identifier"}],"title":"ZDKProvider","type":"topic","abstract":[{"text":"ZDKProvider class","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProvider","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkprovider","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKProvider"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getRequestsByStatus(_:withCallback:)":{"title":"getRequestsByStatus(_:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getrequestsbystatus(_:withcallback:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getRequestsByStatus","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestListCallback","kind":"typeIdentifier","text":"ZDKRequestListCallback"},{"kind":"text","text":"!)"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getRequestsByStatus:withCallback:"}],"abstract":[{"type":"text","text":"Filters requests that user has opened by a status."},{"text":" ","type":"text"},{"text":"It will also get an access token if one has not been previously stored.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getRequestsByStatus(_:withCallback:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getAllRequests(callback:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllRequests"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestListCallback","text":"ZDKRequestListCallback"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Gets all requests that user has opened."},{"text":" ","type":"text"},{"text":"It will also get an access token if one has not been previously stored.","type":"text"},{"type":"text","text":" "},{"text":"If you are using anonymous identities we will check to see if you have any stored request IDs.","type":"text"},{"text":" ","type":"text"},{"text":"This is how requests work when dealing with anonymous identities. If you do have stored request","type":"text"},{"type":"text","text":" "},{"type":"text","text":"IDs we will fetch these requests from your Zendesk instance. If you do not have any stored request"},{"type":"text","text":" "},{"text":"IDs we will skip the network call and return an empty list of Requests.","type":"text"}],"title":"getAllRequests(callback:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getAllRequests(callback:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getallrequests(callback:)","navigatorTitle":[{"text":"getAllRequestsWithCallback:","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getRequestById(_:withCallback:)":{"title":"getRequestById(_:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getrequestbyid(_:withcallback:)","type":"topic","navigatorTitle":[{"text":"getRequestById:withCallback:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getRequestById(_:withCallback:)","role":"symbol","abstract":[{"type":"text","text":"Gets the request specified by the ID."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getRequestById","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ZDKRequestCallback","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/createRequest(_:withCallback:)":{"title":"createRequest(_:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/createrequest(_:withcallback:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createRequest"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)ZDKCreateRequest","kind":"typeIdentifier","text":"ZDKCreateRequest"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKCreateRequestCallback","text":"ZDKCreateRequestCallback"},{"kind":"text","text":"!)"}],"type":"topic","navigatorTitle":[{"text":"createRequest:withCallback:","kind":"identifier"}],"abstract":[{"text":"Calls a request service to create a request on behalf of the end user.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/createRequest(_:withCallback:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/markRequestAsRead(_:withCommentCount:)":{"navigatorTitle":[{"kind":"identifier","text":"markRequestAsRead:withCommentCount:"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/markRequestAsRead(_:withCommentCount:)","abstract":[{"text":"Marks all the comments of a request as read","type":"text"},{"type":"text","text":" "},{"type":"text","text":"by making the commentCount and readCommentCount"},{"text":" ","type":"text"},{"text":"equal to the commentCount that is passed in.","type":"text"}],"title":"markRequestAsRead(_:withCommentCount:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/markrequestasread(_:withcommentcount:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"markRequestAsRead"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"withCommentCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getTicketForm(withIds:callback:)":{"title":"getTicketForm(withIds:callback:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getticketform(withids:callback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getTicketForm"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]!, "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ZDKTicketFormCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKTicketFormCallback"},{"kind":"text","text":"!)"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getTicketFormWithIds:callback:"}],"abstract":[{"text":"Gets the ticket froms","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Only the first 5 ticket form Ids will be fetched."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getTicketForm(withIds:callback:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"navigatorTitle":[{"text":"ZDKRequestProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","abstract":[],"title":"ZDKRequestProvider","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKRequestProvider","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/getCommentsWithRequestId(_:since:onlyAgent:withCallback:)":{"title":"getCommentsWithRequestId(_:since:onlyAgent:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/getcommentswithrequestid(_:since:onlyagent:withcallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getCommentsWithRequestId","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"since"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"onlyAgent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKRequestProvider.h@T@ZDKRequestCommentListCallback","text":"ZDKRequestCommentListCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCommentsWithRequestId:sinceDate:onlyAgent:withCallback:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getCommentsWithRequestId(_:since:onlyAgent:withCallback:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"ZDKRequestProvider","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKRequestProvider"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKRequestProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/addComment(_:forRequestId:attachments:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/addComment(_:forRequestId:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/createRequest(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getAllRequests(callback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getCommentsWithRequestId(_:since:onlyAgent:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getCommentsWithRequestId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getRequestById(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getRequestsByStatus(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getTicketForm(withIds:callback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/getUpdatesForDevice(callback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/markRequestAsRead(_:withCommentCount:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/markRequestAsUnread(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/updateRequestStorageWithRequests(_:)"]}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKProvider"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestProvider"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKProvider","text":"ZDKProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKProvider"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1markRequestAsUnread(_:)\/title","value":"markRequestAsUnread:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"markRequestAsUnread:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1markRequestAsUnread(_:)\/fragments"},{"op":"replace","value":"getCommentsWithRequestId:withCallback:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getCommentsWithRequestId(_:withCallback:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getCommentsWithRequestId(_:withCallback:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getCommentsWithRequestId:withCallback:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1addComment(_:forRequestId:attachments:withCallback:)\/title","value":"addComment:forRequestId:attachments:withCallback:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1addComment(_:forRequestId:attachments:withCallback:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addComment:forRequestId:attachments:withCallback:"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getUpdatesForDevice(callback:)\/title","op":"replace","value":"getUpdatesForDeviceWithCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getUpdatesForDevice(callback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUpdatesForDeviceWithCallback:"}]},{"value":"addComment:forRequestId:withCallback:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1addComment(_:forRequestId:withCallback:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1addComment(_:forRequestId:withCallback:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addComment:forRequestId:withCallback:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1updateRequestStorageWithRequests(_:)\/title","value":"updateRequestStorageWithRequests:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateRequestStorageWithRequests:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1updateRequestStorageWithRequests(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKProvider\/title","value":"ZDKProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKProvider\/fragments","value":[{"text":"ZDKProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getRequestsByStatus(_:withCallback:)\/title","op":"replace","value":"getRequestsByStatus:withCallback:"},{"value":[{"text":"- ","kind":"text"},{"text":"getRequestsByStatus:withCallback:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getRequestsByStatus(_:withCallback:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getAllRequests(callback:)\/title","value":"getAllRequestsWithCallback:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"getAllRequestsWithCallback:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getAllRequests(callback:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getRequestById(_:withCallback:)\/title","value":"getRequestById:withCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getRequestById(_:withCallback:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"getRequestById:withCallback:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1createRequest(_:withCallback:)\/title","value":"createRequest:withCallback:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createRequest:withCallback:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1createRequest(_:withCallback:)\/fragments"},{"value":"markRequestAsRead:withCommentCount:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1markRequestAsRead(_:withCommentCount:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1markRequestAsRead(_:withCommentCount:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"markRequestAsRead:withCommentCount:"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getTicketForm(withIds:callback:)\/title","value":"getTicketFormWithIds:callback:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getTicketFormWithIds:callback:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getTicketForm(withIds:callback:)\/fragments"},{"value":"ZDKRequestProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title"},{"value":[{"text":"ZDKRequestProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments"},{"op":"replace","value":"getCommentsWithRequestId:sinceDate:onlyAgent:withCallback:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getCommentsWithRequestId(_:since:onlyAgent:withCallback:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCommentsWithRequestId:sinceDate:onlyAgent:withCallback:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1getCommentsWithRequestId(_:since:onlyAgent:withCallback:)\/fragments"}]}]}