{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/markRequestAsRead(_:withCommentCount:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markRequestAsRead"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"requestId","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCommentCount"},{"kind":"text","text":" "},{"kind":"internalParam","text":"commentCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"requestId","content":[{"inlineContent":[{"type":"text","text":"ID of request to mark as read"}],"type":"paragraph"}]},{"name":"commentCount","content":[{"inlineContent":[{"type":"text","text":"This sets both the commentCount and readCommentCount as this number."}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/markrequestasread(_:withcommentcount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestprovider\/markrequestasread(_:withcommentcount:)"]}],"sections":[],"abstract":[{"text":"Marks all the comments of a request as read","type":"text"},{"type":"text","text":" "},{"text":"by making the commentCount and readCommentCount","type":"text"},{"text":" ","type":"text"},{"text":"equal to the commentCount that is passed in.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@CM@SupportProvidersSDK@@objc(cs)ZDKRequestProvider(im)markRequestAsRead:withCommentCount:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markRequestAsRead"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"withCommentCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"markRequestAsRead:withCommentCount:"}],"title":"markRequestAsRead(_:withCommentCount:)","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider":{"navigatorTitle":[{"text":"ZDKRequestProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider","abstract":[],"title":"ZDKRequestProvider","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKRequestProvider","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestProvider/markRequestAsRead(_:withCommentCount:)":{"navigatorTitle":[{"kind":"identifier","text":"markRequestAsRead:withCommentCount:"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestProvider\/markRequestAsRead(_:withCommentCount:)","abstract":[{"text":"Marks all the comments of a request as read","type":"text"},{"type":"text","text":" "},{"type":"text","text":"by making the commentCount and readCommentCount"},{"text":" ","type":"text"},{"text":"equal to the commentCount that is passed in.","type":"text"}],"title":"markRequestAsRead(_:withCommentCount:)","url":"\/documentation\/supportproviderssdk\/zdkrequestprovider\/markrequestasread(_:withcommentcount:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"markRequestAsRead"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"withCommentCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"markRequestAsRead:withCommentCount:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"markRequestAsRead:withCommentCount:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"markRequestAsRead:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"requestId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withCommentCount:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"commentCount"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/title","value":"ZDKRequestProvider"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKRequestProvider"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider\/fragments"},{"value":"markRequestAsRead:withCommentCount:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1markRequestAsRead(_:withCommentCount:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestProvider~1markRequestAsRead(_:withCommentCount:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"markRequestAsRead:withCommentCount:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}