{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"title":"humanReadableFileSize()","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"humanReadableFileSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"externalID":"c:objc(cs)ZDKHelpCenterAttachment(im)humanReadableFileSize","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"humanReadableFileSize","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/humanReadableFileSize()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"humanReadableFileSize"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"human readable format of the file size."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/humanreadablefilesize()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/humanreadablefilesize()"]}],"abstract":[{"type":"text","text":"Returns a string human readable format of file size."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment":{"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterAttachment"}],"title":"ZDKHelpCenterAttachment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment","abstract":[{"text":"A model for Help Center Attachments.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterAttachment"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/humanReadableFileSize()":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/humanReadableFileSize()","title":"humanReadableFileSize()","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Returns a string human readable format of file size."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"humanReadableFileSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"humanReadableFileSize","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/humanreadablefilesize()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"humanReadableFileSize","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"humanReadableFileSize","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"humanReadableFileSize"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment\/title","value":"ZDKHelpCenterAttachment","op":"replace"},{"op":"replace","value":[{"text":"ZDKHelpCenterAttachment","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment\/fragments"},{"op":"replace","value":"humanReadableFileSize","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1humanReadableFileSize()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1humanReadableFileSize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"humanReadableFileSize"}]}]}]}