{"kind":"symbol","metadata":{"title":"convertError(response:originalError:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"convertErrorWithResponse:originalError:"}],"modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Type Method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"convertError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"response","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse","text":"URLResponse"},{"text":"?, ","kind":"text"},{"text":"originalError","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?","kind":"text"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)DispatcherAdapter(cm)convertErrorWithResponse:originalError:"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/dispatcheradapter\/converterror(response:originalerror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/dispatcheradapter\/converterror(response:originalerror:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/convertError(response:originalError:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"convertError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse","text":"URLResponse"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"originalError"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/DispatcherAdapter/convertError(response:originalError:)":{"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convertError","kind":"identifier"},{"kind":"text","text":"("},{"text":"response","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"originalError"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"convertErrorWithResponse:originalError:"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/convertError(response:originalError:)","type":"topic","url":"\/documentation\/supportproviderssdk\/dispatcheradapter\/converterror(response:originalerror:)","title":"convertError(response:originalError:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/DispatcherAdapter":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"DispatcherAdapter","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter","abstract":[],"title":"DispatcherAdapter","url":"\/documentation\/supportproviderssdk\/dispatcheradapter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DispatcherAdapter","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"convertErrorWithResponse:originalError:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"convertErrorWithResponse:originalError:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"convertErrorWithResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLResponse","text":"NSURLResponse","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"response","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"originalError:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"convertErrorWithResponse:originalError:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1convertError(response:originalError:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1convertError(response:originalError:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"convertErrorWithResponse:originalError:","kind":"identifier"}]},{"value":"DispatcherAdapter","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter\/fragments","value":[{"text":"DispatcherAdapter","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}