{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/comboBox","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/combobox"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/combobox"]}],"abstract":[{"text":"Ticket field combobox type (Combobox)","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@E@ZDKTicketFieldType@ZDKTicketFieldTypeComboBox","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"ZDKTicketFieldTypeComboBox","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","title":"ZDKTicketFieldType.comboBox","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"comboBox","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"comboBox","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType":{"navigatorTitle":[{"text":"ZDKTicketFieldType","kind":"identifier"}],"title":"ZDKTicketFieldType","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType","kind":"symbol","type":"topic","abstract":[{"text":"Ticket field type","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldType","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/comboBox":{"title":"ZDKTicketFieldType.comboBox","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"comboBox","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/combobox","abstract":[{"type":"text","text":"Ticket field combobox type (Combobox)"}],"navigatorTitle":[{"text":"ZDKTicketFieldTypeComboBox","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/comboBox","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKTicketFieldTypeComboBox"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKTicketFieldTypeComboBox","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ZDKTicketFieldTypeComboBox","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/title","op":"replace","value":"ZDKTicketFieldType"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/fragments","value":[{"text":"ZDKTicketFieldType","kind":"identifier"}],"op":"replace"},{"value":"ZDKTicketFieldTypeComboBox","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1comboBox\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1comboBox\/fragments","value":[{"text":"ZDKTicketFieldTypeComboBox","kind":"identifier"}]}]}]}