{"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"ZDKTicketFieldTypeDate","kind":"identifier"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","externalID":"c:@E@ZDKTicketFieldType@ZDKTicketFieldTypeDate","title":"ZDKTicketFieldType.date","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"date","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType"]]},"abstract":[{"type":"text","text":"Ticket field date selection type"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/date"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/date"]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/date","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"date"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/date":{"title":"ZDKTicketFieldType.date","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"date","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Ticket field date selection type"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/date","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldTypeDate"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/date","kind":"symbol","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType":{"navigatorTitle":[{"text":"ZDKTicketFieldType","kind":"identifier"}],"title":"ZDKTicketFieldType","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType","kind":"symbol","type":"topic","abstract":[{"text":"Ticket field type","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKTicketFieldTypeDate","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKTicketFieldTypeDate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ZDKTicketFieldTypeDate","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1date\/title","value":"ZDKTicketFieldTypeDate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1date\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldTypeDate"}]},{"value":"ZDKTicketFieldType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldType"}]}]}]}