{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType"]]},"abstract":[{"type":"text","text":"Ticket field regular expression type"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/regex","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"regex"}]}]}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/regex"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype\/regex"]}],"kind":"symbol","metadata":{"externalID":"c:@E@ZDKTicketFieldType@ZDKTicketFieldTypeRegex","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"ZDKTicketFieldTypeRegex","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","title":"ZDKTicketFieldType.regex","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"regex","kind":"identifier"}]},"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/regex":{"title":"ZDKTicketFieldType.regex","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"regex","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/regex","abstract":[{"type":"text","text":"Ticket field regular expression type"}],"navigatorTitle":[{"text":"ZDKTicketFieldTypeRegex","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/regex","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType":{"navigatorTitle":[{"text":"ZDKTicketFieldType","kind":"identifier"}],"title":"ZDKTicketFieldType","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType","kind":"symbol","type":"topic","abstract":[{"text":"Ticket field type","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKTicketFieldTypeRegex"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKTicketFieldTypeRegex"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ZDKTicketFieldTypeRegex","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKTicketFieldTypeRegex","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1regex\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1regex\/fragments","value":[{"text":"ZDKTicketFieldTypeRegex","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/title","value":"ZDKTicketFieldType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/fragments","value":[{"text":"ZDKTicketFieldType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}