{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recordArticleViewRequestJson","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A dictionary containing the last search model and a unique search result click. nil if no search has been preformed.","type":"text"}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache\/recordArticleViewRequestJson()","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"recordArticleViewRequestJson"}],"roleHeading":"Type Method","title":"recordArticleViewRequestJson()","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recordArticleViewRequestJson"},{"kind":"text","text":"() -> ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"externalID":"c:objc(cs)ZDKHelpCenterSessionCache(cm)recordArticleViewRequestJson","role":"symbol"},"abstract":[{"text":"Used when submitting an article view with the Help Center provider.","type":"text"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/recordarticleviewrequestjson()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/recordarticleviewrequestjson()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache"]]},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSessionCache":{"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterSessionCache","kind":"identifier"}],"title":"ZDKHelpCenterSessionCache","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache","url":"\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterSessionCache"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSessionCache/recordArticleViewRequestJson()":{"abstract":[{"type":"text","text":"Used when submitting an article view with the Help Center provider."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"recordArticleViewRequestJson"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/recordarticleviewrequestjson()","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache\/recordArticleViewRequestJson()","type":"topic","title":"recordArticleViewRequestJson()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordArticleViewRequestJson"},{"kind":"text","text":"() -> ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"recordArticleViewRequestJson"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"recordArticleViewRequestJson","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"recordArticleViewRequestJson"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache\/title","op":"replace","value":"ZDKHelpCenterSessionCache"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterSessionCache"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache\/fragments","op":"replace"},{"op":"replace","value":"recordArticleViewRequestJson","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache~1recordArticleViewRequestJson()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache~1recordArticleViewRequestJson()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"recordArticleViewRequestJson","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}