{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/unsetuniquesearchresultclick()"]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/unsetuniquesearchresultclick()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache\/unsetUniqueSearchResultClick()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Un-sets the unique search result click flag"}],"metadata":{"externalID":"c:objc(cs)ZDKHelpCenterSessionCache(cm)unsetUniqueSearchResultClick","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"unsetUniqueSearchResultClick","kind":"identifier"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol","title":"unsetUniqueSearchResultClick()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unsetUniqueSearchResultClick"},{"kind":"text","text":"()"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unsetUniqueSearchResultClick"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSessionCache/unsetUniqueSearchResultClick()":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache\/unsetUniqueSearchResultClick()","type":"topic","kind":"symbol","navigatorTitle":[{"text":"unsetUniqueSearchResultClick","kind":"identifier"}],"abstract":[{"type":"text","text":"Un-sets the unique search result click flag"}],"role":"symbol","title":"unsetUniqueSearchResultClick()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unsetUniqueSearchResultClick","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/unsetuniquesearchresultclick()"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSessionCache":{"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterSessionCache","kind":"identifier"}],"title":"ZDKHelpCenterSessionCache","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache","url":"\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterSessionCache"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"unsetUniqueSearchResultClick"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unsetUniqueSearchResultClick"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"unsetUniqueSearchResultClick","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache~1unsetUniqueSearchResultClick()\/title","op":"replace","value":"unsetUniqueSearchResultClick"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache~1unsetUniqueSearchResultClick()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unsetUniqueSearchResultClick"}],"op":"replace"},{"value":"ZDKHelpCenterSessionCache","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterSessionCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}