{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKValidation"]]},"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","externalID":"c:@E@ZDKValidation@ZDKValidationNilError","title":"ZDKValidation.nilError","navigatorTitle":[{"text":"ZDKValidationNilError","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nilError"}],"symbolKind":"case","roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"nilError","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"abstract":[{"type":"text","text":"Nil value error code"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkvalidation\/nilerror"]},{"paths":["\/documentation\/supportproviderssdk\/zdkvalidation\/nilerror"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKValidation\/nilError","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKValidation":{"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkvalidation","role":"symbol","type":"topic","abstract":[{"text":"Validation error codes","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKValidation","kind":"identifier"}],"title":"ZDKValidation","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKValidation","navigatorTitle":[{"kind":"identifier","text":"ZDKValidation"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKValidation/nilError":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nilError"}],"abstract":[{"type":"text","text":"Nil value error code"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKValidationNilError","kind":"identifier"}],"title":"ZDKValidation.nilError","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKValidation\/nilError","url":"\/documentation\/supportproviderssdk\/zdkvalidation\/nilerror"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ZDKValidationNilError","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKValidationNilError","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKValidationNilError"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKValidation\/title","op":"replace","value":"ZDKValidation"},{"value":[{"text":"ZDKValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKValidation\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKValidation~1nilError\/title","op":"replace","value":"ZDKValidationNilError"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKValidation~1nilError\/fragments","value":[{"text":"ZDKValidationNilError","kind":"identifier"}],"op":"replace"}]}]}