{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSettingsProvider"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getHelpCenterSettings","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"text":"HelpCenterSettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSettings"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSettingsProvider(cm)getHelpCenterSettingsWithCallback:","navigatorTitle":[{"text":"getHelpCenterSettingsWithCallback:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getHelpCenterSettings"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSettings","text":"HelpCenterSettings"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"getHelpCenterSettings(callback:)","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Type Method"},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersettingsprovider\/gethelpcentersettings(callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersettingsprovider\/gethelpcentersettings(callback:)"]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSettingsProvider\/getHelpCenterSettings(callback:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSettingsProvider/getHelpCenterSettings(callback:)":{"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersettingsprovider\/gethelpcentersettings(callback:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getHelpCenterSettings","kind":"identifier"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"HelpCenterSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSettings"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[],"title":"getHelpCenterSettings(callback:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"getHelpCenterSettingsWithCallback:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSettingsProvider\/getHelpCenterSettings(callback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSettingsProvider":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterSettingsProvider","kind":"identifier"}],"title":"ZDKHelpCenterSettingsProvider","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSettingsProvider","url":"\/documentation\/supportproviderssdk\/zdkhelpcentersettingsprovider","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterSettingsProvider"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSettings":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HelpCenterSettings"}],"abstract":[],"title":"HelpCenterSettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HelpCenterSettings","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/helpcentersettings"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"getHelpCenterSettingsWithCallback:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getHelpCenterSettingsWithCallback:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"getHelpCenterSettingsWithCallback:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(ZDKHelpCenterSettings *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSettings)"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSettingsProvider~1getHelpCenterSettings(callback:)\/title","op":"replace","value":"getHelpCenterSettingsWithCallback:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSettingsProvider~1getHelpCenterSettings(callback:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getHelpCenterSettingsWithCallback:"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSettingsProvider\/title","value":"ZDKHelpCenterSettingsProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSettingsProvider\/fragments","value":[{"text":"ZDKHelpCenterSettingsProvider","kind":"identifier"}]},{"value":"ZDKHelpCenterSettings","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings\/fragments","value":[{"text":"ZDKHelpCenterSettings","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}