{"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"addEtagToRequest:","kind":"identifier"}],"externalID":"c:objc(cs)ZDKETag(cm)addEtagToRequest:","roleHeading":"Type Method","role":"symbol","title":"addEtag(to:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addEtag","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSMutableURLRequest","text":"NSMutableURLRequest","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"symbolKind":"method"},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKETag\/addEtag(to:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addEtag","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":" ","kind":"text"},{"text":"request","kind":"internalParam"},{"kind":"text","text":": "},{"text":"NSMutableURLRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableURLRequest"},{"text":"!)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"request","content":[{"type":"paragraph","inlineContent":[{"text":"the request to which the etag will be added","type":"text"}]}]}]}],"abstract":[{"type":"text","text":"Adds the etag to the request if one is known."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKETag"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdketag\/addetag(to:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdketag\/addetag(to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKETag":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKETag"}],"abstract":[{"type":"text","text":"ETag lookup."}],"title":"ZDKETag","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKETag","type":"topic","url":"\/documentation\/supportproviderssdk\/zdketag","navigatorTitle":[{"kind":"identifier","text":"ZDKETag"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKETag/addEtag(to:)":{"title":"addEtag(to:)","type":"topic","url":"\/documentation\/supportproviderssdk\/zdketag\/addetag(to:)","navigatorTitle":[{"kind":"identifier","text":"addEtagToRequest:"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKETag\/addEtag(to:)","role":"symbol","abstract":[{"type":"text","text":"Adds the etag to the request if one is known."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addEtag","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSMutableURLRequest","preciseIdentifier":"c:objc(cs)NSMutableURLRequest","kind":"typeIdentifier"},{"text":"!)","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"addEtagToRequest:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"addEtagToRequest:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addEtagToRequest:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSMutableURLRequest","preciseIdentifier":"c:objc(cs)NSMutableURLRequest","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"request","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKETag\/title","value":"ZDKETag"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKETag\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKETag"}]},{"value":"addEtagToRequest:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKETag~1addEtag(to:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKETag~1addEtag(to:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addEtagToRequest:"}]}]}]}