{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFormsSettingsProvider\/getTicketFormsSettings(callback:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","roleHeading":"Type Method","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKTicketFormsSettingsProvider(cm)getTicketFormsSettingsWithCallback:","modules":[{"name":"SupportProvidersSDK"}],"title":"getTicketFormsSettings(callback:)","symbolKind":"method","navigatorTitle":[{"text":"getTicketFormsSettingsWithCallback:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getTicketFormsSettings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKTicketFormsSettings","text":"TicketFormsSettings","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTicketFormsSettings"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKTicketFormsSettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/TicketFormsSettings","text":"TicketFormsSettings"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketformssettingsprovider\/getticketformssettings(callback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketformssettingsprovider\/getticketformssettings(callback:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFormsSettingsProvider"]]},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFormsSettingsProvider/getTicketFormsSettings(callback:)":{"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketformssettingsprovider\/getticketformssettings(callback:)","navigatorTitle":[{"text":"getTicketFormsSettingsWithCallback:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFormsSettingsProvider\/getTicketFormsSettings(callback:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTicketFormsSettings","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"text":"TicketFormsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKTicketFormsSettings","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"title":"getTicketFormsSettings(callback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/TicketFormsSettings":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TicketFormsSettings"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/TicketFormsSettings","url":"\/documentation\/supportproviderssdk\/ticketformssettings","title":"TicketFormsSettings","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TicketFormsSettings"}],"kind":"symbol","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFormsSettingsProvider":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKTicketFormsSettingsProvider"}],"role":"symbol","type":"topic","abstract":[],"title":"ZDKTicketFormsSettingsProvider","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFormsSettingsProvider","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFormsSettingsProvider"}],"url":"\/documentation\/supportproviderssdk\/zdkticketformssettingsprovider"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"getTicketFormsSettingsWithCallback:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getTicketFormsSettingsWithCallback:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"getTicketFormsSettingsWithCallback:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$@M@SupportProvidersSDK@objc(cs)ZDKTicketFormsSettings)","text":"void (^)(ZDKTicketFormsSettings *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFormsSettingsProvider~1getTicketFormsSettings(callback:)\/title","value":"getTicketFormsSettingsWithCallback:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getTicketFormsSettingsWithCallback:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFormsSettingsProvider~1getTicketFormsSettings(callback:)\/fragments"},{"value":"ZDKTicketFormsSettings","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1TicketFormsSettings\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1TicketFormsSettings\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFormsSettings"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFormsSettingsProvider\/title","value":"ZDKTicketFormsSettingsProvider"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFormsSettingsProvider\/fragments","value":[{"text":"ZDKTicketFormsSettingsProvider","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}