{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkAndMigrateOldTicketIds"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator\/checkandmigrateoldticketids()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator\/checkandmigrateoldticketids()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator\/checkAndMigrateOldTicketIds()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkAndMigrateOldTicketIds"},{"kind":"text","text":"()"}],"title":"checkAndMigrateOldTicketIds()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SupportProvidersSDK@objc(cs)ZDKLegacyRequestStorageMigrator(im)checkAndMigrateOldTicketIds","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"checkAndMigrateOldTicketIds"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/LegacyRequestStorageMigrator/checkAndMigrateOldTicketIds()":{"role":"symbol","title":"checkAndMigrateOldTicketIds()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkAndMigrateOldTicketIds"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator\/checkAndMigrateOldTicketIds()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkAndMigrateOldTicketIds"}],"url":"\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator\/checkandmigrateoldticketids()"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/LegacyRequestStorageMigrator":{"role":"symbol","title":"LegacyRequestStorageMigrator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegacyRequestStorageMigrator"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/LegacyRequestStorageMigrator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegacyRequestStorageMigrator"}],"url":"\/documentation\/supportproviderssdk\/legacyrequeststoragemigrator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"checkAndMigrateOldTicketIds"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkAndMigrateOldTicketIds"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"checkAndMigrateOldTicketIds"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator~1checkAndMigrateOldTicketIds()\/title","value":"checkAndMigrateOldTicketIds"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator~1checkAndMigrateOldTicketIds()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkAndMigrateOldTicketIds"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator\/title","value":"ZDKLegacyRequestStorageMigrator"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1LegacyRequestStorageMigrator\/fragments","value":[{"kind":"identifier","text":"ZDKLegacyRequestStorageMigrator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}