{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheLastSearch","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"lastSearch","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch","kind":"typeIdentifier","text":"ZDKHelpCenterLastSearch","preciseIdentifier":"c:objc(cs)ZDKHelpCenterLastSearch"},{"kind":"text","text":"!)"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"lastSearch","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The search to be cached."}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/cachelastsearch(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/cachelastsearch(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache"]]},"abstract":[{"text":"Cache a search. This has the side effect of setting a unique search result click BOOL to yes.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"cacheLastSearch:","kind":"identifier"}],"role":"symbol","title":"cacheLastSearch(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cacheLastSearch","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterLastSearch","kind":"typeIdentifier","text":"ZDKHelpCenterLastSearch"},{"text":"!)","kind":"text"}],"externalID":"c:objc(cs)ZDKHelpCenterSessionCache(cm)cacheLastSearch:","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","roleHeading":"Type Method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache\/cacheLastSearch(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterLastSearch":{"type":"topic","navigatorTitle":[{"text":"ZDKHelpCenterLastSearch","kind":"identifier"}],"title":"ZDKHelpCenterLastSearch","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}],"role":"symbol","abstract":[{"text":"A model for recording the last search in Help Center.","type":"text"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSessionCache/cacheLastSearch(_:)":{"navigatorTitle":[{"text":"cacheLastSearch:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/cachelastsearch(_:)","title":"cacheLastSearch(_:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cacheLastSearch","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterLastSearch","text":"ZDKHelpCenterLastSearch","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"abstract":[{"type":"text","text":"Cache a search. This has the side effect of setting a unique search result click BOOL to yes."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache\/cacheLastSearch(_:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSessionCache":{"title":"ZDKHelpCenterSessionCache","url":"\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterSessionCache"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterSessionCache"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"cacheLastSearch:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cacheLastSearch:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"cacheLastSearch:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterLastSearch","text":"ZDKHelpCenterLastSearch","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch"},{"text":" *) ","kind":"text"},{"text":"lastSearch","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch\/title","value":"ZDKHelpCenterLastSearch","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache~1cacheLastSearch(_:)\/title","value":"cacheLastSearch:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache~1cacheLastSearch(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"cacheLastSearch:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache\/title","value":"ZDKHelpCenterSessionCache"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterSessionCache"}],"op":"replace"}]}]}