{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/localizedlabel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/localizedlabel"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizedLabel"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Nav bar button with localized label for conversations."}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/localizedLabel","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType"]]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeLocalizedLabel"}],"role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Case","externalID":"c:@E@ZDKNavBarConversationsUIType@ZDKNavBarConversationsUITypeLocalizedLabel","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedLabel"}],"title":"ZDKNavBarConversationsUIType.localizedLabel","symbolKind":"case"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType":{"title":"ZDKNavBarConversationsUIType","kind":"symbol","type":"topic","abstract":[{"text":"Enum to describe the types of nav bar button that display conversations.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKNavBarConversationsUIType"}],"navigatorTitle":[{"text":"ZDKNavBarConversationsUIType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType/localizedLabel":{"title":"ZDKNavBarConversationsUIType.localizedLabel","kind":"symbol","type":"topic","abstract":[{"text":"Nav bar button with localized label for conversations.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/localizedLabel","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedLabel"}],"navigatorTitle":[{"text":"ZDKNavBarConversationsUITypeLocalizedLabel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/localizedlabel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKNavBarConversationsUITypeLocalizedLabel"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeLocalizedLabel"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"ZDKNavBarConversationsUITypeLocalizedLabel","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType\/title","value":"ZDKNavBarConversationsUIType"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType\/fragments","value":[{"text":"ZDKNavBarConversationsUIType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1localizedLabel\/title","op":"replace","value":"ZDKNavBarConversationsUITypeLocalizedLabel"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1localizedLabel\/fragments","value":[{"text":"ZDKNavBarConversationsUITypeLocalizedLabel","kind":"identifier"}],"op":"replace"}]}]}