{"kind":"symbol","metadata":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKContactUsSettings(im)init","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"init","roleHeading":"Initializer"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"required"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/contactussettings\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/contactussettings\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ContactUsSettings"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ContactUsSettings\/init()","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ContactUsSettings":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactUsSettings","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ContactUsSettings","url":"\/documentation\/supportproviderssdk\/contactussettings","abstract":[],"navigatorTitle":[{"text":"ContactUsSettings","kind":"identifier"}],"role":"symbol","title":"ContactUsSettings","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ContactUsSettings/init()":{"title":"init()","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ContactUsSettings\/init()","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/contactussettings\/init()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"init"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"ZDKContactUsSettings","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ContactUsSettings\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ContactUsSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKContactUsSettings"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ContactUsSettings~1init()\/title","op":"replace","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ContactUsSettings~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}]}]}