{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKReachability\/forLocalWiFi()"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"forLocalWiFi","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","roleHeading":"Type Method","externalID":"c:objc(cs)ZDKReachability(cm)reachabilityForLocalWiFi","modules":[{"name":"SupportProvidersSDK"}],"title":"forLocalWiFi()","symbolKind":"method","navigatorTitle":[{"text":"reachabilityForLocalWiFi","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"forLocalWiFi","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"},{"text":"!","kind":"text"}]},"abstract":[{"type":"text","text":"Checks whether a local WiFi connection is available."}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKReachability"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkreachability\/forlocalwifi()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkreachability\/forlocalwifi()"]}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKReachability":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKReachability"}],"title":"ZDKReachability","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKReachability"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKReachability","abstract":[],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkreachability"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKReachability/forLocalWiFi()":{"type":"topic","url":"\/documentation\/supportproviderssdk\/zdkreachability\/forlocalwifi()","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKReachability\/forLocalWiFi()","navigatorTitle":[{"kind":"identifier","text":"reachabilityForLocalWiFi"}],"role":"symbol","abstract":[{"type":"text","text":"Checks whether a local WiFi connection is available."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"forLocalWiFi","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":"!","kind":"text"}],"title":"forLocalWiFi()"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"reachabilityForLocalWiFi"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"reachabilityForLocalWiFi"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"reachabilityForLocalWiFi","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKReachability\/title","value":"ZDKReachability","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKReachability"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKReachability\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKReachability~1forLocalWiFi()\/title","op":"replace","value":"reachabilityForLocalWiFi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKReachability~1forLocalWiFi()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"reachabilityForLocalWiFi"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}