{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/support\/instance"]},{"paths":["\/documentation\/supportproviderssdk\/support\/instance"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Get the API instance (singleton).","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"instance","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport","text":"Support"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/instance"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support"]]},"metadata":{"role":"symbol","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport(cpy)instance","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Type Property","title":"instance","navigatorTitle":[{"kind":"identifier","text":"instance"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"instance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport","kind":"typeIdentifier","text":"Support"},{"text":"?","kind":"text"}],"symbolKind":"property"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support/instance":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"instance"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport","kind":"typeIdentifier","text":"Support"},{"kind":"text","text":"?"}],"url":"\/documentation\/supportproviderssdk\/support\/instance","abstract":[{"text":"Get the API instance (singleton).","type":"text"}],"title":"instance","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/instance","type":"topic","role":"symbol","navigatorTitle":[{"text":"instance","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support":{"url":"\/documentation\/supportproviderssdk\/support","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support","abstract":[{"type":"text","text":"ZDKSupport is responsible for initialization of"},{"type":"text","text":" "},{"type":"text","text":"the SDK and manages the backend configuration."}],"kind":"symbol","role":"symbol","title":"Support","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Support","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Support","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","value":"instance","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"instance"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support","text":"ZDKSupport"},{"kind":"text","text":" * "},{"text":"instance","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"instance","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1instance\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1instance\/fragments","value":[{"kind":"identifier","text":"instance"}]},{"value":"ZDKSupport","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support\/fragments","value":[{"kind":"identifier","text":"ZDKSupport"}]}]}]}