{"abstract":[{"type":"text","text":"Get a string of an article’s breadcrumb(i.e. it’s relevant section and category)."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle"]]},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)ZDKHelpCenterFlatArticle(im)getArticleBreadcrumb","title":"getBreadcrumb()","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getArticleBreadcrumb"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getBreadcrumb","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle\/getBreadcrumb()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle\/getbreadcrumb()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle\/getbreadcrumb()"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getBreadcrumb","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A string with the article’s name, followed by it’s section name and category name."}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterFlatArticle/getBreadcrumb()":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Get a string of an article’s breadcrumb(i.e. it’s relevant section and category)."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle\/getBreadcrumb()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getBreadcrumb","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle\/getbreadcrumb()","navigatorTitle":[{"kind":"identifier","text":"getArticleBreadcrumb"}],"title":"getBreadcrumb()"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterFlatArticle":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterFlatArticle"}],"role":"symbol","type":"topic","abstract":[{"text":"A Help Center FlatArticle.","type":"text"}],"title":"ZDKHelpCenterFlatArticle","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterFlatArticle"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getArticleBreadcrumb"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getArticleBreadcrumb"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"getArticleBreadcrumb"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle~1getBreadcrumb()\/title","value":"getArticleBreadcrumb","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getArticleBreadcrumb"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle~1getBreadcrumb()\/fragments"},{"value":"ZDKHelpCenterFlatArticle","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle\/fragments","value":[{"text":"ZDKHelpCenterFlatArticle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}