{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearSettingsAndSession"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/dispatcheradapter\/clearsettingsandsession()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/dispatcheradapter\/clearsettingsandsession()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/clearSettingsAndSession()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearSettingsAndSession"},{"kind":"text","text":"()"}],"title":"clearSettingsAndSession()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SupportProvidersSDK@objc(cs)DispatcherAdapter(cm)clearSettingsAndSession","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"clearSettingsAndSession"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/DispatcherAdapter/clearSettingsAndSession()":{"role":"symbol","title":"clearSettingsAndSession()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearSettingsAndSession"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/clearSettingsAndSession()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearSettingsAndSession"}],"url":"\/documentation\/supportproviderssdk\/dispatcheradapter\/clearsettingsandsession()"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/DispatcherAdapter":{"role":"symbol","title":"DispatcherAdapter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DispatcherAdapter"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DispatcherAdapter"}],"url":"\/documentation\/supportproviderssdk\/dispatcheradapter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"clearSettingsAndSession"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clearSettingsAndSession"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearSettingsAndSession"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1clearSettingsAndSession()\/title","value":"clearSettingsAndSession"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1clearSettingsAndSession()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clearSettingsAndSession"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter\/title","value":"DispatcherAdapter"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter\/fragments","value":[{"kind":"identifier","text":"DispatcherAdapter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}