{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","roleHeading":"Type Method","role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseSimpleArticle"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> "},{"text":"ZDKHelpCenterSimpleArticle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterSimpleArticle"},{"text":"!","kind":"text"}],"title":"parseSimpleArticle(_:)","externalID":"c:objc(cs)ZDKHelpCenterSimpleArticle(cm)parseSimpleArticle:","navigatorTitle":[{"text":"parseSimpleArticle:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parseSimpleArticle","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"simpleArticleJSON","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!) -> ","kind":"text"},{"text":"ZDKHelpCenterSimpleArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterSimpleArticle","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle","kind":"typeIdentifier"},{"kind":"text","text":"!"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle\/parseSimpleArticle(_:)"},"abstract":[{"text":"Parse a single simple article object.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle\/parsesimplearticle(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle\/parsesimplearticle(_:)"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSimpleArticle/parseSimpleArticle(_:)":{"role":"symbol","navigatorTitle":[{"text":"parseSimpleArticle:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"parseSimpleArticle","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!) -> ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterSimpleArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterSimpleArticle"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle\/parseSimpleArticle(_:)","title":"parseSimpleArticle(_:)","abstract":[{"text":"Parse a single simple article object.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle\/parsesimplearticle(_:)","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSimpleArticle":{"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle","title":"ZDKHelpCenterSimpleArticle","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterSimpleArticle","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKHelpCenterSimpleArticle","kind":"identifier"}],"abstract":[{"text":"This is a model object for a simple article returned by the suggested article provider","type":"text"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"parseSimpleArticle:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"parseSimpleArticle:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle","text":"ZDKHelpCenterSimpleArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterSimpleArticle","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"parseSimpleArticle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"simpleArticleJSON","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"parseSimpleArticle:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle~1parseSimpleArticle(_:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"parseSimpleArticle:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle~1parseSimpleArticle(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle\/title","op":"replace","value":"ZDKHelpCenterSimpleArticle"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterSimpleArticle"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle\/fragments"}]}]}