{"abstract":[{"type":"text","text":"Convert the date to an NSNumber of the timeIntervalSince1970."}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDateUtil\/date(asNumber:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","role":"symbol","externalID":"c:objc(cs)ZDKDateUtil(cm)dateAsNumber:","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"date"},{"kind":"text","text":"("},{"kind":"externalParam","text":"asNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"dateAsNumber:"}],"title":"date(asNumber:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"date","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"asNumber"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"date"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"date","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the date to be converted"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"the NSNumber of the timeIntervalSince1970","type":"text"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkdateutil\/date(asnumber:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkdateutil\/date(asnumber:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDateUtil"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDateUtil":{"navigatorTitle":[{"text":"ZDKDateUtil","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKDateUtil"}],"type":"topic","abstract":[{"type":"text","text":"A date util."}],"url":"\/documentation\/supportproviderssdk\/zdkdateutil","kind":"symbol","title":"ZDKDateUtil","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDateUtil"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDateUtil/date(asNumber:)":{"url":"\/documentation\/supportproviderssdk\/zdkdateutil\/date(asnumber:)","title":"date(asNumber:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dateAsNumber:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"date","kind":"identifier"},{"text":"(","kind":"text"},{"text":"asNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"!) -> "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDateUtil\/date(asNumber:)","abstract":[{"type":"text","text":"Convert the date to an NSNumber of the timeIntervalSince1970."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","value":"dateAsNumber:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"dateAsNumber:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"dateAsNumber:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"date","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDateUtil\/title","value":"ZDKDateUtil","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDateUtil\/fragments","value":[{"kind":"identifier","text":"ZDKDateUtil"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDateUtil~1date(asNumber:)\/title","value":"dateAsNumber:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDateUtil~1date(asNumber:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"dateAsNumber:"}]}]}]}