{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil"]]},"abstract":[{"text":"Check the value for NSNull.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cleanJSONVal","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"val","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"!) -> ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"!","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"the value to be checked","type":"text"}]}],"name":"val"}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"the value if not NSNull, otherwise nil"}]}]}],"metadata":{"roleHeading":"Type Method","externalID":"c:objc(cs)ZDKJsonUtil(cm)cleanJSONVal:","navigatorTitle":[{"kind":"identifier","text":"cleanJSONVal:"}],"symbolKind":"method","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cleanJSONVal"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"!) -> "},{"text":"Any","kind":"keyword"},{"text":"!","kind":"text"}],"role":"symbol","title":"cleanJSONVal(_:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil\/cleanjsonval(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil\/cleanjsonval(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/cleanJSONVal(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/cleanJSONVal(_:)":{"role":"symbol","navigatorTitle":[{"text":"cleanJSONVal:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanJSONVal"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/cleanJSONVal(_:)","title":"cleanJSONVal(_:)","abstract":[{"text":"Check the value for NSNull.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/cleanjsonval(_:)","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKJsonUtil","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil","title":"ZDKJsonUtil","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkjsonutil","navigatorTitle":[{"kind":"identifier","text":"ZDKJsonUtil"}],"abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"cleanJSONVal:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"cleanJSONVal:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"cleanJSONVal:"},{"kind":"text","text":"("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"val","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1cleanJSONVal(_:)\/title","value":"cleanJSONVal:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1cleanJSONVal(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"cleanJSONVal:"}]},{"value":"ZDKJsonUtil","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/fragments","value":[{"text":"ZDKJsonUtil","kind":"identifier"}],"op":"replace"}]}]}