{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertArray(ofJsonObjects:toArrayOfType:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Converts an array of json into an array of objects. The objects","type":"text"},{"type":"text","text":" "},{"type":"text","text":"in the return array will be instances of the class that was passed in."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertArray"},{"text":"(","kind":"text"},{"text":"ofJsonObjects","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"jsonArray"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"toArrayOfType"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"classToMap"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableArray","text":"NSMutableArray"},{"text":"!","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"jsonArray","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of json objects"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The class to map the json objects to."}],"type":"paragraph"}],"name":"classToMap"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An array of objects.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil\/convertarray(ofjsonobjects:toarrayoftype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkjsonutil\/convertarray(ofjsonobjects:toarrayoftype:)"]}],"metadata":{"roleHeading":"Type Method","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"convertArray"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ofJsonObjects"},{"text":": [","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!, ","kind":"text"},{"kind":"externalParam","text":"toArrayOfType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSMutableArray","text":"NSMutableArray","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"title":"convertArray(ofJsonObjects:toArrayOfType:)","symbolKind":"method","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:objc(cs)ZDKJsonUtil(cm)convertArrayOfJsonObjects:toArrayOfType:","navigatorTitle":[{"text":"convertArrayOfJsonObjects:toArrayOfType:","kind":"identifier"}]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil/convertArray(ofJsonObjects:toArrayOfType:)":{"type":"topic","url":"\/documentation\/supportproviderssdk\/zdkjsonutil\/convertarray(ofjsonobjects:toarrayoftype:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil\/convertArray(ofJsonObjects:toArrayOfType:)","title":"convertArray(ofJsonObjects:toArrayOfType:)","abstract":[{"text":"Converts an array of json into an array of objects. The objects","type":"text"},{"text":" ","type":"text"},{"text":"in the return array will be instances of the class that was passed in.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"convertArray","kind":"identifier"},{"kind":"text","text":"("},{"text":"ofJsonObjects","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!, "},{"text":"toArrayOfType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"convertArrayOfJsonObjects:toArrayOfType:"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKJsonUtil":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKJsonUtil","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKJsonUtil","title":"ZDKJsonUtil","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkjsonutil","navigatorTitle":[{"kind":"identifier","text":"ZDKJsonUtil"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"convertArrayOfJsonObjects:toArrayOfType:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"convertArrayOfJsonObjects:toArrayOfType:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSMutableArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"convertArrayOfJsonObjects:"},{"text":"(","kind":"text"},{"text":"NSArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"jsonArray"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toArrayOfType:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:@T@Class"},{"kind":"text","text":") "},{"text":"classToMap","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertArray(ofJsonObjects:toArrayOfType:)\/title","value":"convertArrayOfJsonObjects:toArrayOfType:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"convertArrayOfJsonObjects:toArrayOfType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil~1convertArray(ofJsonObjects:toArrayOfType:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/title","op":"replace","value":"ZDKJsonUtil"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKJsonUtil\/fragments","value":[{"kind":"identifier","text":"ZDKJsonUtil"}]}]}]}