{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@NSCopying","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"labelNames"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSMutableArray","kind":"typeIdentifier","text":"NSMutableArray"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/labelNames"},"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)ZDKHelpCenterDeflection(py)labelNames","navigatorTitle":[{"text":"labelNames","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelNames"},{"text":": ","kind":"text"},{"text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","title":"labelNames"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection\/labelnames"]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection\/labelnames"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"This models the “label_names” parameter. This will be a comma-separated list of label names to restrict the search to."}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection/labelNames":{"kind":"symbol","abstract":[{"type":"text","text":"This models the “label_names” parameter. This will be a comma-separated list of label names to restrict the search to."}],"title":"labelNames","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection\/labelnames","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/labelNames","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"labelNames","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSMutableArray","text":"NSMutableArray","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"labelNames","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterDeflection"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection","title":"ZDKHelpCenterDeflection","abstract":[{"type":"text","text":"This class models a Help Center Deflection search. It has the same contract as a normal Help Center search."},{"text":" ","type":"text"},{"type":"text","text":"https:\/\/developer.zendesk.com\/rest_api\/docs\/help_center\/search"}],"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterDeflection","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"labelNames"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"labelNames","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSMutableArray","kind":"typeIdentifier","text":"NSMutableArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"labelNames"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"labelNames","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1labelNames\/title"},{"op":"replace","value":[{"text":"labelNames","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1labelNames\/fragments"},{"value":"ZDKHelpCenterDeflection","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterDeflection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}