{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Initialize a system ticket field option with a dictionary","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"text":"dictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"dictionary","content":[{"inlineContent":[{"type":"text","text":"The dictionary"}],"type":"paragraph"}]}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"a ticket field option"}]}],"kind":"content"}],"metadata":{"roleHeading":"Initializer","externalID":"c:objc(cs)ZDKTicketFieldSystemOption(im)initWithDictionary:","navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"symbolKind":"init","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"dictionary"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"role":"symbol","title":"init(dictionary:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldsystemoption\/init(dictionary:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldsystemoption\/init(dictionary:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption\/init(dictionary:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldSystemOption":{"title":"ZDKTicketFieldSystemOption","abstract":[{"type":"text","text":"Ticket Field System Option (for "},{"type":"codeVoice","code":"ZDKTicketFieldTypeStatus"},{"text":", ","type":"text"},{"type":"codeVoice","code":"ZDKTicketFieldTypePriority"},{"text":" and ","type":"text"},{"code":"ZDKTicketFieldTypeTicketType","type":"codeVoice"},{"text":" ticket field types)","type":"text"}],"navigatorTitle":[{"text":"ZDKTicketFieldSystemOption","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKTicketFieldSystemOption","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption","url":"\/documentation\/supportproviderssdk\/zdkticketfieldsystemoption"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldSystemOption/init(dictionary:)":{"abstract":[{"text":"Initialize a system ticket field option with a dictionary","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption\/init(dictionary:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!)"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldsystemoption\/init(dictionary:)","title":"init(dictionary:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWithDictionary:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDictionary:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithDictionary:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dictionary"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption\/title","value":"ZDKTicketFieldSystemOption","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption\/fragments","op":"replace","value":[{"text":"ZDKTicketFieldSystemOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption~1init(dictionary:)\/title","value":"initWithDictionary:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption~1init(dictionary:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:"}],"op":"replace"}]}]}