{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getLastSearch","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterLastSearch","text":"ZDKHelpCenterLastSearch","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getLastSearch"}],"roleHeading":"Type Method","title":"getLastSearch()","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","externalID":"c:objc(cs)ZDKHelpCenterSessionCache(cm)getLastSearch"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache\/getLastSearch()"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getLastSearch","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ZDKHelpCenterLastSearch","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterLastSearch"},{"text":"!","kind":"text"}]}]},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The last search, can be nil.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Get the last search"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/getlastsearch()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/getlastsearch()"]}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSessionCache":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache","type":"topic","kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache","title":"ZDKHelpCenterSessionCache","abstract":[],"navigatorTitle":[{"text":"ZDKHelpCenterSessionCache","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterSessionCache","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterLastSearch":{"title":"ZDKHelpCenterLastSearch","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch","abstract":[{"type":"text","text":"A model for recording the last search in Help Center."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterLastSearch","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSessionCache/getLastSearch()":{"navigatorTitle":[{"kind":"identifier","text":"getLastSearch"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSessionCache\/getLastSearch()","url":"\/documentation\/supportproviderssdk\/zdkhelpcentersessioncache\/getlastsearch()","kind":"symbol","type":"topic","abstract":[{"text":"Get the last search","type":"text"}],"title":"getLastSearch()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLastSearch"},{"kind":"text","text":"() -> "},{"text":"ZDKHelpCenterLastSearch","preciseIdentifier":"c:objc(cs)ZDKHelpCenterLastSearch","kind":"typeIdentifier"},{"kind":"text","text":"!"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"getLastSearch","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"getLastSearch","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"ZDKHelpCenterLastSearch","preciseIdentifier":"c:objc(cs)ZDKHelpCenterLastSearch","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch"},{"text":" *) ","kind":"text"},{"text":"getLastSearch","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache\/title","op":"replace","value":"ZDKHelpCenterSessionCache"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterSessionCache"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch\/title","op":"replace","value":"ZDKHelpCenterLastSearch"},{"op":"replace","value":[{"text":"ZDKHelpCenterLastSearch","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch\/fragments"},{"value":"getLastSearch","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache~1getLastSearch()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSessionCache~1getLastSearch()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"getLastSearch","kind":"identifier"}]}]}]}