{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","symbolKind":"class","roleHeading":"Class","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestForStorage"}],"navigatorTitle":[{"kind":"identifier","text":"RequestForStorage"}],"title":"RequestForStorage"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/Se","doc:\/\/com.zendesk.SupportProvidersSDK\/SE","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKRequestForStorage) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RequestForStorage","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/requestforstorage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/requestforstorage"]}],"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/init(from:)"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/commentCount"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/incrementCommentCounts()"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/createFromRequest(_:readCommentCount:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/Se","title":"Swift.Decodable"},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.SupportProvidersSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SE","title":"Swift.Encodable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage/incrementCommentCounts()":{"kind":"symbol","navigatorTitle":[{"text":"incrementCommentCounts","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/requestforstorage\/incrementcommentcounts()","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/incrementCommentCounts()","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"incrementCommentCounts"},{"kind":"text","text":"()"}],"title":"incrementCommentCounts()"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage/createFromRequest(_:readCommentCount:)":{"title":"createFromRequest(_:readCommentCount:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createFromRequest","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)ZDKRequest","kind":"typeIdentifier","text":"ZDKRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"readCommentCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"createFromRequest:readCommentCount:"}],"role":"symbol","kind":"symbol","url":"\/documentation\/supportproviderssdk\/requestforstorage\/createfromrequest(_:readcommentcount:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/createFromRequest(_:readCommentCount:)"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage":{"title":"RequestForStorage","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestForStorage","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/supportproviderssdk\/requestforstorage","type":"topic","navigatorTitle":[{"text":"RequestForStorage","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage/commentCount":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/commentCount","type":"topic","url":"\/documentation\/supportproviderssdk\/requestforstorage\/commentcount","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"commentCount"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"commentCount"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage/init(from:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"init(from:)","url":"\/documentation\/supportproviderssdk\/requestforstorage\/init(from:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/init(from:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKRequestForStorage"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKRequestForStorage"}]},{"value":[{"kind":"identifier","text":"ZDKRequestForStorage"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/incrementCommentCounts()"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/createFromRequest(_:readCommentCount:)"],"title":"Type Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKRequestForStorage","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"incrementCommentCounts","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage~1incrementCommentCounts()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"incrementCommentCounts","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage~1incrementCommentCounts()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage~1createFromRequest(_:readCommentCount:)\/title","value":"createFromRequest:readCommentCount:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage~1createFromRequest(_:readCommentCount:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createFromRequest:readCommentCount:"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/title","op":"replace","value":"ZDKRequestForStorage"},{"op":"replace","value":[{"text":"ZDKRequestForStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}