{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_ArticleByIdStarting"},"abstract":[{"text":"Notification that help centre article is being fetched.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"ZD_HC_ArticleByIdStarting","kind":"identifier"}],"roleHeading":"Global Variable","symbolKind":"var","role":"symbol","externalID":"c:@ZD_HC_ArticleByIdStarting","modules":[{"name":"SupportProvidersSDK"}],"title":"ZD_HC_ArticleByIdStarting","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZD_HC_ArticleByIdStarting","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zd_hc_articlebyidstarting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zd_hc_articlebyidstarting"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZD_HC_ArticleByIdStarting"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZD_HC_ArticleByIdStarting":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZD_HC_ArticleByIdStarting","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Notification that help centre article is being fetched."}],"title":"ZD_HC_ArticleByIdStarting","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_ArticleByIdStarting","navigatorTitle":[{"text":"ZD_HC_ArticleByIdStarting","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zd_hc_articlebyidstarting"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"value":"ZD_HC_ArticleByIdStarting","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZD_HC_ArticleByIdStarting","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZD_HC_ArticleByIdStarting"}]}]},"path":"\/primaryContentSections\/0"},{"value":"ZD_HC_ArticleByIdStarting","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_ArticleByIdStarting\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_ArticleByIdStarting\/fragments","op":"replace","value":[{"text":"ZD_HC_ArticleByIdStarting","kind":"identifier"}]}]}]}