{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"zdk_on_queue"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"queue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier","text":"dispatch_queue_t"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"block","kind":"internalParam"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")!)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The queue that will execute the block.","type":"text"}]}],"name":"queue"},{"name":"block","content":[{"inlineContent":[{"text":"Block the block to be executed.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdk_on_queue(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdk_on_queue(_:_:)"]}],"metadata":{"role":"symbol","symbolKind":"func","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"zdk_on_queue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t"},{"kind":"text","text":"!, (() -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")!)"}],"externalID":"c:ZDKDispatcher.h@F@zdk_on_queue","navigatorTitle":[{"text":"zdk_on_queue","kind":"identifier"}],"title":"zdk_on_queue(_:_:)","roleHeading":"Function","modules":[{"name":"SupportProvidersSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/zdk_on_queue(_:_:)"},"abstract":[{"type":"text","text":"Convenience method for executing a block on the request queue."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/zdk_on_queue(_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"zdk_on_queue","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier","text":"dispatch_queue_t"},{"kind":"text","text":"!, (() -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Convenience method for executing a block on the request queue."}],"title":"zdk_on_queue(_:_:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/zdk_on_queue(_:_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"zdk_on_queue"}],"url":"\/documentation\/supportproviderssdk\/zdk_on_queue(_:_:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"zdk_on_queue"},{"value":"func","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"zdk_on_queue"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" "},{"text":"zdk_on_queue","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue","text":"NSObject<OS_dispatch_queue>"},{"text":" * ","kind":"text"},{"text":"queue","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@dispatch_block_t","text":"dispatch_block_t","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"block"},{"text":")","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"zdk_on_queue","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1zdk_on_queue(_:_:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1zdk_on_queue(_:_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"zdk_on_queue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}