{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_commentlistsuccess"]},{"paths":["\/documentation\/supportproviderssdk\/zdkapi_commentlistsuccess"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"ZDKAPI_CommentListSuccess","symbolKind":"var","roleHeading":"Global Variable","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAPI_CommentListSuccess","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"ZDKAPI_CommentListSuccess","kind":"identifier"}],"externalID":"c:@ZDKAPI_CommentListSuccess","role":"symbol"},"abstract":[{"text":"Notification that the list has been retrieved.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAPI_CommentListSuccess","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_CommentListSuccess","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPI_CommentListSuccess":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_CommentListSuccess"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","type":"topic","abstract":[{"text":"Notification that the list has been retrieved.","type":"text"}],"title":"ZDKAPI_CommentListSuccess","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_CommentListSuccess","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_CommentListSuccess"}],"url":"\/documentation\/supportproviderssdk\/zdkapi_commentlistsuccess"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"ZDKAPI_CommentListSuccess"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"value":[{"text":"ZDKAPI_CommentListSuccess","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAPI_CommentListSuccess","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_CommentListSuccess\/title","value":"ZDKAPI_CommentListSuccess","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_CommentListSuccess\/fragments","value":[{"text":"ZDKAPI_CommentListSuccess","kind":"identifier"}],"op":"replace"}]}]}