{"sections":[],"abstract":[{"text":"Notification that a request to add a user field has succeeded","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_setuserfieldssuccess"]},{"paths":["\/documentation\/supportproviderssdk\/zdkapi_setuserfieldssuccess"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAPI_SetUserFieldsSuccess","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"var","roleHeading":"Global Variable","title":"ZDKAPI_SetUserFieldsSuccess","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAPI_SetUserFieldsSuccess"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@ZDKAPI_SetUserFieldsSuccess","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_SetUserFieldsSuccess"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_SetUserFieldsSuccess","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPI_SetUserFieldsSuccess":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDKAPI_SetUserFieldsSuccess","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Notification that a request to add a user field has succeeded"}],"title":"ZDKAPI_SetUserFieldsSuccess","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_SetUserFieldsSuccess","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_SetUserFieldsSuccess"}],"url":"\/documentation\/supportproviderssdk\/zdkapi_setuserfieldssuccess"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKAPI_SetUserFieldsSuccess"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKAPI_SetUserFieldsSuccess"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"text":"ZDKAPI_SetUserFieldsSuccess","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKAPI_SetUserFieldsSuccess","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_SetUserFieldsSuccess\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_SetUserFieldsSuccess\/fragments","value":[{"text":"ZDKAPI_SetUserFieldsSuccess","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}