{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_CommentSubmissionSuccess"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_commentsubmissionsuccess"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_commentsubmissionsuccess"]}],"abstract":[{"text":"Notification that a comment has been successfully submitted.","type":"text"}],"kind":"symbol","metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"var","title":"ZDKAPI_CommentSubmissionSuccess","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_CommentSubmissionSuccess"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"externalID":"c:@ZDKAPI_CommentSubmissionSuccess","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_CommentSubmissionSuccess"}],"roleHeading":"Global Variable"},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_CommentSubmissionSuccess","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPI_CommentSubmissionSuccess":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_CommentSubmissionSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Notification that a comment has been successfully submitted."}],"title":"ZDKAPI_CommentSubmissionSuccess","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_CommentSubmissionSuccess","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_CommentSubmissionSuccess"}],"url":"\/documentation\/supportproviderssdk\/zdkapi_commentsubmissionsuccess"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKAPI_CommentSubmissionSuccess"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"value":[{"text":"ZDKAPI_CommentSubmissionSuccess","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_CommentSubmissionSuccess"}]}],"kind":"declarations"}},{"value":"ZDKAPI_CommentSubmissionSuccess","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_CommentSubmissionSuccess\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_CommentSubmissionSuccess\/fragments","op":"replace","value":[{"text":"ZDKAPI_CommentSubmissionSuccess","kind":"identifier"}]}]}]}