{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_RequestByIdSuccess"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_requestbyidsuccess"]},{"paths":["\/documentation\/supportproviderssdk\/zdkapi_requestbyidsuccess"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Global Variable","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:@ZDKAPI_RequestByIdSuccess","title":"ZDKAPI_RequestByIdSuccess","symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_RequestByIdSuccess"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAPI_RequestByIdSuccess","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_RequestByIdSuccess"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Notification that a request was successfully retrieved."}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPI_RequestByIdSuccess":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_RequestByIdSuccess"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","type":"topic","abstract":[{"text":"Notification that a request was successfully retrieved.","type":"text"}],"title":"ZDKAPI_RequestByIdSuccess","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_RequestByIdSuccess","kind":"symbol","navigatorTitle":[{"text":"ZDKAPI_RequestByIdSuccess","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkapi_requestbyidsuccess"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","value":"ZDKAPI_RequestByIdSuccess","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKAPI_RequestByIdSuccess","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAPI_RequestByIdSuccess","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_RequestByIdSuccess\/title","value":"ZDKAPI_RequestByIdSuccess"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_RequestByIdSuccess\/fragments","value":[{"text":"ZDKAPI_RequestByIdSuccess","kind":"identifier"}]}]}]}