{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkcreaterequestcallback"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkcreaterequestcallback"]}],"metadata":{"roleHeading":"Type Alias","title":"ZDKCreateRequestCallback","symbolKind":"typealias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ZDKCreateRequestCallback","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKCreateRequestCallback"}],"externalID":"c:ZDKRequestProvider.h@T@ZDKCreateRequestCallback","role":"symbol"},"abstract":[{"text":"Block defined for a callback to be used for handling async server response for creating a request","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequestCallback","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKCreateRequestCallback"},{"text":" = (","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"id object as a result of the API request sent to a Zendesk instance, can be nil on error"}]}],"name":"result"},{"name":"error","content":[{"inlineContent":[{"text":"NSError returned as a result of any errors taking place when the request is executed, can be nil on success","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequestCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ZDKCreateRequestCallback","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Block defined for a callback to be used for handling async server response for creating a request"}],"title":"ZDKCreateRequestCallback","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequestCallback","navigatorTitle":[{"kind":"identifier","text":"ZDKCreateRequestCallback"}],"url":"\/documentation\/supportproviderssdk\/zdkcreaterequestcallback"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"ZDKCreateRequestCallback","op":"replace"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKCreateRequestCallback"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ZDKCreateRequestCallback"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:BFv(#*Qo#*$objc(cs)NSError)","text":"void (^)(id, NSError *)","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"ZDKCreateRequestCallback","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKCreateRequestCallback","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequestCallback\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequestCallback\/fragments","op":"replace","value":[{"text":"ZDKCreateRequestCallback","kind":"identifier"}]}]}]}