{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKCreateRequest","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"]}],"metadata":{"title":"ZDKCreateRequest","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKCreateRequest","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ZDKCreateRequest","navigatorTitle":[{"text":"ZDKCreateRequest","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/init(dict:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/attachments","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/customFields","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/requestDescription","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/subject","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/tags","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/ticketFormId"],"title":"Instance Properties"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkcreaterequest"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkcreaterequest"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest"},"abstract":[{"type":"text","text":"A request sent by the user."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest/attachments":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"attachments","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"title":"attachments","role":"symbol","navigatorTitle":[{"text":"attachments","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/attachments","abstract":[{"type":"text","text":"List of ZDKUploadResponse objects."}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest\/attachments"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest":{"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKCreateRequest","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest","navigatorTitle":[{"text":"ZDKCreateRequest","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"A request sent by the user.","type":"text"}],"title":"ZDKCreateRequest"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest/ticketFormId":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ticketFormId"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"title":"ticketFormId","role":"symbol","navigatorTitle":[{"text":"ticketFormId","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/ticketFormId","abstract":[{"type":"text","text":"Form id for ticket creation."}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest\/ticketformid"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest/requestDescription":{"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest\/requestdescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/requestDescription","navigatorTitle":[{"text":"requestDescription","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The body of the request","type":"text"}],"title":"requestDescription"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest/customFields":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customFields","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CustomField","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKCustomField"},{"kind":"text","text":"]!"}],"title":"customFields","role":"symbol","navigatorTitle":[{"text":"customFields","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/customFields","abstract":[{"type":"text","text":"An array for custom fields."}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest\/customfields"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest/init(dict:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"dict"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!)"}],"title":"init(dict:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDict:"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/init(dict:)","abstract":[{"type":"text","text":"Init with dictionary"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest\/init(dict:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest/subject":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"subject","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"title":"subject","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"subject"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/subject","abstract":[{"type":"text","text":"The subject of the request, if subject is enabled in the account."}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest\/subject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCreateRequest/tags":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tags","kind":"identifier"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"title":"tags","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tags"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/tags","abstract":[{"type":"text","text":"List of tags associated with the request"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcreaterequest\/tags"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"ZDKCreateRequest","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKCreateRequest","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKCreateRequest"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/attachments","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/customFields","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/requestDescription","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/subject","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/tags","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/ticketFormId"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCreateRequest\/init(dict:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKCreateRequest","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1attachments\/title","op":"replace","value":"attachments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1attachments\/fragments","value":[{"text":"attachments","kind":"identifier"}]},{"value":"ZDKCreateRequest","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest\/fragments","value":[{"kind":"identifier","text":"ZDKCreateRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1ticketFormId\/title","value":"ticketFormId"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1ticketFormId\/fragments","value":[{"text":"ticketFormId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1requestDescription\/title","value":"requestDescription","op":"replace"},{"value":[{"kind":"identifier","text":"requestDescription"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1requestDescription\/fragments"},{"value":"customFields","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1customFields\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1customFields\/fragments","value":[{"kind":"identifier","text":"customFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1init(dict:)\/title","value":"initWithDict:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDict:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1init(dict:)\/fragments"},{"value":"subject","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1subject\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1subject\/fragments","value":[{"text":"subject","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1tags\/title","value":"tags"},{"value":[{"kind":"identifier","text":"tags"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCreateRequest~1tags\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}