{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKNetworkStatus"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdknetworkstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdknetworkstatus"]}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH","doc:\/\/com.zendesk.SupportProvidersSDK\/SY","doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP"],"title":"Conforms To"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"ZDKNetworkStatus","kind":"identifier"}],"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKNetworkStatus"}],"title":"ZDKNetworkStatus","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:@E@ZDKNetworkStatus","role":"symbol","symbolKind":"enum"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/notReachable","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/reachableViaWWAN","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/reachableViaWiFi"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/Equatable-Implementations","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus/init(rawValue:)":{"kind":"symbol","type":"topic","abstract":[],"title":"init(rawValue:)","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdknetworkstatus\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/init(rawValue:)"},"doc://com.zendesk.SupportProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus/Equatable-Implementations":{"role":"collectionGroup","url":"\/documentation\/supportproviderssdk\/zdknetworkstatus\/equatable-implementations","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/Equatable-Implementations","kind":"article","type":"topic","abstract":[],"title":"Equatable Implementations"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus/RawRepresentable-Implementations":{"kind":"article","abstract":[],"url":"\/documentation\/supportproviderssdk\/zdknetworkstatus\/rawrepresentable-implementations","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus/reachableViaWWAN":{"kind":"symbol","navigatorTitle":[{"text":"ZDKNetworkStatusReachableViaWWAN","kind":"identifier"}],"abstract":[],"title":"ZDKNetworkStatus.reachableViaWWAN","url":"\/documentation\/supportproviderssdk\/zdknetworkstatus\/reachableviawwan","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reachableViaWWAN","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/reachableViaWWAN","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/SY":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus/reachableViaWiFi":{"navigatorTitle":[{"kind":"identifier","text":"ZDKNetworkStatusReachableViaWiFi"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"reachableViaWiFi","kind":"identifier"}],"title":"ZDKNetworkStatus.reachableViaWiFi","url":"\/documentation\/supportproviderssdk\/zdknetworkstatus\/reachableviawifi","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/reachableViaWiFi","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus":{"kind":"symbol","navigatorTitle":[{"text":"ZDKNetworkStatus","kind":"identifier"}],"abstract":[],"title":"ZDKNetworkStatus","url":"\/documentation\/supportproviderssdk\/zdknetworkstatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKNetworkStatus","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus/notReachable":{"navigatorTitle":[{"kind":"identifier","text":"ZDKNetworkStatusNotReachable"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notReachable"}],"url":"\/documentation\/supportproviderssdk\/zdknetworkstatus\/notreachable","title":"ZDKNetworkStatus.notReachable","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/notReachable","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s8SendableP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"ZDKNetworkStatus","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKNetworkStatus","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKNetworkStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/notReachable","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/reachableViaWWAN","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/reachableViaWiFi"],"title":"Enumeration Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKNetworkStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1reachableViaWWAN\/title","op":"replace","value":"ZDKNetworkStatusReachableViaWWAN"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKNetworkStatusReachableViaWWAN"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1reachableViaWWAN\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1reachableViaWiFi\/title","value":"ZDKNetworkStatusReachableViaWiFi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1reachableViaWiFi\/fragments","value":[{"kind":"identifier","text":"ZDKNetworkStatusReachableViaWiFi"}]},{"value":"ZDKNetworkStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus\/fragments","value":[{"text":"ZDKNetworkStatus","kind":"identifier"}]},{"value":"ZDKNetworkStatusNotReachable","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1notReachable\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1notReachable\/fragments","value":[{"kind":"identifier","text":"ZDKNetworkStatusNotReachable"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}