{"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestListCallback","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestlistcallback"]},{"paths":["\/documentation\/supportproviderssdk\/zdkrequestlistcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"ZDKRequestListCallback","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestListCallback"}],"role":"symbol","roleHeading":"Type Alias","externalID":"c:ZDKRequestProvider.h@T@ZDKRequestListCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestListCallback"}],"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"typealias"},"abstract":[{"text":"Block defined for callback to be used for handling async server responses for fetching a list of requests and agents that have publically","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"commented on them"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ZDKRequestListCallback","kind":"identifier"},{"text":" = (","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKRequestsWithCommentingAgents","text":"ZDKRequestsWithCommentingAgents"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}]}]},{"parameters":[{"name":"requestsWithCommentingAgents","content":[{"type":"paragraph","inlineContent":[{"text":"an object containing an array of requests and users, can be nil on error.","type":"text"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"NSError returned as a result of any errors taking place when the request is executed, can be nil on success","type":"text"}]}]}],"kind":"parameters"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestsWithCommentingAgents":{"title":"ZDKRequestsWithCommentingAgents","url":"\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestListCallback":{"title":"ZDKRequestListCallback","url":"\/documentation\/supportproviderssdk\/zdkrequestlistcallback","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestListCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestListCallback"}],"kind":"symbol","abstract":[{"text":"Block defined for callback to be used for handling async server responses for fetching a list of requests and agents that have publically","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"commented on them"}],"navigatorTitle":[{"text":"ZDKRequestListCallback","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKRequestListCallback"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKRequestListCallback"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKRequestListCallback","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)ZDKRequestsWithCommentingAgents#*$objc(cs)NSError)","kind":"typeIdentifier","text":"void (^)(ZDKRequestsWithCommentingAgents *, NSError *)"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestListCallback"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents\/title","value":"ZDKRequestsWithCommentingAgents"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents\/fragments","op":"replace","value":[{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestListCallback\/title","value":"ZDKRequestListCallback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestListCallback\/fragments","value":[{"text":"ZDKRequestListCallback","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}