{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ZDKRequestCommentListCallback","kind":"identifier"},{"kind":"text","text":" = (["},{"text":"ZDKCommentWithUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKCommentWithUser","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser"},{"kind":"text","text":"]?, "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"array of ZDKCommentWithUser objects as a result of the API request sent to a Zendesk instance, can be nil on error"}],"type":"paragraph"}],"name":"commentsWithUsers"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSError returned as a result of any errors taking place when the request is executed, can be nil on success"}]}],"name":"error"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestcommentlistcallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestcommentlistcallback"]}],"metadata":{"externalID":"c:ZDKRequestProvider.h@T@ZDKRequestCommentListCallback","roleHeading":"Type Alias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKRequestCommentListCallback"}],"symbolKind":"typealias","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestCommentListCallback"}],"title":"ZDKRequestCommentListCallback","modules":[{"name":"SupportProvidersSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestCommentListCallback"},"abstract":[{"type":"text","text":"Block defined for callback to be used for handling async server responses for fetching a list of comments"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentWithUser":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKCommentWithUser","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Aggregate model for comments with users."}],"title":"ZDKCommentWithUser","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKCommentWithUser"}],"url":"\/documentation\/supportproviderssdk\/zdkcommentwithuser"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestCommentListCallback":{"role":"symbol","title":"ZDKRequestCommentListCallback","url":"\/documentation\/supportproviderssdk\/zdkrequestcommentlistcallback","abstract":[{"type":"text","text":"Block defined for callback to be used for handling async server responses for fetching a list of comments"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestCommentListCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKRequestCommentListCallback","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKRequestCommentListCallback","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"ZDKRequestCommentListCallback"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKRequestCommentListCallback"}]},{"value":[{"text":"ZDKRequestCommentListCallback","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)","text":"void (^)(NSArray<ZDKCommentWithUser *> *, NSError *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"ZDKRequestCommentListCallback","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser\/title","value":"ZDKCommentWithUser"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser\/fragments","op":"replace","value":[{"text":"ZDKCommentWithUser","kind":"identifier"}]},{"value":"ZDKRequestCommentListCallback","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestCommentListCallback\/title"},{"value":[{"text":"ZDKRequestCommentListCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestCommentListCallback\/fragments","op":"replace"}]}]}