{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKTicketField","kind":"identifier"}],"roleHeading":"Class","externalID":"c:objc(cs)ZDKTicketField","title":"ZDKTicketField","navigatorTitle":[{"text":"ZDKTicketField","kind":"identifier"}],"symbolKind":"class"},"abstract":[{"text":"Ticket field class","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDictionaryCreatable"]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/init(dictionary:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/fieldDescription","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/fieldId","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/options","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/required","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/systemOptions","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/title","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/titleInPortal","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/type","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/validationRegex"],"title":"Instance Properties"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKTicketField","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkticketfield"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfield"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/options":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/options","navigatorTitle":[{"text":"options","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfield\/options","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKTicketFieldOption","kind":"typeIdentifier","text":"ZDKTicketFieldOption"},{"kind":"text","text":"]!"}],"kind":"symbol","title":"options","type":"topic","abstract":[{"type":"text","text":"Ticket field options, this field will only be populated for "},{"code":"ZDKTicketFieldTypeComboBox","type":"codeVoice"},{"text":" field types","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/fieldDescription":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/fieldDescription","navigatorTitle":[{"text":"fieldDescription","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfield\/fielddescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldDescription"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"kind":"symbol","title":"fieldDescription","type":"topic","abstract":[{"text":"Ticket field english description","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDictionaryCreatable":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKDictionaryCreatable","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"title":"ZDKDictionaryCreatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDictionaryCreatable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKDictionaryCreatable"}],"url":"\/documentation\/supportproviderssdk\/zdkdictionarycreatable"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/validationRegex":{"title":"validationRegex","url":"\/documentation\/supportproviderssdk\/zdkticketfield\/validationregex","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"validationRegex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/validationRegex","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Ticket field validation regular expression"}],"navigatorTitle":[{"kind":"identifier","text":"validationRegex"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/init(dictionary:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"dictionary"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/init(dictionary:)","title":"init(dictionary:)","kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfield\/init(dictionary:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Initialize a ticket field with a dictionary"}],"navigatorTitle":[{"text":"initWithDictionary:","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/type":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"text":"ZDKTicketFieldType","kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKTicketFieldType"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Ticket field type"}],"title":"type","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/type","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfield\/type"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/systemOptions":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"systemOptions"}],"title":"systemOptions","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemOptions"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKTicketFieldSystemOption","kind":"typeIdentifier","text":"ZDKTicketFieldSystemOption"},{"text":"]!","kind":"text"}],"type":"topic","abstract":[{"text":"Ticket field system options, this field will only be populated for ","type":"text"},{"code":"ZDKTicketFieldTypeStatus","type":"codeVoice"},{"type":"text","text":", "},{"code":"ZDKTicketFieldTypePriority","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"ZDKTicketFieldTypeTicketType"},{"type":"text","text":" field types"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfield\/systemoptions","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/systemOptions","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/fieldId":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/fieldId","navigatorTitle":[{"text":"fieldId","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfield\/fieldid","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fieldId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"!","kind":"text"}],"kind":"symbol","title":"fieldId","type":"topic","abstract":[{"type":"text","text":"The ticket field ID"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/titleInPortal":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleInPortal"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"title":"titleInPortal","role":"symbol","navigatorTitle":[{"text":"titleInPortal","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/titleInPortal","abstract":[{"type":"text","text":"Ticket field title in portal"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfield\/titleinportal"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/required":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/required","navigatorTitle":[{"text":"required","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfield\/required","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"required","type":"topic","abstract":[{"type":"text","text":"Ticket field requiry status"}]},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/title":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"role":"symbol","navigatorTitle":[{"text":"title","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfield\/title","abstract":[{"text":"Ticket field title","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/title","type":"topic","kind":"symbol","title":"title"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKTicketField","kind":"identifier"}],"title":"ZDKTicketField","role":"symbol","navigatorTitle":[{"text":"ZDKTicketField","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField","abstract":[{"type":"text","text":"Ticket field class"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfield"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKTicketField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"ZDKTicketField","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ZDKTicketField","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/fieldDescription","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/fieldId","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/options","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/required","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/systemOptions","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/title","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/titleInPortal","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/type","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/validationRegex"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/init(dictionary:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDictionaryCreatable"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKTicketField","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"options","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1options\/title"},{"op":"replace","value":[{"kind":"identifier","text":"options"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1options\/fragments"},{"op":"replace","value":"fieldDescription","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1fieldDescription\/title"},{"op":"replace","value":[{"text":"fieldDescription","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1fieldDescription\/fragments"},{"op":"replace","value":"ZDKDictionaryCreatable","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDictionaryCreatable\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDictionaryCreatable\/fragments","value":[{"kind":"identifier","text":"ZDKDictionaryCreatable"}],"op":"replace"},{"value":"validationRegex","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1validationRegex\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1validationRegex\/fragments","value":[{"text":"validationRegex","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1init(dictionary:)\/title","value":"initWithDictionary:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1init(dictionary:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:"}]},{"op":"replace","value":"type","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1type\/title"},{"op":"replace","value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1type\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1systemOptions\/title","value":"systemOptions","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"systemOptions"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1systemOptions\/fragments"},{"value":"fieldId","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1fieldId\/title"},{"value":[{"kind":"identifier","text":"fieldId"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1fieldId\/fragments"},{"value":"titleInPortal","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1titleInPortal\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1titleInPortal\/fragments","value":[{"text":"titleInPortal","kind":"identifier"}]},{"value":"required","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1required\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1required\/fragments","value":[{"kind":"identifier","text":"required"}]},{"value":"title","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1title\/title"},{"value":[{"kind":"identifier","text":"title"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1title\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField\/title","value":"ZDKTicketField"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField\/fragments","value":[{"text":"ZDKTicketField","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}