{"metadata":{"roleHeading":"Class","externalID":"c:objc(cs)ZDKTicketFieldOption","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKTicketFieldOption","kind":"identifier"}],"title":"ZDKTicketFieldOption","symbolKind":"class","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldOption"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldoption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldoption"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKTicketFieldOption"}]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/init(dictionary:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/fieldOptionId","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/isDefaultValue","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/name","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/value"]}],"abstract":[{"type":"text","text":"Ticket Field Option (for ZDKTicketFieldTypeTagger ticket field types)"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldOption/fieldOptionId":{"kind":"symbol","abstract":[{"text":"Ticket Field Option ID","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fieldOptionId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldoption\/fieldoptionid","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/fieldOptionId","type":"topic","title":"fieldOptionId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fieldOptionId"}]},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldOption/init(dictionary:)":{"title":"init(dictionary:)","url":"\/documentation\/supportproviderssdk\/zdkticketfieldoption\/init(dictionary:)","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/init(dictionary:)","fragments":[{"text":"init","kind":"identifier"},{"text":"!(","kind":"text"},{"kind":"externalParam","text":"dictionary"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"abstract":[{"type":"text","text":"Initialize a ticket field with a dictionary"}],"role":"symbol","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldOption":{"title":"ZDKTicketFieldOption","url":"\/documentation\/supportproviderssdk\/zdkticketfieldoption","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldOption","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKTicketFieldOption","kind":"identifier"}],"abstract":[{"type":"text","text":"Ticket Field Option (for ZDKTicketFieldTypeTagger ticket field types)"}],"role":"symbol","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldOption/value":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"title":"value","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/value","abstract":[{"type":"text","text":"Option Value, passed to zendesk server"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldoption\/value","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldOption/name":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"title":"name","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/name","url":"\/documentation\/supportproviderssdk\/zdkticketfieldoption\/name","abstract":[{"type":"text","text":"Option Name"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldOption/isDefaultValue":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isDefaultValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isDefaultValue","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/isDefaultValue","abstract":[{"text":"If isDefaultValue is true, then this option is the default selected one","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldoption\/isdefaultvalue","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isDefaultValue"}]},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"ZDKTicketFieldOption","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldOption"}]},{"value":[{"kind":"identifier","text":"ZDKTicketFieldOption"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/fieldOptionId","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/isDefaultValue","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/name","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/value"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/init(dictionary:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKTicketFieldOption"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1fieldOptionId\/title","value":"fieldOptionId"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1fieldOptionId\/fragments","op":"replace","value":[{"text":"fieldOptionId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1init(dictionary:)\/title","value":"initWithDictionary:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDictionary:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1init(dictionary:)\/fragments"},{"op":"replace","value":"ZDKTicketFieldOption","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption\/fragments","op":"replace","value":[{"text":"ZDKTicketFieldOption","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1value\/title","value":"value"},{"op":"replace","value":[{"text":"value","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1value\/fragments"},{"value":"name","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1name\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1name\/fragments","value":[{"text":"name","kind":"identifier"}]},{"op":"replace","value":"isDefaultValue","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1isDefaultValue\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1isDefaultValue\/fragments","value":[{"text":"isDefaultValue","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}