{"abstract":[{"text":"Block defined for callback to be used for handling async server responses for uploading an attachment.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ZDKUploadCallback","kind":"identifier"},{"text":" = (","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKUploadResponse","kind":"typeIdentifier","text":"ZDKUploadResponse","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadResponse"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"a response containing a ZDKAttachment and upload token."}],"type":"paragraph"}],"name":"uploadResponse"},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSError returned as a result of any errors taking place when the request is executed, can be nil on success."}]}]}],"kind":"parameters"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkuploadcallback"]},{"paths":["\/documentation\/supportproviderssdk\/zdkuploadcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKUploadCallback","kind":"identifier"}],"roleHeading":"Type Alias","role":"symbol","title":"ZDKUploadCallback","navigatorTitle":[{"text":"ZDKUploadCallback","kind":"identifier"}],"externalID":"c:ZDKUploadProvider.h@T@ZDKUploadCallback"},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadCallback","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKUploadCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKUploadCallback"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Block defined for callback to be used for handling async server responses for uploading an attachment."}],"title":"ZDKUploadCallback","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadCallback","navigatorTitle":[{"text":"ZDKUploadCallback","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkuploadcallback"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKUploadResponse":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUploadResponse"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Model for an upload response."}],"title":"ZDKUploadResponse","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadResponse","kind":"symbol","navigatorTitle":[{"text":"ZDKUploadResponse","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkuploadresponse"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKUploadCallback","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKUploadCallback"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKUploadCallback"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:BFv(#*$objc(cs)ZDKUploadResponse#*$objc(cs)NSError)","kind":"typeIdentifier","text":"void (^)(ZDKUploadResponse *, NSError *)"},{"kind":"text","text":" "},{"text":"ZDKUploadCallback","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadCallback\/title","op":"replace","value":"ZDKUploadCallback"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKUploadCallback"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadResponse\/title","value":"ZDKUploadResponse"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadResponse\/fragments","value":[{"kind":"identifier","text":"ZDKUploadResponse"}],"op":"replace"}]}]}