{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navBarConversationsUIType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType","preciseIdentifier":"c:@E@ZDKNavBarConversationsUIType","text":"ZDKNavBarConversationsUIType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/navbarconversationsuitype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/navbarconversationsuitype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/navBarConversationsUIType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Use text or an icon in the right nav bar button."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"navBarConversationsUIType"}],"role":"symbol","title":"navBarConversationsUIType","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navBarConversationsUIType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKNavBarConversationsUIType","preciseIdentifier":"c:@E@ZDKNavBarConversationsUIType"}],"symbolKind":"property","externalID":"c:objc(cs)ZDKHelpCenterOverviewContentModel(py)navBarConversationsUIType","modules":[{"name":"SupportProvidersSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Deprecated as of 1.10.0.1, use ZDKHelpCenterConversationsUIDelegate instead."}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel":{"role":"symbol","title":"ZDKHelpCenterOverviewContentModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterOverviewContentModel"}],"abstract":[{"type":"text","text":"Model which allows customizations on the content displayed by Help Center."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterOverviewContentModel"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel/navBarConversationsUIType":{"deprecated":true,"role":"symbol","title":"navBarConversationsUIType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navBarConversationsUIType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKNavBarConversationsUIType","preciseIdentifier":"c:@E@ZDKNavBarConversationsUIType"}],"abstract":[{"type":"text","text":"Use text or an icon in the right nav bar button."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/navBarConversationsUIType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"navBarConversationsUIType"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/navbarconversationsuitype"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType":{"role":"symbol","title":"ZDKNavBarConversationsUIType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKNavBarConversationsUIType"}],"abstract":[{"type":"text","text":"Enum to describe the types of nav bar button that display conversations."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarConversationsUIType"}],"url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"navBarConversationsUIType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"navBarConversationsUIType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType","preciseIdentifier":"c:@E@ZDKNavBarConversationsUIType","text":"ZDKNavBarConversationsUIType"},{"kind":"text","text":" "},{"kind":"identifier","text":"navBarConversationsUIType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/title","value":"ZDKHelpCenterOverviewContentModel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterOverviewContentModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1navBarConversationsUIType\/title","value":"navBarConversationsUIType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1navBarConversationsUIType\/fragments","value":[{"kind":"identifier","text":"navBarConversationsUIType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType\/title","value":"ZDKNavBarConversationsUIType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType\/fragments","value":[{"kind":"identifier","text":"ZDKNavBarConversationsUIType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}