{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentercategory\/parsecategories(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentercategory\/parsecategories(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory\/parseCategories(_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ZDKHelpCenterCategory(cm)parseCategories:","title":"parseCategories(_:)","roleHeading":"Type Method","navigatorTitle":[{"text":"parseCategories:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parseCategories","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"modules":[{"name":"SupportProvidersSDK"}]},"abstract":[{"text":"Parses a collection of Help Center json category objects","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parseCategories"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!) -> [","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of ZDKHelpCenterCategory objects."}]}],"kind":"content"}],"sections":[],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCategory/parseCategories(_:)":{"navigatorTitle":[{"text":"parseCategories:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory\/parseCategories(_:)","title":"parseCategories(_:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parseCategories"},{"text":"([","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!) -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercategory\/parsecategories(_:)","kind":"symbol","abstract":[{"type":"text","text":"Parses a collection of Help Center json category objects"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCategory":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterCategory","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentercategory","title":"ZDKHelpCenterCategory","navigatorTitle":[{"text":"ZDKHelpCenterCategory","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"parseCategories:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"parseCategories:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray"},{"text":" *) ","kind":"text"},{"text":"parseCategories:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"json"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategory~1parseCategories(_:)\/title","value":"parseCategories:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategory~1parseCategories(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"parseCategories:","kind":"identifier"}],"op":"replace"},{"value":"ZDKHelpCenterCategory","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategory\/title"},{"value":[{"text":"ZDKHelpCenterCategory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategory\/fragments"}]}]}