{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detailTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/supportproviderssdk\/helpcentersectionviewmodel\/detailtitle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/helpcentersectionviewmodel\/detailtitle"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel\/detailTitle","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","title":"detailTitle","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"detailTitle"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSectionViewModel(py)detailTitle","role":"symbol"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSectionViewModel":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterSectionViewModel","kind":"identifier"}],"type":"topic","url":"\/documentation\/supportproviderssdk\/helpcentersectionviewmodel","title":"HelpCenterSectionViewModel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HelpCenterSectionViewModel"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSectionViewModel/detailTitle":{"title":"detailTitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"detailTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/supportproviderssdk\/helpcentersectionviewmodel\/detailtitle","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detailTitle"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSectionViewModel\/detailTitle","kind":"symbol","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"detailTitle","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"detailTitle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"detailTitle","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel\/title","value":"ZDKHelpCenterSectionViewModel"},{"value":[{"text":"ZDKHelpCenterSectionViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel~1detailTitle\/title","value":"detailTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSectionViewModel~1detailTitle\/fragments","value":[{"text":"detailTitle","kind":"identifier"}],"op":"replace"}]}]}