{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdknetworkstatus\/notreachable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdknetworkstatus\/notreachable"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/notReachable","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notReachable"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:@E@ZDKNetworkStatus@ZDKNetworkStatusNotReachable","roleHeading":"Case","title":"ZDKNetworkStatus.notReachable","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"ZDKNetworkStatusNotReachable"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notReachable","kind":"identifier"}]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus":{"kind":"symbol","navigatorTitle":[{"text":"ZDKNetworkStatus","kind":"identifier"}],"abstract":[],"title":"ZDKNetworkStatus","url":"\/documentation\/supportproviderssdk\/zdknetworkstatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKNetworkStatus","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus/notReachable":{"navigatorTitle":[{"kind":"identifier","text":"ZDKNetworkStatusNotReachable"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notReachable"}],"url":"\/documentation\/supportproviderssdk\/zdknetworkstatus\/notreachable","title":"ZDKNetworkStatus.notReachable","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/notReachable","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKNetworkStatusNotReachable"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKNetworkStatusNotReachable","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKNetworkStatusNotReachable","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKNetworkStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus\/fragments","value":[{"text":"ZDKNetworkStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1notReachable\/title","op":"replace","value":"ZDKNetworkStatusNotReachable"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1notReachable\/fragments","value":[{"text":"ZDKNetworkStatusNotReachable","kind":"identifier"}],"op":"replace"}]}]}