{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/reachableViaWiFi","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"reachableViaWiFi","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@E@ZDKNetworkStatus@ZDKNetworkStatusReachableViaWiFi","modules":[{"name":"SupportProvidersSDK"}],"title":"ZDKNetworkStatus.reachableViaWiFi","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"ZDKNetworkStatusReachableViaWiFi"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reachableViaWiFi"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdknetworkstatus\/reachableviawifi"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdknetworkstatus\/reachableviawifi"]}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus/reachableViaWiFi":{"navigatorTitle":[{"kind":"identifier","text":"ZDKNetworkStatusReachableViaWiFi"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"reachableViaWiFi","kind":"identifier"}],"title":"ZDKNetworkStatus.reachableViaWiFi","url":"\/documentation\/supportproviderssdk\/zdknetworkstatus\/reachableviawifi","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus\/reachableViaWiFi","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNetworkStatus":{"kind":"symbol","navigatorTitle":[{"text":"ZDKNetworkStatus","kind":"identifier"}],"abstract":[],"title":"ZDKNetworkStatus","url":"\/documentation\/supportproviderssdk\/zdknetworkstatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKNetworkStatus","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNetworkStatus","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"ZDKNetworkStatusReachableViaWiFi","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"ZDKNetworkStatusReachableViaWiFi","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKNetworkStatusReachableViaWiFi"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1reachableViaWiFi\/title","value":"ZDKNetworkStatusReachableViaWiFi","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus~1reachableViaWiFi\/fragments","value":[{"kind":"identifier","text":"ZDKNetworkStatusReachableViaWiFi"}]},{"op":"replace","value":"ZDKNetworkStatus","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNetworkStatus\/fragments","value":[{"kind":"identifier","text":"ZDKNetworkStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}