{"metadata":{"role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"category"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterCategory","text":"ZDKHelpCenterCategory"},{"kind":"text","text":"!"}],"title":"category","externalID":"c:objc(cs)ZDKHelpCenterFlatArticle(py)category","navigatorTitle":[{"text":"category","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"category","kind":"identifier"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCategory","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterCategory"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle\/category"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle\/category"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle\/category","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Category object."}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCategory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterCategory","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKHelpCenterCategory","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory","title":"ZDKHelpCenterCategory","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercategory","role":"symbol","type":"topic","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterFlatArticle":{"abstract":[{"text":"A Help Center FlatArticle.","type":"text"}],"navigatorTitle":[{"text":"ZDKHelpCenterFlatArticle","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle","title":"ZDKHelpCenterFlatArticle","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterFlatArticle"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterFlatArticle/category":{"abstract":[{"type":"text","text":"A Category object."}],"title":"category","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle\/category","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle\/category","role":"symbol","navigatorTitle":[{"text":"category","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"category","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ZDKHelpCenterCategory","preciseIdentifier":"c:objc(cs)ZDKHelpCenterCategory","kind":"typeIdentifier"},{"kind":"text","text":"!"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"category"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"category","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"ZDKHelpCenterCategory","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterCategory"},{"text":" * ","kind":"text"},{"text":"category","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"ZDKHelpCenterCategory","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategory\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategory\/fragments","op":"replace","value":[{"text":"ZDKHelpCenterCategory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle\/title","value":"ZDKHelpCenterFlatArticle","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterFlatArticle"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle~1category\/title","value":"category","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle~1category\/fragments","value":[{"kind":"identifier","text":"category"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}