{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle\/section","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"section"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterSection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSection","preciseIdentifier":"c:objc(cs)ZDKHelpCenterSection"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle\/section"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle\/section"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A Section object."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"section"}],"roleHeading":"Instance Property","title":"section","symbolKind":"property","externalID":"c:objc(cs)ZDKHelpCenterFlatArticle(py)section","role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"section"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterSection","text":"ZDKHelpCenterSection","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterFlatArticle":{"abstract":[{"text":"A Help Center FlatArticle.","type":"text"}],"navigatorTitle":[{"text":"ZDKHelpCenterFlatArticle","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle","title":"ZDKHelpCenterFlatArticle","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterFlatArticle"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterFlatArticle/section":{"title":"section","navigatorTitle":[{"kind":"identifier","text":"section"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterFlatArticle\/section","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterflatarticle\/section","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"section"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterSection","text":"ZDKHelpCenterSection","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"abstract":[{"text":"A Section object.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSection":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterSection","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKHelpCenterSection","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcentersection","role":"symbol","title":"ZDKHelpCenterSection","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"section"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"section"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSection","text":"ZDKHelpCenterSection","preciseIdentifier":"c:objc(cs)ZDKHelpCenterSection"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"section"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle\/title","value":"ZDKHelpCenterFlatArticle"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle\/fragments","op":"replace","value":[{"text":"ZDKHelpCenterFlatArticle","kind":"identifier"}]},{"value":"section","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle~1section\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterFlatArticle~1section\/fragments","value":[{"text":"section","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSection\/title","value":"ZDKHelpCenterSection"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSection\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterSection"}],"op":"replace"}]}]}