{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpCenterLocaleOverride"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Locale override for help center"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/helpCenterLocaleOverride","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/support\/helpcenterlocaleoverride"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/support\/helpcenterlocaleoverride"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"role":"symbol","title":"helpCenterLocaleOverride","navigatorTitle":[{"text":"helpCenterLocaleOverride","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"helpCenterLocaleOverride","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport(py)helpCenterLocaleOverride","symbolKind":"property","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support":{"role":"symbol","navigatorTitle":[{"text":"Support","kind":"identifier"}],"abstract":[{"text":"ZDKSupport is responsible for initialization of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the SDK and manages the backend configuration."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support","url":"\/documentation\/supportproviderssdk\/support","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Support","kind":"identifier"}],"kind":"symbol","title":"Support","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support/helpCenterLocaleOverride":{"role":"symbol","navigatorTitle":[{"text":"helpCenterLocaleOverride","kind":"identifier"}],"abstract":[{"type":"text","text":"Locale override for help center"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/helpCenterLocaleOverride","url":"\/documentation\/supportproviderssdk\/support\/helpcenterlocaleoverride","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpCenterLocaleOverride","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","title":"helpCenterLocaleOverride","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"helpCenterLocaleOverride","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"helpCenterLocaleOverride","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"helpCenterLocaleOverride","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support\/title","value":"ZDKSupport"},{"value":[{"kind":"identifier","text":"ZDKSupport"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support\/fragments"},{"value":"helpCenterLocaleOverride","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1helpCenterLocaleOverride\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1helpCenterLocaleOverride\/fragments","value":[{"text":"helpCenterLocaleOverride","kind":"identifier"}]}]}]}