{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ticketFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ZDKTicketField","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKTicketField","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField"},{"kind":"text","text":"]! { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketform\/ticketfields"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketform\/ticketfields"]}],"metadata":{"externalID":"c:objc(cs)ZDKTicketForm(py)ticketFields","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ticketFields"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)ZDKTicketField","text":"ZDKTicketField","kind":"typeIdentifier"},{"text":"]!","kind":"text"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"ticketFields","kind":"identifier"}],"title":"ticketFields","modules":[{"name":"SupportProvidersSDK"}]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketForm\/ticketFields","interfaceLanguage":"swift"},"abstract":[{"text":"List of ticket field objects","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketForm"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketForm":{"url":"\/documentation\/supportproviderssdk\/zdkticketform","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKTicketForm","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketForm","title":"ZDKTicketForm","abstract":[{"text":"Ticket form class","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketForm"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketForm/ticketFields":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ticketFields"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKTicketField","kind":"typeIdentifier","text":"ZDKTicketField"},{"text":"]!","kind":"text"}],"title":"ticketFields","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ticketFields"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketForm\/ticketFields","abstract":[{"type":"text","text":"List of ticket field objects"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketform\/ticketfields"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKTicketField","kind":"identifier"}],"title":"ZDKTicketField","role":"symbol","navigatorTitle":[{"text":"ZDKTicketField","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField","abstract":[{"type":"text","text":"Ticket field class"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfield"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"ticketFields","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ticketFields"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"NSArray<ZDKTicketField *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"ticketFields","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKTicketForm","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketForm\/title"},{"value":[{"text":"ZDKTicketForm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketForm\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketForm~1ticketFields\/title","value":"ticketFields"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketForm~1ticketFields\/fragments","value":[{"text":"ticketFields","kind":"identifier"}]},{"op":"replace","value":"ZDKTicketField","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField\/fragments","value":[{"text":"ZDKTicketField","kind":"identifier"}]}]}]}