{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/init()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/init(from:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/enabled","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/helpCenterArticleVotingEnabled","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/locale"],"title":"Instance Properties"},{"title":"Type Aliases","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/DefaultType"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/default"]}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/helpcentersettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/helpcentersettings"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"HelpCenterSettings"}],"roleHeading":"Class","title":"HelpCenterSettings","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterSettings"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSettings","role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/Se","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH","doc:\/\/com.zendesk.SupportProvidersSDK\/14ZendeskCoreSDK16DecodableDefaultP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKHelpCenterSettings) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterSettings"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSettings/init(from:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/helpcentersettings\/init(from:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/init(from:)","type":"topic","title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSettings/init()":{"title":"init()","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/init()","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/helpcentersettings\/init()","role":"symbol","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSettings/locale":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"locale","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/helpcentersettings\/locale","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/locale","type":"topic","title":"locale","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"locale","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSettings/default":{"abstract":[],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/helpcentersettings\/default","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/default","type":"topic","title":"default","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"text":": ","kind":"text"},{"text":"HelpCenterSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKHelpCenterSettings"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.SupportProvidersSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/Se"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSettings":{"title":"HelpCenterSettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterSettings"}],"url":"\/documentation\/supportproviderssdk\/helpcentersettings","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HelpCenterSettings"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSettings/helpCenterArticleVotingEnabled":{"navigatorTitle":[{"text":"helpCenterArticleVotingEnabled","kind":"identifier"}],"title":"helpCenterArticleVotingEnabled","url":"\/documentation\/supportproviderssdk\/helpcentersettings\/helpcenterarticlevotingenabled","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/helpCenterArticleVotingEnabled","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpCenterArticleVotingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/14ZendeskCoreSDK16DecodableDefaultP":{"type":"unresolvable","title":"ZendeskCoreSDK.DecodableDefault","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/14ZendeskCoreSDK16DecodableDefaultP"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSettings/DefaultType":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DefaultType"}],"url":"\/documentation\/supportproviderssdk\/helpcentersettings\/defaulttype","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/DefaultType","type":"topic","title":"HelpCenterSettings.DefaultType","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"DefaultType","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterSettings/enabled":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"enabled","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/helpcentersettings\/enabled","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/enabled","type":"topic","title":"enabled","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"ZDKHelpCenterSettings","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterSettings"}]},{"value":[{"kind":"identifier","text":"ZDKHelpCenterSettings"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/enabled","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/helpCenterArticleVotingEnabled","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/locale"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterSettings\/init()"],"title":"Instance Methods"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterSettings","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"init","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings~1init()\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings~1init()\/fragments"},{"op":"replace","value":"locale","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings~1locale\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings~1locale\/fragments","op":"replace","value":[{"kind":"identifier","text":"locale"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings\/title","op":"replace","value":"ZDKHelpCenterSettings"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterSettings"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings~1helpCenterArticleVotingEnabled\/title","value":"helpCenterArticleVotingEnabled"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings~1helpCenterArticleVotingEnabled\/fragments","op":"replace","value":[{"text":"helpCenterArticleVotingEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings~1enabled\/title","value":"enabled"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1HelpCenterSettings~1enabled\/fragments","value":[{"kind":"identifier","text":"enabled"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}