{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_CategoryByIdSuccess","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zd_hc_categorybyidsuccess"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zd_hc_categorybyidsuccess"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZD_HC_CategoryByIdSuccess"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:@ZD_HC_CategoryByIdSuccess","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZD_HC_CategoryByIdSuccess"}],"roleHeading":"Global Variable","symbolKind":"var","role":"symbol","title":"ZD_HC_CategoryByIdSuccess","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZD_HC_CategoryByIdSuccess","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"abstract":[{"type":"text","text":"Notification that a help centre category was successfully retrieved."}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZD_HC_CategoryByIdSuccess":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_CategoryByIdSuccess","url":"\/documentation\/supportproviderssdk\/zd_hc_categorybyidsuccess","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZD_HC_CategoryByIdSuccess"}],"type":"topic","title":"ZD_HC_CategoryByIdSuccess","abstract":[{"type":"text","text":"Notification that a help centre category was successfully retrieved."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZD_HC_CategoryByIdSuccess"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"ZD_HC_CategoryByIdSuccess","op":"replace"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZD_HC_CategoryByIdSuccess","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZD_HC_CategoryByIdSuccess"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_CategoryByIdSuccess\/title","value":"ZD_HC_CategoryByIdSuccess"},{"value":[{"kind":"identifier","text":"ZD_HC_CategoryByIdSuccess"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_CategoryByIdSuccess\/fragments"}]}]}