{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_DeflectionSearchSuccess","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zd_hc_deflectionsearchsuccess"]},{"paths":["\/documentation\/supportproviderssdk\/zd_hc_deflectionsearchsuccess"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Notification that a help center deflection search succeed.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@ZD_HC_DeflectionSearchSuccess","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZD_HC_DeflectionSearchSuccess"}],"roleHeading":"Global Variable","symbolKind":"var","role":"symbol","title":"ZD_HC_DeflectionSearchSuccess","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZD_HC_DeflectionSearchSuccess","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZD_HC_DeflectionSearchSuccess"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZD_HC_DeflectionSearchSuccess":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZD_HC_DeflectionSearchSuccess","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"ZD_HC_DeflectionSearchSuccess"}],"abstract":[{"type":"text","text":"Notification that a help center deflection search succeed."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_DeflectionSearchSuccess","type":"topic","title":"ZD_HC_DeflectionSearchSuccess","url":"\/documentation\/supportproviderssdk\/zd_hc_deflectionsearchsuccess"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"value":"ZD_HC_DeflectionSearchSuccess","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZD_HC_DeflectionSearchSuccess","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZD_HC_DeflectionSearchSuccess"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_DeflectionSearchSuccess\/title","value":"ZD_HC_DeflectionSearchSuccess"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_DeflectionSearchSuccess\/fragments","value":[{"text":"ZD_HC_DeflectionSearchSuccess","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}