{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdk_on_main_thread(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdk_on_main_thread(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/zdk_on_main_thread(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"zdk_on_main_thread"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"block","kind":"internalParam"},{"kind":"text","text":": (() -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")!)","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"c:ZDKDispatcher.h@F@zdk_on_main_thread","title":"zdk_on_main_thread(_:)","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Function","symbolKind":"func","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"zdk_on_main_thread","kind":"identifier"},{"text":"((() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"text":"zdk_on_main_thread","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Convenience method for executing a block on the UI queue"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/zdk_on_main_thread(_:)":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/zdk_on_main_thread(_:)","url":"\/documentation\/supportproviderssdk\/zdk_on_main_thread(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"zdk_on_main_thread"}],"type":"topic","abstract":[{"text":"Convenience method for executing a block on the UI queue","type":"text"}],"title":"zdk_on_main_thread(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"zdk_on_main_thread","kind":"identifier"},{"kind":"text","text":"((() -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")!)"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Function","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"zdk_on_main_thread"},{"value":"func","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"zdk_on_main_thread","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"zdk_on_main_thread"},{"kind":"text","text":"("},{"text":"dispatch_block_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_block_t"},{"kind":"text","text":" "},{"text":"block","kind":"internalParam"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1zdk_on_main_thread(_:)\/title","value":"zdk_on_main_thread"},{"op":"replace","value":[{"text":"zdk_on_main_thread","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1zdk_on_main_thread(_:)\/fragments"}]}]}