{"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"ZDKAPISuccess","kind":"identifier"}],"symbolKind":"typealias","roleHeading":"Type Alias","role":"symbol","title":"ZDKAPISuccess","externalID":"c:ZDKDispatcher.h@T@ZDKAPISuccess","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAPISuccess"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"abstract":[{"type":"text","text":"API success block."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkapisuccess"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkapisuccess"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPISuccess"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPISuccess"},{"text":" = (","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPISuccess":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPISuccess","url":"\/documentation\/supportproviderssdk\/zdkapisuccess","kind":"symbol","navigatorTitle":[{"text":"ZDKAPISuccess","kind":"identifier"}],"type":"topic","abstract":[{"text":"API success block.","type":"text"}],"title":"ZDKAPISuccess","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAPISuccess"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKAPISuccess"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKAPISuccess","kind":"identifier"}]},{"op":"replace","value":[{"text":"ZDKAPISuccess","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(id)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Qo)"},{"text":" ","kind":"text"},{"text":"ZDKAPISuccess","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKAPISuccess","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPISuccess\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPISuccess\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKAPISuccess"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}