{"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/init(dict:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/attachmentId","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/contentType","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/contentURLString","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/filename","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/imageDimension","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/size","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/thumbnails"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"kind":"symbol","metadata":{"externalID":"c:objc(cs)ZDKAttachment","navigatorTitle":[{"kind":"identifier","text":"ZDKAttachment"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAttachment"}],"title":"ZDKAttachment"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAttachment","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"An attachment to a Zendesk comment","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkattachment"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkattachment"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment/thumbnails":{"navigatorTitle":[{"kind":"identifier","text":"thumbnails"}],"url":"\/documentation\/supportproviderssdk\/zdkattachment\/thumbnails","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/thumbnails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnails"},{"text":": [","kind":"text"},{"text":"ZDKAttachment","preciseIdentifier":"c:objc(cs)ZDKAttachment","kind":"typeIdentifier"},{"kind":"text","text":"]!"}],"kind":"symbol","abstract":[{"text":"Thumbnails associated with the attachment. A thumbnail is an attachment with a nil thumbnails array.","type":"text"}],"title":"thumbnails"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment/imageDimension":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/imageDimension","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageDimension"}],"abstract":[{"text":"The dimension of the attachment.","type":"text"}],"role":"symbol","title":"imageDimension","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"imageDimension","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"url":"\/documentation\/supportproviderssdk\/zdkattachment\/imagedimension"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment/attachmentId":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/attachmentId","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"attachmentId"}],"abstract":[{"type":"text","text":"The id of this attachment in Zendesk."}],"role":"symbol","title":"attachmentId","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"attachmentId","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"url":"\/documentation\/supportproviderssdk\/zdkattachment\/attachmentid"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment/filename":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/filename","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"filename"}],"abstract":[{"type":"text","text":"The name of the attachment in Zendesk."}],"role":"symbol","title":"filename","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"filename","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"url":"\/documentation\/supportproviderssdk\/zdkattachment\/filename"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment","url":"\/documentation\/supportproviderssdk\/zdkattachment","kind":"symbol","navigatorTitle":[{"text":"ZDKAttachment","kind":"identifier"}],"type":"topic","title":"ZDKAttachment","abstract":[{"text":"An attachment to a Zendesk comment","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAttachment"}]},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment/init(dict:)":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/init(dict:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithDict:","kind":"identifier"}],"abstract":[{"type":"text","text":"Init with dictionary from API response."}],"role":"symbol","title":"init(dict:)","fragments":[{"kind":"identifier","text":"init"},{"text":"!(","kind":"text"},{"text":"dict","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!)","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkattachment\/init(dict:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment/contentURLString":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/contentURLString","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentURLString"}],"abstract":[{"type":"text","text":"The full url where the attachment can be downloaded."}],"role":"symbol","title":"contentURLString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"contentURLString","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkattachment\/contenturlstring"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment/contentType":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/contentType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentType"}],"abstract":[{"text":"The content type of the attachment, i.e. image\/png","type":"text"}],"role":"symbol","title":"contentType","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"contentType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkattachment\/contenttype"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment/size":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/size","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"size"}],"abstract":[{"type":"text","text":"The size of the attachment in bytes."}],"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkattachment\/size"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"ZDKAttachment","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKAttachment"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKAttachment"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/attachmentId","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/contentType","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/contentURLString","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/filename","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/imageDimension","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/size","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/thumbnails"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/init(dict:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAttachment"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"thumbnails","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1thumbnails\/title"},{"value":[{"text":"thumbnails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1thumbnails\/fragments","op":"replace"},{"value":"imageDimension","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1imageDimension\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1imageDimension\/fragments","value":[{"text":"imageDimension","kind":"identifier"}]},{"value":"attachmentId","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1attachmentId\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1attachmentId\/fragments","value":[{"text":"attachmentId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1filename\/title","value":"filename","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1filename\/fragments","value":[{"kind":"identifier","text":"filename"}],"op":"replace"},{"value":"ZDKAttachment","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment\/fragments","value":[{"text":"ZDKAttachment","kind":"identifier"}],"op":"replace"},{"value":"initWithDict:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1init(dict:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDict:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1init(dict:)\/fragments"},{"op":"replace","value":"contentURLString","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1contentURLString\/title"},{"value":[{"kind":"identifier","text":"contentURLString"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1contentURLString\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1contentType\/title","value":"contentType","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1contentType\/fragments","value":[{"text":"contentType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1size\/title","op":"replace","value":"size"},{"value":[{"text":"size","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1size\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}