{"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKConversationsSettingsProvider\/getConversationsSettings(callback:)"],"title":"Type Methods"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ConversationsSettingsProviderProtocol","doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKConversationsSettingsProvider"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationsSettingsProvider","kind":"identifier"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettingsProvider","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"ZDKConversationsSettingsProvider","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","role":"symbol","title":"ZDKConversationsSettingsProvider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKConversationsSettingsProvider","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkconversationssettingsprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkconversationssettingsprovider"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKConversationsSettingsProvider":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKConversationsSettingsProvider","url":"\/documentation\/supportproviderssdk\/zdkconversationssettingsprovider","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationsSettingsProvider"}],"type":"topic","title":"ZDKConversationsSettingsProvider","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKConversationsSettingsProvider"}]},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ConversationsSettingsProviderProtocol":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ConversationsSettingsProviderProtocol","url":"\/documentation\/supportproviderssdk\/conversationssettingsproviderprotocol","kind":"symbol","navigatorTitle":[{"text":"ConversationsSettingsProviderProtocol","kind":"identifier"}],"type":"topic","abstract":[],"title":"ConversationsSettingsProviderProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsSettingsProviderProtocol"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKConversationsSettingsProvider/getConversationsSettings(callback:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getConversationsSettings","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"text":": (","kind":"text"},{"text":"ConversationsSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettings"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"getConversationsSettingsWithCallback:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKConversationsSettingsProvider\/getConversationsSettings(callback:)","type":"topic","title":"getConversationsSettings(callback:)","url":"\/documentation\/supportproviderssdk\/zdkconversationssettingsprovider\/getconversationssettings(callback:)"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKConversationsSettingsProvider/init":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKConversationsSettingsProvider\/init","type":"topic","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkconversationssettingsprovider\/init"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKConversationsSettingsProvider"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKConversationsSettingsProvider","kind":"identifier"}]},{"value":[{"text":"ZDKConversationsSettingsProvider","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKConversationsSettingsProvider\/init"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKConversationsSettingsProvider\/getConversationsSettings(callback:)"]}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationsSettingsProvider"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKConversationsSettingsProvider","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKConversationsSettingsProvider\/title","op":"replace"},{"value":[{"text":"ZDKConversationsSettingsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKConversationsSettingsProvider\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKConversationsSettingsProvider~1getConversationsSettings(callback:)\/title","value":"getConversationsSettingsWithCallback:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKConversationsSettingsProvider~1getConversationsSettings(callback:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"getConversationsSettingsWithCallback:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}