{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"abstract":[{"type":"text","text":"Callback for Help Center simple responses, i.e. Status codes."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterGenericCallback"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterGenericCallback"},{"text":" = (","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"response","content":[{"type":"paragraph","inlineContent":[{"text":"The response for a request","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An error, nil if no error occurred."}]}],"name":"error"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentergenericcallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentergenericcallback"]}],"kind":"symbol","metadata":{"roleHeading":"Type Alias","externalID":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterGenericCallback","symbolKind":"typealias","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","title":"ZDKHelpCenterGenericCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterGenericCallback","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKHelpCenterGenericCallback","kind":"identifier"}]},"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterGenericCallback":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterGenericCallback","url":"\/documentation\/supportproviderssdk\/zdkhelpcentergenericcallback","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterGenericCallback"}],"type":"topic","abstract":[{"text":"Callback for Help Center simple responses, i.e. Status codes.","type":"text"}],"title":"ZDKHelpCenterGenericCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterGenericCallback"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"path":"\/metadata\/title","op":"replace","value":"ZDKHelpCenterGenericCallback"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterGenericCallback"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKHelpCenterGenericCallback","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*Qo#*$objc(cs)NSError)","text":"void (^)(id, NSError *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterGenericCallback","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterGenericCallback\/title","value":"ZDKHelpCenterGenericCallback"},{"value":[{"text":"ZDKHelpCenterGenericCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterGenericCallback\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}