{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterattachment"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterattachment"]}],"abstract":[{"type":"text","text":"A model for Help Center Attachments."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:objc(cs)ZDKHelpCenterAttachment","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterAttachment"}],"roleHeading":"Class","symbolKind":"class","role":"symbol","title":"ZDKHelpCenterAttachment","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterAttachment","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/article_id","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/content_type","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/content_url","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/file_name","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/identifier","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/isInline","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/size","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/url"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/humanReadableFileSize()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/parseAttachment(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/parseAttachments(_:)"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterAttachment"}]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/file_name":{"title":"file_name","navigatorTitle":[{"text":"file_name","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"file_name","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/file_name","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/file_name","abstract":[{"type":"text","text":"The file name of an attachment."}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/parseAttachments(_:)":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseAttachments"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!) -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/parseattachments(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"parseAttachments:"}],"type":"topic","abstract":[{"type":"text","text":"Parses a collection of Help Center json attachments objects."}],"title":"parseAttachments(_:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/parseAttachments(_:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/article_id":{"title":"article_id","navigatorTitle":[{"text":"article_id","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"article_id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"!","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/article_id","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/article_id","abstract":[{"type":"text","text":"The id of the article for which an attachment belongs."}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/url":{"title":"url","navigatorTitle":[{"text":"url","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"url","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/url","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/url","abstract":[{"type":"text","text":"The url where the attachment can be found."}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/size":{"title":"size","navigatorTitle":[{"text":"size","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/size","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/size","abstract":[{"type":"text","text":"Attachment file size."}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/humanReadableFileSize()":{"title":"humanReadableFileSize()","navigatorTitle":[{"text":"humanReadableFileSize","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"humanReadableFileSize"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/humanReadableFileSize()","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/humanreadablefilesize()","abstract":[{"type":"text","text":"Returns a string human readable format of file size."}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/content_url":{"title":"content_url","navigatorTitle":[{"text":"content_url","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content_url","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/content_url","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/content_url","abstract":[{"type":"text","text":"Content url for an attachment."}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/identifier":{"role":"symbol","abstract":[{"text":"The id of an attachment.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/identifier","type":"topic","title":"identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"!"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/identifier"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/content_type":{"title":"content_type","navigatorTitle":[{"text":"content_type","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"content_type"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/content_type","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/content_type","abstract":[{"type":"text","text":"The MIME type for an attachment."}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/isInline":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/isInline","type":"topic","kind":"symbol","navigatorTitle":[{"text":"isInline","kind":"identifier"}],"abstract":[{"text":"Is this an inline attachment?","type":"text"}],"role":"symbol","title":"isInline","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInline"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/isinline"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/parseAttachment(_:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Parses a single Help Center json attachment object."}],"kind":"symbol","title":"parseAttachment(_:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/parseattachment(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseAttachment"},{"text":"([","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterAttachment","text":"ZDKHelpCenterAttachment"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"parseAttachment:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/parseAttachment(_:)"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterAttachment","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterAttachment","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A model for Help Center Attachments."}],"title":"ZDKHelpCenterAttachment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKHelpCenterAttachment"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"ZDKHelpCenterAttachment","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"ZDKHelpCenterAttachment","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/article_id","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/content_type","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/content_url","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/file_name","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/identifier","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/isInline","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/size","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/url"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/humanReadableFileSize()"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/parseAttachment(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/parseAttachments(_:)"],"title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterAttachment"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1file_name\/title","value":"file_name"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1file_name\/fragments","value":[{"text":"file_name","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1parseAttachments(_:)\/title","op":"replace","value":"parseAttachments:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1parseAttachments(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"parseAttachments:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1article_id\/title","value":"article_id"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1article_id\/fragments","value":[{"kind":"identifier","text":"article_id"}],"op":"replace"},{"op":"replace","value":"url","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1url\/title"},{"value":[{"kind":"identifier","text":"url"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1url\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1size\/title","value":"size"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1size\/fragments","op":"replace","value":[{"text":"size","kind":"identifier"}]},{"value":"humanReadableFileSize","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1humanReadableFileSize()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"humanReadableFileSize"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1humanReadableFileSize()\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1content_url\/title","op":"replace","value":"content_url"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1content_url\/fragments","op":"replace","value":[{"kind":"identifier","text":"content_url"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1identifier\/title","value":"identifier"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1identifier\/fragments","value":[{"text":"identifier","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1content_type\/title","value":"content_type"},{"value":[{"kind":"identifier","text":"content_type"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1content_type\/fragments","op":"replace"},{"value":"isInline","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1isInline\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1isInline\/fragments","value":[{"text":"isInline","kind":"identifier"}]},{"value":"parseAttachment:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1parseAttachment(_:)\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"parseAttachment:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1parseAttachment(_:)\/fragments"},{"value":"ZDKHelpCenterAttachment","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment\/fragments","op":"replace","value":[{"text":"ZDKHelpCenterAttachment","kind":"identifier"}]}]}]}