{"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Ticket Field System Option (for "},{"type":"codeVoice","code":"ZDKTicketFieldTypeStatus"},{"text":", ","type":"text"},{"type":"codeVoice","code":"ZDKTicketFieldTypePriority"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"ZDKTicketFieldTypeTicketType"},{"text":" ticket field types)","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption\/init(dictionary:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption\/name","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption\/value"],"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKTicketFieldSystemOption"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldsystemoption"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldsystemoption"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"ZDKTicketFieldSystemOption","kind":"identifier"}],"roleHeading":"Class","title":"ZDKTicketFieldSystemOption","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldSystemOption","kind":"identifier"}],"externalID":"c:objc(cs)ZDKTicketFieldSystemOption","symbolKind":"class"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldSystemOption":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption","url":"\/documentation\/supportproviderssdk\/zdkticketfieldsystemoption","kind":"symbol","navigatorTitle":[{"text":"ZDKTicketFieldSystemOption","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Ticket Field System Option (for "},{"type":"codeVoice","code":"ZDKTicketFieldTypeStatus"},{"text":", ","type":"text"},{"code":"ZDKTicketFieldTypePriority","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"ZDKTicketFieldTypeTicketType"},{"text":" ticket field types)","type":"text"}],"title":"ZDKTicketFieldSystemOption","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKTicketFieldSystemOption"}]},"doc://com.zendesk.SupportProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldSystemOption/init(dictionary:)":{"abstract":[{"text":"Initialize a system ticket field option with a dictionary","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initWithDictionary:","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldsystemoption\/init(dictionary:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption\/init(dictionary:)","type":"topic","title":"init(dictionary:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldSystemOption/value":{"url":"\/documentation\/supportproviderssdk\/zdkticketfieldsystemoption\/value","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}],"title":"value","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption\/value","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"abstract":[{"text":"System Option Value, passed to zendesk server","type":"text"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldSystemOption/name":{"abstract":[{"type":"text","text":"System Option Name"}],"kind":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldsystemoption\/name","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption\/name","type":"topic","title":"name","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"ZDKTicketFieldSystemOption","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKTicketFieldSystemOption"}]},{"value":[{"kind":"identifier","text":"ZDKTicketFieldSystemOption"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption\/name","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption\/value"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldSystemOption\/init(dictionary:)"],"title":"Instance Methods"}]},{"value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKTicketFieldSystemOption"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption\/title","value":"ZDKTicketFieldSystemOption","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKTicketFieldSystemOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption~1init(dictionary:)\/title","value":"initWithDictionary:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption~1init(dictionary:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDictionary:","kind":"identifier"}]},{"value":"value","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption~1value\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption~1value\/fragments","value":[{"text":"value","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption~1name\/title","op":"replace","value":"name"},{"op":"replace","value":[{"text":"name","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldSystemOption~1name\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}