{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"firstComment"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKComment","kind":"typeIdentifier","text":"ZDKComment","preciseIdentifier":"c:objc(cs)ZDKComment"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequest\/firstcomment"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequest\/firstcomment"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest\/firstComment","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)ZDKRequest(py)firstComment","modules":[{"name":"SupportProvidersSDK"}],"title":"firstComment","symbolKind":"property","navigatorTitle":[{"text":"firstComment","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstComment"},{"text":": ","kind":"text"},{"text":"ZDKComment","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKComment"},{"text":"?","kind":"text"}]},"abstract":[{"text":"First public comment on request","type":"text"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequest":{"title":"ZDKRequest","navigatorTitle":[{"text":"ZDKRequest","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkrequest","abstract":[{"type":"text","text":"Object representing a Zendesk end user request returned by the server."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequest"}],"role":"symbol","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKComment":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKComment","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"title":"ZDKComment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKComment","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKComment"}],"url":"\/documentation\/supportproviderssdk\/zdkcomment"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequest/firstComment":{"navigatorTitle":[{"kind":"identifier","text":"firstComment"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"firstComment"},{"text":": ","kind":"text"},{"text":"ZDKComment","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKComment"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkrequest\/firstcomment","abstract":[{"type":"text","text":"First public comment on request"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest\/firstComment","title":"firstComment","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"firstComment","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"firstComment"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":", "},{"text":"nullable","kind":"keyword"},{"kind":"text","text":") "},{"text":"ZDKComment","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKComment","preciseIdentifier":"c:objc(cs)ZDKComment"},{"text":" * ","kind":"text"},{"text":"firstComment","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"ZDKRequest","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/fragments","value":[{"kind":"identifier","text":"ZDKRequest"}],"op":"replace"},{"value":"ZDKComment","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKComment\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKComment\/fragments","value":[{"kind":"identifier","text":"ZDKComment"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest~1firstComment\/title","op":"replace","value":"firstComment"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest~1firstComment\/fragments","op":"replace","value":[{"kind":"identifier","text":"firstComment"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}