{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/section","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/section"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/section"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"section"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Used to specify that section ids are being used."}],"metadata":{"externalID":"c:@E@ZDKHelpCenterOverviewGroupType@ZDKHelpCenterOverviewGroupTypeSection","roleHeading":"Case","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"ZDKHelpCenterOverviewGroupTypeSection","kind":"identifier"}],"title":"ZDKHelpCenterOverviewGroupType.section","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"section","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType"]]},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupType"}],"abstract":[{"type":"text","text":"Used to specify what type of ids will be supplied."}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype","navigatorTitle":[{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType","title":"ZDKHelpCenterOverviewGroupType"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType/section":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"section"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/section","title":"ZDKHelpCenterOverviewGroupType.section","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/section","abstract":[{"type":"text","text":"Used to specify that section ids are being used."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterOverviewGroupTypeSection","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"ZDKHelpCenterOverviewGroupTypeSection","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKHelpCenterOverviewGroupTypeSection","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupTypeSection"}]}]},"op":"replace"},{"op":"replace","value":"ZDKHelpCenterOverviewGroupType","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType\/title"},{"value":[{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1section\/title","op":"replace","value":"ZDKHelpCenterOverviewGroupTypeSection"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupTypeSection"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1section\/fragments"}]}]}