{"abstract":[{"text":"Delete an upload from Zendesk. Will only work if the upload has not been associated with a request\/ticket.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkuploadprovider\/deleteupload(_:andcallback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkuploadprovider\/deleteupload(_:andcallback:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadProvider\/deleteUpload(_:andCallback:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadProvider"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteUpload","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"uploadToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"andCallback"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":": ","kind":"text"},{"text":"ZDKDeleteUploadCallback","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeleteUploadCallback","preciseIdentifier":"c:ZDKUploadProvider.h@T@ZDKDeleteUploadCallback"},{"kind":"text","text":"!)"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Upload token of file to delete"}]}],"name":"uploadToken"},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"text":"Block callback executed on request error or success. Can be nil.","type":"text"}]}]}],"kind":"parameters"}],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteUpload"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!, "},{"text":"andCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ZDKDeleteUploadCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKUploadProvider.h@T@ZDKDeleteUploadCallback"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"deleteUpload:andCallback:","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}],"title":"deleteUpload(_:andCallback:)","roleHeading":"Instance Method","externalID":"c:objc(cs)ZDKUploadProvider(im)deleteUpload:andCallback:"},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKUploadProvider":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadProvider","navigatorTitle":[{"kind":"identifier","text":"ZDKUploadProvider"}],"title":"ZDKUploadProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKUploadProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"A provider for uploading images to Zendesk which can then be attached to requests."}],"url":"\/documentation\/supportproviderssdk\/zdkuploadprovider","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDeleteUploadCallback":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeleteUploadCallback","kind":"symbol","navigatorTitle":[{"text":"ZDKDeleteUploadCallback","kind":"identifier"}],"type":"topic","title":"ZDKDeleteUploadCallback","abstract":[{"type":"text","text":"Block defined for callback to be used for handling async server responses for deleting an upload attachment."}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkdeleteuploadcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKDeleteUploadCallback","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKUploadProvider/deleteUpload(_:andCallback:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKUploadProvider\/deleteUpload(_:andCallback:)","navigatorTitle":[{"kind":"identifier","text":"deleteUpload:andCallback:"}],"title":"deleteUpload(_:andCallback:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteUpload","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"andCallback"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKUploadProvider.h@T@ZDKDeleteUploadCallback","text":"ZDKDeleteUploadCallback"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Delete an upload from Zendesk. Will only work if the upload has not been associated with a request\/ticket."}],"url":"\/documentation\/supportproviderssdk\/zdkuploadprovider\/deleteupload(_:andcallback:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"deleteUpload:andCallback:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deleteUpload:andCallback:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"deleteUpload:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"uploadToken"},{"kind":"text","text":" "},{"text":"andCallback:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKDeleteUploadCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeleteUploadCallback","preciseIdentifier":"c:ZDKUploadProvider.h@T@ZDKDeleteUploadCallback"},{"kind":"text","text":") "},{"text":"callback","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKUploadProvider","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKUploadProvider"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeleteUploadCallback\/title","value":"ZDKDeleteUploadCallback"},{"op":"replace","value":[{"text":"ZDKDeleteUploadCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeleteUploadCallback\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadProvider~1deleteUpload(_:andCallback:)\/title","value":"deleteUpload:andCallback:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteUpload:andCallback:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKUploadProvider~1deleteUpload(_:andCallback:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}