{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfield\/options"]},{"paths":["\/documentation\/supportproviderssdk\/zdkticketfield\/options"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"SupportProvidersSDK"}],"title":"options","navigatorTitle":[{"kind":"identifier","text":"options"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"options"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKTicketFieldOption","kind":"typeIdentifier","text":"ZDKTicketFieldOption"},{"text":"]!","kind":"text"}],"symbolKind":"property","externalID":"c:objc(cs)ZDKTicketField(py)options"},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/options","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Ticket field options, this field will only be populated for "},{"type":"codeVoice","code":"ZDKTicketFieldTypeComboBox"},{"type":"text","text":" field types"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ZDKTicketFieldOption","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption","preciseIdentifier":"c:objc(cs)ZDKTicketFieldOption"},{"kind":"text","text":"]! { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKTicketField","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfield","navigatorTitle":[{"text":"ZDKTicketField","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField","type":"topic","abstract":[{"type":"text","text":"Ticket field class"}],"title":"ZDKTicketField","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketField/options":{"url":"\/documentation\/supportproviderssdk\/zdkticketfield\/options","navigatorTitle":[{"kind":"identifier","text":"options"}],"kind":"symbol","abstract":[{"type":"text","text":"Ticket field options, this field will only be populated for "},{"type":"codeVoice","code":"ZDKTicketFieldTypeComboBox"},{"text":" field types","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"options","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)ZDKTicketFieldOption","kind":"typeIdentifier","text":"ZDKTicketFieldOption"},{"text":"]!","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketField\/options","type":"topic","role":"symbol","title":"options"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldOption":{"url":"\/documentation\/supportproviderssdk\/zdkticketfieldoption","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldOption"}],"kind":"symbol","abstract":[{"type":"text","text":"Ticket Field Option (for ZDKTicketFieldTypeTagger ticket field types)"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldOption","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption","type":"topic","role":"symbol","title":"ZDKTicketFieldOption"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"options","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"options"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<ZDKTicketFieldOption *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"options"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKTicketField","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField\/fragments","value":[{"kind":"identifier","text":"ZDKTicketField"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1options\/title","value":"options","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketField~1options\/fragments","value":[{"text":"options","kind":"identifier"}]},{"value":"ZDKTicketFieldOption","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption\/fragments","op":"replace","value":[{"text":"ZDKTicketFieldOption","kind":"identifier"}]}]}]}