{"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Deprecated as of 2.3.0, use ZDKHelpCenterUiConfigration instead"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/hideContactSupport"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Hide the ","type":"text"},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button that is displayed upon an empty search in Help Center"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideContactSupport"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/hidecontactsupport"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/hidecontactsupport"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel"]]},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"hideContactSupport","kind":"identifier"}],"platforms":[],"title":"hideContactSupport","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:objc(cs)ZDKHelpCenterOverviewContentModel(py)hideContactSupport","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hideContactSupport","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel/hideContactSupport":{"navigatorTitle":[{"kind":"identifier","text":"hideContactSupport"}],"title":"hideContactSupport","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/hidecontactsupport","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/hideContactSupport","abstract":[{"text":"Hide the ","type":"text"},{"code":"Contact Support","type":"codeVoice"},{"type":"text","text":" button that is displayed upon an empty search in Help Center"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hideContactSupport","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"deprecated":true,"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel":{"title":"ZDKHelpCenterOverviewContentModel","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel","abstract":[{"type":"text","text":"Model which allows customizations on the content displayed by Help Center."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterOverviewContentModel"}],"type":"topic","navigatorTitle":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hideContactSupport","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"hideContactSupport","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"hideContactSupport","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1hideContactSupport\/title","value":"hideContactSupport"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1hideContactSupport\/fragments","value":[{"text":"hideContactSupport","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/title","op":"replace","value":"ZDKHelpCenterOverviewContentModel"},{"value":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}