{"abstract":[{"text":"The SDK has an oauth token that was valid the last time it was used.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkapiloginstate\/loggedin"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkapiloginstate\/loggedin"]}],"sections":[],"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"ZDKAPILoginStateLoggedIn","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","title":"ZDKAPILoginState.loggedIn","externalID":"c:@E@ZDKAPILoginState@ZDKAPILoginStateLoggedIn","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"loggedIn","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/loggedIn","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"loggedIn","kind":"identifier"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState":{"url":"\/documentation\/supportproviderssdk\/zdkapiloginstate","abstract":[{"text":"ZDKAPI Login state.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAPILoginState"}],"kind":"symbol","title":"ZDKAPILoginState","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState","navigatorTitle":[{"text":"ZDKAPILoginState","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPILoginState/loggedIn":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPILoginState\/loggedIn","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ZDKAPILoginStateLoggedIn","kind":"identifier"}],"abstract":[{"text":"The SDK has an oauth token that was valid the last time it was used.","type":"text"}],"role":"symbol","title":"ZDKAPILoginState.loggedIn","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loggedIn"}],"url":"\/documentation\/supportproviderssdk\/zdkapiloginstate\/loggedin"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKAPILoginStateLoggedIn","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKAPILoginStateLoggedIn","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKAPILoginStateLoggedIn"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState\/title","value":"ZDKAPILoginState"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState\/fragments","value":[{"kind":"identifier","text":"ZDKAPILoginState"}],"op":"replace"},{"value":"ZDKAPILoginStateLoggedIn","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1loggedIn\/title","op":"replace"},{"value":[{"text":"ZDKAPILoginStateLoggedIn","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPILoginState~1loggedIn\/fragments","op":"replace"}]}]}