{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Foundation\/NSNotification\/Name\/ZDKAPI_ReachabilityChanged","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Notification that the network status has changed."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/foundation\/nsnotification\/name\/zdkapi_reachabilitychanged"]},{"paths":["\/documentation\/supportproviderssdk\/foundation\/nsnotification\/name\/zdkapi_reachabilitychanged"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAPI_ReachabilityChanged","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"sections":[],"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:@ZDKAPI_ReachabilityChangedNotification","title":"ZDKAPI_ReachabilityChanged","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAPI_ReachabilityChanged"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"symbolKind":"property","roleHeading":"Type Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_ReachabilityChangedNotification"}]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Foundation/NSNotification/Name/ZDKAPI_ReachabilityChanged":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ZDKAPI_ReachabilityChanged","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"text":".","kind":"text"},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Notification that the network status has changed."}],"title":"ZDKAPI_ReachabilityChanged","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Foundation\/NSNotification\/Name\/ZDKAPI_ReachabilityChanged","kind":"symbol","navigatorTitle":[{"text":"ZDKAPI_ReachabilityChangedNotification","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/foundation\/nsnotification\/name\/zdkapi_reachabilitychanged"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"value":"ZDKAPI_ReachabilityChangedNotification","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKAPI_ReachabilityChangedNotification"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAPI_ReachabilityChangedNotification","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Foundation~1NSNotification~1Name~1ZDKAPI_ReachabilityChanged\/title","value":"ZDKAPI_ReachabilityChangedNotification"},{"op":"replace","value":[{"text":"ZDKAPI_ReachabilityChangedNotification","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Foundation~1NSNotification~1Name~1ZDKAPI_ReachabilityChanged\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}