{"abstract":[{"type":"text","text":"Parses a single Help Center json category object."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentercategory\/parsecategory(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentercategory\/parsecategory(_:)"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parseCategory"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"categoryJson","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> "},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory","text":"ZDKHelpCenterCategory","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterCategory"},{"kind":"text","text":"!"}]}]},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new ZDKHelpCenterCategory."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory\/parseCategory(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory"]]},"metadata":{"navigatorTitle":[{"text":"parseCategory:","kind":"identifier"}],"title":"parseCategory(_:)","roleHeading":"Type Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseCategory"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!) -> ","kind":"text"},{"text":"ZDKHelpCenterCategory","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterCategory"},{"kind":"text","text":"!"}],"role":"symbol","externalID":"c:objc(cs)ZDKHelpCenterCategory(cm)parseCategory:","modules":[{"name":"SupportProvidersSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCategory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterCategory","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKHelpCenterCategory","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory","title":"ZDKHelpCenterCategory","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercategory","role":"symbol","type":"topic","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCategory/parseCategory(_:)":{"navigatorTitle":[{"kind":"identifier","text":"parseCategory:"}],"type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercategory\/parsecategory(_:)","kind":"symbol","abstract":[{"text":"Parses a single Help Center json category object.","type":"text"}],"title":"parseCategory(_:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory\/parseCategory(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parseCategory","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!) -> ","kind":"text"},{"text":"ZDKHelpCenterCategory","preciseIdentifier":"c:objc(cs)ZDKHelpCenterCategory","kind":"typeIdentifier"},{"text":"!","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"parseCategory:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"parseCategory:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterCategory","kind":"typeIdentifier","text":"ZDKHelpCenterCategory","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategory"},{"kind":"text","text":" *) "},{"text":"parseCategory:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"categoryJson","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategory\/title","value":"ZDKHelpCenterCategory","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterCategory"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategory\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategory~1parseCategory(_:)\/title","op":"replace","value":"parseCategory:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"parseCategory:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategory~1parseCategory(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}