{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/supportsettings"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/supportsettings"]}],"metadata":{"symbolKind":"class","title":"SupportSettings","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupportSettings","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportSettings","kind":"identifier"}],"role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SupportSettings"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKSupportSettings) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportSettings"}],"languages":["swift"]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/init()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/attachmentSettings","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/contactUsSettings","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/conversationSettings","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/neverRequestEmail","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/referrerUrl","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/showClosedRequests","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/showReferrerLogo","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/systemMessage","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/ticketFormsSettings"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/DefaultType"],"title":"Type Aliases"},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/default"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/Se","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH","doc:\/\/com.zendesk.SupportProvidersSDK\/14ZendeskCoreSDK16DecodableDefaultP"],"title":"Conforms To"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/contactUsSettings":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"contactUsSettings"}],"type":"topic","title":"contactUsSettings","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactUsSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactUsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKContactUsSettings"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/contactussettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/contactUsSettings","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/referrerUrl":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"referrerUrl"}],"title":"referrerUrl","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"referrerUrl"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/referrerurl","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/referrerUrl","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/showClosedRequests":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"showClosedRequests"}],"type":"topic","title":"showClosedRequests","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showClosedRequests"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/showclosedrequests","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/showClosedRequests","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/showReferrerLogo":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"showReferrerLogo"}],"type":"topic","title":"showReferrerLogo","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"showReferrerLogo"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/showreferrerlogo","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/showReferrerLogo","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/init(from:)":{"kind":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/init(from:)","title":"init(from:)","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/init(from:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/DefaultType":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DefaultType"}],"title":"SupportSettings.DefaultType","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DefaultType"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/defaulttype","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/DefaultType","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/systemMessage":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"systemMessage"}],"title":"systemMessage","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"systemMessage","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/systemmessage","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/systemMessage","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/conversationSettings":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"conversationSettings"}],"type":"topic","title":"conversationSettings","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettings"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/conversationsettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/conversationSettings","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/Se":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings":{"kind":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings","title":"SupportSettings","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportSettings"}],"navigatorTitle":[{"text":"SupportSettings","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/neverRequestEmail":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"neverRequestEmail"}],"type":"topic","title":"neverRequestEmail","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"neverRequestEmail"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/neverrequestemail","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/neverRequestEmail","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/14ZendeskCoreSDK16DecodableDefaultP":{"title":"ZendeskCoreSDK.DecodableDefault","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/14ZendeskCoreSDK16DecodableDefaultP","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/ticketFormsSettings":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ticketFormsSettings"}],"type":"topic","title":"ticketFormsSettings","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ticketFormsSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TicketFormsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKTicketFormsSettings"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/ticketFormsSettings","url":"\/documentation\/supportproviderssdk\/supportsettings\/ticketformssettings","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/init()":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/init()","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/init()","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/default":{"kind":"symbol","title":"default","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"text":"SupportSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupportSettings"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/default","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/default","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/attachmentSettings":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"attachmentSettings"}],"type":"topic","title":"attachmentSettings","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentSettings"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettings","text":"AttachmentSettings"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/attachmentSettings","url":"\/documentation\/supportproviderssdk\/supportsettings\/attachmentsettings","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKSupportSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKSupportSettings"}]},{"op":"replace","value":[{"kind":"identifier","text":"ZDKSupportSettings"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/attachmentSettings","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/contactUsSettings","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/conversationSettings","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/neverRequestEmail","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/referrerUrl","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/showClosedRequests","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/showReferrerLogo","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/systemMessage","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/ticketFormsSettings"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/init()"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKSupportSettings","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"op":"replace"},{"value":"contactUsSettings","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1contactUsSettings\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1contactUsSettings\/fragments","value":[{"text":"contactUsSettings","kind":"identifier"}],"op":"replace"},{"value":"referrerUrl","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1referrerUrl\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1referrerUrl\/fragments","value":[{"text":"referrerUrl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1showClosedRequests\/title","op":"replace","value":"showClosedRequests"},{"value":[{"kind":"identifier","text":"showClosedRequests"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1showClosedRequests\/fragments"},{"value":"showReferrerLogo","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1showReferrerLogo\/title"},{"value":[{"text":"showReferrerLogo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1showReferrerLogo\/fragments"},{"value":"systemMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1systemMessage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1systemMessage\/fragments","value":[{"text":"systemMessage","kind":"identifier"}]},{"value":"conversationSettings","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1conversationSettings\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1conversationSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"conversationSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings\/title","value":"ZDKSupportSettings"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings\/fragments","value":[{"text":"ZDKSupportSettings","kind":"identifier"}],"op":"replace"},{"value":"neverRequestEmail","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1neverRequestEmail\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1neverRequestEmail\/fragments","value":[{"text":"neverRequestEmail","kind":"identifier"}]},{"value":"ticketFormsSettings","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1ticketFormsSettings\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1ticketFormsSettings\/fragments","op":"replace","value":[{"text":"ticketFormsSettings","kind":"identifier"}]},{"op":"replace","value":"init","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1init()\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","value":"attachmentSettings","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1attachmentSettings\/title"},{"value":[{"text":"attachmentSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1attachmentSettings\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}