{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zd_hc_sectionsupdated"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zd_hc_sectionsupdated"]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_SectionsUpdated","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZD_HC_SectionsUpdated","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"var","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZD_HC_SectionsUpdated"}],"role":"symbol","roleHeading":"Global Variable","title":"ZD_HC_SectionsUpdated","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZD_HC_SectionsUpdated","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"c:@ZD_HC_SectionsUpdated"},"abstract":[{"type":"text","text":"Notification that help centre sections were updated."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZD_HC_SectionsUpdated":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZD_HC_SectionsUpdated"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zd_hc_sectionsupdated","title":"ZD_HC_SectionsUpdated","navigatorTitle":[{"kind":"identifier","text":"ZD_HC_SectionsUpdated"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_SectionsUpdated","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Notification that help centre sections were updated."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"ZD_HC_SectionsUpdated"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"value":[{"kind":"identifier","text":"ZD_HC_SectionsUpdated"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"text":"ZD_HC_SectionsUpdated","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_SectionsUpdated\/title","value":"ZD_HC_SectionsUpdated","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_SectionsUpdated\/fragments","value":[{"kind":"identifier","text":"ZD_HC_SectionsUpdated"}]}]}]}