{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZD_HC_DownvoteStarting","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zd_hc_downvotestarting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zd_hc_downvotestarting"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"abstract":[{"text":"Notification that a Help Center article downvote request started","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ZD_HC_DownvoteStarting"}],"role":"symbol","title":"ZD_HC_DownvoteStarting","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZD_HC_DownvoteStarting"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@ZD_HC_DownvoteStarting","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"var","roleHeading":"Global Variable"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_DownvoteStarting","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZD_HC_DownvoteStarting":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZD_HC_DownvoteStarting","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zd_hc_downvotestarting","title":"ZD_HC_DownvoteStarting","navigatorTitle":[{"kind":"identifier","text":"ZD_HC_DownvoteStarting"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_DownvoteStarting","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Notification that a Help Center article downvote request started"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZD_HC_DownvoteStarting"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ZD_HC_DownvoteStarting","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZD_HC_DownvoteStarting"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_DownvoteStarting\/title","op":"replace","value":"ZD_HC_DownvoteStarting"},{"value":[{"text":"ZD_HC_DownvoteStarting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_DownvoteStarting\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}