{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDD_AcceptLanguage","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdd_acceptlanguage"]},{"paths":["\/documentation\/supportproviderssdk\/zdd_acceptlanguage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDD_AcceptLanguage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"sections":[],"metadata":{"symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"ZDD_AcceptLanguage"}],"title":"ZDD_AcceptLanguage","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","externalID":"c:@ZDD_AcceptLanguage","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDD_AcceptLanguage","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Global Variable"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDD_AcceptLanguage":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDD_AcceptLanguage"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdd_acceptlanguage","title":"ZDD_AcceptLanguage","navigatorTitle":[{"kind":"identifier","text":"ZDD_AcceptLanguage"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDD_AcceptLanguage","kind":"symbol","type":"topic","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDD_AcceptLanguage","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"value":[{"kind":"identifier","text":"ZDD_AcceptLanguage"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDD_AcceptLanguage"}],"languages":["occ"]}]}},{"value":"ZDD_AcceptLanguage","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDD_AcceptLanguage\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDD_AcceptLanguage\/fragments","value":[{"kind":"identifier","text":"ZDD_AcceptLanguage"}]}]}]}