{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_requestsstarting"]},{"paths":["\/documentation\/supportproviderssdk\/zdkapi_requestsstarting"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAPI_RequestsStarting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Notification that the request list is about to be retrieved."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_RequestsStarting"},"metadata":{"role":"symbol","title":"ZDKAPI_RequestsStarting","externalID":"c:@ZDKAPI_RequestsStarting","navigatorTitle":[{"text":"ZDKAPI_RequestsStarting","kind":"identifier"}],"symbolKind":"var","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Global Variable","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_RequestsStarting"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPI_RequestsStarting":{"type":"topic","navigatorTitle":[{"text":"ZDKAPI_RequestsStarting","kind":"identifier"}],"title":"ZDKAPI_RequestsStarting","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ZDKAPI_RequestsStarting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Notification that the request list is about to be retrieved.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkapi_requestsstarting","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_RequestsStarting"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKAPI_RequestsStarting"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"value":[{"text":"ZDKAPI_RequestsStarting","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAPI_RequestsStarting"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_RequestsStarting\/title","value":"ZDKAPI_RequestsStarting"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_RequestsStarting\/fragments","op":"replace","value":[{"text":"ZDKAPI_RequestsStarting","kind":"identifier"}]}]}]}