{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_DeleteUploadStarting","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Notification that an upload deletion is starting."}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkapi_deleteuploadstarting"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_deleteuploadstarting"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"sections":[],"metadata":{"symbolKind":"var","externalID":"c:@ZDKAPI_DeleteUploadStarting","navigatorTitle":[{"text":"ZDKAPI_DeleteUploadStarting","kind":"identifier"}],"roleHeading":"Global Variable","role":"symbol","title":"ZDKAPI_DeleteUploadStarting","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_DeleteUploadStarting"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"SupportProvidersSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDKAPI_DeleteUploadStarting","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPI_DeleteUploadStarting":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAPI_DeleteUploadStarting"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkapi_deleteuploadstarting","title":"ZDKAPI_DeleteUploadStarting","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_DeleteUploadStarting"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_DeleteUploadStarting","kind":"symbol","type":"topic","abstract":[{"text":"Notification that an upload deletion is starting.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"value":"ZDKAPI_DeleteUploadStarting","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKAPI_DeleteUploadStarting","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAPI_DeleteUploadStarting","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_DeleteUploadStarting\/title","value":"ZDKAPI_DeleteUploadStarting"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_DeleteUploadStarting\/fragments","value":[{"text":"ZDKAPI_DeleteUploadStarting","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}