{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"kind":"symbol","metadata":{"symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_RequestsUpdated"}],"title":"ZDKAPI_RequestsUpdated","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","externalID":"c:@ZDKAPI_RequestsUpdated","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDKAPI_RequestsUpdated","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Global Variable"},"abstract":[{"type":"text","text":"Notification for triggering storage of requests."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_RequestsUpdated"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkapi_requestsupdated"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_requestsupdated"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_RequestsUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPI_RequestsUpdated":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_RequestsUpdated"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkapi_requestsupdated","title":"ZDKAPI_RequestsUpdated","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_RequestsUpdated"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_RequestsUpdated","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Notification for triggering storage of requests."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKAPI_RequestsUpdated"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"value":[{"kind":"identifier","text":"ZDKAPI_RequestsUpdated"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_RequestsUpdated"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKAPI_RequestsUpdated","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_RequestsUpdated\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_RequestsUpdated\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKAPI_RequestsUpdated"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}