{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_UsersUpdated"},"kind":"symbol","sections":[],"metadata":{"externalID":"c:@ZDKAPI_UsersUpdated","role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ZDKAPI_UsersUpdated","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"ZDKAPI_UsersUpdated","symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_UsersUpdated"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkapi_usersupdated"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_usersupdated"]}],"abstract":[{"type":"text","text":"Notification for triggering storage of users."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDKAPI_UsersUpdated","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPI_UsersUpdated":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_UsersUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkapi_usersupdated","title":"ZDKAPI_UsersUpdated","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_UsersUpdated"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_UsersUpdated","kind":"symbol","type":"topic","abstract":[{"text":"Notification for triggering storage of users.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ZDKAPI_UsersUpdated","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKAPI_UsersUpdated"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAPI_UsersUpdated","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_UsersUpdated\/title","value":"ZDKAPI_UsersUpdated"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAPI_UsersUpdated"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_UsersUpdated\/fragments"}]}]}