{"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/JWT","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/anonymous","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/unknown"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/Equatable-Implementations","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"metadata":{"symbolKind":"enum","role":"symbol","externalID":"c:@E@ZDKAuthenticationType","title":"ZDKAuthenticationType","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationType"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKAuthenticationType","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"abstract":[{"type":"text","text":"Represents the types of authentication SDK supports."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkauthenticationtype"]},{"paths":["\/documentation\/supportproviderssdk\/zdkauthenticationtype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType"},"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH","doc:\/\/com.zendesk.SupportProvidersSDK\/SY","doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKAuthenticationType","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType/JWT":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKAuthenticationTypeJWT","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype\/jwt","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/JWT","title":"ZDKAuthenticationType.JWT","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"JWT","kind":"identifier"}],"abstract":[{"text":"JWT authentication.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType/RawRepresentable-Implementations":{"role":"collectionGroup","url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/RawRepresentable-Implementations","kind":"article","type":"topic","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SY"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType/unknown":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype\/unknown","title":"ZDKAuthenticationType.unknown","navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationTypeUnknown"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/unknown","kind":"symbol","type":"topic","abstract":[{"text":"Authentication type unknown.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType/anonymous":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"anonymous","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype\/anonymous","title":"ZDKAuthenticationType.anonymous","navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationTypeAnonymous"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/anonymous","kind":"symbol","type":"topic","abstract":[{"text":"Anonymous authentication.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKAuthenticationType","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType","title":"ZDKAuthenticationType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAuthenticationType"}],"abstract":[{"text":"Represents the types of authentication SDK supports.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/init(rawValue:)","kind":"symbol","type":"topic","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType/Equatable-Implementations":{"role":"collectionGroup","url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype\/equatable-implementations","title":"Equatable Implementations","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/Equatable-Implementations","kind":"article","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"ZDKAuthenticationType","path":"\/metadata\/title","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKAuthenticationType","kind":"identifier"}]},{"value":[{"text":"ZDKAuthenticationType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/JWT","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/anonymous","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/unknown"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAuthenticationType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1JWT\/title","value":"ZDKAuthenticationTypeJWT","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAuthenticationTypeJWT"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1JWT\/fragments"},{"op":"replace","value":"ZDKAuthenticationTypeUnknown","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1unknown\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1unknown\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKAuthenticationTypeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1anonymous\/title","value":"ZDKAuthenticationTypeAnonymous"},{"value":[{"kind":"identifier","text":"ZDKAuthenticationTypeAnonymous"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1anonymous\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType\/title","op":"replace","value":"ZDKAuthenticationType"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType\/fragments","value":[{"text":"ZDKAuthenticationType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}