{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/frameworkResourceBundle()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/frameworkStringsBundle()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/helpCenterCss()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/imageNamed(_:ofType:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/path(forFrameworkResource:ofType:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/stringsTableName()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/userDefinedHelpCenterCss()"],"title":"Type Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkbundleutils"]},{"paths":["\/documentation\/supportproviderssdk\/zdkbundleutils"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils","interfaceLanguage":"swift"},"abstract":[{"text":"Util for working with SupportSDK bundles.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKBundleUtils"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"metadata":{"symbolKind":"class","externalID":"c:objc(cs)ZDKBundleUtils","navigatorTitle":[{"text":"ZDKBundleUtils","kind":"identifier"}],"roleHeading":"Class","title":"ZDKBundleUtils","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKBundleUtils"}],"modules":[{"name":"SupportProvidersSDK"}],"role":"symbol"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils/frameworkStringsBundle()":{"url":"\/documentation\/supportproviderssdk\/zdkbundleutils\/frameworkstringsbundle()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameworkStringsBundle"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/frameworkStringsBundle()","abstract":[{"type":"text","text":"Gets the framework strings bundle."}],"title":"frameworkStringsBundle()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"frameworkStringsBundle"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils/path(forFrameworkResource:ofType:)":{"url":"\/documentation\/supportproviderssdk\/zdkbundleutils\/path(forframeworkresource:oftype:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"path"},{"kind":"text","text":"("},{"text":"forFrameworkResource","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"text":"ofType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"type":"topic","abstract":[{"text":"Get the path for a resource in the SDK bundle.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/path(forFrameworkResource:ofType:)","title":"path(forFrameworkResource:ofType:)","role":"symbol","navigatorTitle":[{"text":"pathForFrameworkResource:ofType:","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils":{"navigatorTitle":[{"kind":"identifier","text":"ZDKBundleUtils"}],"type":"topic","title":"ZDKBundleUtils","role":"symbol","abstract":[{"text":"Util for working with SupportSDK bundles.","type":"text"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkbundleutils","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKBundleUtils","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils/stringsTableName()":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/stringsTableName()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringsTableName"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"title":"stringsTableName()","navigatorTitle":[{"kind":"identifier","text":"stringsTableName"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkbundleutils\/stringstablename()","type":"topic","kind":"symbol","abstract":[{"text":"The name of the frameworks strings table","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils/imageNamed(_:ofType:)":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/imageNamed(_:ofType:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imageNamed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"ofType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!) -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"!"}],"title":"imageNamed(_:ofType:)","navigatorTitle":[{"text":"imageNamed:ofType:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkbundleutils\/imagenamed(_:oftype:)","type":"topic","kind":"symbol","abstract":[{"text":"Returns an image resource from SupportSDK bundle.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils/frameworkResourceBundle()":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/frameworkResourceBundle()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"frameworkResourceBundle","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"text":"!","kind":"text"}],"title":"frameworkResourceBundle()","navigatorTitle":[{"kind":"identifier","text":"frameworkResourceBundle"}],"role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkbundleutils\/frameworkresourcebundle()","kind":"symbol","abstract":[{"text":"Gets the framework resource bundle.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils/helpCenterCss()":{"navigatorTitle":[{"text":"helpCenterCss","kind":"identifier"}],"type":"topic","title":"helpCenterCss()","role":"symbol","abstract":[{"type":"text","text":"Get the help center css file in the SDK bundle and return as a string."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/helpCenterCss()","url":"\/documentation\/supportproviderssdk\/zdkbundleutils\/helpcentercss()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"helpCenterCss","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}]},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils/userDefinedHelpCenterCss()":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/userDefinedHelpCenterCss()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"userDefinedHelpCenterCss","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"title":"userDefinedHelpCenterCss()","navigatorTitle":[{"kind":"identifier","text":"userDefinedHelpCenterCss"}],"role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkbundleutils\/userdefinedhelpcentercss()","kind":"symbol","abstract":[{"text":"Get the help center css file in the host apps main bundle and return as a string.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"ZDKBundleUtils","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKBundleUtils","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKBundleUtils"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/frameworkResourceBundle()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/frameworkStringsBundle()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/helpCenterCss()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/imageNamed(_:ofType:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/path(forFrameworkResource:ofType:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/stringsTableName()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/userDefinedHelpCenterCss()"],"title":"Type Methods"}]},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKBundleUtils"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1frameworkStringsBundle()\/title","value":"frameworkStringsBundle","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"frameworkStringsBundle"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1frameworkStringsBundle()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1path(forFrameworkResource:ofType:)\/title","value":"pathForFrameworkResource:ofType:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1path(forFrameworkResource:ofType:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"pathForFrameworkResource:ofType:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils\/title","value":"ZDKBundleUtils","op":"replace"},{"value":[{"text":"ZDKBundleUtils","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1stringsTableName()\/title","value":"stringsTableName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1stringsTableName()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"stringsTableName","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1imageNamed(_:ofType:)\/title","value":"imageNamed:ofType:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1imageNamed(_:ofType:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"imageNamed:ofType:","kind":"identifier"}]},{"op":"replace","value":"frameworkResourceBundle","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1frameworkResourceBundle()\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1frameworkResourceBundle()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"frameworkResourceBundle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1helpCenterCss()\/title","value":"helpCenterCss","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"helpCenterCss"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1helpCenterCss()\/fragments"},{"value":"userDefinedHelpCenterCss","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1userDefinedHelpCenterCss()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"userDefinedHelpCenterCss","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1userDefinedHelpCenterCss()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}