{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKDeleteUploadCallback"},{"text":" = (","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"responseCode","content":[{"inlineContent":[{"type":"text","text":"response code for a delete action."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"NSError returned as a result of any errors taking place when the request is executed, can be nil on success.","type":"text"}]}],"name":"error"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkdeleteuploadcallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkdeleteuploadcallback"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"symbolKind":"typealias","navigatorTitle":[{"text":"ZDKDeleteUploadCallback","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}],"title":"ZDKDeleteUploadCallback","role":"symbol","externalID":"c:ZDKUploadProvider.h@T@ZDKDeleteUploadCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ZDKDeleteUploadCallback","kind":"identifier"}],"roleHeading":"Type Alias"},"abstract":[{"type":"text","text":"Block defined for callback to be used for handling async server responses for deleting an upload attachment."}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeleteUploadCallback","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDeleteUploadCallback":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"ZDKDeleteUploadCallback","kind":"identifier"}],"title":"ZDKDeleteUploadCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKDeleteUploadCallback","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkdeleteuploadcallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeleteUploadCallback","abstract":[{"text":"Block defined for callback to be used for handling async server responses for deleting an upload attachment.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"ZDKDeleteUploadCallback"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKDeleteUploadCallback","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKDeleteUploadCallback","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(NSString *, NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSString#*$objc(cs)NSError)"},{"text":" ","kind":"text"},{"text":"ZDKDeleteUploadCallback","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"ZDKDeleteUploadCallback","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeleteUploadCallback\/title","op":"replace"},{"op":"replace","value":[{"text":"ZDKDeleteUploadCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeleteUploadCallback\/fragments"}]}]}