{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterViewModel\/detailTitle","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterViewModel\/name"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"ZDKHelpCenterViewModel","kind":"identifier"}],"role":"symbol","title":"ZDKHelpCenterViewModel","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterViewModel","kind":"identifier"}],"externalID":"c:objc(pl)ZDKHelpCenterViewModel","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"protocol","roleHeading":"Protocol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterviewmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterviewmodel"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterViewModel"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterViewModel"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"languages":["swift"]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject"],"type":"inheritsFrom"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterViewModel/detailTitle":{"navigatorTitle":[{"text":"detailTitle","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterviewmodel\/detailtitle","title":"detailTitle","type":"topic","kind":"symbol","required":true,"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterViewModel\/detailTitle"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterViewModel/name":{"navigatorTitle":[{"text":"name","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterviewmodel\/name","title":"name","type":"topic","kind":"symbol","required":true,"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterViewModel\/name"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","title":"NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterViewModel":{"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterViewModel"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterviewmodel","title":"ZDKHelpCenterViewModel","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterViewModel"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterViewModel"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKHelpCenterViewModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"ZDKHelpCenterViewModel","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterViewModel"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterViewModel\/detailTitle","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterViewModel\/name"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterViewModel","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterViewModel~1detailTitle\/title","value":"detailTitle"},{"op":"replace","value":[{"kind":"identifier","text":"detailTitle"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterViewModel~1detailTitle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterViewModel~1name\/title","value":"name"},{"value":[{"text":"name","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterViewModel~1name\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterViewModel\/title","value":"ZDKHelpCenterViewModel","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterViewModel"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterViewModel\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}