{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"kind":"symbol","metadata":{"symbolKind":"class","navigatorTitle":[{"text":"ZDKHelpCenterDeflection","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}],"title":"ZDKHelpCenterDeflection","role":"symbol","externalID":"c:objc(cs)ZDKHelpCenterDeflection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterDeflection","kind":"identifier"}],"roleHeading":"Class"},"abstract":[{"type":"text","text":"This class models a Help Center Deflection search. It has the same contract as a normal Help Center search."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/developer.zendesk.com\/rest_api\/docs\/help_center\/search"}],"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/categoryId","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/labelNames","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/locale","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/page","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/query","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/resultsPerPage","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/sectionId","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/sideLoads"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterDeflection"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection/sideLoads":{"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection\/sideloads","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sideLoads"},{"kind":"text","text":": "},{"text":"NSMutableArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"text":"!","kind":"text"}],"kind":"symbol","title":"sideLoads","navigatorTitle":[{"text":"sideLoads","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/sideLoads","abstract":[{"text":"This models the “include” parameter.  This specifies the elements to side-load and include in the results.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection/categoryId":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/categoryId","title":"categoryId","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"categoryId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"kind":"symbol","navigatorTitle":[{"text":"categoryId","kind":"identifier"}],"abstract":[{"text":"This models the “category” parameter.  This specifies that the search will be restricted to content that is in the given","type":"text"},{"text":" ","type":"text"},{"text":"category.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection\/categoryid","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection":{"type":"topic","title":"ZDKHelpCenterDeflection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection","abstract":[{"type":"text","text":"This class models a Help Center Deflection search. It has the same contract as a normal Help Center search."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/developer.zendesk.com\/rest_api\/docs\/help_center\/search"}],"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterDeflection","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterDeflection","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection/page":{"type":"topic","kind":"symbol","title":"page","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/page","abstract":[{"type":"text","text":"This models the “page” parameter. This specifies what page of results to return.  This is closely tied to the resultsPerPage"},{"type":"text","text":" "},{"type":"text","text":"property."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"page"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"page","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection\/page"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection/sectionId":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sectionId"}],"title":"sectionId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sectionId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"!","kind":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection\/sectionid","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/sectionId","abstract":[{"type":"text","text":"This models the “section” parameter.  This specifies that the search will be restricted to content that is in the given"},{"type":"text","text":" "},{"text":"section.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection/query":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"query"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection\/query","title":"query","navigatorTitle":[{"kind":"identifier","text":"query"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/query","kind":"symbol","type":"topic","abstract":[{"text":"This models the free-form text query.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection/resultsPerPage":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"resultsPerPage","kind":"identifier"}],"title":"resultsPerPage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultsPerPage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"!","kind":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection\/resultsperpage","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/resultsPerPage","abstract":[{"type":"text","text":"This models the “per_page” parameter.  This specifies how many results to return for the current page.  The current page is"},{"type":"text","text":" "},{"type":"text","text":"specified by the page property."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection/labelNames":{"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection\/labelnames","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/labelNames","kind":"symbol","role":"symbol","type":"topic","title":"labelNames","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"labelNames"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"text":"!","kind":"text"}],"abstract":[{"text":"This models the “label_names” parameter. This will be a comma-separated list of label names to restrict the search to.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"labelNames"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection/locale":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/locale","role":"symbol","title":"locale","kind":"symbol","navigatorTitle":[{"text":"locale","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection\/locale","abstract":[{"type":"text","text":"This models the “locale” parameter. This specifies that the search will be restricted to content with this locale.  The locale"},{"text":" ","type":"text"},{"type":"text","text":"is in the format of “ll-cc”, e.g. “en-us”.  Locales in the form of “ll” are also permitted, e.g. “en”."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"locale","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}]},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKHelpCenterDeflection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterDeflection"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"ZDKHelpCenterDeflection","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/categoryId","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/labelNames","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/locale","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/page","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/query","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/resultsPerPage","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/sectionId","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection\/sideLoads"]}]},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterDeflection","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1sideLoads\/title","value":"sideLoads"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1sideLoads\/fragments","value":[{"kind":"identifier","text":"sideLoads"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1categoryId\/title","value":"categoryId"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1categoryId\/fragments","value":[{"text":"categoryId","kind":"identifier"}]},{"op":"replace","value":"ZDKHelpCenterDeflection","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterDeflection"}]},{"value":"page","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1page\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1page\/fragments","op":"replace","value":[{"kind":"identifier","text":"page"}]},{"op":"replace","value":"sectionId","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1sectionId\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1sectionId\/fragments","value":[{"kind":"identifier","text":"sectionId"}]},{"value":"query","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1query\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1query\/fragments","value":[{"text":"query","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1resultsPerPage\/title","op":"replace","value":"resultsPerPage"},{"op":"replace","value":[{"text":"resultsPerPage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1resultsPerPage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1labelNames\/title","value":"labelNames"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1labelNames\/fragments","value":[{"text":"labelNames","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1locale\/title","value":"locale"},{"value":[{"kind":"identifier","text":"locale"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection~1locale\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}