{"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"title":"ZDKHelpCenterProvider","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","externalID":"c:objc(cs)ZDKHelpCenterProvider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKProvider"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterProviderProtocol","doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterProvider"}]}],"kind":"declarations"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/downVoteArticle(withId:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticleSuggestions(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticleWithId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticlesByLabels(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticlesWithSectionId(_:labels:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticlesWithSectionId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getAttachmentWithArticleId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getCategoriesWithCallback(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getCategoryWithId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getFlatArticles(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getFlatArticles(callback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getHelpCenterOverview(withHelpCenterOverviewModel:callback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getSectionWithId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getSectionsWithCategoryId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/removeVote(withId:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/searchArticles(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/searchForArticles(usingQuery:andLabels:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/searchForArticles(usingQuery:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/submitRecordArticleView(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/upVoteArticle(withId:withCallback:)"],"title":"Instance Methods"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/searchArticles(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"searchArticles:withCallback:","kind":"identifier"}],"title":"searchArticles(_:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"searchArticles"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKHelpCenterSearch","preciseIdentifier":"c:objc(cs)ZDKHelpCenterSearch"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/searcharticles(_:withcallback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/searchArticles(_:withCallback:)","abstract":[{"text":"This method will search articles in your Help Center filtered by the parameters in the given ZDKHelpCenterSearch model.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getArticleWithId(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"getArticleWithId:withCallback:","kind":"identifier"}],"title":"getArticleWithId(_:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getArticleWithId"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticleWithId(_:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlewithid(_:withcallback:)","abstract":[{"text":"Fetch an article by ID.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getSectionsWithCategoryId(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"getSectionsWithCategoryId:withCallback:","kind":"identifier"}],"title":"getSectionsWithCategoryId(_:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getSectionsWithCategoryId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getsectionswithcategoryid(_:withcallback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getSectionsWithCategoryId(_:withCallback:)","abstract":[{"text":"Fetch a list of sections for a given categoryId from a Help Center instance","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/submitRecordArticleView(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"submitRecordArticleView:withCallback:","kind":"identifier"}],"title":"submitRecordArticleView(_:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitRecordArticleView"},{"text":"(","kind":"text"},{"text":"ZDKHelpCenterArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterGenericCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterGenericCallback"},{"text":"!)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/submitRecordArticleView(_:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/submitrecordarticleview(_:withcallback:)","abstract":[{"text":"Used for the purpose of reporting in Zendesk. This will record an article as being viewed by the client.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getCategoryWithId(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"getCategoryWithId:withCallback:","kind":"identifier"}],"title":"getCategoryWithId(_:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCategoryWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getcategorywithid(_:withcallback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getCategoryWithId(_:withCallback:)","abstract":[{"text":"Fetches a category object for a particular categoryId.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/searchForArticles(usingQuery:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"searchForArticlesUsingQuery:withCallback:","kind":"identifier"}],"title":"searchForArticles(usingQuery:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"searchForArticles","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"usingQuery"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/searchForArticles(usingQuery:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/searchforarticles(usingquery:withcallback:)","abstract":[{"text":"This method will search articles in your Help Center.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method will also sideload categories, sections and users."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getHelpCenterOverview(withHelpCenterOverviewModel:callback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getHelpCenterOverviewWithHelpCenterOverviewModel:callback:"}],"title":"getHelpCenterOverview(withHelpCenterOverviewModel:callback:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getHelpCenterOverview","kind":"identifier"},{"kind":"text","text":"("},{"text":"withHelpCenterOverviewModel","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterOverviewContentModel","text":"ZDKHelpCenterOverviewContentModel","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCategoriesCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCategoriesCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/gethelpcenteroverview(withhelpcenteroverviewmodel:callback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getHelpCenterOverview(withHelpCenterOverviewModel:callback:)","abstract":[{"type":"text","text":"Fetches the data required to model the overview UI in Help Center."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getArticleSuggestions(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getArticleSuggestions:withCallback:"}],"title":"getArticleSuggestions(_:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getArticleSuggestions"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterDeflection","text":"ZDKHelpCenterDeflection"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withCallback"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticleSuggestions(_:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlesuggestions(_:withcallback:)","abstract":[{"type":"text","text":"Fetch a list of suggested articles filtered by the parameters in the given ZDKHelpCenterDeflection model."}]},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getFlatArticles(callback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"getFlatArticlesWithCallback:","kind":"identifier"}],"title":"getFlatArticles(callback:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getFlatArticles","kind":"identifier"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getFlatArticles(callback:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getflatarticles(callback:)","abstract":[{"type":"text","text":"Fetch a list of FlatArticle objects for a given Help Center instance. Supplies a hardcoded perPage of 100 and page of 1 to getFlatArticles:withCallback."}],"deprecated":true},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/upVoteArticle(withId:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"upVoteArticleWithId:withCallback:"}],"title":"upVoteArticle(withId:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"upVoteArticle"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/upvotearticle(withid:withcallback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/upVoteArticle(withId:withCallback:)","abstract":[{"type":"text","text":"Post an upvote for a given article. If a vote already exists for the source object it is updated."}]},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/downVoteArticle(withId:withCallback:)":{"navigatorTitle":[{"text":"downVoteArticleWithId:withCallback:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/downvotearticle(withid:withcallback:)","title":"downVoteArticle(withId:withCallback:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"downVoteArticle"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ZDKHelpCenterCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Post a downvote for a given article. If a vote already exists for the source object it is updated."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/downVoteArticle(withId:withCallback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKProvider":{"navigatorTitle":[{"kind":"identifier","text":"ZDKProvider"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkprovider","title":"ZDKProvider","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKProvider"}],"abstract":[{"type":"text","text":"ZDKProvider class"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKProvider"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/searchForArticles(usingQuery:andLabels:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"searchForArticlesUsingQuery:andLabels:withCallback:","kind":"identifier"}],"title":"searchForArticles(usingQuery:andLabels:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchForArticles"},{"text":"(","kind":"text"},{"text":"usingQuery","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"andLabels","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/searchForArticles(usingQuery:andLabels:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/searchforarticles(usingquery:andlabels:withcallback:)","abstract":[{"type":"text","text":"This method will search articles in your Help Center filtered by an array of labels"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/removeVote(withId:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"removeVoteWithId:withCallback:","kind":"identifier"}],"title":"removeVote(withId:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeVote"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withCallback"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterGenericCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterGenericCallback"},{"text":"!)","kind":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/removevote(withid:withcallback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/removeVote(withId:withCallback:)","abstract":[{"type":"text","text":"Deletes a vote for a given id"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getCategoriesWithCallback(_:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"getCategoriesWithCallback:","kind":"identifier"}],"title":"getCategoriesWithCallback(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getCategoriesWithCallback","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getCategoriesWithCallback(_:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getcategorieswithcallback(_:)","abstract":[{"type":"text","text":"Fetch a list of categories from a Help Center instance."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getArticlesWithSectionId(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getArticlesWithSectionId:withCallback:"}],"title":"getArticlesWithSectionId(_:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getArticlesWithSectionId"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticleswithsectionid(_:withcallback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticlesWithSectionId(_:withCallback:)","abstract":[{"type":"text","text":"Fetch a list of articles for a given sectionId from a Help Center instance"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/HelpCenterProviderProtocol":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HelpCenterProviderProtocol"}],"title":"HelpCenterProviderProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterProviderProtocol"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/HelpCenterProviderProtocol","url":"\/documentation\/supportproviderssdk\/helpcenterproviderprotocol","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getFlatArticles(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getFlatArticles:withCallback:"}],"title":"getFlatArticles(_:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getFlatArticles"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKListArticleQuery","text":"ListArticleQuery","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getflatarticles(_:withcallback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getFlatArticles(_:withCallback:)","abstract":[{"type":"text","text":"Fetch number of FlatArticle objects based on the number of results and page provided in the ZDKListArticleQuery object."}]},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getSectionWithId(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getSectionWithId:withCallback:"}],"title":"getSectionWithId(_:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getSectionWithId"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getSectionWithId(_:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getsectionwithid(_:withcallback:)","abstract":[{"type":"text","text":"Fetches a section object for a particular sectionId."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider","title":"ZDKHelpCenterProvider","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getAttachmentWithArticleId(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getAttachmentWithArticleId:withCallback:"}],"title":"getAttachmentWithArticleId(_:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getAttachmentWithArticleId"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getattachmentwitharticleid(_:withcallback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getAttachmentWithArticleId(_:withCallback:)","abstract":[{"type":"text","text":"This method returns a list of attachments for a single article."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getArticlesByLabels(_:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getArticlesByLabels:withCallback:"}],"title":"getArticlesByLabels(_:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getArticlesByLabels"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticlesByLabels(_:withCallback:)","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlesbylabels(_:withcallback:)","abstract":[{"type":"text","text":"Fetch a list of articles for a given array of labels from a Help Center instance"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getArticlesWithSectionId(_:labels:withCallback:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getArticlesWithSectionId:labels:withCallback:"}],"title":"getArticlesWithSectionId(_:labels:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getArticlesWithSectionId"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"labels","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"withCallback"},{"text":": ","kind":"text"},{"text":"ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticleswithsectionid(_:labels:withcallback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticlesWithSectionId(_:labels:withCallback:)","abstract":[{"type":"text","text":"Fetch a list of articles for a given sectionId from a Help Center instance"}]},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"ZDKHelpCenterProvider","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/downVoteArticle(withId:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticleSuggestions(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticleWithId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticlesByLabels(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticlesWithSectionId(_:labels:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticlesWithSectionId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getAttachmentWithArticleId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getCategoriesWithCallback(_:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getCategoryWithId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getFlatArticles(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getFlatArticles(callback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getHelpCenterOverview(withHelpCenterOverviewModel:callback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getSectionWithId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getSectionsWithCategoryId(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/removeVote(withId:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/searchArticles(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/searchForArticles(usingQuery:andLabels:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/searchForArticles(usingQuery:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/submitRecordArticleView(_:withCallback:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/upVoteArticle(withId:withCallback:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKProvider"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterProvider"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKProvider","text":"ZDKProvider","preciseIdentifier":"c:objc(cs)ZDKProvider","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"searchArticles:withCallback:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1searchArticles(_:withCallback:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1searchArticles(_:withCallback:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"searchArticles:withCallback:"}]},{"op":"replace","value":"getArticleWithId:withCallback:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticleWithId(_:withCallback:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getArticleWithId:withCallback:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticleWithId(_:withCallback:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getSectionsWithCategoryId(_:withCallback:)\/title","value":"getSectionsWithCategoryId:withCallback:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getSectionsWithCategoryId(_:withCallback:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSectionsWithCategoryId:withCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1submitRecordArticleView(_:withCallback:)\/title","value":"submitRecordArticleView:withCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1submitRecordArticleView(_:withCallback:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"submitRecordArticleView:withCallback:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getCategoryWithId(_:withCallback:)\/title","value":"getCategoryWithId:withCallback:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getCategoryWithId(_:withCallback:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCategoryWithId:withCallback:"}]},{"value":"searchForArticlesUsingQuery:withCallback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1searchForArticles(usingQuery:withCallback:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1searchForArticles(usingQuery:withCallback:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"searchForArticlesUsingQuery:withCallback:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getHelpCenterOverview(withHelpCenterOverviewModel:callback:)\/title","value":"getHelpCenterOverviewWithHelpCenterOverviewModel:callback:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getHelpCenterOverview(withHelpCenterOverviewModel:callback:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getHelpCenterOverviewWithHelpCenterOverviewModel:callback:","kind":"identifier"}],"op":"replace"},{"value":"getArticleSuggestions:withCallback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticleSuggestions(_:withCallback:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getArticleSuggestions:withCallback:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticleSuggestions(_:withCallback:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getFlatArticles(callback:)\/title","value":"getFlatArticlesWithCallback:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getFlatArticlesWithCallback:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getFlatArticles(callback:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1upVoteArticle(withId:withCallback:)\/title","value":"upVoteArticleWithId:withCallback:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1upVoteArticle(withId:withCallback:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"upVoteArticleWithId:withCallback:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"downVoteArticleWithId:withCallback:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1downVoteArticle(withId:withCallback:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"downVoteArticleWithId:withCallback:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1downVoteArticle(withId:withCallback:)\/fragments"},{"value":"ZDKProvider","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKProvider\/title","op":"replace"},{"value":[{"text":"ZDKProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKProvider\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1searchForArticles(usingQuery:andLabels:withCallback:)\/title","value":"searchForArticlesUsingQuery:andLabels:withCallback:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"searchForArticlesUsingQuery:andLabels:withCallback:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1searchForArticles(usingQuery:andLabels:withCallback:)\/fragments"},{"value":"removeVoteWithId:withCallback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1removeVote(withId:withCallback:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1removeVote(withId:withCallback:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeVoteWithId:withCallback:","kind":"identifier"}]},{"value":"getCategoriesWithCallback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getCategoriesWithCallback(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCategoriesWithCallback:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getCategoriesWithCallback(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticlesWithSectionId(_:withCallback:)\/title","op":"replace","value":"getArticlesWithSectionId:withCallback:"},{"value":[{"text":"- ","kind":"text"},{"text":"getArticlesWithSectionId:withCallback:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticlesWithSectionId(_:withCallback:)\/fragments"},{"value":"getFlatArticles:withCallback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getFlatArticles(_:withCallback:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getFlatArticles(_:withCallback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFlatArticles:withCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getSectionWithId(_:withCallback:)\/title","value":"getSectionWithId:withCallback:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getSectionWithId(_:withCallback:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getSectionWithId:withCallback:","kind":"identifier"}]},{"value":"ZDKHelpCenterProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getAttachmentWithArticleId(_:withCallback:)\/title","value":"getAttachmentWithArticleId:withCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getAttachmentWithArticleId(_:withCallback:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getAttachmentWithArticleId:withCallback:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticlesByLabels(_:withCallback:)\/title","op":"replace","value":"getArticlesByLabels:withCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticlesByLabels(_:withCallback:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getArticlesByLabels:withCallback:","kind":"identifier"}]},{"value":"getArticlesWithSectionId:labels:withCallback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticlesWithSectionId(_:labels:withCallback:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticlesWithSectionId(_:labels:withCallback:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getArticlesWithSectionId:labels:withCallback:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}