{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/init(requests:andCommentingAgents:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/commentingAgents","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/requests"],"title":"Instance Properties"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}]}]}],"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}],"role":"symbol","roleHeading":"Class","externalID":"c:objc(cs)ZDKRequestsWithCommentingAgents","title":"ZDKRequestsWithCommentingAgents","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestsWithCommentingAgents"}]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestsWithCommentingAgents/init(requests:andCommentingAgents:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithRequests:andCommentingAgents:","kind":"identifier"}],"title":"init(requests:andCommentingAgents:)","fragments":[{"kind":"identifier","text":"init"},{"text":"!(","kind":"text"},{"text":"requests","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"ZDKRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKRequest"},{"text":"]!, ","kind":"text"},{"text":"andCommentingAgents","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)ZDKSupportUser","text":"ZDKSupportUser","kind":"typeIdentifier"},{"text":"]!)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/init(requests:andCommentingAgents:)","url":"\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents\/init(requests:andcommentingagents:)","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestsWithCommentingAgents/requests":{"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents\/requests","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requests","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKRequest","text":"ZDKRequest","kind":"typeIdentifier"},{"text":"]!","kind":"text"}],"title":"requests","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/requests","navigatorTitle":[{"text":"requests","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestsWithCommentingAgents/commentingAgents":{"url":"\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents\/commentingagents","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commentingAgents","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKSupportUser","text":"ZDKSupportUser"},{"kind":"text","text":"]!"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/commentingAgents","abstract":[],"title":"commentingAgents","role":"symbol","navigatorTitle":[{"text":"commentingAgents","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestsWithCommentingAgents":{"url":"\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestsWithCommentingAgents"}],"title":"ZDKRequestsWithCommentingAgents","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ZDKRequestsWithCommentingAgents","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/commentingAgents","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/requests"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/init(requests:andCommentingAgents:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestsWithCommentingAgents"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"initWithRequests:andCommentingAgents:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents~1init(requests:andCommentingAgents:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents~1init(requests:andCommentingAgents:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRequests:andCommentingAgents:"}]},{"value":"requests","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents~1requests\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents~1requests\/fragments","op":"replace","value":[{"kind":"identifier","text":"requests"}]},{"value":"commentingAgents","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents~1commentingAgents\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents~1commentingAgents\/fragments","value":[{"kind":"identifier","text":"commentingAgents"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents\/title","value":"ZDKRequestsWithCommentingAgents"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKRequestsWithCommentingAgents"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}