{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalDiskspace"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkdeviceinfo\/totaldiskspace()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkdeviceinfo\/totaldiskspace()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeviceInfo\/totalDiskspace()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the total disk space of the device."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalDiskspace"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"totalDiskspace()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ZDKDeviceInfo(cm)totalDiskspace","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"totalDiskspace"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeviceInfo"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDeviceInfo/totalDiskspace()":{"role":"symbol","title":"totalDiskspace()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalDiskspace"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get the total disk space of the device."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeviceInfo\/totalDiskspace()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalDiskspace"}],"url":"\/documentation\/supportproviderssdk\/zdkdeviceinfo\/totaldiskspace()"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDeviceInfo":{"role":"symbol","title":"ZDKDeviceInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKDeviceInfo"}],"abstract":[{"type":"text","text":"Helper class for retrieving device information."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDeviceInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKDeviceInfo"}],"url":"\/documentation\/supportproviderssdk\/zdkdeviceinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"totalDiskspace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"totalDiskspace"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"identifier","text":"totalDiskspace"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeviceInfo~1totalDiskspace()\/title","value":"totalDiskspace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeviceInfo~1totalDiskspace()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"totalDiskspace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeviceInfo\/title","value":"ZDKDeviceInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDeviceInfo\/fragments","value":[{"kind":"identifier","text":"ZDKDeviceInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}