{"metadata":{"navigatorTitle":[{"text":"initWithQuery:resultsCount:","kind":"identifier"}],"role":"symbol","title":"init(query:resultsCount:)","fragments":[{"kind":"identifier","text":"init"},{"text":"!(","kind":"text"},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"resultsCount"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"!)","kind":"text"}],"externalID":"c:objc(cs)ZDKHelpCenterLastSearch(im)initWithQuery:resultsCount:","modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"init","roleHeading":"Initializer"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch\/init(query:resultscount:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch\/init(query:resultscount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/init(query:resultsCount:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Create a new last search model."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"!(","kind":"text"},{"text":"query","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"resultsCount"},{"text":" ","kind":"text"},{"text":"count","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"!)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The search query.","type":"text"}],"type":"paragraph"}],"name":"query"},{"name":"count","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The results count."}]}]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A new instance.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterLastSearch/init(query:resultsCount:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithQuery:resultsCount:","kind":"identifier"}],"title":"init(query:resultsCount:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"text":"resultsCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"!)","kind":"text"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch\/init(query:resultscount:)","abstract":[{"type":"text","text":"Create a new last search model."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch\/init(query:resultsCount:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterLastSearch":{"type":"topic","navigatorTitle":[{"text":"ZDKHelpCenterLastSearch","kind":"identifier"}],"title":"ZDKHelpCenterLastSearch","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterLastSearch"}],"role":"symbol","abstract":[{"text":"A model for recording the last search in Help Center.","type":"text"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterlastsearch","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterLastSearch"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithQuery:resultsCount:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithQuery:resultsCount:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithQuery:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"query"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resultsCount:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"count"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"initWithQuery:resultsCount:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch~1init(query:resultsCount:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithQuery:resultsCount:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch~1init(query:resultsCount:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch\/title","value":"ZDKHelpCenterLastSearch","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterLastSearch\/fragments","value":[{"text":"ZDKHelpCenterLastSearch","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}