{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getAttachmentWithArticleId(_:withCallback:)"},"abstract":[{"type":"text","text":"This method returns a list of attachments for a single article."}],"metadata":{"externalID":"c:objc(cs)ZDKHelpCenterProvider(im)getAttachmentWithArticleId:withCallback:","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"getAttachmentWithArticleId:withCallback:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","title":"getAttachmentWithArticleId(_:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getAttachmentWithArticleId"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getattachmentwitharticleid(_:withcallback:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getattachmentwitharticleid(_:withcallback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAttachmentWithArticleId"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"articleId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCallback","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"articleId","content":[{"inlineContent":[{"text":"the identifier to be used to retrieve an article from a Help Center instance","type":"text"}],"type":"paragraph"}]},{"name":"callback","content":[{"inlineContent":[{"text":"the callback that is invoked when a request is either successful or has errors","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCallback":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercallback","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterCallback"}],"type":"topic","abstract":[{"type":"text","text":"Callback block."}],"title":"ZDKHelpCenterCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterCallback","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"role":"symbol","title":"ZDKHelpCenterProvider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider","type":"topic","navigatorTitle":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getAttachmentWithArticleId(_:withCallback:)":{"kind":"symbol","abstract":[{"text":"This method returns a list of attachments for a single article.","type":"text"}],"title":"getAttachmentWithArticleId(_:withCallback:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"getAttachmentWithArticleId:withCallback:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAttachmentWithArticleId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallback"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getattachmentwitharticleid(_:withcallback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getAttachmentWithArticleId(_:withCallback:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"getAttachmentWithArticleId:withCallback:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getAttachmentWithArticleId:withCallback:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"getAttachmentWithArticleId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"articleId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCallback:"},{"text":"(","kind":"text"},{"text":"ZDKHelpCenterCallback","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"kind":"text","text":") "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/title","op":"replace","value":"ZDKHelpCenterCallback"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/fragments","value":[{"text":"ZDKHelpCenterCallback","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title","op":"replace","value":"ZDKHelpCenterProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getAttachmentWithArticleId(_:withCallback:)\/title","op":"replace","value":"getAttachmentWithArticleId:withCallback:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getAttachmentWithArticleId:withCallback:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getAttachmentWithArticleId(_:withCallback:)\/fragments"}]}]}