{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/searchforarticles(usingquery:withcallback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/searchforarticles(usingquery:withcallback:)"]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/searchForArticles(usingQuery:withCallback:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"searchForArticles"},{"kind":"text","text":"("},{"text":"usingQuery","kind":"externalParam"},{"kind":"text","text":" "},{"text":"query","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The query text used to perform the search","type":"text"}]}],"name":"query"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback which will be called upon a successful or an erroneous response."}]}],"name":"callback"}]}],"abstract":[{"text":"This method will search articles in your Help Center.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method will also sideload categories, sections and users."}],"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"searchForArticlesUsingQuery:withCallback:"}],"roleHeading":"Instance Method","title":"searchForArticles(usingQuery:withCallback:)","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"searchForArticles"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"usingQuery"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withCallback"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"externalID":"c:objc(cs)ZDKHelpCenterProvider(im)searchForArticlesUsingQuery:withCallback:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"role":"symbol","title":"ZDKHelpCenterProvider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterProvider"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider","type":"topic","navigatorTitle":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/searchForArticles(usingQuery:withCallback:)":{"abstract":[{"type":"text","text":"This method will search articles in your Help Center."},{"text":" ","type":"text"},{"type":"text","text":"This method will also sideload categories, sections and users."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"searchForArticlesUsingQuery:withCallback:"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/searchforarticles(usingquery:withcallback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/searchForArticles(usingQuery:withCallback:)","type":"topic","title":"searchForArticles(usingQuery:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"searchForArticles","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"usingQuery"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCallback":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercallback","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterCallback"}],"type":"topic","abstract":[{"type":"text","text":"Callback block."}],"title":"ZDKHelpCenterCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterCallback","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"searchForArticlesUsingQuery:withCallback:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"searchForArticlesUsingQuery:withCallback:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"searchForArticlesUsingQuery:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"query"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCallback:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title","op":"replace","value":"ZDKHelpCenterProvider"},{"value":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1searchForArticles(usingQuery:withCallback:)\/title","value":"searchForArticlesUsingQuery:withCallback:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1searchForArticles(usingQuery:withCallback:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"searchForArticlesUsingQuery:withCallback:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/title","value":"ZDKHelpCenterCallback"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterCallback"}],"op":"replace"}]}]}