{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption"]]},"abstract":[{"type":"text","text":"Option Value, passed to zendesk server"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"! { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/value"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldoption\/value"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldoption\/value"]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"value","kind":"identifier"}],"title":"value","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","externalID":"c:objc(cs)ZDKTicketFieldOption(py)value","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"roleHeading":"Instance Property"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldOption":{"abstract":[{"type":"text","text":"Ticket Field Option (for ZDKTicketFieldTypeTagger ticket field types)"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldOption","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldOption"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldoption","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption","kind":"symbol","title":"ZDKTicketFieldOption","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldOption/value":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}],"title":"value","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldOption\/value","url":"\/documentation\/supportproviderssdk\/zdkticketfieldoption\/value","abstract":[{"type":"text","text":"Option Value, passed to zendesk server"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"value","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"value"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"value","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption\/title","value":"ZDKTicketFieldOption","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldOption"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1value\/title","op":"replace","value":"value"},{"value":[{"text":"value","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldOption~1value\/fragments"}]}]}