{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle"]]},"sections":[],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"id","kind":"identifier"}],"title":"id","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","externalID":"c:objc(cs)ZDKHelpCenterSimpleArticle(py)id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The article ID."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle\/id"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle\/id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle\/id"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSimpleArticle":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle","navigatorTitle":[{"text":"ZDKHelpCenterSimpleArticle","kind":"identifier"}],"title":"ZDKHelpCenterSimpleArticle","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterSimpleArticle"}],"type":"topic","abstract":[{"type":"text","text":"This is a model object for a simple article returned by the suggested article provider"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterSimpleArticle/id":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterSimpleArticle\/id","navigatorTitle":[{"text":"id","kind":"identifier"}],"title":"id","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"type":"topic","abstract":[{"text":"The article ID.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcentersimplearticle\/id"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"id","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"id","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle\/title","op":"replace","value":"ZDKHelpCenterSimpleArticle"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle\/fragments","op":"replace","value":[{"text":"ZDKHelpCenterSimpleArticle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle~1id\/title","value":"id"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterSimpleArticle~1id\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}