{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversationsSettings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ConversationsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettings","text":"ConversationsSettings"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkconversationssettingsprovider\/getconversationssettings(callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkconversationssettingsprovider\/getconversationssettings(callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKConversationsSettingsProvider\/getConversationsSettings(callback:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ConversationsSettingsProviderProtocol.getConversationsSettings(callback:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversationsSettings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ConversationsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettings"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"getConversationsSettings(callback:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettingsProvider(cm)getConversationsSettingsWithCallback:","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getConversationsSettingsWithCallback:"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKConversationsSettingsProvider"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKConversationsSettingsProvider/getConversationsSettings(callback:)":{"role":"symbol","title":"getConversationsSettings(callback:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversationsSettings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ConversationsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettings"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKConversationsSettingsProvider\/getConversationsSettings(callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getConversationsSettingsWithCallback:"}],"url":"\/documentation\/supportproviderssdk\/zdkconversationssettingsprovider\/getconversationssettings(callback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ConversationsSettings":{"role":"symbol","title":"ConversationsSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsSettings"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ConversationsSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationsSettings"}],"url":"\/documentation\/supportproviderssdk\/conversationssettings"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKConversationsSettingsProvider":{"role":"symbol","title":"ZDKConversationsSettingsProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationsSettingsProvider"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKConversationsSettingsProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationsSettingsProvider"}],"url":"\/documentation\/supportproviderssdk\/zdkconversationssettingsprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getConversationsSettingsWithCallback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getConversationsSettingsWithCallback:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getConversationsSettingsWithCallback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(ZDKConversationsSettings *)","preciseIdentifier":"c:BFv(#*$@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettings)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKConversationsSettingsProvider~1getConversationsSettings(callback:)\/title","value":"getConversationsSettingsWithCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKConversationsSettingsProvider~1getConversationsSettings(callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getConversationsSettingsWithCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ConversationsSettings\/title","value":"ZDKConversationsSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ConversationsSettings\/fragments","value":[{"kind":"identifier","text":"ZDKConversationsSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKConversationsSettingsProvider\/title","value":"ZDKConversationsSettingsProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKConversationsSettingsProvider\/fragments","value":[{"kind":"identifier","text":"ZDKConversationsSettingsProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}