{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/createCategoryLookup(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Parses a json array of Help Center categories."}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/createcategorylookup(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/createcategorylookup(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:objc(cs)ZDKHelpCenterParser(cm)createCategoryLookup:","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createCategoryLookup","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!","kind":"text"}],"roleHeading":"Type Method","title":"createCategoryLookup(_:)","navigatorTitle":[{"text":"createCategoryLookup:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createCategoryLookup","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"categories","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!) -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary of ZDKHelpCenterCategory objects with categoryId pointers."}]}],"kind":"content"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser":{"abstract":[{"type":"text","text":"A Help Center Parser class containing static and instance methods to parse json to objects."}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterParser"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterParser","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser","title":"ZDKHelpCenterParser","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser/createCategoryLookup(_:)":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/createCategoryLookup(_:)","kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/createcategorylookup(_:)","navigatorTitle":[{"kind":"identifier","text":"createCategoryLookup:"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createCategoryLookup","kind":"identifier"},{"kind":"text","text":"(["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!) -> ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"title":"createCategoryLookup(_:)","abstract":[{"text":"Parses a json array of Help Center categories.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"createCategoryLookup:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createCategoryLookup:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"createCategoryLookup:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"kind":"text","text":" *) "},{"text":"categories","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"ZDKHelpCenterParser","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterParser"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser\/fragments"},{"value":"createCategoryLookup:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1createCategoryLookup(_:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createCategoryLookup:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1createCategoryLookup(_:)\/fragments","op":"replace"}]}]}