{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseFlatArticles(_:)"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Parses a collection of Help Center json article objects, section objects and category objects","type":"text"},{"text":" ","type":"text"},{"text":"into a FlatArticle objects and puts them in alphabetical order.","type":"text"}],"metadata":{"title":"parseFlatArticles(_:)","navigatorTitle":[{"text":"parseFlatArticles:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)ZDKHelpCenterParser(im)parseFlatArticles:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parseFlatArticles"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> ["},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"SupportProvidersSDK"}]},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/parseflatarticles(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/parseflatarticles(_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parseFlatArticles"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"json","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!) -> [","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of ZDKHelpCenterFlatArticle objects."}]}]}],"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser/parseFlatArticles(_:)":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser\/parseFlatArticles(_:)","kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser\/parseflatarticles(_:)","navigatorTitle":[{"text":"parseFlatArticles:","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parseFlatArticles"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!) -> ["},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"title":"parseFlatArticles(_:)","abstract":[{"text":"Parses a collection of Help Center json article objects, section objects and category objects","type":"text"},{"type":"text","text":" "},{"type":"text","text":"into a FlatArticle objects and puts them in alphabetical order."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterParser":{"abstract":[{"type":"text","text":"A Help Center Parser class containing static and instance methods to parse json to objects."}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterParser"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterParser","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterparser","title":"ZDKHelpCenterParser","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterParser"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"parseFlatArticles:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"parseFlatArticles:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"parseFlatArticles:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseFlatArticles(_:)\/title","value":"parseFlatArticles:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser~1parseFlatArticles(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"parseFlatArticles:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser\/title","value":"ZDKHelpCenterParser"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterParser\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterParser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}