{"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getAttachmentSettings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettings","text":"AttachmentSettings"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"roleHeading":"Type Method","role":"symbol","title":"getAttachmentSettings(callback:)","navigatorTitle":[{"kind":"identifier","text":"getAttachmentSettingsWithCallback:"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettingsProvider(cm)getAttachmentSettingsWithCallback:"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachmentSettingsProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAttachmentSettings"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings","text":"AttachmentSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettings"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachmentSettingsProvider\/getAttachmentSettings(callback:)"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkattachmentsettingsprovider\/getattachmentsettings(callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkattachmentsettingsprovider\/getattachmentsettings(callback:)"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachmentSettingsProvider/getAttachmentSettings(callback:)":{"kind":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAttachmentSettings","kind":"identifier"},{"kind":"text","text":"("},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettings","text":"AttachmentSettings"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"url":"\/documentation\/supportproviderssdk\/zdkattachmentsettingsprovider\/getattachmentsettings(callback:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachmentSettingsProvider\/getAttachmentSettings(callback:)","type":"topic","title":"getAttachmentSettings(callback:)","role":"symbol","navigatorTitle":[{"text":"getAttachmentSettingsWithCallback:","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/AttachmentSettings":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentSettings"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings","url":"\/documentation\/supportproviderssdk\/attachmentsettings","title":"AttachmentSettings","abstract":[],"type":"topic","navigatorTitle":[{"text":"AttachmentSettings","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachmentSettingsProvider":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAttachmentSettingsProvider","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"title":"ZDKAttachmentSettingsProvider","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachmentSettingsProvider","navigatorTitle":[{"kind":"identifier","text":"ZDKAttachmentSettingsProvider"}],"url":"\/documentation\/supportproviderssdk\/zdkattachmentsettingsprovider"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"getAttachmentSettingsWithCallback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getAttachmentSettingsWithCallback:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"getAttachmentSettingsWithCallback:"},{"text":"(","kind":"text"},{"text":"void (^)(ZDKAttachmentSettings *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettings)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"getAttachmentSettingsWithCallback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachmentSettingsProvider~1getAttachmentSettings(callback:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"getAttachmentSettingsWithCallback:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachmentSettingsProvider~1getAttachmentSettings(callback:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings\/title","value":"ZDKAttachmentSettings"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKAttachmentSettings"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachmentSettingsProvider\/title","op":"replace","value":"ZDKAttachmentSettingsProvider"},{"value":[{"kind":"identifier","text":"ZDKAttachmentSettingsProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachmentSettingsProvider\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}