{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/attachmentsettings\/enabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/attachmentsettings\/enabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings\/enabled","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"enabled","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettings(py)enabled","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"enabled"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/AttachmentSettings":{"role":"symbol","title":"AttachmentSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentSettings"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AttachmentSettings"}],"url":"\/documentation\/supportproviderssdk\/attachmentsettings"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/AttachmentSettings/enabled":{"role":"symbol","title":"enabled","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings\/enabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enabled"}],"url":"\/documentation\/supportproviderssdk\/attachmentsettings\/enabled"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"enabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"enabled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings\/title","value":"ZDKAttachmentSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings\/fragments","value":[{"kind":"identifier","text":"ZDKAttachmentSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings~1enabled\/title","value":"enabled"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings~1enabled\/fragments","value":[{"kind":"identifier","text":"enabled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}