{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents\/commentingagents"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents\/commentingagents"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"commentingAgents"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKSupportUser","text":"ZDKSupportUser","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportUser","kind":"typeIdentifier"},{"kind":"text","text":"]! { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"commentingAgents"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commentingAgents","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKSupportUser","text":"ZDKSupportUser","kind":"typeIdentifier"},{"kind":"text","text":"]!"}],"modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Instance Property","title":"commentingAgents","symbolKind":"property","externalID":"c:objc(cs)ZDKRequestsWithCommentingAgents(py)commentingAgents"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/commentingAgents"},"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestsWithCommentingAgents/commentingAgents":{"url":"\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents\/commentingagents","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commentingAgents","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKSupportUser","text":"ZDKSupportUser"},{"kind":"text","text":"]!"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/commentingAgents","abstract":[],"title":"commentingAgents","role":"symbol","navigatorTitle":[{"text":"commentingAgents","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestsWithCommentingAgents":{"url":"\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestsWithCommentingAgents"}],"title":"ZDKRequestsWithCommentingAgents","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKSupportUser":{"url":"\/documentation\/supportproviderssdk\/zdksupportuser","title":"ZDKSupportUser","navigatorTitle":[{"text":"ZDKSupportUser","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKSupportUser","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportUser"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"commentingAgents","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"commentingAgents","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ZDKSupportUser *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"commentingAgents"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents~1commentingAgents\/title","op":"replace","value":"commentingAgents"},{"value":[{"kind":"identifier","text":"commentingAgents"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents~1commentingAgents\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents\/title","op":"replace","value":"ZDKRequestsWithCommentingAgents"},{"op":"replace","value":[{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportUser\/title","value":"ZDKSupportUser"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportUser\/fragments","value":[{"text":"ZDKSupportUser","kind":"identifier"}],"op":"replace"}]}]}