{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/init(requests:andCommentingAgents:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","navigatorTitle":[{"text":"initWithRequests:andCommentingAgents:","kind":"identifier"}],"title":"init(requests:andCommentingAgents:)","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","externalID":"c:objc(cs)ZDKRequestsWithCommentingAgents(im)initWithRequests:andCommentingAgents:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"requests"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKRequest","text":"ZDKRequest"},{"text":"]!, ","kind":"text"},{"text":"andCommentingAgents","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"ZDKSupportUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKSupportUser"},{"text":"]!)","kind":"text"}],"roleHeading":"Initializer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents\/init(requests:andcommentingagents:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents\/init(requests:andcommentingagents:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"!(","kind":"text"},{"kind":"externalParam","text":"requests"},{"text":": [","kind":"text"},{"text":"ZDKRequest","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","preciseIdentifier":"c:objc(cs)ZDKRequest"},{"text":"]!, ","kind":"text"},{"text":"andCommentingAgents","kind":"externalParam"},{"kind":"text","text":" "},{"text":"commentingAgents","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"ZDKSupportUser","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportUser","preciseIdentifier":"c:objc(cs)ZDKSupportUser","kind":"typeIdentifier"},{"text":"]!)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestsWithCommentingAgents/init(requests:andCommentingAgents:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithRequests:andCommentingAgents:","kind":"identifier"}],"title":"init(requests:andCommentingAgents:)","fragments":[{"kind":"identifier","text":"init"},{"text":"!(","kind":"text"},{"text":"requests","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"ZDKRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKRequest"},{"text":"]!, ","kind":"text"},{"text":"andCommentingAgents","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)ZDKSupportUser","text":"ZDKSupportUser","kind":"typeIdentifier"},{"text":"]!)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents\/init(requests:andCommentingAgents:)","url":"\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents\/init(requests:andcommentingagents:)","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKSupportUser":{"url":"\/documentation\/supportproviderssdk\/zdksupportuser","title":"ZDKSupportUser","navigatorTitle":[{"text":"ZDKSupportUser","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKSupportUser","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportUser"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequestsWithCommentingAgents":{"url":"\/documentation\/supportproviderssdk\/zdkrequestswithcommentingagents","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequestsWithCommentingAgents","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequestsWithCommentingAgents"}],"title":"ZDKRequestsWithCommentingAgents","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequest":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKRequest"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKRequest","kind":"identifier"}],"abstract":[{"type":"text","text":"Object representing a Zendesk end user request returned by the server."}],"kind":"symbol","title":"ZDKRequest","url":"\/documentation\/supportproviderssdk\/zdkrequest"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithRequests:andCommentingAgents:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRequests:andCommentingAgents:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithRequests:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<ZDKRequest *>"},{"text":" *) ","kind":"text"},{"text":"requests","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"andCommentingAgents:"},{"kind":"text","text":"("},{"text":"NSArray<ZDKSupportUser *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"commentingAgents","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents~1init(requests:andCommentingAgents:)\/title","op":"replace","value":"initWithRequests:andCommentingAgents:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithRequests:andCommentingAgents:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents~1init(requests:andCommentingAgents:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportUser\/title","value":"ZDKSupportUser"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportUser\/fragments","value":[{"text":"ZDKSupportUser","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents\/title","op":"replace","value":"ZDKRequestsWithCommentingAgents"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequestsWithCommentingAgents\/fragments","value":[{"text":"ZDKRequestsWithCommentingAgents","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/title","value":"ZDKRequest"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKRequest"}]}]}]}