{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage"]]},"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"extendedModule":"SupportProvidersSDK","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createFromRequest","kind":"identifier"},{"kind":"text","text":"("},{"text":"ZDKRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"readCommentCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","text":"RequestForStorage","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Type Method","title":"createFromRequest(_:readCommentCount:)","navigatorTitle":[{"text":"createFromRequest:readCommentCount:","kind":"identifier"}],"externalID":"c:@CM@SupportProvidersSDK@objc(cs)ZDKRequestForStorage(cm)createFromRequest:readCommentCount:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createFromRequest","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"request"},{"text":": ","kind":"text"},{"text":"ZDKRequest","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","preciseIdentifier":"c:objc(cs)ZDKRequest","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"readCommentCount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","text":"RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/requestforstorage\/createfromrequest(_:readcommentcount:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/requestforstorage\/createfromrequest(_:readcommentcount:)"]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/createFromRequest(_:readCommentCount:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage":{"title":"RequestForStorage","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestForStorage","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/supportproviderssdk\/requestforstorage","type":"topic","navigatorTitle":[{"text":"RequestForStorage","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage/createFromRequest(_:readCommentCount:)":{"title":"createFromRequest(_:readCommentCount:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createFromRequest","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)ZDKRequest","kind":"typeIdentifier","text":"ZDKRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"readCommentCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"createFromRequest:readCommentCount:"}],"role":"symbol","kind":"symbol","url":"\/documentation\/supportproviderssdk\/requestforstorage\/createfromrequest(_:readcommentcount:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage\/createFromRequest(_:readCommentCount:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKRequest":{"title":"ZDKRequest","navigatorTitle":[{"text":"ZDKRequest","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkrequest","abstract":[{"type":"text","text":"Object representing a Zendesk end user request returned by the server."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequest"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"createFromRequest:readCommentCount:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createFromRequest:readCommentCount:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","text":"ZDKRequestForStorage"},{"text":" *) ","kind":"text"},{"text":"createFromRequest:","kind":"identifier"},{"kind":"text","text":"("},{"text":"ZDKRequest","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKRequest","preciseIdentifier":"c:objc(cs)ZDKRequest","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"request"},{"text":" ","kind":"text"},{"text":"readCommentCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"readCommentCount","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/title","value":"ZDKRequestForStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/fragments","value":[{"kind":"identifier","text":"ZDKRequestForStorage"}]},{"value":"createFromRequest:readCommentCount:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage~1createFromRequest(_:readCommentCount:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage~1createFromRequest(_:readCommentCount:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createFromRequest:readCommentCount:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/title","value":"ZDKRequest","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKRequest\/fragments","op":"replace","value":[{"text":"ZDKRequest","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}