{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"title":"Support","role":"symbol","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Support"}],"navigatorTitle":[{"kind":"identifier","text":"Support"}],"symbolKind":"class","roleHeading":"Class"},"abstract":[{"text":"ZDKSupport is responsible for initialization of","type":"text"},{"type":"text","text":" "},{"text":"the SDK and manages the backend configuration.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKSupport) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Support","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/helpCenterLocaleOverride"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/refreshRequest(requestId:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/instance"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/initialize(withZendesk:)"]}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/support"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/support"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support/initialize(withZendesk:)":{"title":"initialize(withZendesk:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeWithZendesk:"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"withZendesk","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Zendesk","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"text":"?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/initialize(withZendesk:)","url":"\/documentation\/supportproviderssdk\/support\/initialize(withzendesk:)","abstract":[{"type":"text","text":"Initialize the Support singleton with the Zendesk singleton"},{"text":" ","type":"text"},{"text":"from ZendeskCoreSDK","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support/helpCenterLocaleOverride":{"title":"helpCenterLocaleOverride","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/helpCenterLocaleOverride","navigatorTitle":[{"kind":"identifier","text":"helpCenterLocaleOverride"}],"abstract":[{"text":"Locale override for help center","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"helpCenterLocaleOverride","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/support\/helpcenterlocaleoverride"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support":{"url":"\/documentation\/supportproviderssdk\/support","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support","abstract":[{"type":"text","text":"ZDKSupport is responsible for initialization of"},{"type":"text","text":" "},{"type":"text","text":"the SDK and manages the backend configuration."}],"kind":"symbol","role":"symbol","title":"Support","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Support","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Support","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support/instance":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"instance"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport","kind":"typeIdentifier","text":"Support"},{"kind":"text","text":"?"}],"url":"\/documentation\/supportproviderssdk\/support\/instance","abstract":[{"text":"Get the API instance (singleton).","type":"text"}],"title":"instance","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/instance","type":"topic","role":"symbol","navigatorTitle":[{"text":"instance","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/Support/refreshRequest(requestId:)":{"role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/support\/refreshrequest(requestid:)","kind":"symbol","title":"refreshRequest(requestId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"refreshRequestWithRequestId:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/refreshRequest(requestId:)","abstract":[{"type":"text","text":"This method can be used to aid in handling push notifications relating to requests."},{"type":"text","text":" "},{"type":"text","text":"This method can result in a dynamic update in the request UI. For this occur,"},{"type":"text","text":" "},{"type":"text","text":"the push notification and the on screen request must contain matching request ids."},{"text":" ","type":"text"},{"text":"This method will return true only in the case of a successful UI update.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A return value of false means that the push notification was unhandled."},{"type":"text","text":" "},{"type":"text","text":"At this point you can decided how best to update the user based on the contents of the notification."}]},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKSupport"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKSupport"}]},{"value":[{"kind":"identifier","text":"ZDKSupport"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/helpCenterLocaleOverride"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/refreshRequest(requestId:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/instance"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/Support\/initialize(withZendesk:)"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKSupport","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1initialize(withZendesk:)\/title","value":"initializeWithZendesk:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1initialize(withZendesk:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"initializeWithZendesk:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1helpCenterLocaleOverride\/title","value":"helpCenterLocaleOverride","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1helpCenterLocaleOverride\/fragments","value":[{"text":"helpCenterLocaleOverride","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support\/title","op":"replace","value":"ZDKSupport"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support\/fragments","value":[{"kind":"identifier","text":"ZDKSupport"}],"op":"replace"},{"op":"replace","value":"instance","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1instance\/title"},{"value":[{"kind":"identifier","text":"instance"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1instance\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1refreshRequest(requestId:)\/title","value":"refreshRequestWithRequestId:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"refreshRequestWithRequestId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1Support~1refreshRequest(requestId:)\/fragments"}]}]}