{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_SearchSuccess","interfaceLanguage":"swift"},"metadata":{"symbolKind":"var","externalID":"c:@ZD_HC_SearchSuccess","role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"ZD_HC_SearchSuccess","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZD_HC_SearchSuccess"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"roleHeading":"Global Variable","title":"ZD_HC_SearchSuccess"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"sections":[],"abstract":[{"type":"text","text":"Notification that help center search results have been successfully retrieved."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zd_hc_searchsuccess"]},{"paths":["\/documentation\/supportproviderssdk\/zd_hc_searchsuccess"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZD_HC_SearchSuccess"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZD_HC_SearchSuccess":{"kind":"symbol","role":"symbol","url":"\/documentation\/supportproviderssdk\/zd_hc_searchsuccess","navigatorTitle":[{"text":"ZD_HC_SearchSuccess","kind":"identifier"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZD_HC_SearchSuccess","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_SearchSuccess","abstract":[{"type":"text","text":"Notification that help center search results have been successfully retrieved."}],"title":"ZD_HC_SearchSuccess"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"value":"ZD_HC_SearchSuccess","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZD_HC_SearchSuccess","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZD_HC_SearchSuccess"}],"languages":["occ"]}]}},{"value":"ZD_HC_SearchSuccess","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_SearchSuccess\/title"},{"value":[{"text":"ZD_HC_SearchSuccess","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_SearchSuccess\/fragments","op":"replace"}]}]}