{"metadata":{"roleHeading":"Global Variable","title":"ZD_HC_VoteDeleteStarting","role":"symbol","externalID":"c:@ZD_HC_VoteDeleteStarting","symbolKind":"var","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZD_HC_VoteDeleteStarting"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"ZD_HC_VoteDeleteStarting","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_VoteDeleteStarting"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZD_HC_VoteDeleteStarting","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zd_hc_votedeletestarting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zd_hc_votedeletestarting"]}],"abstract":[{"text":"Notification that a Help Center vote deletion request started","type":"text"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZD_HC_VoteDeleteStarting":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZD_HC_VoteDeleteStarting"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZD_HC_VoteDeleteStarting","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZD_HC_VoteDeleteStarting"}],"url":"\/documentation\/supportproviderssdk\/zd_hc_votedeletestarting","type":"topic","role":"symbol","title":"ZD_HC_VoteDeleteStarting","abstract":[{"type":"text","text":"Notification that a Help Center vote deletion request started"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"value":"ZD_HC_VoteDeleteStarting","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZD_HC_VoteDeleteStarting"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZD_HC_VoteDeleteStarting"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZD_HC_VoteDeleteStarting","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_VoteDeleteStarting\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZD_HC_VoteDeleteStarting\/fragments","op":"replace","value":[{"text":"ZD_HC_VoteDeleteStarting","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}