{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDD_MIMETypeJPEG"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ZDD_MIMETypeJPEG","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/supportproviderssdk\/zdd_mimetypejpeg"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdd_mimetypejpeg"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"ZDD_MIMETypeJPEG"}],"modules":[{"name":"SupportProvidersSDK"}],"title":"ZDD_MIMETypeJPEG","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDD_MIMETypeJPEG"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"roleHeading":"Global Variable","externalID":"c:@ZDD_MIMETypeJPEG"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDD_MIMETypeJPEG":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDD_MIMETypeJPEG"}],"role":"symbol","title":"ZDD_MIMETypeJPEG","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDD_MIMETypeJPEG","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/supportproviderssdk\/zdd_mimetypejpeg","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDD_MIMETypeJPEG"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"ZDD_MIMETypeJPEG"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ZDD_MIMETypeJPEG"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"text":"ZDD_MIMETypeJPEG","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDD_MIMETypeJPEG\/title","value":"ZDD_MIMETypeJPEG"},{"value":[{"text":"ZDD_MIMETypeJPEG","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDD_MIMETypeJPEG\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}