{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"typealias","externalID":"c:ZDKAttachmentProvider.h@T@ZDKAvatarCallback","title":"ZDKAvatarCallback","role":"symbol","roleHeading":"Type Alias","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAvatarCallback"}],"navigatorTitle":[{"text":"ZDKAvatarCallback","kind":"identifier"}]},"abstract":[{"type":"text","text":"Block invoked to pass data back from API call"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAvatarCallback"},{"kind":"text","text":" = ("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"avatar","content":[{"inlineContent":[{"type":"text","text":"UIImage of the response from server, can be nil on error"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"NSError returned on during error state, can be nil on success","type":"text"}]}],"name":"error"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAvatarCallback"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkavatarcallback"]},{"paths":["\/documentation\/supportproviderssdk\/zdkavatarcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAvatarCallback":{"title":"ZDKAvatarCallback","kind":"symbol","navigatorTitle":[{"text":"ZDKAvatarCallback","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAvatarCallback","role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkavatarcallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAvatarCallback","kind":"identifier"}],"abstract":[{"text":"Block invoked to pass data back from API call","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"ZDKAvatarCallback","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAvatarCallback"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKAvatarCallback"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(UIImage *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"text":"ZDKAvatarCallback","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAvatarCallback\/title","value":"ZDKAvatarCallback"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAvatarCallback\/fragments","op":"replace","value":[{"text":"ZDKAvatarCallback","kind":"identifier"}]}]}]}