{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDKAPI_GetUserFieldsFailure","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_GetUserFieldsFailure"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_getuserfieldsfailure"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkapi_getuserfieldsfailure"]}],"abstract":[{"text":"Notification that a request to get user fields has failed.","type":"text"}],"metadata":{"externalID":"c:@ZDKAPI_GetUserFieldsFailure","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Global Variable","symbolKind":"var","navigatorTitle":[{"text":"ZDKAPI_GetUserFieldsFailure","kind":"identifier"}],"role":"symbol","title":"ZDKAPI_GetUserFieldsFailure","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAPI_GetUserFieldsFailure"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPI_GetUserFieldsFailure":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAPI_GetUserFieldsFailure","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_GetUserFieldsFailure","kind":"symbol","navigatorTitle":[{"text":"ZDKAPI_GetUserFieldsFailure","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkapi_getuserfieldsfailure","type":"topic","role":"symbol","title":"ZDKAPI_GetUserFieldsFailure","abstract":[{"type":"text","text":"Notification that a request to get user fields has failed."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKAPI_GetUserFieldsFailure"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKAPI_GetUserFieldsFailure","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"text":"ZDKAPI_GetUserFieldsFailure","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_GetUserFieldsFailure\/title","op":"replace","value":"ZDKAPI_GetUserFieldsFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_GetUserFieldsFailure\/fragments","value":[{"kind":"identifier","text":"ZDKAPI_GetUserFieldsFailure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}