{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkapi_uploadattachmentstarting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkapi_uploadattachmentstarting"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Notification that an upload attachment request has started."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_UploadAttachmentStarting"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_UploadAttachmentStarting"},"sections":[],"metadata":{"symbolKind":"var","roleHeading":"Global Variable","navigatorTitle":[{"text":"ZDKAPI_UploadAttachmentStarting","kind":"identifier"}],"externalID":"c:@ZDKAPI_UploadAttachmentStarting","modules":[{"name":"SupportProvidersSDK"}],"title":"ZDKAPI_UploadAttachmentStarting","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKAPI_UploadAttachmentStarting"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAPI_UploadAttachmentStarting":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAPI_UploadAttachmentStarting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKAPI_UploadAttachmentStarting"}],"abstract":[{"text":"Notification that an upload attachment request has started.","type":"text"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkapi_uploadattachmentstarting","title":"ZDKAPI_UploadAttachmentStarting","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAPI_UploadAttachmentStarting"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"path":"\/metadata\/title","value":"ZDKAPI_UploadAttachmentStarting","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"value":[{"kind":"identifier","text":"ZDKAPI_UploadAttachmentStarting"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAPI_UploadAttachmentStarting","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_UploadAttachmentStarting\/title","value":"ZDKAPI_UploadAttachmentStarting","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAPI_UploadAttachmentStarting\/fragments","value":[{"text":"ZDKAPI_UploadAttachmentStarting","kind":"identifier"}],"op":"replace"}]}]}