{"kind":"symbol","abstract":[{"text":"Model which allows customizations on the content displayed by Help Center.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:objc(cs)ZDKHelpCenterOverviewContentModel","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Class","title":"ZDKHelpCenterOverviewContentModel","navigatorTitle":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterOverviewContentModel"}],"symbolKind":"class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/groupIds","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/groupType","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/hideContactSupport","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/labels","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/navBarConversationsUIType"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/defaultContent()"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel/labels":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"labels","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"text":"A list of lables to which must be present for an article to show up in the list.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/labels","navigatorTitle":[{"text":"labels","kind":"identifier"}],"kind":"symbol","title":"labels","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/labels","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel","kind":"symbol","abstract":[{"type":"text","text":"Model which allows customizations on the content displayed by Help Center."}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel","title":"ZDKHelpCenterOverviewContentModel"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel/hideContactSupport":{"abstract":[{"type":"text","text":"Hide the "},{"code":"Contact Support","type":"codeVoice"},{"text":" button that is displayed upon an empty search in Help Center","type":"text"}],"title":"hideContactSupport","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hideContactSupport","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"hideContactSupport","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/hideContactSupport","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/hidecontactsupport","type":"topic","kind":"symbol","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel/groupIds":{"role":"symbol","navigatorTitle":[{"text":"groupIds","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"groupIds","kind":"identifier"},{"kind":"text","text":": ["},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]!","kind":"text"}],"type":"topic","kind":"symbol","title":"groupIds","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/groupIds","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/groupids","abstract":[{"type":"text","text":"A list of ids. Only show articles contained in the categorys\/sections."}]},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel/defaultContent()":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultContent","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Self","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"defaultContent","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/defaultcontent()","kind":"symbol","abstract":[{"type":"text","text":"Returns a default model which will fetch all Help Center content for the current locale."},{"type":"text","text":" "},{"type":"text","text":"To customise the content, update propertys on a default model."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/defaultContent()","type":"topic","title":"defaultContent()"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel/groupType":{"abstract":[{"text":"The type of ids being used.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"groupType"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@ZDKHelpCenterOverviewGroupType","kind":"typeIdentifier","text":"ZDKHelpCenterOverviewGroupType"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/groupType","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/grouptype","type":"topic","title":"groupType"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel/navBarConversationsUIType":{"deprecated":true,"type":"topic","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/navbarconversationsuitype","title":"navBarConversationsUIType","abstract":[{"type":"text","text":"Use text or an icon in the right nav bar button."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navBarConversationsUIType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@ZDKNavBarConversationsUIType","text":"ZDKNavBarConversationsUIType","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/navBarConversationsUIType","kind":"symbol","navigatorTitle":[{"text":"navBarConversationsUIType","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKHelpCenterOverviewContentModel","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/groupIds","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/groupType","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/hideContactSupport","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/labels","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/navBarConversationsUIType"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/defaultContent()"],"title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"]}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterOverviewContentModel"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1labels\/title","value":"labels"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1labels\/fragments","value":[{"kind":"identifier","text":"labels"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/title","value":"ZDKHelpCenterOverviewContentModel"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/fragments","value":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1hideContactSupport\/title","value":"hideContactSupport","op":"replace"},{"op":"replace","value":[{"text":"hideContactSupport","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1hideContactSupport\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1groupIds\/title","value":"groupIds","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1groupIds\/fragments","op":"replace","value":[{"kind":"identifier","text":"groupIds"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1defaultContent()\/title","value":"defaultContent"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1defaultContent()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"defaultContent"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1groupType\/title","value":"groupType","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1groupType\/fragments","value":[{"text":"groupType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1navBarConversationsUIType\/title","value":"navBarConversationsUIType"},{"value":[{"text":"navBarConversationsUIType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1navBarConversationsUIType\/fragments","op":"replace"}]}]}