{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype"]}],"abstract":[{"text":"Used to specify what type of ids will be supplied.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/category","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/default","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/section"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/init(rawValue:)"]},{"generated":true,"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/Equatable-Implementations","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}],"title":"ZDKHelpCenterOverviewGroupType","externalID":"c:@E@ZDKHelpCenterOverviewGroupType","role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupType"}],"roleHeading":"Enumeration","symbolKind":"enum"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH","doc:\/\/com.zendesk.SupportProvidersSDK\/SY","doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType/section":{"navigatorTitle":[{"text":"ZDKHelpCenterOverviewGroupTypeSection","kind":"identifier"}],"role":"symbol","title":"ZDKHelpCenterOverviewGroupType.section","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/section","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/section","abstract":[{"text":"Used to specify that section ids are being used.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"section"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType/category":{"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/category","type":"topic","title":"ZDKHelpCenterOverviewGroupType.category","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"category"}],"role":"symbol","abstract":[{"type":"text","text":"Used to specify that category ids are being used."}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupTypeCategory"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/category"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType":{"abstract":[{"text":"Used to specify what type of ids will be supplied.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype","type":"topic","title":"ZDKHelpCenterOverviewGroupType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/rawrepresentable-implementations","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/RawRepresentable-Implementations","type":"topic","abstract":[],"title":"RawRepresentable Implementations"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType/default":{"type":"topic","navigatorTitle":[{"text":"ZDKHelpCenterOverviewGroupTypeDefault","kind":"identifier"}],"abstract":[{"type":"text","text":"This default results in every category and seciton being fetched."}],"kind":"symbol","title":"ZDKHelpCenterOverviewGroupType.default","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/default","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`default`"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/default"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.SupportProvidersSDK/s8SendableP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/SY":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType/init(rawValue:)":{"title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/init(rawValue:)","role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewGroupType/Equatable-Implementations":{"role":"collectionGroup","type":"topic","kind":"article","title":"Equatable Implementations","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/Equatable-Implementations","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewgrouptype\/equatable-implementations","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKHelpCenterOverviewGroupType"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/category","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/default","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewGroupType\/section"]}],"op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1section\/title","value":"ZDKHelpCenterOverviewGroupTypeSection","op":"replace"},{"op":"replace","value":[{"text":"ZDKHelpCenterOverviewGroupTypeSection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1section\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1category\/title","value":"ZDKHelpCenterOverviewGroupTypeCategory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1category\/fragments","value":[{"text":"ZDKHelpCenterOverviewGroupTypeCategory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType\/title","value":"ZDKHelpCenterOverviewGroupType","op":"replace"},{"op":"replace","value":[{"text":"ZDKHelpCenterOverviewGroupType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1default\/title","value":"ZDKHelpCenterOverviewGroupTypeDefault","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewGroupType~1default\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterOverviewGroupTypeDefault"}]}]}]}