{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/image","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/localizedLabel","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/none"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/Equatable-Implementations","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH","doc:\/\/com.zendesk.SupportProvidersSDK\/SY","doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP"],"title":"Conforms To","kind":"relationships"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"abstract":[{"type":"text","text":"Enum to describe the types of nav bar button that display conversations."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKNavBarConversationsUIType"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@E@ZDKNavBarConversationsUIType","symbolKind":"enum","title":"ZDKNavBarConversationsUIType","navigatorTitle":[{"text":"ZDKNavBarConversationsUIType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKNavBarConversationsUIType","kind":"identifier"}],"roleHeading":"Enumeration","modules":[{"name":"SupportProvidersSDK"}],"role":"symbol"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType/image":{"url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/image","title":"ZDKNavBarConversationsUIType.image","navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeImage"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/image","role":"symbol","abstract":[{"text":"Nav bar button with image for conversations.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/s8SendableP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType/localizedLabel":{"title":"ZDKNavBarConversationsUIType.localizedLabel","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/localizedLabel","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedLabel","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeLocalizedLabel"}],"url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/localizedlabel","type":"topic","role":"symbol","abstract":[{"text":"Nav bar button with localized label for conversations.","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType/Equatable-Implementations":{"abstract":[],"kind":"article","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/Equatable-Implementations","type":"topic","url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/equatable-implementations"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType":{"abstract":[{"type":"text","text":"Enum to describe the types of nav bar button that display conversations."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKNavBarConversationsUIType"}],"kind":"symbol","title":"ZDKNavBarConversationsUIType","url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype","navigatorTitle":[{"text":"ZDKNavBarConversationsUIType","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType/none":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/none","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ZDKNavBarConversationsUITypeNone","kind":"identifier"}],"abstract":[{"text":"No conversations nav bar in Help Center.","type":"text"}],"title":"ZDKNavBarConversationsUIType.none","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/none"},"doc://com.zendesk.SupportProvidersSDK/SY":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/rawrepresentable-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/RawRepresentable-Implementations"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/init(rawvalue:)","type":"topic","role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ZDKNavBarConversationsUIType","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ZDKNavBarConversationsUIType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKNavBarConversationsUIType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/image","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/localizedLabel","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/none"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKNavBarConversationsUIType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1image\/title","value":"ZDKNavBarConversationsUITypeImage"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1image\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeImage"}]},{"op":"replace","value":"ZDKNavBarConversationsUITypeLocalizedLabel","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1localizedLabel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1localizedLabel\/fragments","value":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeLocalizedLabel"}]},{"op":"replace","value":"ZDKNavBarConversationsUIType","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKNavBarConversationsUIType"}]},{"value":"ZDKNavBarConversationsUITypeNone","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1none\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1none\/fragments","value":[{"text":"ZDKNavBarConversationsUITypeNone","kind":"identifier"}],"op":"replace"}]}]}