{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType","interfaceLanguage":"swift"},"abstract":[{"text":"Ticket field type","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKTicketFieldType"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Enumeration","navigatorTitle":[{"text":"ZDKTicketFieldType","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKTicketFieldType"}],"modules":[{"name":"SupportProvidersSDK"}],"title":"ZDKTicketFieldType","symbolKind":"enum","externalID":"c:@E@ZDKTicketFieldType"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkticketfieldtype"]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/checkbox","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/comboBox","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/creditCard","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/date","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/decimal","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/description","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/integer","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/multiSelect","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/priority","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/regex","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/status","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/subject","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/text","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/textArea","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/ticketType","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/Equatable-Implementations","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH","doc:\/\/com.zendesk.SupportProvidersSDK\/SY","doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/priority":{"type":"topic","kind":"symbol","title":"ZDKTicketFieldType.priority","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"priority"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/priority","abstract":[{"type":"text","text":"Ticket field priority system type"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/priority","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldTypePriority"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/description":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"}],"kind":"symbol","abstract":[{"text":"Ticket field regular expression type","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/description","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/description","navigatorTitle":[{"text":"ZDKTicketFieldTypeDescription","kind":"identifier"}],"role":"symbol","title":"ZDKTicketFieldType.description"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/textArea":{"title":"ZDKTicketFieldType.textArea","kind":"symbol","navigatorTitle":[{"text":"ZDKTicketFieldTypeTextArea","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/textArea","role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/textarea","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textArea","kind":"identifier"}],"abstract":[{"text":"Ticket field text area type that allows multi-line text","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType":{"role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype","kind":"symbol","title":"ZDKTicketFieldType","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType","abstract":[{"type":"text","text":"Ticket field type"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldType"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/checkbox":{"kind":"symbol","abstract":[{"text":"Ticket field check box type","type":"text"}],"role":"symbol","title":"ZDKTicketFieldType.checkbox","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkbox"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldTypeCheckbox"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/checkbox","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/checkbox"},"doc://com.zendesk.SupportProvidersSDK/SY":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/Equatable-Implementations":{"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/Equatable-Implementations","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/equatable-implementations","abstract":[],"title":"Equatable Implementations"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/date":{"abstract":[{"text":"Ticket field date selection type","type":"text"}],"title":"ZDKTicketFieldType.date","kind":"symbol","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/date","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/date","type":"topic","navigatorTitle":[{"text":"ZDKTicketFieldTypeDate","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"date"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/subject":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"subject","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/subject","abstract":[{"type":"text","text":"Ticket field regular expression type"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/subject","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldTypeSubject"}],"role":"symbol","title":"ZDKTicketFieldType.subject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/integer":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"integer"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/integer","type":"topic","navigatorTitle":[{"text":"ZDKTicketFieldTypeInteger","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/integer","abstract":[{"text":"Ticket field integer box type","type":"text"}],"title":"ZDKTicketFieldType.integer"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/creditCard":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCard"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/creditCard","type":"topic","navigatorTitle":[{"text":"ZDKTicketFieldTypeCreditCard","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/creditcard","abstract":[{"text":"Ticket field credit card type","type":"text"}],"title":"ZDKTicketFieldType.creditCard"},"doc://com.zendesk.SupportProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/init(rawValue:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/init(rawValue:)","type":"topic","title":"init(rawValue:)","abstract":[],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/init(rawvalue:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/multiSelect":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multiSelect"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/multiselect","type":"topic","abstract":[{"text":"Ticket field ticket system type","type":"text"}],"title":"ZDKTicketFieldType.multiSelect","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/multiSelect","navigatorTitle":[{"text":"ZDKTicketFieldTypeMultiSelect","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/status":{"role":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/status","abstract":[{"type":"text","text":"Ticket field status system type"}],"kind":"symbol","navigatorTitle":[{"text":"ZDKTicketFieldTypeStatus","kind":"identifier"}],"title":"ZDKTicketFieldType.status","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/status","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/ticketType":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/ticketType","type":"topic","kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/tickettype","title":"ZDKTicketFieldType.ticketType","navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldTypeTicketType"}],"abstract":[{"type":"text","text":"Ticket field ticket system type"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ticketType"}],"role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/decimal":{"kind":"symbol","navigatorTitle":[{"text":"ZDKTicketFieldTypeDecimal","kind":"identifier"}],"role":"symbol","title":"ZDKTicketFieldType.decimal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decimal"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/decimal","abstract":[{"type":"text","text":"Ticket field decimal box type"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/decimal"},"doc://com.zendesk.SupportProvidersSDK/s8SendableP":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/regex":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/regex","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/regex","abstract":[{"type":"text","text":"Ticket field regular expression type"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKTicketFieldTypeRegex"}],"title":"ZDKTicketFieldType.regex","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"regex"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/comboBox":{"title":"ZDKTicketFieldType.comboBox","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"comboBox"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/combobox","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKTicketFieldTypeComboBox","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/comboBox","role":"symbol","abstract":[{"text":"Ticket field combobox type (Combobox)","type":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/unknown":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/unknown","type":"topic","navigatorTitle":[{"text":"ZDKTicketFieldTypeUnknown","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/unknown","abstract":[{"text":"Ticket field unknown","type":"text"}],"title":"ZDKTicketFieldType.unknown"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/text":{"role":"symbol","abstract":[{"type":"text","text":"Ticket field text type that allows single-line text"}],"title":"ZDKTicketFieldType.text","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/text","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/text","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"text"}],"navigatorTitle":[{"text":"ZDKTicketFieldTypeText","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKTicketFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","url":"\/documentation\/supportproviderssdk\/zdkticketfieldtype\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/RawRepresentable-Implementations"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"ZDKTicketFieldType","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKTicketFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKTicketFieldType"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/checkbox","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/comboBox","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/creditCard","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/date","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/decimal","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/description","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/integer","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/multiSelect","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/priority","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/regex","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/status","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/subject","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/text","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/textArea","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/ticketType","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKTicketFieldType\/unknown"]}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKTicketFieldType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1priority\/title","value":"ZDKTicketFieldTypePriority"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1priority\/fragments","op":"replace","value":[{"text":"ZDKTicketFieldTypePriority","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1description\/title","op":"replace","value":"ZDKTicketFieldTypeDescription"},{"value":[{"text":"ZDKTicketFieldTypeDescription","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1description\/fragments"},{"value":"ZDKTicketFieldTypeTextArea","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1textArea\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1textArea\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKTicketFieldTypeTextArea"}]},{"value":"ZDKTicketFieldType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/title"},{"value":[{"kind":"identifier","text":"ZDKTicketFieldType"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType\/fragments"},{"value":"ZDKTicketFieldTypeCheckbox","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1checkbox\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1checkbox\/fragments","op":"replace","value":[{"text":"ZDKTicketFieldTypeCheckbox","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1date\/title","value":"ZDKTicketFieldTypeDate","op":"replace"},{"value":[{"text":"ZDKTicketFieldTypeDate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1date\/fragments","op":"replace"},{"op":"replace","value":"ZDKTicketFieldTypeSubject","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1subject\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1subject\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldTypeSubject"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1integer\/title","op":"replace","value":"ZDKTicketFieldTypeInteger"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1integer\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldTypeInteger"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1creditCard\/title","value":"ZDKTicketFieldTypeCreditCard"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1creditCard\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldTypeCreditCard"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1multiSelect\/title","value":"ZDKTicketFieldTypeMultiSelect","op":"replace"},{"op":"replace","value":[{"text":"ZDKTicketFieldTypeMultiSelect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1multiSelect\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1status\/title","value":"ZDKTicketFieldTypeStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1status\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldTypeStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1ticketType\/title","value":"ZDKTicketFieldTypeTicketType"},{"value":[{"text":"ZDKTicketFieldTypeTicketType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1ticketType\/fragments"},{"op":"replace","value":"ZDKTicketFieldTypeDecimal","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1decimal\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1decimal\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldTypeDecimal"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1regex\/title","value":"ZDKTicketFieldTypeRegex","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1regex\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldTypeRegex"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1comboBox\/title","value":"ZDKTicketFieldTypeComboBox","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1comboBox\/fragments","value":[{"text":"ZDKTicketFieldTypeComboBox","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1unknown\/title","value":"ZDKTicketFieldTypeUnknown","op":"replace"},{"value":[{"text":"ZDKTicketFieldTypeUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1unknown\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1text\/title","op":"replace","value":"ZDKTicketFieldTypeText"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKTicketFieldType~1text\/fragments","value":[{"kind":"identifier","text":"ZDKTicketFieldTypeText"}],"op":"replace"}]}]}