{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Get the help center css file in the host apps main bundle and return as a string."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkbundleutils\/userdefinedhelpcentercss()"]},{"paths":["\/documentation\/supportproviderssdk\/zdkbundleutils\/userdefinedhelpcentercss()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"userDefinedHelpCenterCss","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"A string containing css for help center."}],"type":"paragraph"}]},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"If you want your own style sheet for help center include a file named","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"help_center_article_style.css in your project and ensure it’s included in the"},{"text":" ","type":"text"},{"type":"text","text":"Copy Bundle Resources build phase."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/userDefinedHelpCenterCss()","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","symbolKind":"method","title":"userDefinedHelpCenterCss()","externalID":"c:objc(cs)ZDKBundleUtils(cm)userDefinedHelpCenterCss","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userDefinedHelpCenterCss","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"userDefinedHelpCenterCss","kind":"identifier"}],"roleHeading":"Type Method"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils":{"abstract":[{"type":"text","text":"Util for working with SupportSDK bundles."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils","type":"topic","role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkbundleutils","navigatorTitle":[{"kind":"identifier","text":"ZDKBundleUtils"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKBundleUtils","kind":"identifier"}],"title":"ZDKBundleUtils"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKBundleUtils/userDefinedHelpCenterCss()":{"navigatorTitle":[{"kind":"identifier","text":"userDefinedHelpCenterCss"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKBundleUtils\/userDefinedHelpCenterCss()","title":"userDefinedHelpCenterCss()","url":"\/documentation\/supportproviderssdk\/zdkbundleutils\/userdefinedhelpcentercss()","role":"symbol","abstract":[{"type":"text","text":"Get the help center css file in the host apps main bundle and return as a string."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userDefinedHelpCenterCss"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"userDefinedHelpCenterCss"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"userDefinedHelpCenterCss"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"userDefinedHelpCenterCss","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"ZDKBundleUtils","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils\/fragments","value":[{"text":"ZDKBundleUtils","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1userDefinedHelpCenterCss()\/title","value":"userDefinedHelpCenterCss","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKBundleUtils~1userDefinedHelpCenterCss()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"userDefinedHelpCenterCss"}]}]}]}