{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"!(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdksupportuser\/init(dictionary:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdksupportuser\/init(dictionary:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportUser"]]},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Initializer","externalID":"c:objc(cs)ZDKSupportUser(im)initWithDictionary:","title":"init(dictionary:)","role":"symbol","symbolKind":"init","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"!(","kind":"text"},{"kind":"externalParam","text":"dictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportUser\/init(dictionary:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKSupportUser/init(dictionary:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"url":"\/documentation\/supportproviderssdk\/zdksupportuser\/init(dictionary:)","abstract":[],"title":"init(dictionary:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"!(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!)"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportUser\/init(dictionary:)","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKSupportUser":{"url":"\/documentation\/supportproviderssdk\/zdksupportuser","title":"ZDKSupportUser","navigatorTitle":[{"text":"ZDKSupportUser","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKSupportUser","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportUser"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithDictionary:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithDictionary:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"text":"dictionary","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportUser~1init(dictionary:)\/title","value":"initWithDictionary:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportUser~1init(dictionary:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDictionary:","kind":"identifier"}],"op":"replace"},{"value":"ZDKSupportUser","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportUser\/title"},{"value":[{"kind":"identifier","text":"ZDKSupportUser"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportUser\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}