{"abstract":[{"text":"Nav bar button with image for conversations.","type":"text"}],"metadata":{"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"}],"title":"ZDKNavBarConversationsUIType.image","symbolKind":"case","modules":[{"name":"SupportProvidersSDK"}],"externalID":"c:@E@ZDKNavBarConversationsUIType@ZDKNavBarConversationsUITypeImage","navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeImage"}]},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/image","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType"]]},"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType":{"title":"ZDKNavBarConversationsUIType","url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype","navigatorTitle":[{"text":"ZDKNavBarConversationsUIType","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Enum to describe the types of nav bar button that display conversations.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKNavBarConversationsUIType"}],"kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKNavBarConversationsUIType/image":{"title":"ZDKNavBarConversationsUIType.image","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeImage"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKNavBarConversationsUIType\/image","url":"\/documentation\/supportproviderssdk\/zdknavbarconversationsuitype\/image","kind":"symbol","abstract":[{"text":"Nav bar button with image for conversations.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ZDKNavBarConversationsUITypeImage"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeImage"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeImage"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKNavBarConversationsUIType","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType\/title"},{"value":[{"kind":"identifier","text":"ZDKNavBarConversationsUIType"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType\/fragments"},{"value":"ZDKNavBarConversationsUITypeImage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1image\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKNavBarConversationsUIType~1image\/fragments","value":[{"kind":"identifier","text":"ZDKNavBarConversationsUITypeImage"}]}]}]}