{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkcommentwithuser\/comment"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkcommentwithuser\/comment"]}],"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"comment","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"comment","externalID":"c:objc(cs)ZDKCommentWithUser(py)comment","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"comment","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKComment","text":"ZDKComment"},{"text":"!","kind":"text"}]},"abstract":[{"text":"The comment model.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/comment","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"comment"},{"text":": ","kind":"text"},{"text":"ZDKComment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKComment","preciseIdentifier":"c:objc(cs)ZDKComment","kind":"typeIdentifier"},{"kind":"text","text":"! { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentWithUser":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser","url":"\/documentation\/supportproviderssdk\/zdkcommentwithuser","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKCommentWithUser"}],"type":"topic","abstract":[{"type":"text","text":"Aggregate model for comments with users."}],"title":"ZDKCommentWithUser","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKCommentWithUser"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentWithUser/comment":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/comment","type":"topic","kind":"symbol","navigatorTitle":[{"text":"comment","kind":"identifier"}],"abstract":[{"type":"text","text":"The comment model."}],"role":"symbol","title":"comment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"comment","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKComment","text":"ZDKComment"},{"text":"!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkcommentwithuser\/comment"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKComment":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKComment","url":"\/documentation\/supportproviderssdk\/zdkcomment","kind":"symbol","navigatorTitle":[{"text":"ZDKComment","kind":"identifier"}],"type":"topic","title":"ZDKComment","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKComment"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"comment","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"comment"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"ZDKComment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKComment","preciseIdentifier":"c:objc(cs)ZDKComment","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"comment","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser\/title","value":"ZDKCommentWithUser"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser\/fragments","value":[{"text":"ZDKCommentWithUser","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1comment\/title","value":"comment","op":"replace"},{"op":"replace","value":[{"text":"comment","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1comment\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKComment\/title","value":"ZDKComment","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKComment\/fragments","value":[{"kind":"identifier","text":"ZDKComment"}]}]}]}