{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKETag\/unmodified(_:)"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdketag\/unmodified(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdketag\/unmodified(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Store the etag from the request and check if the response is ‘unmodified’"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKETag"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"unmodified:","kind":"identifier"}],"externalID":"c:objc(cs)ZDKETag(cm)unmodified:","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unmodified","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)ZDKDispatcherResponse","text":"ZDKDispatcherResponse","kind":"typeIdentifier"},{"kind":"text","text":"!) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"symbolKind":"method","role":"symbol","roleHeading":"Type Method","title":"unmodified(_:)","modules":[{"name":"SupportProvidersSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unmodified","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"response"},{"kind":"text","text":": "},{"text":"ZDKDispatcherResponse","preciseIdentifier":"c:objc(cs)ZDKDispatcherResponse","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDispatcherResponse","kind":"typeIdentifier"},{"kind":"text","text":"!) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"the response data","type":"text"}]}],"name":"response"}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"YES if the response was ‘unmodified’ otherwise NO","type":"text"}]}],"kind":"content"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKETag/unmodified(_:)":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKETag\/unmodified(_:)","navigatorTitle":[{"kind":"identifier","text":"unmodified:"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmodified"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKDispatcherResponse","text":"ZDKDispatcherResponse"},{"text":"!) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"unmodified(_:)","role":"symbol","abstract":[{"text":"Store the etag from the request and check if the response is ‘unmodified’","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdketag\/unmodified(_:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKDispatcherResponse":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDispatcherResponse","navigatorTitle":[{"kind":"identifier","text":"ZDKDispatcherResponse"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKDispatcherResponse"}],"kind":"symbol","title":"ZDKDispatcherResponse","role":"symbol","abstract":[{"text":"A model for the responses from the dispatcher.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkdispatcherresponse"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKETag":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKETag","navigatorTitle":[{"kind":"identifier","text":"ZDKETag"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKETag","kind":"identifier"}],"kind":"symbol","title":"ZDKETag","role":"symbol","abstract":[{"text":"ETag lookup.","type":"text"}],"url":"\/documentation\/supportproviderssdk\/zdketag"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"unmodified:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unmodified:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"unmodified:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKDispatcherResponse","text":"ZDKDispatcherResponse","preciseIdentifier":"c:objc(cs)ZDKDispatcherResponse"},{"kind":"text","text":" *) "},{"text":"response","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKETag~1unmodified(_:)\/title","op":"replace","value":"unmodified:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKETag~1unmodified(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unmodified:"}],"op":"replace"},{"value":"ZDKDispatcherResponse","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDispatcherResponse\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKDispatcherResponse"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKDispatcherResponse\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKETag\/title","value":"ZDKETag"},{"value":[{"text":"ZDKETag","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKETag\/fragments"}]}]}