{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/user"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"user"},{"kind":"text","text":": "},{"text":"ZDKSupportUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKSupportUser"},{"kind":"text","text":"!"}],"title":"user","externalID":"c:objc(cs)ZDKCommentWithUser(py)user","role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"user","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property"},"abstract":[{"text":"The user associated with the comment model.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"user","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportUser","preciseIdentifier":"c:objc(cs)ZDKSupportUser","kind":"typeIdentifier","text":"ZDKSupportUser"},{"kind":"text","text":"! { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkcommentwithuser\/user"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkcommentwithuser\/user"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentWithUser/user":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"user"},{"kind":"text","text":": "},{"text":"ZDKSupportUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKSupportUser"},{"kind":"text","text":"!"}],"title":"user","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/user","kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcommentwithuser\/user","abstract":[{"text":"The user associated with the comment model.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"user","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentWithUser":{"type":"topic","abstract":[{"text":"Aggregate model for comments with users.","type":"text"}],"title":"ZDKCommentWithUser","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ZDKCommentWithUser","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkcommentwithuser","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKCommentWithUser"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKSupportUser":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKSupportUser"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdksupportuser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKSupportUser"}],"abstract":[],"title":"ZDKSupportUser","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportUser"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"user","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"user","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)ZDKSupportUser","kind":"typeIdentifier","text":"ZDKSupportUser","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKSupportUser"},{"kind":"text","text":" * "},{"kind":"identifier","text":"user"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1user\/title","value":"user","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1user\/fragments","value":[{"kind":"identifier","text":"user"}],"op":"replace"},{"value":"ZDKCommentWithUser","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKCommentWithUser"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportUser\/title","value":"ZDKSupportUser","op":"replace"},{"value":[{"text":"ZDKSupportUser","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKSupportUser\/fragments"}]}]}