{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/supportsettings\/attachmentsettings"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/supportsettings\/attachmentsettings"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/attachmentSettings"},"metadata":{"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupportSettings(py)attachmentSettings","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"attachmentSettings","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"attachmentSettings","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"attachmentSettings","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettings","kind":"typeIdentifier","text":"AttachmentSettings"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentSettings","kind":"identifier"},{"kind":"text","text":": "},{"text":"AttachmentSettings","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettings"}]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/attachmentSettings":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"attachmentSettings","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettings","text":"AttachmentSettings"}],"title":"attachmentSettings","navigatorTitle":[{"text":"attachmentSettings","kind":"identifier"}],"abstract":[],"url":"\/documentation\/supportproviderssdk\/supportsettings\/attachmentsettings","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/attachmentSettings","role":"symbol","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/AttachmentSettings":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings","url":"\/documentation\/supportproviderssdk\/attachmentsettings","kind":"symbol","navigatorTitle":[{"text":"AttachmentSettings","kind":"identifier"}],"type":"topic","abstract":[],"title":"AttachmentSettings","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentSettings"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportSettings","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SupportSettings"}],"role":"symbol","title":"SupportSettings","url":"\/documentation\/supportproviderssdk\/supportsettings","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"attachmentSettings","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"attachmentSettings","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"ZDKAttachmentSettings","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/AttachmentSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKAttachmentSettings"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"attachmentSettings"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"attachmentSettings","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1attachmentSettings\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1attachmentSettings\/fragments","value":[{"kind":"identifier","text":"attachmentSettings"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings\/title","value":"ZDKAttachmentSettings"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1AttachmentSettings\/fragments","value":[{"kind":"identifier","text":"ZDKAttachmentSettings"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings\/title","value":"ZDKSupportSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings\/fragments","value":[{"kind":"identifier","text":"ZDKSupportSettings"}]}]}]}