{"metadata":{"role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"title":"conversationSettings","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"conversationSettings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettings","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"conversationSettings"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupportSettings(py)conversationSettings"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"conversationSettings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationsSettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ConversationsSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettings"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/supportsettings\/conversationsettings"]},{"paths":["\/documentation\/supportproviderssdk\/supportsettings\/conversationsettings"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/conversationSettings"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ConversationsSettings":{"navigatorTitle":[{"text":"ConversationsSettings","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/conversationssettings","abstract":[],"role":"symbol","type":"topic","kind":"symbol","title":"ConversationsSettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ConversationsSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationsSettings","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","kind":"symbol","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportSettings","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SupportSettings"}],"role":"symbol","title":"SupportSettings","url":"\/documentation\/supportproviderssdk\/supportsettings","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings","kind":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/SupportSettings/conversationSettings":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationSettings"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettings","text":"ConversationsSettings","kind":"typeIdentifier"}],"title":"conversationSettings","navigatorTitle":[{"kind":"identifier","text":"conversationSettings"}],"abstract":[],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/supportsettings\/conversationsettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/SupportSettings\/conversationSettings","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"conversationSettings"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"conversationSettings"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ConversationsSettings","text":"ZDKConversationsSettings","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKConversationsSettings"},{"kind":"text","text":" * "},{"kind":"identifier","text":"conversationSettings"}]}],"kind":"declarations"}},{"op":"replace","value":"ZDKConversationsSettings","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ConversationsSettings\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ConversationsSettings\/fragments","value":[{"kind":"identifier","text":"ZDKConversationsSettings"}]},{"value":"ZDKSupportSettings","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKSupportSettings"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1conversationSettings\/title","value":"conversationSettings","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1SupportSettings~1conversationSettings\/fragments","value":[{"text":"conversationSettings","kind":"identifier"}]}]}]}