{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentsResponse\/commmentsWithUsers"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentsResponse"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)ZDKCommentsResponse(py)commmentsWithUsers","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"commmentsWithUsers"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"navigatorTitle":[{"text":"commmentsWithUsers","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}],"title":"commmentsWithUsers","symbolKind":"property"},"abstract":[{"type":"text","text":"Array of comments with users."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"commmentsWithUsers","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"text":"]! { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkcommentsresponse\/commmentswithusers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkcommentsresponse\/commmentswithusers"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentsResponse/commmentsWithUsers":{"abstract":[{"type":"text","text":"Array of comments with users."}],"type":"topic","title":"commmentsWithUsers","url":"\/documentation\/supportproviderssdk\/zdkcommentsresponse\/commmentswithusers","navigatorTitle":[{"text":"commmentsWithUsers","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"commmentsWithUsers"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"text":"]!","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentsResponse\/commmentsWithUsers"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentsResponse":{"abstract":[{"text":"Collection model for comments.","type":"text"}],"type":"topic","title":"ZDKCommentsResponse","url":"\/documentation\/supportproviderssdk\/zdkcommentsresponse","navigatorTitle":[{"text":"ZDKCommentsResponse","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKCommentsResponse"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentsResponse"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"commmentsWithUsers"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"commmentsWithUsers","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"commmentsWithUsers","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"commmentsWithUsers","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentsResponse~1commmentsWithUsers\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentsResponse~1commmentsWithUsers\/fragments","value":[{"text":"commmentsWithUsers","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentsResponse\/title","op":"replace","value":"ZDKCommentsResponse"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentsResponse\/fragments","op":"replace","value":[{"text":"ZDKCommentsResponse","kind":"identifier"}]}]}]}