{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DispatcherAdapter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportproviderssdk\/dispatcheradapter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/dispatcheradapter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportProvidersSDK\/SQ","doc:\/\/com.zendesk.SupportProvidersSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/clearSettingsAndSession()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/convertError(response:originalError:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/logError(url:response:error:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/performRequest(zendesk:urlRequest:completionHandler:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DispatcherAdapter"}],"title":"DispatcherAdapter","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SupportProvidersSDK@objc(cs)DispatcherAdapter","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DispatcherAdapter"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.SupportProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SQ"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/DispatcherAdapter/performRequest(zendesk:urlRequest:completionHandler:)":{"role":"symbol","title":"performRequest(zendesk:urlRequest:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"zendesk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"kind":"text","text":", "},{"kind":"externalParam","text":"urlRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/performRequest(zendesk:urlRequest:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"performRequestWithZendesk:urlRequest:completionHandler:"}],"url":"\/documentation\/supportproviderssdk\/dispatcheradapter\/performrequest(zendesk:urlrequest:completionhandler:)"},"doc://com.zendesk.SupportProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/DispatcherAdapter/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/supportproviderssdk\/dispatcheradapter\/init"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/DispatcherAdapter":{"role":"symbol","title":"DispatcherAdapter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DispatcherAdapter"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DispatcherAdapter"}],"url":"\/documentation\/supportproviderssdk\/dispatcheradapter"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"role":"collection","title":"SupportProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportproviderssdk"},"doc://com.zendesk.SupportProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/DispatcherAdapter/clearSettingsAndSession()":{"role":"symbol","title":"clearSettingsAndSession()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearSettingsAndSession"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/clearSettingsAndSession()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearSettingsAndSession"}],"url":"\/documentation\/supportproviderssdk\/dispatcheradapter\/clearsettingsandsession()"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/DispatcherAdapter/convertError(response:originalError:)":{"role":"symbol","title":"convertError(response:originalError:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"originalError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/convertError(response:originalError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"convertErrorWithResponse:originalError:"}],"url":"\/documentation\/supportproviderssdk\/dispatcheradapter\/converterror(response:originalerror:)"},"doc://com.zendesk.SupportProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/DispatcherAdapter/logError(url:response:error:)":{"role":"symbol","title":"logError(url:response:error:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/logError(url:response:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logErrorWithUrl:response:error:"}],"url":"\/documentation\/supportproviderssdk\/dispatcheradapter\/logerror(url:response:error:)"},"doc://com.zendesk.SupportProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DispatcherAdapter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DispatcherAdapter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DispatcherAdapter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/clearSettingsAndSession()","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/convertError(response:originalError:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/logError(url:response:error:)","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/DispatcherAdapter\/performRequest(zendesk:urlRequest:completionHandler:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DispatcherAdapter"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1performRequest(zendesk:urlRequest:completionHandler:)\/title","value":"performRequestWithZendesk:urlRequest:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1performRequest(zendesk:urlRequest:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"performRequestWithZendesk:urlRequest:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter\/title","value":"DispatcherAdapter"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter\/fragments","value":[{"kind":"identifier","text":"DispatcherAdapter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1clearSettingsAndSession()\/title","value":"clearSettingsAndSession"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1clearSettingsAndSession()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clearSettingsAndSession"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1convertError(response:originalError:)\/title","value":"convertErrorWithResponse:originalError:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1convertError(response:originalError:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"convertErrorWithResponse:originalError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1logError(url:response:error:)\/title","value":"logErrorWithUrl:response:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1DispatcherAdapter~1logError(url:response:error:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"logErrorWithUrl:response:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}