{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/groupIds"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupIds","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"]! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/groupids"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/groupids"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel"]]},"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)ZDKHelpCenterOverviewContentModel(py)groupIds","navigatorTitle":[{"text":"groupIds","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupIds"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]!","kind":"text"}],"role":"symbol","title":"groupIds"},"abstract":[{"type":"text","text":"A list of ids. Only show articles contained in the categorys\/sections."}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel/groupIds":{"abstract":[{"type":"text","text":"A list of ids. Only show articles contained in the categorys\/sections."}],"role":"symbol","navigatorTitle":[{"text":"groupIds","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel\/groupIds","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"]!","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel\/groupids","title":"groupIds"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel":{"title":"ZDKHelpCenterOverviewContentModel","url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel","navigatorTitle":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Model which allows customizations on the content displayed by Help Center.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"groupIds","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"groupIds","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"groupIds"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1groupIds\/title","value":"groupIds"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel~1groupIds\/fragments","value":[{"text":"groupIds","kind":"identifier"}]},{"op":"replace","value":"ZDKHelpCenterOverviewContentModel","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterOverviewContentModel"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/fragments"}]}]}