{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"SupportProvidersSDK"}],"title":"getRequests()","externalID":"s:19SupportProvidersSDK14RequestStorageC11getRequestsSayAA0d3ForE0CGyF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getRequests","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage\/getRequests()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getRequests","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","text":"RequestForStorage","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage"},{"kind":"text","text":"]"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/requeststorage\/getrequests()"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestStorage/getRequests()":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage\/getRequests()","role":"symbol","abstract":[],"url":"\/documentation\/supportproviderssdk\/requeststorage\/getrequests()","title":"getRequests()","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getRequests","kind":"identifier"},{"kind":"text","text":"() -> ["},{"text":"RequestForStorage","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestStorage":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"RequestStorage","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RequestStorage","kind":"identifier"}],"title":"RequestStorage","url":"\/documentation\/supportproviderssdk\/requeststorage"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage":{"title":"RequestForStorage","url":"\/documentation\/supportproviderssdk\/requestforstorage","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestForStorage"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestForStorage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/title","op":"replace","value":"ZDKRequestStorage"},{"value":[{"kind":"identifier","text":"ZDKRequestStorage"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/title","value":"ZDKRequestForStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/fragments","value":[{"kind":"identifier","text":"ZDKRequestForStorage"}]}]}]}