{"variants":[{"paths":["\/documentation\/supportproviderssdk\/requeststorage\/init(withzendesk:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/requeststorage\/init(withzendesk:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withZendesk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk","text":"Zendesk"},{"text":")","kind":"text"}],"title":"init(withZendesk:)","symbolKind":"init","externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestStorage(im)initWithZendesk:","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"initWithZendesk:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withZendesk"},{"kind":"text","text":" "},{"kind":"internalParam","text":"zendesk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk","text":"Zendesk"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage\/init(withZendesk:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestStorage/init(withZendesk:)":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithZendesk:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage\/init(withZendesk:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"withZendesk","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"text":")","kind":"text"}],"url":"\/documentation\/supportproviderssdk\/requeststorage\/init(withzendesk:)","title":"init(withZendesk:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestStorage":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"RequestStorage","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RequestStorage","kind":"identifier"}],"title":"RequestStorage","url":"\/documentation\/supportproviderssdk\/requeststorage"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"initWithZendesk:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithZendesk:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithZendesk:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ZDKClassicZendesk","preciseIdentifier":"c:objc(cs)ZDKClassicZendesk","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zendesk"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"initWithZendesk:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage~1init(withZendesk:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage~1init(withZendesk:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithZendesk:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/title","value":"ZDKRequestStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/fragments","value":[{"text":"ZDKRequestStorage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}