{"metadata":{"title":"storeRequest(_:)","symbolKind":"method","navigatorTitle":[{"text":"storeRequest:","kind":"identifier"}],"extendedModule":"SupportProvidersSDK","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeRequest"},{"text":"(","kind":"text"},{"text":"RequestForStorage","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"c:@CM@SupportProvidersSDK@objc(cs)ZDKRequestStorage(im)storeRequest:"},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage\/storeRequest(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"request","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"RequestForStorage","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/supportproviderssdk\/requeststorage\/storerequest(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/requeststorage\/storerequest(_:)"]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestStorage":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"RequestStorage","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RequestStorage","kind":"identifier"}],"title":"RequestStorage","url":"\/documentation\/supportproviderssdk\/requeststorage"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestStorage/storeRequest(_:)":{"title":"storeRequest(_:)","url":"\/documentation\/supportproviderssdk\/requeststorage\/storerequest(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"storeRequest:"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestStorage\/storeRequest(_:)","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"storeRequest"},{"kind":"text","text":"("},{"text":"RequestForStorage","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/RequestForStorage":{"title":"RequestForStorage","url":"\/documentation\/supportproviderssdk\/requestforstorage","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestForStorage"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestForStorage","kind":"identifier"}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"storeRequest:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"storeRequest:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"storeRequest:","kind":"identifier"},{"kind":"text","text":"("},{"text":"ZDKRequestForStorage","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/RequestForStorage","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKRequestForStorage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"request"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/title","value":"ZDKRequestStorage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage\/fragments","value":[{"text":"ZDKRequestStorage","kind":"identifier"}]},{"value":"storeRequest:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage~1storeRequest(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestStorage~1storeRequest(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"storeRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/title","value":"ZDKRequestForStorage"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1RequestForStorage\/fragments","value":[{"text":"ZDKRequestForStorage","kind":"identifier"}]}]}]}