{"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/build(_:withUsers:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser"]]},"abstract":[{"text":"Build an instance with comment and a user.","type":"text"}],"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKComment","preciseIdentifier":"c:objc(cs)ZDKComment"},{"text":"!, ","kind":"text"},{"text":"withUsers","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"text":"]!) -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"roleHeading":"Type Method","role":"symbol","title":"build(_:withUsers:)","navigatorTitle":[{"kind":"identifier","text":"buildCommentWithUser:withUsers:"}],"externalID":"c:objc(cs)ZDKCommentWithUser(cm)buildCommentWithUser:withUsers:"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"comment"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKComment","kind":"typeIdentifier","text":"ZDKComment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKComment"},{"text":"!, ","kind":"text"},{"text":"withUsers","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"users","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!) -> "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"comment","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A comment to build with."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"A user to associate to a comment."}],"type":"paragraph"}],"name":"users"}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new instance."}]}]}],"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkcommentwithuser\/build(_:withusers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportproviderssdk\/zdkcommentwithuser\/build(_:withusers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentWithUser":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKCommentWithUser","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Aggregate model for comments with users."}],"title":"ZDKCommentWithUser","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKCommentWithUser"}],"url":"\/documentation\/supportproviderssdk\/zdkcommentwithuser"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKCommentWithUser/build(_:withUsers:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"build","kind":"identifier"},{"kind":"text","text":"("},{"text":"ZDKComment","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKComment"},{"text":"!, ","kind":"text"},{"text":"withUsers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!) -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"build(_:withUsers:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"buildCommentWithUser:withUsers:"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKCommentWithUser\/build(_:withUsers:)","abstract":[{"text":"Build an instance with comment and a user.","type":"text"}],"kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkcommentwithuser\/build(_:withusers:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKComment":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKComment","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"title":"ZDKComment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKComment","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKComment"}],"url":"\/documentation\/supportproviderssdk\/zdkcomment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"buildCommentWithUser:withUsers:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"buildCommentWithUser:withUsers:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"buildCommentWithUser:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKComment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKComment","text":"ZDKComment"},{"text":" *) ","kind":"text"},{"text":"comment","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withUsers:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray"},{"kind":"text","text":" *) "},{"text":"users","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser\/title","op":"replace","value":"ZDKCommentWithUser"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser\/fragments","value":[{"kind":"identifier","text":"ZDKCommentWithUser"}]},{"value":"buildCommentWithUser:withUsers:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1build(_:withUsers:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKCommentWithUser~1build(_:withUsers:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"buildCommentWithUser:withUsers:"}]},{"value":"ZDKComment","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKComment\/title"},{"value":[{"text":"ZDKComment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKComment\/fragments"}]}]}