{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkauthenticationtype\/jwt"]},{"paths":["\/documentation\/supportproviderssdk\/zdkauthenticationtype\/jwt"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/JWT","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"JWT","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","externalID":"c:@E@ZDKAuthenticationType@ZDKAuthenticationTypeJWT","navigatorTitle":[{"text":"ZDKAuthenticationTypeJWT","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"SupportProvidersSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWT"}],"role":"symbol","title":"ZDKAuthenticationType.JWT"},"abstract":[{"text":"JWT authentication.","type":"text"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType":{"navigatorTitle":[{"text":"ZDKAuthenticationType","kind":"identifier"}],"abstract":[{"text":"Represents the types of authentication SDK supports.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAuthenticationType","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType","title":"ZDKAuthenticationType","role":"symbol","kind":"symbol","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"kind":"symbol","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAuthenticationType/JWT":{"abstract":[{"text":"JWT authentication.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ZDKAuthenticationTypeJWT","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAuthenticationType\/JWT","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWT"}],"url":"\/documentation\/supportproviderssdk\/zdkauthenticationtype\/jwt","title":"ZDKAuthenticationType.JWT"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKAuthenticationTypeJWT"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"ZDKAuthenticationTypeJWT","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKAuthenticationTypeJWT","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKAuthenticationType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKAuthenticationType"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1JWT\/title","value":"ZDKAuthenticationTypeJWT","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAuthenticationType~1JWT\/fragments","value":[{"kind":"identifier","text":"ZDKAuthenticationTypeJWT"}]}]}]}