{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getArticleSuggestions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"search","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection","text":"ZDKHelpCenterDeflection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterDeflection"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The search to preform"}]}],"name":"search"},{"name":"callback","content":[{"inlineContent":[{"type":"text","text":"The callback that is invoked when a request is either successful or has error."}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlesuggestions(_:withcallback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlesuggestions(_:withcallback:)"]}],"abstract":[{"text":"Fetch a list of suggested articles filtered by the parameters in the given ZDKHelpCenterDeflection model.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticleSuggestions(_:withCallback:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getArticleSuggestions","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ZDKHelpCenterDeflection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterDeflection"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"title":"getArticleSuggestions(_:withCallback:)","externalID":"c:objc(cs)ZDKHelpCenterProvider(im)getArticleSuggestions:withCallback:","role":"symbol","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"getArticleSuggestions:withCallback:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterDeflection":{"abstract":[{"type":"text","text":"This class models a Help Center Deflection search. It has the same contract as a normal Help Center search."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/developer.zendesk.com\/rest_api\/docs\/help_center\/search"}],"navigatorTitle":[{"text":"ZDKHelpCenterDeflection","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterDeflection","kind":"identifier"}],"title":"ZDKHelpCenterDeflection","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterdeflection","kind":"symbol","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterCallback"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterCallback"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercallback","title":"ZDKHelpCenterCallback","role":"symbol","abstract":[{"type":"text","text":"Callback block."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getArticleSuggestions(_:withCallback:)":{"navigatorTitle":[{"kind":"identifier","text":"getArticleSuggestions:withCallback:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getArticleSuggestions","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterDeflection","text":"ZDKHelpCenterDeflection","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withCallback","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"abstract":[{"type":"text","text":"Fetch a list of suggested articles filtered by the parameters in the given ZDKHelpCenterDeflection model."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getArticleSuggestions(_:withCallback:)","kind":"symbol","role":"symbol","title":"getArticleSuggestions(_:withCallback:)","type":"topic","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getarticlesuggestions(_:withcallback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ZDKHelpCenterProvider","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"getArticleSuggestions:withCallback:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getArticleSuggestions:withCallback:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"getArticleSuggestions:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterDeflection","text":"ZDKHelpCenterDeflection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterDeflection"},{"text":" *) ","kind":"text"},{"text":"search","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withCallback:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","text":"ZDKHelpCenterCallback"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"ZDKHelpCenterDeflection","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection\/title"},{"value":[{"text":"ZDKHelpCenterDeflection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterDeflection\/fragments"},{"value":"ZDKHelpCenterCallback","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/title","op":"replace"},{"op":"replace","value":[{"text":"ZDKHelpCenterCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/fragments"},{"value":"getArticleSuggestions:withCallback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticleSuggestions(_:withCallback:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getArticleSuggestions:withCallback:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getArticleSuggestions(_:withCallback:)\/fragments"},{"op":"replace","value":"ZDKHelpCenterProvider","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}