{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Fetch a list of categories from a Help Center instance.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getCategoriesWithCallback(_:)"},"metadata":{"modules":[{"name":"SupportProvidersSDK"}],"symbolKind":"method","externalID":"c:objc(cs)ZDKHelpCenterProvider(im)getCategoriesWithCallback:","title":"getCategoriesWithCallback(_:)","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCategoriesWithCallback","kind":"identifier"},{"kind":"text","text":"("},{"text":"ZDKHelpCenterCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"getCategoriesWithCallback:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getcategorieswithcallback(_:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getcategorieswithcallback(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getCategoriesWithCallback","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}],"platforms":["iOS"]}]},{"parameters":[{"name":"callback","content":[{"inlineContent":[{"type":"text","text":"Callback that will deliver a list of categories available on the instance of the Help Center for the provided locale"}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getCategoriesWithCallback(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCategoriesWithCallback"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback"},{"kind":"text","text":"!)"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getCategoriesWithCallback(_:)","navigatorTitle":[{"kind":"identifier","text":"getCategoriesWithCallback:"}],"abstract":[{"type":"text","text":"Fetch a list of categories from a Help Center instance."}],"title":"getCategoriesWithCallback(_:)","kind":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getcategorieswithcallback(_:)","role":"symbol"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ZDKHelpCenterProvider","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterCallback"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterCallback"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercallback","title":"ZDKHelpCenterCallback","role":"symbol","abstract":[{"type":"text","text":"Callback block."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getCategoriesWithCallback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getCategoriesWithCallback:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"getCategoriesWithCallback:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier","text":"ZDKHelpCenterCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getCategoriesWithCallback(_:)\/title","value":"getCategoriesWithCallback:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getCategoriesWithCallback:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getCategoriesWithCallback(_:)\/fragments"},{"op":"replace","value":"ZDKHelpCenterProvider","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments","value":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"op":"replace"},{"value":"ZDKHelpCenterCallback","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterCallback"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}