{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getHelpCenterOverview(withHelpCenterOverviewModel:callback:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getHelpCenterOverview","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withHelpCenterOverviewModel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterOverviewContentModel","text":"ZDKHelpCenterOverviewContentModel","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCategoriesCallback","kind":"typeIdentifier","text":"ZDKHelpCenterCategoriesCallback"},{"text":"!)","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(cs)ZDKHelpCenterProvider(im)getHelpCenterOverviewWithHelpCenterOverviewModel:callback:","modules":[{"name":"SupportProvidersSDK"}],"navigatorTitle":[{"text":"getHelpCenterOverviewWithHelpCenterOverviewModel:callback:","kind":"identifier"}],"title":"getHelpCenterOverview(withHelpCenterOverviewModel:callback:)"},"abstract":[{"text":"Fetches the data required to model the overview UI in Help Center.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/gethelpcenteroverview(withhelpcenteroverviewmodel:callback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/gethelpcenteroverview(withhelpcenteroverviewmodel:callback:)"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getHelpCenterOverview","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withHelpCenterOverviewModel","kind":"externalParam"},{"kind":"text","text":" "},{"text":"helpCenterModel","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"ZDKHelpCenterOverviewContentModel","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterOverviewContentModel"},{"kind":"text","text":"!, "},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ZDKHelpCenterCategoriesCallback","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategoriesCallback","kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCategoriesCallback"},{"kind":"text","text":"!)"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"content model to scope"}],"type":"paragraph"}],"name":"helpCenterModel"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"callback which provides an array of ZDKHelpCenterCategoryViewModel"}]}],"name":"callback"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"]]},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCategoriesCallback":{"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercategoriescallback","abstract":[{"type":"text","text":"Callback block for help center overview."}],"title":"ZDKHelpCenterCategoriesCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterCategoriesCallback","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterCategoriesCallback"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategoriesCallback"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getHelpCenterOverview(withHelpCenterOverviewModel:callback:)":{"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/gethelpcenteroverview(withhelpcenteroverviewmodel:callback:)","title":"getHelpCenterOverview(withHelpCenterOverviewModel:callback:)","abstract":[{"type":"text","text":"Fetches the data required to model the overview UI in Help Center."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getHelpCenterOverview","kind":"identifier"},{"kind":"text","text":"("},{"text":"withHelpCenterOverviewModel","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterOverviewContentModel","text":"ZDKHelpCenterOverviewContentModel"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCategoriesCallback","text":"ZDKHelpCenterCategoriesCallback","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"getHelpCenterOverviewWithHelpCenterOverviewModel:callback:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getHelpCenterOverview(withHelpCenterOverviewModel:callback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ZDKHelpCenterProvider","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterOverviewContentModel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenteroverviewcontentmodel","kind":"symbol","abstract":[{"type":"text","text":"Model which allows customizations on the content displayed by Help Center."}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel","title":"ZDKHelpCenterOverviewContentModel"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"getHelpCenterOverviewWithHelpCenterOverviewModel:callback:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getHelpCenterOverviewWithHelpCenterOverviewModel:callback:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"getHelpCenterOverviewWithHelpCenterOverviewModel:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterOverviewContentModel","preciseIdentifier":"c:objc(cs)ZDKHelpCenterOverviewContentModel","text":"ZDKHelpCenterOverviewContentModel"},{"text":" *) ","kind":"text"},{"text":"helpCenterModel","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"callback:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCategoriesCallback","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCategoriesCallback","text":"ZDKHelpCenterCategoriesCallback"},{"kind":"text","text":") "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKHelpCenterCategoriesCallback","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategoriesCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCategoriesCallback\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterCategoriesCallback"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getHelpCenterOverview(withHelpCenterOverviewModel:callback:)\/title","value":"getHelpCenterOverviewWithHelpCenterOverviewModel:callback:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getHelpCenterOverviewWithHelpCenterOverviewModel:callback:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getHelpCenterOverview(withHelpCenterOverviewModel:callback:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title","op":"replace","value":"ZDKHelpCenterProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments","value":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/title","value":"ZDKHelpCenterOverviewContentModel"},{"value":[{"text":"ZDKHelpCenterOverviewContentModel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterOverviewContentModel\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}