{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Fetches a section object for a particular sectionId."}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"getSectionWithId:withCallback:","kind":"identifier"}],"modules":[{"name":"SupportProvidersSDK"}],"title":"getSectionWithId(_:withCallback:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getSectionWithId","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withCallback"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)ZDKHelpCenterProvider(im)getSectionWithId:withCallback:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSectionWithId"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sectionId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"withCallback","kind":"externalParam"},{"kind":"text","text":" "},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback"},{"text":"!)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The id of the section to fetch.","type":"text"}],"type":"paragraph"}],"name":"sectionId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback that is invoked when a request is either successful or has error."}]}],"name":"callback"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getSectionWithId(_:withCallback:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getsectionwithid(_:withcallback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getsectionwithid(_:withcallback:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider"]]},"kind":"symbol","references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterCallback"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterCallback"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","url":"\/documentation\/supportproviderssdk\/zdkhelpcentercallback","title":"ZDKHelpCenterCallback","role":"symbol","abstract":[{"type":"text","text":"Callback block."}]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider":{"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterProvider","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ZDKHelpCenterProvider","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider","abstract":[]},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterProvider/getSectionWithId(_:withCallback:)":{"kind":"symbol","navigatorTitle":[{"text":"getSectionWithId:withCallback:","kind":"identifier"}],"role":"symbol","title":"getSectionWithId(_:withCallback:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getSectionWithId","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterprovider\/getsectionwithid(_:withcallback:)","abstract":[{"type":"text","text":"Fetches a section object for a particular sectionId."}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterProvider\/getSectionWithId(_:withCallback:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"getSectionWithId:withCallback:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getSectionWithId:withCallback:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"getSectionWithId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sectionId"},{"text":" ","kind":"text"},{"text":"withCallback:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterCallback","preciseIdentifier":"c:ZDKHelpCenterProvider.h@T@ZDKHelpCenterCallback","text":"ZDKHelpCenterCallback","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"ZDKHelpCenterCallback","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterCallback\/fragments","value":[{"text":"ZDKHelpCenterCallback","kind":"identifier"}]},{"value":"ZDKHelpCenterProvider","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterProvider"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getSectionWithId(_:withCallback:)\/title","value":"getSectionWithId:withCallback:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"getSectionWithId:withCallback:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterProvider~1getSectionWithId(_:withCallback:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}