{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getContactUsSettings","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKContactUsSettings","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ContactUsSettings","text":"ContactUsSettings","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkcontactussettingsprovider\/getcontactussettings(callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkcontactussettingsprovider\/getcontactussettings(callback:)"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKContactUsSettingsProvider"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKContactUsSettingsProvider\/getContactUsSettings(callback:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"getContactUsSettingsWithCallback:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getContactUsSettings","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKContactUsSettings","text":"ContactUsSettings"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@SupportProvidersSDK@objc(cs)ZDKContactUsSettingsProvider(cm)getContactUsSettingsWithCallback:","modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Type Method","title":"getContactUsSettings(callback:)","symbolKind":"method"},"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"title":"SupportProvidersSDK","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","abstract":[],"kind":"symbol","role":"collection","type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ContactUsSettings":{"role":"symbol","navigatorTitle":[{"text":"ContactUsSettings","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ContactUsSettings","title":"ContactUsSettings","url":"\/documentation\/supportproviderssdk\/contactussettings","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactUsSettings","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKContactUsSettingsProvider":{"role":"symbol","navigatorTitle":[{"text":"ZDKContactUsSettingsProvider","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKContactUsSettingsProvider","url":"\/documentation\/supportproviderssdk\/zdkcontactussettingsprovider","title":"ZDKContactUsSettingsProvider","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKContactUsSettingsProvider"}],"type":"topic"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKContactUsSettingsProvider/getContactUsSettings(callback:)":{"role":"symbol","navigatorTitle":[{"text":"getContactUsSettingsWithCallback:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKContactUsSettingsProvider\/getContactUsSettings(callback:)","title":"getContactUsSettings(callback:)","url":"\/documentation\/supportproviderssdk\/zdkcontactussettingsprovider\/getcontactussettings(callback:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getContactUsSettings"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKContactUsSettings","text":"ContactUsSettings","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"getContactUsSettingsWithCallback:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"getContactUsSettingsWithCallback:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"getContactUsSettingsWithCallback:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(ZDKContactUsSettings *)","preciseIdentifier":"c:BFv(#*$@M@SupportProvidersSDK@objc(cs)ZDKContactUsSettings)"},{"kind":"text","text":") "},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ContactUsSettings\/title","value":"ZDKContactUsSettings","op":"replace"},{"value":[{"text":"ZDKContactUsSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ContactUsSettings\/fragments","op":"replace"},{"op":"replace","value":"ZDKContactUsSettingsProvider","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKContactUsSettingsProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKContactUsSettingsProvider\/fragments","value":[{"kind":"identifier","text":"ZDKContactUsSettingsProvider"}]},{"op":"replace","value":"getContactUsSettingsWithCallback:","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKContactUsSettingsProvider~1getContactUsSettings(callback:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKContactUsSettingsProvider~1getContactUsSettings(callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getContactUsSettingsWithCallback:"}]}]}]}