{"variants":[{"paths":["\/documentation\/supportproviderssdk\/zdkattachment\/thumbnails"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportproviderssdk\/zdkattachment\/thumbnails"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"thumbnails","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)ZDKAttachment","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment","text":"ZDKAttachment","kind":"typeIdentifier"},{"text":"]! { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","navigatorTitle":[{"text":"thumbnails","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"thumbnails","kind":"identifier"},{"kind":"text","text":": ["},{"text":"ZDKAttachment","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKAttachment"},{"kind":"text","text":"]!"}],"modules":[{"name":"SupportProvidersSDK"}],"roleHeading":"Instance Property","title":"thumbnails","symbolKind":"property","externalID":"c:objc(cs)ZDKAttachment(py)thumbnails"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/thumbnails","interfaceLanguage":"swift"},"abstract":[{"text":"Thumbnails associated with the attachment. A thumbnail is an attachment with a nil thumbnails array.","type":"text"}],"sections":[],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment/thumbnails":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"thumbnails","kind":"identifier"}],"title":"thumbnails","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"thumbnails","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKAttachment","text":"ZDKAttachment","kind":"typeIdentifier"},{"kind":"text","text":"]!"}],"role":"symbol","url":"\/documentation\/supportproviderssdk\/zdkattachment\/thumbnails","abstract":[{"type":"text","text":"Thumbnails associated with the attachment. A thumbnail is an attachment with a nil thumbnails array."}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment\/thumbnails"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","title":"SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKAttachment":{"navigatorTitle":[{"kind":"identifier","text":"ZDKAttachment"}],"abstract":[{"text":"An attachment to a Zendesk comment","type":"text"}],"type":"topic","url":"\/documentation\/supportproviderssdk\/zdkattachment","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAttachment","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKAttachment","role":"symbol","title":"ZDKAttachment"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"thumbnails","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"thumbnails","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ZDKAttachment *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"thumbnails"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1thumbnails\/title","value":"thumbnails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment~1thumbnails\/fragments","value":[{"text":"thumbnails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment\/title","value":"ZDKAttachment","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKAttachment"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKAttachment\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}