{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/parseattachments(_:)"]},{"paths":["\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/parseattachments(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/parseAttachments(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Parses a collection of Help Center json attachments objects.","type":"text"}],"sections":[],"metadata":{"title":"parseAttachments(_:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parseAttachments"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!) -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"modules":[{"name":"SupportProvidersSDK"}],"role":"symbol","externalID":"c:objc(cs)ZDKHelpCenterAttachment(cm)parseAttachments:","symbolKind":"method","navigatorTitle":[{"text":"parseAttachments:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"parseAttachments","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!) -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"JSON representation of attachments."}],"type":"paragraph"}],"name":"json"}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of Help Center attachment models."}]}]}],"references":{"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment/parseAttachments(_:)":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Parses a collection of Help Center json attachments objects.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment\/parseAttachments(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"parseAttachments","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!) -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment\/parseattachments(_:)","navigatorTitle":[{"kind":"identifier","text":"parseAttachments:"}],"title":"parseAttachments(_:)"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK","url":"\/documentation\/supportproviderssdk","role":"collection","title":"SupportProvidersSDK"},"doc://com.zendesk.SupportProvidersSDK/documentation/SupportProvidersSDK/ZDKHelpCenterAttachment":{"identifier":"doc:\/\/com.zendesk.SupportProvidersSDK\/documentation\/SupportProvidersSDK\/ZDKHelpCenterAttachment","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterAttachment"}],"kind":"symbol","title":"ZDKHelpCenterAttachment","url":"\/documentation\/supportproviderssdk\/zdkhelpcenterattachment","role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterAttachment","kind":"identifier"}],"abstract":[{"type":"text","text":"A model for Help Center Attachments."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"parseAttachments:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"parseAttachments:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"parseAttachments:"},{"kind":"text","text":"("},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1parseAttachments(_:)\/title","op":"replace","value":"parseAttachments:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment~1parseAttachments(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"parseAttachments:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment\/title","value":"ZDKHelpCenterAttachment","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportProvidersSDK~1documentation~1SupportProvidersSDK~1ZDKHelpCenterAttachment\/fragments","value":[{"text":"ZDKHelpCenterAttachment","kind":"identifier"}],"op":"replace"}]}]}